### ISSUE TITLE
Left hand nav bug under "Guides" "Creating accessible interfaces"

### ISSUE THREAD

**Issue by stephanieosan** [cfpb/design-manual#111]
If I go to the "Guides" section of the tool and click on "Accessible interfaces", the left hand nav should have a green bar to the left of the words "Accessible interfaces". But, it's missing. My suspicion is this is somehow related to the fact that "Accessible interfaces" wraps to two lines (it's the only page that this happens for, and it's the only page that has a two-lined title). 
#### Accessible interfaces page:

![screen shot 2014-04-09 at 10 51 11 am](https://cloud.githubusercontent.com/assets/6433178/2656888/8ec4ff48-bff6-11e3-8980-f1babe6e5f85.png)
#### How it should work (and currently works on all other pages):

![screen shot 2014-04-07 at 4 50 49 pm](https://cloud.githubusercontent.com/assets/6433178/2656892/9b845454-bff6-11e3-952c-bc0797bfd1bc.png)

**Comment by ascott1** [comment]
@stephanieosan I believe the way this is coded is that they title and the navigation text need to match exactly for the correct class to be applied. The quick fix for this is to either change the text in the navigation to read "Accessible interfaces" or the title of the page to "Creating accessible interfaces."

**Comment by stephanieosan** [comment]
Interesting...

**Comment by stephanieosan** [comment]
Hooray! That worked! Thanks @ascott1
