### ISSUE TITLE
UI toolkit > Links page

### ISSUE THREAD

**Issue by iuloshi** [cfpb/design-manual#117]
Is this ready to get built out? 
## Comp:

![ui-toolkit_sk_140403_v1_links](https://cloud.githubusercontent.com/assets/1676307/2699775/8f52552e-c40a-11e3-83f8-9174fc398094.png)

**Comment by mebates** [comment]
@iuloshi the blue nav links at the top should be U/L and bigger, matching the identity pages

**Comment by mebates** [comment]
And add two more Nav items: Emphasizing and States

**Comment by iuloshi** [comment]
Assigning @ell0ell0 to complete this mission, should you accept it! @marcesher Can we add @ell0ell0 (Lee) to the CFPB GH org? He's going to help out with some Design Manual stuff too. Thanks!

**Comment by mebates** [comment]
AND, sorry, 'View on Capital Framework' should probably have an underline throughout

**Comment by iuloshi** [comment]
Restructuring @mebates' comments above as an easier to track checklist:
- [x] the blue nav links at the top should be sentence case and bigger, matching the identity pages
- [x] add two more Nav items: Emphasizing and States (N/A)
- [ ] 'View on Capital Framework' should probably have an underline throughout

**Comment by iuloshi** [comment]
See [#73](https://github.com/cfpb/design-manual/issues/73#issuecomment-40525702) for latest Links page comp.

![4b305f36-c4e5-11e3-8b58-51b36c47826a](https://cloud.githubusercontent.com/assets/1676307/2721383/f3fb7f2a-c57a-11e3-948d-70fcc9bf6ca7.png)

**Comment by iuloshi** [comment]
#### FEWD tasks:
- [x] Add coded example of links in navigation
- [ ] Style links with minicons (minicons with no underline, but maintain other link states) - See [CF issue](https://github.com/cfpb/cf-typography/issues/10#issuecomment-41195102)
- [x] Increase leading of Document link examples

**Comment by iuloshi** [comment]
Closing because only outstanding task is covered in issue #163.
