### ISSUE TITLE
Should we create SVGs for our isocons? 

### ISSUE THREAD

**Issue by iuloshi** [cfpb/design-manual#119]
On the Identity > Isocons page, we're currently just using PNGs for the isocons asset library. In the spirit of being open source, should we also have SVG versions for web-use? This is minor/not a priority.

**Comment by mebates** [comment]
n00b here: can you explain the advantage of providing an SVG and how much additional work it would be? Is it in addition to the png or replacing them? Thx!

**Comment by iuloshi** [comment]
@mebates Scaled Vector Graphics is an image file format that basically use geometry in the browser to create resolution independent vectors, like Illustrator vectors but for the web. One of the main advantages is that we wouldn't need to create a second set of Retina PNGs of the isocons. You would export an SVG in Illustrator just as you would export a PNG, and then we could do a little more work to further optimize the file. I don't think that an SVG set of isocons should replace the PNGs, but rather supplement them. However, I do think this could potentially replace the need for an isocon font.

While an SVG file is pretty lightweight in and of itself, rather than linking externally to the file in the source code, there's also the options of embedding the code directly into the HTML or CSS/LESS stylesheet, which would decrease the overall load time for the website and be one less HTTP call. Unfortunately though, the embeddable code is sort of bloated. It also doesn't have IE8 support, but we could have fallback options.

Mollie, for reference: [CSS-Tricks article on SVG](http://css-tricks.com/using-svg/)

@Scotchester @himedlooff What are your thoughts on SVGs for the isocon library?  I could see this being more of a nice-to-have, but it's easily something I could implement. (We only have about 20 isocons currently.)

**Comment by himedlooff** [comment]
The issue with SVG is browser support http://caniuse.com/svg

**Comment by iuloshi** [comment]
Could we provide a fallback option?

**Comment by himedlooff** [comment]
Fallback options are possible in background scenarios but are harder to implement when being used as inline images.

We used them on http://www.consumerfinance.gov/es/ for the full page background with NO fallback for older browsers since it would only be seen on larger screens.

**Comment by himedlooff** [comment]
I think it's a great idea to provide them on the Design Manual so people can use them as source files if they want to tweak the icons for their own use.

**Comment by Scotchester** [comment]
Actually, I came across a pretty ingenious fallback recently and implemented it on CF.gov (not in production yet). [link coming soon]

**Comment by nataliafitzgerald** [comment]
Taking a few steps back from whether we should share SVG files of our isocon library, now is a good time to pick back up on the larger discussion as to what open-sourcing means for our visual brand assets. Our visual brand is largely anchored to our icon library, illustrations, isocons, and minicons. There is value in open-sourcing certain content as it can used outside of our organization by the larger public to strengthen general visual communications. But we must consider our brand when deciding what open-sourcing means for our visual design assets. 

The logic with open-sourcing the minicon font and vector files is that they are universal icons and can be used by any organization, company, or individual without being visually tied back to our brand. The library then becomes a living organism that can evolve and reach wider audiences. There is a real public benefit to open-sourcing these icons and there is no risk to the CFPB brand. It's a win-win.  

Our isocons, drawn in an isometric view with very specific styling detail, are key components of the CFPB brand. We can open-source the principles that we have used to develop this library without sharing the actual design files. I will add that up to this point, any use of isocons in CFPB branded materials has come directly from CFPB Design. We have not provided our isocon library (vector or raster) to outside contractors or vendors working on CFPB materials. Keeping this library in-house has ensured that our isocons are used in the way that they are intended by our brand guidelines. 

At this point in time, let's refrain from open-sourcing design files (including PNGs or SVG's) of our isocons or illustrations. At our next branding meeting we'll reserve time to discuss our GD team thoughts/plans/philosophies with regard to the open-sourcing of our branded content.

**Comment by ohsk** [comment]
I don't think this thread is about open sourcing the SVGs, but whether or not they're the best approach in terms of file type for web implementation.

**Comment by ohsk** [comment]
But I think that's an important discussion to have, Natalia! Did you see Daniel's issue on open sourcing the Minicons in the OSWG repo?

**Comment by iuloshi** [comment]
+1 To @ohsk's comments! This issue was directed more at FEWDs for a technical perspective about which file format is best for isocons on the web, especially with regards to Capital Framework.

**Comment by iuloshi** [comment]
SVG Accessibility link per @davidakennedy http://schepers.cc/authoring-accessible-svg

**Comment by nataliafitzgerald** [comment]
@ohsk - I'll be sure to check out Daniel's issue related to open sourcing the minicons. I have moved the visual brand open source discussion to a new issue within the Identity milestone. Check it out here: "Open sourcing our brand assets" #141

**Comment by stephanieosan** [comment]
What image file formats are we using for illustrations these days? PNGs and jpegs? 

I'm not sure we need this issue anymore...?

**Comment by Scotchester** [comment]
Our illustrations currently go on the web as PNGs, because we're not scaling them arbitrarily (we decided on fixed sizes for them), and PNGs typically offer the best filesize for the style of illustrations we use.

The advantage of offering SVG versions in the Design Manual is that others could use them at any size without loss of quality, or modify them in a vector graphics program and use them as they please.

**Comment by caheberer** [comment]
Thanks @Scotchester. Seems like we can close.
