### ISSUE TITLE
Homepage

### ISSUE THREAD

**Issue by iuloshi** [cfpb/design-manual#121]
- [x] Cut image asset
- [x] Add minicons to headers

![caa9b778-b6c4-11e3-9030-dd03c98526d5](https://cloud.githubusercontent.com/assets/1676307/2721223/89878c2a-c579-11e3-902e-f5f906cfce67.png)

**Comment by dezzie** [comment]
:thumbsup:

**Comment by ohsk** [comment]
Open to other feature image ideas as well! I made that minicon one pretty quickly and actually think it's a little too off-brand in styling...

**Comment by mebates** [comment]
@iuloshi and @stephanieosan and I just decided that we should go with it and it can be changed at a later date if someone comes up with something better. #getitdone

**Comment by iuloshi** [comment]
- [x] Homepage isn't full page width for some reason. Is it allotting space for the secondary side-nav?  (FEWD task)

![screen shot 2014-04-18 at 4 08 15 pm](https://cloud.githubusercontent.com/assets/1676307/2745393/683bcd84-c735-11e3-8cc9-b4db3373c820.png)
