### ISSUE TITLE
Develop content for Guides and UI toolkit landing pages

### ISSUE THREAD

**Issue by iuloshi** [cfpb/design-manual#122]
Per @mebates in issue #90:

> Developing copy for home page and interior landing pages (Guides, Identity, UI) on this wiki: https://github.com/cfpb/design-manual/wiki/Overview-Explanatory-content
> 
> Copy is loaded on live site now for home page and Identity. Need some help to craft words for 'Guides' and 'UI Toolkit', please edit the wiki if you have some ideas, or comment below.

**Comment by stephanieosan** [comment]
What about just this for the UI Toolkit intro? Do we need one more sentence?

The UI toolkit contains guidelines for using CFPB's [Capital Framework](http://cfpb.github.io/capital-framework/), a set of front-end components built by in-house developers to make creating consistent, on-brand web products as easy as possible. 

@mebates

**Comment by mebates** [comment]
I think that's good, let's toss it in to see how it looks. Others can pull edits if they'd like!

**Comment by stephanieosan** [comment]
@iuloshi  Make it happen!

**Comment by stephanieosan** [comment]
How about this for the guides page? It's even shorter. Anything else we need to say about them?

These guides reflect the design principles and best practices espoused by the CFPB tech team. 

@mebates @iuloshi

**Comment by iuloshi** [comment]
Added content! (See my [demo page](http://iuloshi.github.io/design-manual/) for now until someone accepts my PR.)
