### ISSUE TITLE
Reorder Guides and Identity sub-navs alphabetically

### ISSUE THREAD

**Issue by iuloshi** [cfpb/design-manual#124]
Per @benguhin:

> that's assuming that folks are going to view each page in the order that they're listed
> rather than coming to the manual looking for something specific
> 
> now that we have the section overview pages, I think alphabetical is much more viable for both sections and ultimately more scalable

Re: [issue #34](https://github.com/cfpb/design-manual/issues/34#issuecomment-40619014)

**Comment by ohsk** [comment]
I would tend to disagree with alphabetical ordering, WRT at least the Identity section. The order implies a loose hierarchy or degree of significance of brand elements that we would want to maintain. We spent a bit of time on the Style Guide determining a purposeful logic for moving someone through a sequence of our brand.

| Current order | Alphabetical |
| :-- | :-- |
| Logo | Beam pattern |
| Color | Color |
| Typography | Illustration |
| Minicons | Isocons |
| Isocons | Logo |
| Illustration | Minicons |
| Beam pattern | Photography |
| Photography | Typography |
| Video | Video |

The alphabetical ordering puts logo and typography too far down, and beams at the top, which I think is misleading about the basic components of our brand.

The proximity of Minicons + Isocons + Illustrations in sequence, as well as Photography + Video was pretty important as well. The proximity of these sections reinforces someone being able to relate these content areas.

I don't think the menu is so long that it poses a problem to scan and find what you're looking for. And in some cases, people may not know the name of what they're searching for. For example, "I'm looking to find information about the CFPB's icons, but I don't happen to know that they have specific names for their icon libraries." In this case, the proximity of Minicons + Isocons would likely help make the icon sections more recognizable.

**Comment by mebates** [comment]
I agree completely with @ohsk and appreciate the time he took to articulate the reasoning!

**Comment by benguhin** [comment]
Yeah I totally agree Logo + Color + Typography are most important, and that Minicons + Isocons + Illustrations make sense in sequence, as do Photography + Video. Here's what I'm thinking:
1. The order of the current, flat list seems a bit random and isn't any more scannable than alphabetical order
2. We should try to use the same ordering pattern on both this section and the UI toolkit section

Possible solution: How about grouping the pages more explicitly in the side nav? @ohsk you might already have a style for this – just a small eyebrow title over each of those three groupings to make the structure clearer. The pattern could also help in giving more structure to the UI toolkit section.

**Comment by ohsk** [comment]
You thinking something more like these groupings? I'm not exactly sure what the best exact eyebrows might be, but here's an initial attempt.

| Foundation |
| :-- |
| Logo |
| Color |
| Typography |

| Graphic elements |
| :-- |
| Minicons |
| Isocons |
| Illustration |
| Beam pattern |

| Documentation |
| :-- |
| Photography |
| Video |

**Comment by benguhin** [comment]
To recap of a recent discussion with @iuloshi and @ohsk, the eyebrows thing could work but isn't terribly necessary for v1.0, so we're gonna punt that possibility to R2.

Proposal for R1:
Identity will continue to keep the order of the pdf version, without any formal groupings
UI toolkit will continue to be alphabetical unless/until a better order is proposed
