### ISSUE TITLE
Add standard for skip links

### ISSUE THREAD

**Issue by davidakennedy** [cfpb/design-manual#127]
We should add a standard for the visual appearance and functionality of skip links. What's a skip link? See this [article from WebAIM](http://webaim.org/techniques/skipnav/). I'm in the process of adding a skip link to the current consumerfinance.gov site, and thought it would be a good time to hash things out.

We should break it into visual appearance and functionality. I've developed a working prototype that I've taken a screenshot of. I think it's a good stating point for discussion:

![skip-link](https://cloud.githubusercontent.com/assets/1473618/2722124/25b14a82-c584-11e3-9823-9975240c9f06.png)
## Functionality

**Visible or Only Visible on Focus**: My prototype has the link only visible on focus? Should we reconsider?

**Managing focus**: This relates to the point, in the WebAIM piece, that not all browsers actually shift the focus after the link is clicked to it's container. We can fix this with some simple JavaScript/jQuery:

``` javascript
$("#skip").click(function() {
        $("#wrapper").attr("tabindex", "-1");
        $("#wrapper").focus();
    });
```

Should we do that? Is it still necessary? I need to research more.

Should we add a simple animation when this is displayed? Maybe with CSS3.
## Visual

The above screenshot is a starting point... Do we need to make adjustments visually to make it look better?
## Other skip links

Is there anything else we should consider when thinking about using skip links elsewhere?
### Related
- The Design Manual has a skip link that's styled like a normal link.
- [Skip Navigation Links](http://webaim.org/techniques/skipnav/)
- [Back to Basics: Skip to Main Content Links](http://terrillthompson.com/blog/161)

**Comment by Scotchester** [comment]
Bump. I'm implementing this on the landing page I'm working on now to make it as accessible as can be. I went a slightly different route than @davidakennedy to avoid shifting the page content down when tabbing to the skip link. Here's what I've got:

![screen shot 2015-04-10 at 16 25 28](https://cloud.githubusercontent.com/assets/1044670/7096867/fa1d7d92-df9e-11e4-947e-ec2dbef015ea.png)

Any feedback?

**Comment by JenniferHoran** [comment]
http://www.access-board.gov/guidelines-and-standards/communications-and-it/about-the-section-508-standards/section-508-standards#subpart_b

In case anyone is wondering where this requirement is located in the 508 Standards:
Subpart B — Technical Standards
§ 1194.22   Web-based intranet and internet information and applications.
(o) A method shall be provided that permits users to skip repetitive navigation links.

**Comment by mebates** [comment]
So, when does that link appear? Only when you hit tab for the first time?

**Comment by KimberlyMunoz** [comment]
I created a skip link on http://beta.consumerfinance.gov/ and it's live. Just hit tab to see it in action.

**Comment by stephanieosan** [comment]
Need to figure out: 
* how is this implemented on cf.gov currently?
* does this need to be included as a standard on the design manual?

**Comment by jimmynotjim** [comment]
@stephanieosan the version Kim created to is what's on production currently.

![screen shot 2017-01-03 at 3 17 25 pm](https://cloud.githubusercontent.com/assets/1280430/21623395/cc1fec32-d1c7-11e6-99ce-e9378764a73d.png)

**Comment by KimberlyMunoz** [comment]
Yep. It's mostly done through CSS to display when someone first hits tab on
the page. There's also some JS with it to fix a bug on chrome which may
have been fixed now, it's worth looking into and deleting if it's no longer
needed.

**Comment by caheberer** [comment]
Complete!
