### ISSUE TITLE
modals and tooltips not in CF?

### ISSUE THREAD

**Issue by mebates** [cfpb/design-manual#128]
@Scotchester @himedlooff:

Are tooltips and modals part of the Capital Framework project? I noticed that they don't have any content in the Design Manual right now.

If they're not, should we still include them? Should we mock up static examples or code real ones?

**Comment by himedlooff** [comment]
I can answer question 1; no they have not been built yet.

**Comment by mebates** [comment]
@himedlooff is that scheduled to happen anytime soon? Perhaps cf.gov doesn't use either of these things yet?

**Comment by himedlooff** [comment]
No it's not. Those components aren't needed yet for us so I would imagine we wouldn't get to them any time soon.

**Comment by mebates** [comment]
@stephanieosan @iuloshi and I have decided to remove these two elements from the UI toolkit for now and place them in the backlog. We don't want to make static images as examples with no code associated with them.
