### ISSUE TITLE
Flickr square minicon 

### ISSUE THREAD

**Issue by iuloshi** [cfpb/design-manual#132]
For some reason the square background version of the Flickr minicon is displaying the old, incorrect version in the [Design Manual](http://cfpb.github.io/design-manual/identity/minicons.html), but in the `cf-icon` [docs](http://cfpb.github.io/cf-icons/docs/), it's correct. Any ideas on why this might be? Thanks! @himedlooff @Scotchester

![screen shot 2014-04-17 at 2 45 15 pm](https://cloud.githubusercontent.com/assets/1676307/2735577/982db626-c661-11e3-8c0a-d3317a615f7c.png)

**Comment by iuloshi** [comment]
ccing @ascott1 @Dnpizarro Thanks guys!

**Comment by Dnpizarro** [comment]
I know we updated the font itself about a month ago. However, I know we have been struggling to get a working version of the the font webkit. @ascott1 do you have a version they could use with our last updates?

**Comment by ohsk** [comment]
Sidebar convo hijack warning:
This is how the asset library displays on my phone right now, and it is awesome.

![](http://i.imgur.com/hQWpyhB.jpg)

**Comment by iuloshi** [comment]
hahaha :+1: I feel like @ascott1 is to blame if it involves emoji. :wink:

**Comment by ascott1** [comment]
@iuloshi could it be the local version of the font you have installed is displaying? That is indeed weird.

Also, i am both **SO EXCITED** and completely terrified by the fact that emoji are displaying. :man:

**Comment by mebates** [comment]
LOL

**Comment by ascott1** [comment]
@iuloshi [pointed out](https://github.com/cfpb/cf-icons/issues/23#issuecomment-40757934) that things render fine for her when looking at the cf-icons docs. Was the cf-icons component downloaded through bower or installed manually?

**Comment by himedlooff** [comment]
It's done with bower, it might be out of date. I JUST pushed a new tag 0.2.1 to cf-icons since I made some minor tweaks (not to the fonts though).

**Comment by ascott1** [comment]
I disabled the font locally in Font Book and then the icons fail to load for me:

![screen shot 2014-04-17 at 4 45 54 pm](https://cloud.githubusercontent.com/assets/212533/2736739/5e1fe4d0-c671-11e3-8908-7dca724d7a8b.png)

Similarly when visiting the cfpb.github.io/design-manual on a virtual machine (that does not have the font), I see the same empty boxes. Strangely enough, there is no 404 logged in the console.

**Comment by ascott1** [comment]
What the above means is that @iuloshi is seeing her local copy of the font when she visits the design manual page, but the @font-face version when she looks at the cf-icons docs.

As for @ohsk... :no_mouth:

**Comment by iuloshi** [comment]
hmm So does that mean that because we don't have the minicon font installed on our phones, we're getting emojified?

**Comment by ascott1** [comment]
Exactly!

It looks like the CSS points to a `fonts` directory, but the actuall font files are in a directory called `font` , which would explain why they aren't loading.

**Comment by ascott1** [comment]
[This pull request](https://github.com/cfpb/design-manual/pull/133) should fix. :rocket:

**Comment by iuloshi** [comment]
:sparkles: ADAM SCOTT FOR THE WIN!!! :sparkles: 

Thank you @ascott1!!!

**Comment by ascott1** [comment]
:dancers:

**Comment by ohsk** [comment]
Easter non-Easter non-religious miracle!!!

**Comment by ohsk** [comment]
![](http://i.imgur.com/eXqFGEU.jpg)

**Comment by mebates** [comment]
:star: :star2: :star: :star2: :star: :star2: :star: :star2:

**Comment by Dnpizarro** [comment]
@ascott1 thanks for working on that fix!
