### ISSUE TITLE
Open sourcing our brand assets

### ISSUE THREAD

**Issue by nataliafitzgerald** [cfpb/design-manual#141]
## Open source for visual brand assets

As we move forward with the development and release of the Design Manual we have a unique design opportunity. There is value in open-sourcing certain visual content as it can then be accessed by the larger public to strengthen general visual communications. In deciding which brand assets we share and which we do not, what are the benefits and drawbacks of open sourcing specific assets? 
##### Background

The CFPB visual brand is largely communicated through the look of our core brand assets, including minicons, isocons, illustrations, and beam patterning. Our visual brand is also supported by our color palette and typefaces.   
#### Minicons

The CFPB minicon library is a collection of universal consumer financial icons that make up the third tier of our illustration hierarchy. Making the minicon library available to the public allows it to become a living organism that can evolve, serve other applications, and ultimately reach a wider audience. Because of their universal look and feel, these assets can be used by any organization, company, or individual without a clear visual connection to the CFPB brand. There is a real public benefit to open-sourcing the minicons and there is no risk to the CFPB brand. 
#### Isocons

CFPB Isocons are drawn in an isometric view with specialized styling detail and represent the second tier of our illustration hierarchy. Isocons are easily recognizable as CFPB branded elements. Up to this point, any use of isocons in CFPB branded materials has come directly from CFPB Design. We have not provided our isocon library (vector or raster) to outside contractors or vendors working on CFPB materials. Keeping this library in-house has ensured that our isocons are implemented as intended by our style guidelines. 
#### Illustrations

CFPB illustrations make up the first tier of our image hierarchy. Our illustrations are flat and front or top facing with varied approaches with respect to coloring and detail depending on whether the audience is consumer or industry. Our illustrations are easily recognizable as CFPB branded elements and are closely tied to the brand. Keeping the illustration library in-house has ensured that our standard of consistency in styling and implementation is adhered to.  
#### Beam patterning

The beam of light, represented in the CFPB logo, is an integral part of the CFPB brand. The beam represents our efforts to illuminate the financial landscape and foster transparency in the marketplace. As our brand has evolved we have designed more complex beam patterning. The simple and complex beam patterning is a primary brand element and does not have significance when taken out of the context of our brand.

**Comment by elizbond** [comment]
Can we tweak this a bit and add to the Design Manual as an explanation of our visual hierarchy? I'd say that's a component that is missing from the current pages.

**Comment by nataliafitzgerald** [comment]
@elizbond - I looked at the Design Manual and the thing is that I don't know where this could live in the current structure. As it stands, minicons, isocons, and illustrations are all in their own section. So there isn't a place to talk about the system as a whole. This also brings up the fact that we now have additional tier 2 imagery in the form of circle illustrations and illustrations outside of a circle (that support secondary content, as opposed to hero graphic/top level content. In sum, I agree that this thinking should be documented in the Manual but I am not sure where it could go if we maintain the current structure. Ideas? @klocraft @elizbond @Dnpizarro

**Comment by elizbond** [comment]
Maybe it's something to propose in the [updated IA](https://github.com/cfpb/design-manual/issues/283)

**Comment by Dnpizarro** [comment]
I agree with @elizbond , it would have to be something to add to the new Information Architecture. As it currently exist, your right @nataliafitzgerald there really isn't anywhere in the Design Manual where we can explain that system clearly.
