### ISSUE TITLE
Adjust footer to align with page content

### ISSUE THREAD

**Issue by mebates** [cfpb/design-manual#144]
The footer content doesn't line up well with the page content. Can both sections move over to align left with the left sidebar and main content?

![screen shot 2014-04-18 at 5 44 39 pm](https://cloud.githubusercontent.com/assets/6223901/2746221/c714955e-c742-11e3-894a-1a06fa7b4ec5.png)

**Comment by iuloshi** [comment]
Ha, I just noticed this too.
