### ISSUE TITLE
Add Grid to Design Manual

### ISSUE THREAD

**Issue by iuloshi** [cfpb/design-manual#152]
It's already built out on [Capital Framework](https://github.com/cfpb/cf-grid). Seems like a fundamental design and web standard that should be included.

[CF demo](http://cfpb.github.io/cf-grid/custom-demo/)

**Comment by iuloshi** [comment]
Should this go in UI toolkit? @benguhin @mebates @stephanieosan @ohsk 

I can work on the content and build this out. I think it's important to have for release 1.

**Comment by benguhin** [comment]
assigning to @ohsk

**Comment by iuloshi** [comment]
I [styled it a bit more](http://iuloshi.github.io/design-manual/ui-toolkit/grid-and-layout.html) and removed the prefixing/suffixing, pushing/pulling, and nesting sections from the Design Manual, since they're more FEWD-oriented and are already included on the CF demo site.
- [x] Write copy for intro and Use sections

**Comment by iuloshi** [comment]
High fives! I think that finishes out the content. :punch:

**Comment by mebates** [comment]
w00t! So close! :fireworks:

**Comment by mebates** [comment]
oops, looks like my addition broke something. type should be in georgia; plus the grid dropped out

**Comment by iuloshi** [comment]
Fixed it! Will be updated when my pull request is merged.

http://iuloshi.github.io/design-manual/ui-toolkit/grid-and-layout.html
