### ISSUE TITLE
Math minicons

### ISSUE THREAD

**Issue by elizbond** [cfpb/design-manual#156]
We need math symbols in the form of minicons--
- dollar sign
- plus
- minus
- multiply
- division
- equal
- not equal
- approximately

**Comment by mebates** [comment]
- a percentage sign

Owning a Home has an immediate need to add the percentage for our Loan Options page. Is anyone working on these math symbols? Can we move this to the top of the priority list?

**Comment by mebates** [comment]
Does someone have bandwidth to work on the illustrator files for this? Perhaps Reed? or @ohsk?

**Comment by klocraft** [comment]
@mebates , I've done a few quick minicon mock-ups for print material (with dollar sign, for example). I'm happy to take on this project.

**Comment by mebates** [comment]
Awesome! I think Daniel may have a template that you can use. Thanks!

**Comment by Dnpizarro** [comment]
@klocraft I have a template that you can use. I'll send it to your email.

**Comment by Dnpizarro** [comment]
10/20 Design Manual Review update:
- @klocraft will create the designs for all of the math icons listed above.
- All icons should have circle and non-circle options.
- Once final approval is received, create a new issue to add the new icons to the minicon font.

**Comment by klocraft** [comment]
The math icons are (mostly) straightforward. But any feedback or edits are welcome.
1. The dollar sign, equal sign, and division sign.
   These are all based off the lines and angles of current minicons (i.e. the addition and subtraction minicons. 
   
   Do you think the equal sign should be a little shorter to better fit in the circle?
   
   ![screen shot 2014-10-31 at 12 32 12 pm](https://cloud.githubusercontent.com/assets/8646678/4864403/084a30a6-611c-11e4-9e98-b0b73ae09efe.png)
2. The "does not equal" sign: Consists of the the equal sign (above) + diagonal line from the multiplication symbol. 
   
   Do we have a use case for this? Is it worth pursuing?
   
   ![screen shot 2014-10-31 at 12 41 17 pm](https://cloud.githubusercontent.com/assets/8646678/4864499/ca2fdec8-611c-11e4-82ae-6df9f31cb0d0.png)
3. The percent sign. We are currently using the percent sign in several isocons (Option A). I therefore assume this should be used for the minicon as well. But for the sake of discussion and consistency, I'm exploring an option that follows other math symbol minicons. 
   
   Option B uses the same angle and line weight as both the multiplication and devision minicons, but I think has less readability at 14pts.
   ![screen shot 2014-10-31 at 1 00 41 pm](https://cloud.githubusercontent.com/assets/8646678/4864870/c5e40dbe-611f-11e4-8eee-e8ff2b100224.png)

**Comment by ohsk** [comment]
Looking good! Some quick thoughts:

#### Equals

Maybe in the circle version, the equals sign could be scaled down just a tad? More breathing room within the circle (I think just a bit would help). Your horizontal shortening could also work. 

Maybe they should also be just slightly closer together (also applies to the "does not equal").

#### Percentage

At first glance, Option A feels more resolved, as the circles and the diagonal have a more similar weight. The diagonal in Option B feels awkwardly heavier.

**Comment by nataliafitzgerald** [comment]
These look great, with the changes proposed, can we wrap this up? @klocraft - can you post the other math symbols here too (subtract and add)? 
- Dollar sign looks good. 
- I agree what we should slightly scale down the equals sign when in a circle and the spacing of the bars of the equal sign. 
- I haven't seen a use case for the "does not equal" so I am not sure we need it at this time (unless someone has a need for it?). 
- I prefer Option A for the percent minicon.

**Comment by mebates** [comment]
+1 to all of @nataliafitzgerald's comments

**Comment by klocraft** [comment]
Thanks for the feedback everyone, sorry for missing your original response @ohsk!

I've scaled down the equals sign within the circle; it's definitely feeling better. And I'm only including option A for % (again, this is what our isocons currently use, so option A makes perfect sense).

I'm also posting our current math symbols for direct comparison.

![screen shot 2014-11-17 at 3 41 52 pm](https://cloud.githubusercontent.com/assets/8646678/5077336/43f27404-6e70-11e4-891c-66aa574d458b.png)

**Comment by nataliafitzgerald** [comment]
These minicons look great and are approved. Nice work, @klocraft!

**Comment by Dnpizarro** [comment]
Good work @klocraft ! When you get a chance just send me the file files and I will set up a task to add them to the minicon font.
