### ISSUE TITLE
Body margin bug

### ISSUE THREAD

**Issue by iuloshi** [cfpb/design-manual#165]
Per @Scotchester's [last PR,](https://github.com/cfpb/design-manual/pull/162#issuecomment-41593502), might be related to a cf-grid update.   

![screen shot 2014-04-28 at 2 28 59 pm](https://cloud.githubusercontent.com/assets/1676307/2821180/ffa64a8a-cf02-11e3-8270-829f56bb11ef.png)

**Comment by iuloshi** [comment]
Assigning to @Scotchester since it might be related to a change in `cf-grid`.

**Comment by iuloshi** [comment]
Hey @Scotchester: 

Have you had a chance to look at this bug? At a bare minimum, would love to have this fixed for R1. Thanks!

**Comment by Scotchester** [comment]
R1 is a week from today, right? I'll definitely get it done by then.

**Comment by iuloshi** [comment]
Yep. Thank you kindly!
