### ISSUE TITLE
Flapjack newsroom category minicons

### ISSUE THREAD

**Issue by duelj** [cfpb/design-manual#166]
Flapjack is now working on the newsroom page which will look and function very similarly to the blog but will have different categories to filter and organize the content. We have identified four categories that will need minicons distinct from those for blogs, they are as follows: 
- Speeches
- Op-eds
- Testimonies
- Press releases

**Comment by duelj** [comment]
Here is a concept for the press release minicon that our team was toying with, based off of an earlier design from Daniel and Stephen. 

![screen shot 2014-04-28 at 3 53 18 pm](https://cloud.githubusercontent.com/assets/6873734/2822106/d5a9a4d2-cf0e-11e3-800c-5cd16c80b574.png)

**Comment by elizbond** [comment]
### Updated list

Speeches
Op-eds
Testimonies
Press releases
Blog posts

**Comment by Dnpizarro** [comment]
Here are our recommendations for the Newsroom minicons (minus "Op-eds"):

![screen shot 2014-04-30 at 6 16 41 pm](https://cloud.githubusercontent.com/assets/6852363/2848012/dd2bcd9e-d0b6-11e3-970d-1947aeb08eec.png)

**Comment by duelj** [comment]
Cool, here are some concepts I had on Op-eds to maybe help the thought process. I am guessing that Op-eds just needed some more time since it is a tricky one? Just want to make sure you weren't waiting on us for something to do with the op ed icon. 

![screen shot 2014-05-01 at 11 44 57 am](https://cloud.githubusercontent.com/assets/6873734/2853748/1ca64c06-d148-11e3-8be4-b01cb04f523d.png)

**Comment by elizbond** [comment]
@duelj Good suggestions, we were brainstorming around a pen of some type so I think # 4 makes sense. I'm wondering if we need the chat bubble though? 

We wanted to get you guys suggestions by EOD yesterday and didn't have time to get to it. Thanks for the help.

**Comment by Scotchester** [comment]
:+1: To the fountain pen head, in some form.

The _dual_ speech bubbles seem like they imply a two-way conversation, which an op-ed is not, by definition.

(But I really like the interlocking one, second from left, and would love to see it used somewhere!)

**Comment by Dnpizarro** [comment]
I came up with an option where we use the newspaper elements in a bubble. I'm thinking this approach could potentially function for the "blog" minicon as well if we don't use it here.

![op-eds](https://cloud.githubusercontent.com/assets/6852363/2867745/bf96786c-d23a-11e3-936b-e5e0bd477c7c.png)

**Comment by duelj** [comment]
After a group chat today with FJ we like the idea of using the fountain pen icon for op-eds. We know it exists in the library currently for "contracts" but we were unsure if it was actually  being used? If it is not, can we just use it for op-eds, or is there the potential for overlap like @elizbond suggested and use it for both? 

If it is being used can we use the pen with a modifier of some type? Our hold up with the icon proposed by @Dnpizarro  is that we are relying on the speech bubble too much and feel that it it is going to make it harder on the user to distinguish between icons at a small scale. 

#### The rest of the icons we are comfortable with for the newsroom section.

We are curious if here is some deadline estimate of when the approved icons will make it into the icon font or what the next steps are for adding these to the library for use?

**Comment by Dnpizarro** [comment]
I agree with @duelj on the overuse of the bubble. Below are some options I mocked up based on FJ's suggestions for the fountain pen w/modifier. I also included a more casual pen option at the bottom. 

![screen shot 2014-05-13 at 12 51 33 pm](https://cloud.githubusercontent.com/assets/6852363/2960706/e7e4e4f2-dabe-11e3-9216-639ca1cb8621.png)

**Comment by Dnpizarro** [comment]
I reworked the quotation marks for Testimonies. Let me know your thoughts.

![screen shot 2014-05-13 at 1 07 09 pm](https://cloud.githubusercontent.com/assets/6852363/2960922/1171a89e-dac1-11e3-97a5-773e3e3df63b.png)

**Comment by Dnpizarro** [comment]
Like we discussed in the meeting, I pulled the whole set together, which includes all the Newsroom and Blog minicons. I also gathered all of the explorations we did for Blog incase we decide we like one of those options.

![screen shot 2014-05-13 at 3 54 51 pm](https://cloud.githubusercontent.com/assets/6852363/2963208/893ed006-dad8-11e3-80bd-d8f61b84de5b.png)

**Comment by nataliafitzgerald** [comment]
Below is a document that illustrates my recommendations for the consumerfinance.gov minicons for "Newsroom" and "Blog." The following are approved without comments: Newsroom, Speeches, Press Release/Announcements, Op Eds, Testimonies, Consumer Information, and Innovation. 

For "Blog", the pencil with the quote bubble feels overly complicated and somewhat visually confusing. It could work better if it was a pencil on a box that is not a quote bubble but then we are getting into territory where it may be confused for "edit." So, my recommendation is the quote bubble with the lines. This approach is simple and scales well. 

For "Events & Engagements", the double quotes is confusing for me, however it may be that the label for this category is really what is causing the confusion for me. When I see the word "event" I want to see a calendar or something to that effect. "Engagement" has various meanings depending on who is using it and in what context. With that being said, I leave it up to the Flapjack team to make the final call on whether the calendar or the double quotes works best. 

At some point it could prove useful to test out the final language with consumers, maybe at a later date as the complete library takes shape. Nice work everyone! 

![fj_final round_2](https://cloud.githubusercontent.com/assets/6887128/3018082/a7126306-df81-11e3-8a68-cafdc9b85477.png)

**Comment by ell0ell0** [comment]
Awesome, so we'll go with the speech bubbles for Engagments and events so we can save the calendar/date for specifically events at some point. 

My follow up will then be how soon can these be incorporated into the minicon font for Scott and Mike to start working with in code?

**Comment by Dnpizarro** [comment]
I can incorporate these into the font by this Friday, May 23. I'll include an image of the new set with their respective unicodes.

**Comment by ell0ell0** [comment]
Thats awesome, looking forward to seeing em in the wild. Thanks Daniel.

**Comment by himedlooff** [comment]
The icons have been added to [cf-icons](http://cfpb.github.io/cf-icons/docs/).
