### ISSUE TITLE
Color swatch height

### ISSUE THREAD

**Issue by iuloshi** [cfpb/design-manual#167]
On the [Colors page](http://cfpb.github.io/design-manual/identity/color-principles.html), why are the swatches in the background and secondary colors sections so short now? Was this a decision meant to save vertical space, or a glitch when making the Colors page responsive? 

I personally prefer the taller color swatches for desktop because it visually highlights the vibrancy of the colors themselves, rather than the different color build specs, and the added swatch height doesn't make the page significantly longer. It also reminds me of Pantone color swatches, which is a nice graphical reference.

cc: @Scotchester 

![screen shot 2014-04-29 at 10 54 57 am](https://cloud.githubusercontent.com/assets/1676307/2830383/4e8be08c-cfae-11e3-8d38-3971ae268d5d.png)

**Comment by Scotchester** [comment]
Because comps :)

I can't easily find a place on our public issues here where that comp was posted, but that is how Stephen laid it out. I did make them a little too short, though, I now realize as I refer back to the PDF comp compilation.

**Comment by iuloshi** [comment]
Okay, and I get displaying the hierarchy between the primary and other colors. I'll tweak the sizes a bit.

**Comment by iuloshi** [comment]
Hey and thanks for making it responsive! :+1:
