### ISSUE TITLE
Flapjack "Newsroom" platform minicon

### ISSUE THREAD

**Issue by elizbond** [cfpb/design-manual#171]
Flapjack needs a newsroom minicon because further down the line, there will be a site feed (think Facebook) that will have all our dynamic content show up all together.

**Comment by duelj** [comment]
So after some chatting with the FJ team we would be comfortable with the Newsroom minicon being the same as the proposed press release minicon. In the same way that the blog icon will be an overarching blog section on activity feeds and the like we feel that the press release icon could do that same for newsroom. 

##### I pass this over to Design Ops for their opinion on the overlap

![screen shot 2014-05-01 at 5 25 04 pm](https://cloud.githubusercontent.com/assets/6873734/2857392/1ff2cc34-d177-11e3-93d3-0e50b74c846e.png)

**Comment by elizbond** [comment]
We agree that this fits for Newsroom, but worry using the same icon in a different location could create confusion. It's a little bit of a gray area since Newsroom represents Press Releases (among other things) so anyone could argue that it's okay. However, the Blog icon will not pull from the list of blog category icons. It will be unique. With that in mind, I'm leaning more towards all icons should be unique and there should be no overlap so the treatment is consistent.

@nataliafitzgerald thoughts?

**Comment by Dnpizarro** [comment]
I would agree with everyones comments for using this icon for the "Newsroom" representation. However, I don't think it would work to have this icon also represent "Press release" because it would cause clear confusion. Its still part of the same grouping which is why I am hesitant to use it for both contexts.

**Comment by nataliafitzgerald** [comment]
Since "Blog" and "Newsroom" are on the same level in the minicon hierarchy and "Blog" is a unique identifier, "Newsroom" should follow the same logic and also be a unique identifier. I agree with @Dnpizarro that using the same minicon to represent two different categories could cause confusion.

**Comment by duelj** [comment]
After FJ discussing this icon we are cool with it being the same as newsroom but understand design ops desire to have independent icons. Would there be the possibility of using a podium for this?

**Comment by elizbond** [comment]
Closing this, resolved in #166
