### ISSUE TITLE
Flapjack Share icon

### ISSUE THREAD

**Issue by elizbond** [cfpb/design-manual#172]
Moving the Share icon from #130 to here since it will be used throughout the site and is not a category or a label within the blog but an action.

@Dnpizarro will post his latest revision shortly.

**Comment by duelj** [comment]
Just wanted to get the ball rolling again here, since the discussion moved. I believe we left off with the discussion revolving around the arrows weight compared to the box and there were three versions that were shared (the last one was courtesy of @ohsk and I only had a screenshot of it). 

Are we cool with the third option or is there more work to be done one this? If so, what are the issues/concerns that still exist that need to be resolved?
![screen shot 2014-05-01 at 11 59 46 am](https://cloud.githubusercontent.com/assets/6873734/2853896/12790974-d14a-11e3-92d9-c4e55adf107f.png)

**Comment by duelj** [comment]
I just wanted to spark this conversation again and see if anyone had any input on this icon? I'd be happy to try some things to try and get it buttoned up.

**Comment by ohsk** [comment]
I think the second one just looks bloated and the last one feels a bit more resolved, and I don't think the "genie effect" is so discordant from the minicon style that it's worth deviating from representation used fairly often elsewhere in the web.

Including a slightly crispier version...
![image](https://cloud.githubusercontent.com/assets/1689222/2920458/301102dc-d6e7-11e3-9d95-222c07e93591.png)

**Comment by benguhin** [comment]
agreed with @ohsk that the second one is better but bloated. I think it makes sense to experiment with the "genie effect" a bit further but also to remove the rounded caps from some of the lines – there's probably a compromise between 2 and 3 in terms of edginess.

**Comment by duelj** [comment]
I am happy to use the stock style that @ohsk  found or if we feel the that we need a specific one to our icons would something like this be more what @benguhin was talking about? If not, is it worth us spending more time on it or should we just go with the "off the shelf" style?
![screen shot 2014-05-13 at 11 11 35 am](https://cloud.githubusercontent.com/assets/6873734/2959229/e5587b08-dab0-11e3-8930-969088acce0e.png)

**Comment by ohsk** [comment]
:+1: Nice work, JJ. I think I prefer the second one, and I think this hybrid help alleviate some of the concerns about the genie effect. Perhaps the one thing to tweak a bit is the relative proportion between the rectangle and the arrow (can we try a slightly scaled-down rectangle, so the arrow jumps a bit outside its bounds?).

**Comment by Dnpizarro** [comment]
@duelj good work! The second is definitely a good hybrid solution. I would echo @ohsk suggestion and potentially adding a bit more white space around the arrow.

**Comment by benguhin** [comment]
Sweet. That's a really nice combination of our style and the iOS pattern

**Comment by duelj** [comment]
Here are a couple versions based off of what was discussed in the design crit. meeting today. The main adjustments were, keeping the arrow from the second option I showed above but incorporating the rounded outside box that earlier versions I showed had. 

![screen shot 2014-05-13 at 8 37 58 pm](https://cloud.githubusercontent.com/assets/6873734/2965836/090d4c32-db00-11e3-9160-efacdc2bcfd8.png)

**Comment by nataliafitzgerald** [comment]
@duelj - Both of these options look good to me. The one on the left comes closer to the share convention. Additionally the arrow comes out from the box a bit more so that could drive the point home of "share." So, the left is my recommendation.

**Comment by himedlooff** [comment]
Has anyone brought up that this looks like our external link icon?

![screen shot 2014-06-06 at 11 57 43 am](https://cloud.githubusercontent.com/assets/1093373/3202721/57ac26c4-ed93-11e3-941a-42e2b5813e6d.png)

**Comment by duelj** [comment]
I think this had been considered but we they are both pretty conventional symbols for web including both the font awesome library and bootstrap. I believe between their different use cases and familiarity it should minimize confusion. But, its a great point, if others feel this way we can always reconsider.

**Comment by himedlooff** [comment]
That's true, I bet it'd be clear when seeing them in context. I didn't see the external icon brought up in this thread so I just wanted to point it out. Thanks!

**Comment by ohsk** [comment]
FastCo.Design article today:
[WHY ISN'T THERE A STANDARD SHARE ICON?
AND WHICH ONE IS BEST? A LOOK AT THE MANY (MANY) OPTIONS.](http://m.fastcodesign.com/3031872/why-isnt-there-a-standard-share-button?partner=newsletter)

![](http://i.imgur.com/JFRSoQZ.jpg)

![](http://i.imgur.com/BdV3DaE.jpg)
