### ISSUE TITLE
Download minicon font

### ISSUE THREAD

**Issue by iuloshi** [cfpb/design-manual#175]

**Comment by Dnpizarro** [comment]
Currently we cannot provide a downloadable link to the minicon font because it has not yet been approved for open source. However, I have been in talks with the appropriate parties and we should be getting a definitive answer within the next 2 weeks.

**Comment by Dnpizarro** [comment]
<B>Update: The open sourcing of the Minicon Font has been approved!</B> 

Next steps would be to add a downloadable link from our [minicon page](https://cfpb.github.io/design-manual/identity/minicons.html). Maybe something similar to what is below. I'm open to any ideas…

![screen shot 2015-01-08 at 3 41 00 pm](https://cloud.githubusercontent.com/assets/6852363/5670351/1bf86cf0-974d-11e4-80aa-fc3f1b59e356.png)

Also, we have individual svg files of our whole library of minicons uploaded to [The Noun Project](http://thenounproject.com/cfpb_minicons/). So we should also consider placing a link from our minicon page to that site as well.

**Comment by mebates** [comment]
Sounds great, Daniel. Have you talked to Steve about pushing the latest to designers?

I think we can add a little section on the Noun Project - a few sentences on what it is and why/how we've posted to it.

**Comment by nataliafitzgerald** [comment]
@Dnpizarro 

This is really exciting! +1 on the Noun Project explainer and link. 

Your mock-up looks good. Is there any concern from a UX perspective that the other links in the row are jump links and the download link isn't? It does have the minicon qualifier (and the word "download") to suggest that it serves a different purpose so perhaps it is fine. An alternate location for the "Download" would be under the intro paragraph for the minicon font. Do we have any other instances of downloads on the Design Manual?

**Comment by mebates** [comment]
Link to "The Noun Project" in the top menu. Add a few short sentences about what that is. Add 'Download font' link below the intro paragraph. 

Zip file of all four assets needed for the web: .ttf, .otf, .wofs, .eot, .svg

@Dnpizarro and @Scotchester will double check the assets needed

**Comment by mebates** [comment]
Hey guys - this is looking funky. The button is breaking to two lines in Safari, and I don't think that the link is the correct font. 

![screen shot 2015-01-30 at 11 40 50 am](https://cloud.githubusercontent.com/assets/6223901/5979382/3fee44b6-a875-11e4-8a05-50ed5b3edbaf.png)

**Comment by ohsk** [comment]
Yeah, some of that was noted in PR #266. @Scotchester said some of this may get fixed automatically when they make some of their projected updates to CF as implemented in the Design Manual.

**Comment by Dnpizarro** [comment]
This was already merged in #266
