### ISSUE TITLE
finalize accessibility guide

### ISSUE THREAD

**Issue by benguhin** [cfpb/design-manual#179]
@benguhin and @miulo made some changes, I'm taking a final pass on copy 
http://cfpb.github.io/design-manual/guides/accessible-interfaces.html

ccing the esteemed author @davidakennedy

**Comment by benguhin** [comment]
- [x] decide on whether this should have an image

**Comment by benguhin** [comment]
updated with #183

**Comment by davidakennedy** [comment]
Actually, the copy comes from the legendary John Yuda. :+1: 

Also, two small accessibility issues I want to fix:
- [x] The heading structure skips around a bit. Not ideal. See [Wave report](http://wave.webaim.org/report#/http%3A%2F%2Fcfpb.github.io%2Fdesign-manual%2Fguides%2Faccessible-interfaces.html).
- [x] The links to the W3C site all have the same text, but go to different places. The link text should be more descriptive. We can hide text, if necessary.

I will work on a PR.

**Comment by benguhin** [comment]
good catches! can you do a PR with the more descriptive link text hidden?

**Comment by davidakennedy** [comment]
Yeah, was planning to do it that way.

**Comment by benguhin** [comment]
ok sweet! any chance you can get to this on monday?

**Comment by davidakennedy** [comment]
Will work on this today!

**Comment by davidakennedy** [comment]
Both issues addressed in above PR.

**Comment by mebates** [comment]
@davidakennedy Can we close this issue before you leave? All set?

**Comment by davidakennedy** [comment]
Yep, we're good here. Closing.
