### ISSUE TITLE
Tweak vertical alignments

### ISSUE THREAD

**Issue by iuloshi** [cfpb/design-manual#187]
Perform vertical alignment audit on every page and make tweaks as necessary.

**Comment by iuloshi** [comment]
Hey guys! If you have any last minute minor alignment/spacing tweaks, take a screen cap and drop 'em in some comments here por favor! It'd be helpful if you noted which page they are on too. 

For instance, do you think the examples should be top aligned with the corresponding headers to the left or the body text below the headers (in this case the bullets)? FWIW, almost all of the other examples are top-aligned with the header to the left.
![screen shot 2014-05-19 at 11 13 26 am](https://cloud.githubusercontent.com/assets/1676307/3015934/26d7ebd4-df68-11e3-9554-c131940ba369.png)

Thanks! @mebates @stephanieosan @ohsk

**Comment by Dnpizarro** [comment]
Since Mehgan has left the agency, do we have someone to take over her responsibilities with some of the FEWD stuff she started? Not suggesting we close out this issue, just trying to get a general idea with how we deal with the issues that are assigned to her and still open. We should discuss this with the fewd….

**Comment by iuloshi** [comment]
muahaha I'm still here! Just straight lurkin'. 

:raising_hand: @Dnpizarro!

**Comment by dezzie** [comment]
@iuloshi! HAI!

**Comment by Dnpizarro** [comment]
Hey @iuloshi ! If you're up for it, I think it would be great if we could merge a pull request from you every now and then….

**Comment by iuloshi** [comment]
HAI @dezzie!

@Dnpizarro haha yah, i'll get right on that :wink: Hope you're keeping warm! :guardsman:
