### ISSUE TITLE
Forms guide: rebrand GDS form illustrations

### ISSUE THREAD

**Issue by iuloshi** [cfpb/design-manual#188]
Per #155

**Comment by ohsk** [comment]
Took a first stab at this. Let me know if y'all have suggested changes!
http://ohsk.github.io/design-manual/guides/effective-forms.html

![image](https://cloud.githubusercontent.com/assets/1689222/2884429/c5c3e054-d4aa-11e3-9e7a-cfa9f17c5205.png)

![image](https://cloud.githubusercontent.com/assets/1689222/2884430/caf8498e-d4aa-11e3-90ef-514a0a393884.png)

![image](https://cloud.githubusercontent.com/assets/1689222/2884432/d143b67a-d4aa-11e3-827b-f450f888dee2.png)

![image](https://cloud.githubusercontent.com/assets/1689222/2884434/d8092904-d4aa-11e3-9d8c-67079d30811e.png)

**Comment by iuloshi** [comment]
Beautiful!! 

This is minor and I can adjust in the CSS, but what do you think about possibly scaling down the first single-page illustration and slightly enlarging the other three so that they're all on a more similar scale? That would also kill a lot of the white space beneath "the good" and "the bad" sections next to the first illustration. 

Otherwise I think these are :ok_hand:

**Comment by mebates** [comment]
Nice job @ohsk!

**Comment by dezzie** [comment]
This is so good!

**Comment by ohsk** [comment]
Thanks y'all! @iuloshi, that makes sense to me. Let me know if you need me to reexport to specific dimensions.
