### ISSUE TITLE
Grids page: grid wrapping bug

### ISSUE THREAD

**Issue by iuloshi** [cfpb/design-manual#189]
@Scotchester Do you think this is related to the body margin bug in #165?

![screen shot 2014-05-05 at 12 41 59 pm](https://cloud.githubusercontent.com/assets/1676307/2880402/5e562bbe-d475-11e3-9c43-92ea2086d3e7.png)

**Comment by Scotchester** [comment]
Perhaps. I'll look into that, as well.

**Comment by iuloshi** [comment]
@Scotchester You are my hero.

**Comment by Scotchester** [comment]
I may have fixed this inadvertently when doing the margin thing, but I can't reproduce it now. After my impending PR is closed, please verify if fixed, @iuloshi.

**Comment by benguhin** [comment]
Here's another today in Chrome:
![screen shot 2014-05-20 at 3 05 28 pm](https://cloud.githubusercontent.com/assets/6953063/3031920/d65cec50-e051-11e3-90b8-5e36442f1291.png)

**Comment by benguhin** [comment]
Scott's fork works!

![screen shot 2014-05-20 at 3 08 44 pm](https://cloud.githubusercontent.com/assets/6953063/3031961/35ea3e8e-e052-11e3-8b5b-20c10322a6bb.png)
