### ISSUE TITLE
minicons + links + Georgia

### ISSUE THREAD

**Issue by mebates** [cfpb/design-manual#191]
Point of clarification: Can we use minicons after links set in Georgia? If so, we should probably show an example in the Design Manual.

See the 'more >' link on the Intranet's Resource Library, or the example below: 

![screen shot 2014-05-06 at 2 03 45 pm](https://cloud.githubusercontent.com/assets/6223901/2893464/d2121a3a-d548-11e3-8f13-05251dc13d39.png)

**Comment by mebates** [comment]
Any thoughts on this? Easy to add to the Design Manual if the answer is 'yes'.

**Comment by Scotchester** [comment]
Doesn't bother me any.

**Comment by Scotchester** [comment]
It will also come up with external link and download icons in body copy.

**Comment by mebates** [comment]
We all agreed in the monthly Design Manual Review that this is necessary for in-line use. If the link is not in-line, it should switch to Avenir.

Flagging for @nataliafitzgerald to see.

Moving to R2 Design Manual Maintenance milestone so it can be added to the Manual.

**Comment by nataliafitzgerald** [comment]
+1 on this "We all agreed in the monthly Design Manual Review that this is necessary for in-line use. If the link is not in-line, it should switch to Avenir". 

Sounds like a good solution.

**Comment by Dnpizarro** [comment]
@Scotchester since you are on this thread, do you know how to best get a FEWD to take on this task?

**Comment by Scotchester** [comment]
There isn't really a FEWD task for this. I think someone just needs to write up whatever statement we want to make about it, if any. I'm not sure it actually requires one. The rule really boils down to "Georgia is used for paragraphs and list items in long-read scenarios," which is already well established.

**Comment by mebates** [comment]
@scotchester, I think we're just looking for an example added in the Design Manual. It could go in the Links > Links with Icons section and just be stacked under the Avenir examples. I think if you just did it for Internal and External links, people would get the point.

**Comment by Dnpizarro** [comment]
Reference #264 for clarification
