### ISSUE TITLE
Illustration guidelines

### ISSUE THREAD

**Issue by elizbond** [cfpb/design-manual#192]
In an effort to document the 10 hour ideas session with @duelj, @ajbush, @ohsk, and @nataliafitzgerald I've developed a draft of potential illustration guidelines. I've included feedback from github issues like #50 and various branding conversations with members of the team and outside vendors. The goal is to have more detail, specifically on highlights, shadows, and viewpoint. Feel free to add to and provide feedback. 
# Illustration guidelines

**Illustrations are an important tool for introducing the subject matter of a page, event, or topic.**

Illustrations are vector-based graphics that support primary headers and text. They function as the brand's top-level illustration style with detail and clarity. Illustration is universally relatable and accessible to all audiences. The content of an illustration should always be politically and socially neutral. 
## Consumer illustrations

Consumer illustrations are universally relatable and set a friendly tone when communicating complex topics. 

The color palette should use the full range of primary and secondary colors, but selectively use a maximum of 3-4 colors, using midtones and tints to differentiate components. Illustrations should also make use of 100% white and black.
### Front-facing

These illustrations should feature flat elements and avoid showing things in three dimensions. Elements should not appear to be outlined. 
### Top-facing

Top-facing illustrations are object-based. Illustrations should be arranged in a way that it appears the viewer is immersed in a real life scenario. These should include 4-6 objects and relative sizing to create a realistic and natural perspective. Shadows around objects can be used to create realism in top-facing perspective. If using top-facing perspective in a project, all illustrations should maintain that perspective for consistency.
## Composition

All illustrations should have relative sizing when more than one object is included. Illustrations should appear natural, but stylized. Do not scale-up or collage minicons or isocons for use in illustrations. Minicons can be used as graphic details when scaled appropriately.

Illustrations should be compositionally balanced with related headers and text. Reduce “floating” by bleeding illustrations off the edges of the graphic. Make use of layering and subtle, vector-based background patterns to help ground the illustration. Shadows are appropriate when objects overlap but should not extend outside of objects.

Do not use negative space to define outlines.
## Form

All illustrations should be based on commonly used geometric shapes like circles, triangles, beams, and rectangles. _Complimentary image – pointing out the circles within the car?_

To stylize illustrations according to CFPB standards, use relative sizing on stroke weights with a rounded end cap. For curved lines, the stylized stroke is recommended throughout illustrations. _Show examples in context for both_
## Shading

Objects should be lit from the left side. This is consistent with the beam in our logo.

In front-facing illustrations, shading is permitted when contained within the object. Shadows are also appropriate when objects overlap but should not extend outside of objects. In top-facing illustrations, shadows around objects can be used to create realism.

Shading should be achieved using subtle, solid tints, not gradients, textures, multiply, or blurs. Shadows are created using a darker tint of the background color.
_Image should show two examples, shadow within object and during overlap_
## Highlights

There are two types of highlights available for illustrations; curved and diagonal. The curved highlight is recommended when the object is round. Diagonal highlights are mostly used in rectangular objects. They are also frequently used to show reflections. To create a diagonal highlight, a tint of the background color is cast from the top-right corner of an object at a 45º angle.

The overall placement of highlights and shadows should be carefully decided by the designer and consistent throughout the project.

_Image should show two examples, curved highlights and diagonal highlights._
## Industry illustrations

Industry Illustrations are simple graphics that support a key topic or concept. Industry facing illustrations feature flat, front-facing elements and avoid the illusion of depth by excluding drop shadows and highlights. 

The color palette is green and grey, including midtones and tints and a thoughtful use of whitespace.

**Comment by mebates** [comment]
"Objects should be lit from the left side. This is consistent with the beam in our logo."
I think we need to say upper-left here. Lighting only from the left will not work to give dimension to most objects. 

Do we want to get more specific about materials for highlights? Objects that would shine: glass, metal, etc?

Industry illustrations shouldn't just be front-facing. We used lots of top facing (i.e. piles of paper on a desk) in ideas42.

**Comment by ohsk** [comment]
@mebates, I think you're right about "upper-left" shadow directionality. We can probably show a few examples and call out what they are in terms of reflective material, without being overly proscriptive.

Adding top-facing to industry seems fine to me.

Can we set a deadline for feedback by tomorrow, in order to get this stuff in by the end of the week?

**Comment by ohsk** [comment]
Here's a first stab at mocking-up with supporting visual examples. Still need to find better use-cases for some of these, so please point in the right direction if you have suggest replacements!

For example, I'd like another illustration to show the basic shapes used in the Forms section.

![style_sk_140513_illustration_illustrations copy](https://cloud.githubusercontent.com/assets/1689222/2960050/833c95d2-dab8-11e3-8d9c-ca26b2355f91.png)

**Comment by ohsk** [comment]
From GD Brand Critique today:
- Combine Shading & Highlights into one section
- Add a section describing Shadows specifically

**Comment by ohsk** [comment]
Ok, updated based on the GD Brand Crit on tuesday:
http://ohsk.github.io/design-manual/identity/illustration.html

Let me know if there's any further feedback!

![illustration](https://cloud.githubusercontent.com/assets/1689222/2978753/17151fb2-dbbe-11e3-8791-d486d5c4af47.png)

**Comment by ohsk** [comment]
cc: @nataliafitzgerald @elizbond 

Can y'all take a last look at this before I submit a pull-request for inclusion in the release by tomorrow? [The content is live here.](http://ohsk.github.io/design-manual/identity/illustration.html)

**Comment by stephanieosan** [comment]
@ohsk This looks really good!

The only thing I noticed is that in the shading and highlights section: we talk about both curved and diagonal highlight/shadows being available for use, and we recommend using a curve when the object is round. But, in our examples to the right, we have nothing demonstrating when to use curved highlights and we have a circular coin with a diagonal highlight, which is a little confusing.

Let me know if I'm understanding the rule right, and maybe it's just a matter of tweaking the wording:
do we use a diagonal highlight because the coin (although in the shape of a circle) is in fact, flat? And we'd use a curved highlight to for an object that is three-dimensionally a sphere, not just two-dimensionally round?

**Comment by ohsk** [comment]
@stephanieosan thanks! Yes, we should amend to include an example. 

I think you're reading the coin thing right. The surface is flat and metal, so it has a sheen, as opposed to showing a curved shadow on a dimensional sphere. The coin does have a curved shadow around its rim:

![image](https://cloud.githubusercontent.com/assets/1689222/2998639/0bff9418-dd0d-11e3-906e-7ae7134134f0.png)

We have three things right now that I see having a curved shadow are below. It is most evident in the yarn ball, but I was hesitant to include that because we haven't really used in it any final graphics. 

![image](https://cloud.githubusercontent.com/assets/1689222/2998692/c569c1c6-dd0d-11e3-9e47-477ea4558adf.png)

Can anyone remember anything else? This is what I have from the approved library...

**Comment by elizbond** [comment]
My only feedback would be do we need to show a variety of shading/highlight examples. Right now it's limited to the diagonal highlight. Should the page also show examples of the the the straight up and down shading, as well as the round shading Stephanie mentioned?

**Comment by ohsk** [comment]
Updated with additional examples + call-outs for Shading & Highlights:

![image](https://cloud.githubusercontent.com/assets/1689222/3033766/76ab21de-e068-11e3-9f7c-1680796f4122.png)

**Comment by ohsk** [comment]
Updated via PR #205 to address @elizbond's [concerns here](https://github.com/cfpb/design-manual/issues/192#issuecomment-43344608). @nataliafitzgerald, et al, let me know if you catch anything else!

**Comment by stephanieosan** [comment]
:+1: awesome!

**Comment by nataliafitzgerald** [comment]
@ohsk This is looking great! Just a few comments: 

For the house illustration, did you pull in the most up-to-date version? We had been looking at one with the line down the middle in the examiner video but I'm not sure where we landed on that. I recall we were looking at a few variations. Wherever you think we landed works for me.  
![screen shot 2014-05-21 at 3 41 14 pm](https://cloud.githubusercontent.com/assets/6887128/3045692/035cd412-e120-11e3-94fb-968d1d2fa252.png)

Do you imagine that at a later date we would be able to update the illustration examples as we have more? We are kind of "Paying for College" heavy at the top. 

My eye is getting stuck where we have a header 3 followed by a header 4. In this layout it's where we have the word "Viewpoint" and then "Front-facing." "Front facing" is anchored at the top of the image box but "Viewpoint" feels like it's floating. Is there any way we can address this or are there more global reasons as to why we have it like this?

**Comment by ohsk** [comment]
Thanks @nataliafitzgerald!

The house I pulled in there was straight from the approved video storyboard, so I'm game to go with that. I think the line down the middle is an example of a shadow that we're generally avoiding in Industry-facing illustrations.

I definitely think we can pull in new illustrations examples down the road. I was trying to be conscious of using examples that are "live in the wild," so to speak. The good thing is that even though we know that the examples at the top are all from Paying for College, I think they'd feel fairly generalist to someone unfamiliar with where they've been deployed.

Let's note your concerns regarding vertical alignment with the different headers on issue #187 that @iuloshi started.

**Comment by ohsk** [comment]
Closing as updates have been included in the initial release!
