### ISSUE TITLE
IE jankiness

### ISSUE THREAD

**Issue by iuloshi** [cfpb/design-manual#199]
Per @virtix:

> The manual, as well as http://cfpb.github.io/, is quite janky in IE.  This is less of an issue for our target audience, but I would put it at the top of the queue.  The reason being is that I suspect this could get picked up broadly and it would be great if it also worked broadly.

cfpb.github.io repo [issue #30](https://github.com/cfpb/cfpb.github.io/issues/30)

**Comment by mebates** [comment]
- minicons don't display on Buttons or Expandables page
- Grey box linking to Capital Framework is messed up on all UI pages:
  ![screen shot 2014-05-20 at 12 26 27 pm](https://cloud.githubusercontent.com/assets/6223901/3030003/b960b3ea-e03b-11e3-9c90-70c06b0d509a.png)

**Comment by Scotchester** [comment]
Something about the Effective Forms guide is making IE8 freak out (ish). It makes the page way wider than it needs to be. Still trying to run down exactly why.

**Comment by Scotchester** [comment]
Effective Forms layout bug fixed in #204!

**Comment by Scotchester** [comment]
Minicons and repo boxes should be fixed with #206.
