### ISSUE TITLE
Homepage > "Help us make improvements" section

### ISSUE THREAD

**Issue by iuloshi** [cfpb/design-manual#200]
Add copy/links outlining _how_ people can contribute to the Design Manual through forking, pull-requests, and filing issues and bugs, etc.

**Comment by benguhin** [comment]
"concrete steps" to be created by @michelet

include this in the overview as well as the readme
- possibly via email or github issue?

**Comment by micheletepper** [comment]
Just realized that I never got this issue because I'm not michelet on public GitHub.

We need to have a method for designers who don't have GitHub accounts (or find making pull requests to text as completely user-hostile as it actually is) to make suggestions. Can we accept emails?

**Comment by Scotchester** [comment]
Sure, I'd say have them email tech@consumerfinance.gov.

**Comment by micheletepper** [comment]
OK. So maybe the language is "Not on GitHub? Email us your suggestions at tech@consumerfinance.gov"

I can't seem to reopen this issue, @Scotchester; can you do so? (See previous point about designers who don't know how to use GitHub…)

**Comment by Scotchester** [comment]
Sure thing!

**Comment by benguhin** [comment]
+1 to the email address option that @micheletepper mentioned

**Comment by stephanieosan** [comment]
This has already been implemented.
