### ISSUE TITLE
Add note about these standards being our newest

### ISSUE THREAD

**Issue by stephanieosan** [cfpb/design-manual#203]
We want to explain how our latest standards are reflected here, and they are not yet incorporated into all of our (older) web products. Everything moving forward is being designed with these. Provide examples of products where you can see these standards in place. 

@sosan will write up the content for this

Someone else needs to add it to various places:
- the readme
- somewhere on the actual design manual. footer?

**Comment by ohsk** [comment]
Brainstorming the projects / products / pages that I think are closest in representing the current identity and UI guidelines. Mainly assessed from the standpoint of button styles, typography, colors, illustration, and iconography.

We could probably just pick 2-3 to point people to if we felt it's still important as part of declaring that the majority of our web products are not yet reflective of our new standards.
- E-Regs
  - [landing page](http://www.consumerfinance.gov/eregulations/)
  - [Regulation Z](http://www.consumerfinance.gov/eregulations/1026)
  - [Regulation E](http://www.consumerfinance.gov/eregulations/1005)
- HMDA
  - [landing page](http://www.consumerfinance.gov/hmda/)
  - [/explore](http://www.consumerfinance.gov/hmda/explore)
  - & other subpages
  - [API documentation](http://cfpb.github.io/api/hmda/)
- Consumer Complaints
  - [landing page](http://www.consumerfinance.gov/complaint/)
  - [/process subpage](http://www.consumerfinance.gov/complaint/process/)
  - [/data-use subpage](http://www.consumerfinance.gov/complaint/data-use/)
  - [Debt Collection form](https://help.consumerfinance.gov/app/debtcollection/ask)
  - [Payday Loan form](https://help.consumerfinance.gov/app/payday/ask#currentPage=0)
- Paying for College
  - [landing page](http://www.consumerfinance.gov/paying-for-college/)
  - & all the subpages

Others that are somewhat reflective:
- Spanish site
  - [cf.gov/es](http://www.consumerfinance.gov/es/)

**Comment by mebates** [comment]
Any thoughts on this @stephanieosan? I'm working to revise the launch announcement.

**Comment by stephanieosan** [comment]
How about this:

These standards reflect our latest thinking and are just beginning to be incorporated into the CFPB's most recent projects. See these standards in practice in [eRegs](http://www.consumerfinance.gov/eregulations/), [Consumer Response](http://www.consumerfinance.gov/complaint/), and [HMDA](http://www.consumerfinance.gov/hmda).

**Comment by mebates** [comment]
Looks good to me. I'll incorporate into the ReadMe and Launch Announcement.

**Comment by Scotchester** [comment]
Sounds good! :+1:

**Comment by iuloshi** [comment]
Do we want to add it to the actual Design Manual also? In the footer perhaps?

**Comment by stephanieosan** [comment]
I'm onboard with adding it to the footer, unless someone feels strongly that we shouldn't. @iuloshi you up for handling that?

**Comment by iuloshi** [comment]
Can do!
