### ISSUE TITLE
Desktop computer

### ISSUE THREAD

**Issue by elizbond** [cfpb/design-manual#207]
Design Ops has discovered the need for a desktop computer illustration. As we continue to build on collaging illustrations, it sometimes feels awkward to position objects in front of the laptop (see below). 

![screen shot 2014-05-22 at 10 17 51 am](https://cloud.githubusercontent.com/assets/6798337/3054923/1aa83b88-e1bc-11e3-9b6f-fb52aebdec9c.png)

We think a desktop computer would be more appropriate here.

**Comment by ell0ell0** [comment]
How about something like so?

![monitor2](https://cloud.githubusercontent.com/assets/3589375/3059753/720ab788-e1ef-11e3-91b4-ce0095f64bb4.png)

**Comment by ohsk** [comment]
Oh, please send that over, @ell0ell0! Forgot you had something like that already.

**Comment by ell0ell0** [comment]
also added the back as well now

![monitor_back](https://cloud.githubusercontent.com/assets/3589375/3106972/d3ac754a-e680-11e3-93a4-4bc02940c1ab.png)

**Comment by nataliafitzgerald** [comment]
@ohsk Can we explore what this would look like if the monitor was a gray tone rather than black. I think having this black option is good but there will be use cases where we need a gray/silver monitor.

**Comment by nataliafitzgerald** [comment]
Hi @ohsk. I made some adjustments to the desktop computer to make it a bit less Mac like. Here it is on it's own... 
![screen shot 2014-06-04 at 2 38 32 pm](https://cloud.githubusercontent.com/assets/6887128/3178159/78426bfa-ec17-11e3-8e07-872a7d480f6c.png)

And in the context of a composition:

![screen shot 2014-06-04 at 2 41 27 pm](https://cloud.githubusercontent.com/assets/6887128/3178197/e7715086-ec17-11e3-8a52-48373773f87b.png)

**Comment by ohsk** [comment]
Sounds good! Can you send me the AI for inclusion in the asset library?
