### ISSUE TITLE
Is there a representative screencap we can add to the Videos page intro section?

### ISSUE THREAD

**Issue by iuloshi** [cfpb/design-manual#212]
All of the other Identity pages have accompanying graphics in the intro sections. Any ideas on what we could use for the [Videos page?](http://cfpb.github.io/design-manual/identity/video.html)

**Comment by mebates** [comment]
We should link to YouTube videos on this page as well.

I think the best one live on YouTube now is the [e-Closing video](https://www.youtube.com/watch?v=NPJYaqf7Ng4). Something like this?

![screen shot 2014-06-02 at 2 04 09 pm](https://cloud.githubusercontent.com/assets/6223901/3151266/73bf7214-ea80-11e3-90a3-9e93337130d9.png)

**Comment by mebates** [comment]
Or, a still from 'Cordray's Corner' https://www.youtube.com/watch?v=rBrZeomtFsk

![screen shot 2014-06-02 at 2 09 49 pm](https://cloud.githubusercontent.com/assets/6223901/3151330/3b718608-ea81-11e3-9c78-1a69ea01fc2c.png)

**Comment by stephanieosan** [comment]
Closing this since it's old and the video section has plenty of images.
