### ISSUE TITLE
Change purse illustration

### ISSUE THREAD

**Issue by nataliafitzgerald** [cfpb/design-manual#216]
A change purse would be a useful addition to our illustration library as we are always looking for new ways to show money. Although the wallet is great for highlighting dollar bills and credit cards, the change purse would provide an option for showing coins, where the coins would be in front of the purse in a composition.  

This is the style of change purse I was envisioning: 

![screen shot 2014-06-06 at 12 12 07 pm](https://cloud.githubusercontent.com/assets/6887128/3202871/5649d374-ed95-11e3-84a4-b862f5dc9141.png)

**Comment by Dnpizarro** [comment]
I'm ok with this idea, but this feels more gender specific to women. I only raise this questions because I thought we were generally trying to stay gender neutral with our illustrations.

**Comment by nataliafitzgerald** [comment]
I can see what you're saying @Dnpizarro but I do feel our exiting wallet skews male. I'm not super concerned about that, though, and it's come in handy in a lot of compositions. I'd be interested to hear other thoughts on this. I clearly don't feel strongly as I started the issue back in June and no progress has been made but it brings up a good discussion topic about gender neutral objects. 
![screen shot 2014-11-14 at 6 21 44 pm](https://cloud.githubusercontent.com/assets/6887128/5055033/33ec3abe-6c2b-11e4-8ab0-f73b22e0e779.png)

**Comment by stephanieosan** [comment]
Do we have a money clip in our library? That could be an alternative to a change purse that is a little less gendered (although it possibly also skews male).

![dosh_metal_money_clip](https://cloud.githubusercontent.com/assets/6433178/5072363/fcfb3136-6e46-11e4-846c-874a4d5138b3.jpg)

**Comment by stephanieosan** [comment]
We don't approve illustrations through the design manual anymore.
