### ISSUE TITLE
Header Links: Active Style

### ISSUE THREAD

**Issue by danny8000** [cfpb/design-manual#22]
I added a css class to the current, or "active" header. I just added a background color to show that the class is working. We will need a comp for the active state.

**Comment by danny8000** [comment]
Please see:

http://danny8000.github.io/design-manual/guides/design-best-practices.html

**Comment by mebates** [comment]
It should match what the Intranet does on active state.

**Comment by Scotchester** [comment]
The intranet just leaves the hover state up.

**Comment by danny8000** [comment]
Fixed!
