### ISSUE TITLE
Paying for college isocon

### ISSUE THREAD

**Issue by ell0ell0** [cfpb/design-manual#224]
Hi everyone, it seems we don't have an official isocon for paying for college. It isn't in the brand 2.0 manual. Stephen didn't have anything, Justin had a few options, Daniel may have the latest, but he's out for his honeymoon. Anyhow I wanted to get this conversation going because I think there will be a need for an official isocon.

![paying_for_college_isocons](https://cloud.githubusercontent.com/assets/3589375/3302209/88b37252-f632-11e3-95ac-dc6389d74268.png)

**Comment by jehlers** [comment]
I think the tassel for 2 is working the best. The ones where the bottom part is disconnected is a little distracting.

**Comment by ajbush** [comment]
I like 2 as well

**Comment by mebates** [comment]
None of our isocons currently feature shading. I vote for 2, minus the shading.

**Comment by stephanieosan** [comment]
I'm also in favor of 2 minus the shading.

**Comment by ell0ell0** [comment]
Voila.

I'll move forward with this guy

![paying_for_college_isocon](https://cloud.githubusercontent.com/assets/3589375/3315503/d5a2c428-f6fa-11e3-804d-1c2ed10e041c.png)

**Comment by stephanieosan** [comment]
:boom:

**Comment by mebates** [comment]
Closed. See issue #235.
