### ISSUE TITLE
Forms: Dropdown styles

### ISSUE THREAD

**Issue by mebates** [cfpb/design-manual#229]
We don't have a consistent style for dropdowns. Has the flapjack team developed one?

HMDA: 
![screen shot 2014-06-26 at 3 35 29 pm](https://cloud.githubusercontent.com/assets/6223901/3403754/8d40cdf4-fd69-11e3-821f-7c4e7fc530e8.png)

OaH Proto:
![screen shot 2014-06-26 at 3 40 06 pm](https://cloud.githubusercontent.com/assets/6223901/3403774/b7a8828a-fd69-11e3-8ce2-7c5b319b0bf7.png)

PFC:
![screen shot 2014-06-26 at 3 36 12 pm](https://cloud.githubusercontent.com/assets/6223901/3403777/c1babfe0-fd69-11e3-9d60-90f40eb07390.png)

**Comment by himedlooff** [comment]
These all look like `<select>` styles. cfgov-refresh is using a similar style that eRegs/OAH are using. Ours is of course slightly different though. It's a jQuery plugin we created (soon to be moved to capital framework, and is also accessible) that transforms a `<select>`.

You can play with it here: http://cfpb.github.io/cfgov-refresh/blog_static/landing.html

And here's a screenshot:

![screen shot 2014-06-26 at 3 55 52 pm](https://cloud.githubusercontent.com/assets/1093373/3403981/065cc290-fd6c-11e3-8405-611f77c75334.png)

Notice that clicking it activates the native select menu, this gives us keybaord and screen reader accessibility for free instead of having to throw a ton more javascript at it:

![screen shot 2014-06-26 at 4 01 17 pm](https://cloud.githubusercontent.com/assets/1093373/3404038/ab4a7b44-fd6c-11e3-83ae-6d95e1309b7d.png)

One thing that seems a little inconsistent with form elements is the border/text color. Is the border black or gray? I've seen form elements with both color borders. Also I think the default placeholder text is gray and then is supposed to turn black when something is selected. Can we agree on the colors for all states please?

**Comment by mebates** [comment]
Nice. I love the caret minicon in the dropdown, and the bright blue when you select. 

We should look at color contrast on the light gray type on white, and the medium gray arrow on light gray. In the proto, it almost looks like those dropdowns are not available for me to click (like, disabled), since they're so gray!

**Comment by himedlooff** [comment]
Oh right, the caret was actually used because we didn't have a down-facing triangle in the icon font. So it's kind of a mistake but...

**Comment by benguhin** [comment]
+1 on the caret, I think that works well. Also agree with @mebates that it could use more contrast

**Comment by jehlers** [comment]
Just to add a few more examples to this conversation:

CR
![screen shot 2014-06-30 at 12 38 51 pm](https://cloud.githubusercontent.com/assets/4267825/3432492/443efb9e-0075-11e4-9cbd-8086152de19a.png)

EREGS
![screen shot 2014-06-30 at 12 39 57 pm](https://cloud.githubusercontent.com/assets/4267825/3432494/4b0cc15e-0075-11e4-87e6-37e04ccd322a.png)

**Comment by jehlers** [comment]
I'm noticing some trends that we can consolidate in the above examples. What do you guys think?
- The text in a drop down should be black (unless it is defaulting to explanatory text or something that isn't actually selected)
- The outline should be gray (I think we are all mostly using #d0d0ce)
- Down caret needs to be the darker gray #75787b (so it is accessible)
- The height of the boxes should always be the same

Examples:

Text at 16pt and Label at 12pt

![screen shot 2014-06-30 at 4 41 38 pm](https://cloud.githubusercontent.com/assets/4267825/3435583/f9f9211e-0096-11e4-8216-799266aa65dc.png)

Text at 12pt and Label at 12pt

![screen shot 2014-06-30 at 4 39 38 pm](https://cloud.githubusercontent.com/assets/4267825/3435571/e8164bd4-0096-11e4-83a0-35a0a2fcba9b.png)

Some other questions I have:
- What about Arial? When do we use it over Avenir Next?
  - Right now, in Owning a Home, I think we are using Avenir for drop downs and Arial for user input text boxes
- Label size?
  - Flapjack seems to be using the h6 style - 12pt All Caps
- Font size inside drop downs and text boxes?
  - Should it be 12 or 16?

**Comment by himedlooff** [comment]
In flapjack we've identified two form label patterns, a form label header and a standard form label.
- http://cfpb.github.io/cfgov-refresh/docs/misc/#form-pattern-showcase
- http://cfpb.github.io/cfgov-refresh/docs/misc/#form-labels

Also regarding border colors they should be consistent with other form elements right? Like text inputs and custom select menus and custom checkboxes should probably use the same border color.

**Comment by jehlers** [comment]
@stephanieosan and I have been using these drop down styles in the Owning a Home Loan Comparison tool, and want to try to solidify this standard by EOD Monday if possible.

Based on my [last comment](https://github.com/cfpb/design-manual/issues/229#issuecomment-47583732), we have been using these drop downs:

![screen shot 2014-07-23 at 4 35 13 pm](https://cloud.githubusercontent.com/assets/4267825/3679819/e4bd16ec-12a8-11e4-99e0-0c9fdc3ff5aa.png)
- The text in a drop down is black (unless it is defaulting to explanatory text or something that isn't actually selected)
- The outline is gray (I think we are all mostly using #babbbd) 
- Down caret is the darker gray #75787b (AKA 'Gray') (so it is accessible)
- The actionable part of the drop down (behind the caret) is the lightest gray (#f1f2f2) (AKA Gray 10%)
- The height of the boxes are 32px with 16pt font inside

Some more questions I have:
- **Do we need to decide on standard labels?** So far, it seems like the H6 style is working when the label is directly above the form field, but if they are stacked to the left, the all caps does not read very well. Is this something that should be defined as a standard, or can it be designed on a case by case basis so long as it follows out standard type hierarchy?
- **What about Arial? When do we use it over Avenir Next?** Right now, in Owning a Home, I think we are using Avenir for drop downs and Arial for user input text boxes. @ell0ell0 and @duelj what are you guys using? @iuloshi? 
- **Are we happy with 16pt font inside the drop downs?** Or should we go down to 12?

What do you guys think? Can we agree on the final solution here, or do we need to discuss this in the UI meeting?

**Comment by mebates** [comment]
- Your outline color should be one of the grays defined in Design Manual. I crosschecked and updated your issue. 
- I think the form label should not be part of this UI discussion, for now. Whatever the form label is should be within the hierarchy.
- I think the font should be black and 16 pt inside the drop down. I'm neutral on Arial vs. Avenir - is it much more work to make it Avenir?

**Comment by jehlers** [comment]
@mebates Not positive where i got that gray (must have been an old swatch), but I updated it to this gray hex #babbbd

**Comment by Dnpizarro** [comment]
Looking to pick this discussion up.

Based on what I gather, @himedlooff has documented these patterns from FJ here:

http://cfpb.github.io/cfgov-refresh/docs/misc/#custom-select-menus-via-jquerycustom-input

Do we feel like these patterns appropriately consolidate the drop-down styles? If so I would like to move this towards an approval so that we can update this on the Design Manual. 
- Note: I'm not seeing the carrot in this documentation. The down facing carrot should be in the icon font.

**Comment by himedlooff** [comment]
Yeah sorry, we're moving away from using github pages in that repo but you can see the same docs internally on our Refresh server `REFRESH_SERVER/docs/misc/#custom-select-menus-via-jquerycustom-input`.

**Comment by Dnpizarro** [comment]
I'm going to queue this up for the Design Manual Review on Monday.

**Comment by mebates** [comment]
This was approved in the Design Manual review, as long as the gray caret changes to a darker shade. @himedlooff and @Scotchester, is the next step to add it to Capital Framework and the Design Manual?

**Comment by himedlooff** [comment]
Yeah, we'll queue it up.

**Comment by mebates** [comment]
@himedlooff and @Scotchester. Is this in Capital Framework now? Could you copy in a link here? And, can/will it be added to the Design Manual once we complete #256 ?

**Comment by himedlooff** [comment]
It has not yet been added to Capital Framework. I just created an issue in the CF repo, you'll see it referenced here in this thread so that you can easily follow the status.

**Comment by mebates** [comment]
Steps to close out this issue:
- [ ] Add to the Design Manual
- [ ] Update Capital Framework
- [ ] Update .ai template(s) to reflect new standard

**Comment by benguhin** [comment]
I think the usage notes need to include the many caveats of dropdowns - see LukeW's recent post [Dropdowns Should be the UI of Last Resort](http://www.lukew.com/ff/entry.asp?1950) or the examples from the Government Digital Service of users struggling with dropdown menus: [Alice Bartlett: Burn your select tags - EpicFEL 2014](https://www.youtube.com/watch?v=CUkMCQR4TpY)

**Comment by stephanieosan** [comment]
Form fields are in progress, which includes this. They need to be taken across the finish line. There's already a PR here: https://github.com/cfpb/design-manual/pull/363
