### ISSUE TITLE
[DATA VIZ] standards

### ISSUE THREAD

**Issue by stephanieosan** [cfpb/design-manual#230]
Here are screenshots from the excel file. Also emailing the team the document. @mebates Did you have concerns about any of the principles outlined, or just the recommended color palette?

![screen shot 2014-06-26 at 5 52 27 pm](https://cloud.githubusercontent.com/assets/6433178/3405348/4a846274-fd7c-11e3-9563-b0866478cc85.png)
![screen shot 2014-06-26 at 5 52 48 pm](https://cloud.githubusercontent.com/assets/6433178/3405349/4a96358a-fd7c-11e3-9d81-7f079eea5f73.png)
![screen shot 2014-06-26 at 5 52 58 pm](https://cloud.githubusercontent.com/assets/6433178/3405350/4a98348e-fd7c-11e3-9e58-1824980c8c9b.png)
![screen shot 2014-06-26 at 5 53 05 pm](https://cloud.githubusercontent.com/assets/6433178/3405351/4a98b4d6-fd7c-11e3-8022-da5a404cd344.png)
![screen shot 2014-06-26 at 5 54 57 pm](https://cloud.githubusercontent.com/assets/6433178/3405373/91b9d3d6-fd7c-11e3-800e-d1b0f4ffee84.png)
![screen shot 2014-06-26 at 5 55 06 pm](https://cloud.githubusercontent.com/assets/6433178/3405375/979ba86a-fd7c-11e3-89ac-f27e536f076e.png)
![screen shot 2014-06-26 at 5 55 10 pm](https://cloud.githubusercontent.com/assets/6433178/3405376/97c76202-fd7c-11e3-9c34-5340eccf55e2.png)

**Comment by mebates** [comment]
Thanks Stephanie. My issue is only with the palette, and mainly with the pie chart. (The thoughts below also apply to the bar chart with Green and Teal at 100%) I came upon them when I was working on the CR Snapshot graphs this last time around. 
- To me, the palette is too heavy overall. I think the Teal and Neutral at 100% dominate the CFPB Green shade, giving those wedges more importance than the primary wedge. 
- In addition, I find that having the Neutral as an early part of the palette creates a 'Thin Mint' palette, which doesn't seem on brand to me. The scheme is jarring. 
- I'm worried that sequencing the same value tones next to each other makes it hard to read, and would be harder when photocopied. Instead of 100%, 100%, 100%, 80, 80, 80, etc., I think it should be 100, 80, 50, 100, 80, 50 or something of that sort.
- Unfortunately, we have to plan for a lot of wedges. As much as we want to limit it, our clients don't.
- We also need to look at how the palette looks in CMYK and RGB in Adobe Creative Suite. Excel lightens the colors quite a bit.
- (I can't find the palette with Pacific in your Excel file, my comments are about 6 wedge+ palette. We should think through how the palette works with 2-10 wedges) 

Excel palette:
![screen shot 2014-06-27 at 3 37 56 pm](https://cloud.githubusercontent.com/assets/6223901/3416956/c23e17a4-fe32-11e3-8d8e-62de2714d937.png)

CMYK palette, matching Excel (appears so much darker):
![screen shot 2014-06-27 at 3 38 42 pm](https://cloud.githubusercontent.com/assets/6223901/3416958/cc25514c-fe32-11e3-9cef-bd8d2590f8c6.png)

Alternative palette (just a starting point):
![screen shot 2014-06-27 at 3 41 24 pm](https://cloud.githubusercontent.com/assets/6223901/3416973/115cb6f6-fe33-11e3-8373-960be6f14326.png)

**Comment by stephanieosan** [comment]
During the crit today, we talked about high-level goals for the revised color palette:
- avoid 100% teal, it's too dark in CMYK
- avoid the neutrals for large slices, feels less on-brand
- avoid using tints of the same color adjacent to each other, makes it seem like there is a correlation
- try to use varied levels of tints next to each other 100,80,50,etc (better for contrast + accessibility)

To follow up on:
- Test that the palette works when photocopied
- Test that colors work for color blind users 
- Test that palette works in grayscale

**Comment by mebates** [comment]
Working on the complaint graphs again. How about this scheme? It pulls in some lighter shades of Pacific before going to the brown.

![screen shot 2014-07-11 at 2 18 05 pm](https://cloud.githubusercontent.com/assets/6223901/3556751/d987533a-0927-11e4-8cfc-4c07ad0ebbd4.png)

![screen shot 2014-07-11 at 2 21 25 pm](https://cloud.githubusercontent.com/assets/6223901/3556783/35283aba-0928-11e4-8a7a-9a0457205221.png)

**Comment by elizbond** [comment]
How would this work for line graphs so there is enough contrast between lines if printed in black and white?

**Comment by Dnpizarro** [comment]
@stephanieosan and @mebates, has there been any testing on the following, as stated above:
- Test that the palette works when photocopied
- Test that colors work for color blind users
- Test that palette works in grayscale

Also, to follow up on @elizbond question, any idea on how this would work with line graphs?

**Comment by elizbond** [comment]
When the Teal 50 is next to the CFPB green, there's not enough contrast in grayscale.

**Comment by elizbond** [comment]
Recent questions about histograms from the data team.

"We were recently asked about whether there was any guidance on how many bins should be shown in a histogram.  Does anyone on your team know of any research about this?  We found something about optimizing bin size but not # of bins.  If we need to, we can just try out different bin sizes during our larger regroup."

After asking Twitter, this is what they found.

"The bin sizes really depend on the data.  With that being said you would have to experiment and play with different bin sizes to determine what the best size is.  If bins are too big you could miss trends vice versa."

Do we have any recommendations or preferences?

**Comment by amycesal** [comment]
Pulling up this issue again. 

I'd like to see if we can take a holistic look at the data visualizations CFPB creates and hopefully include some standards and guidelines in the design manual. It would be super awesome if we could do some user testing too. 

I lead the creation of a data visualization style guide for the Sunlight Foundation, which might be a good start. It's probably more informal in tone than we would want, but I think having suggestions on what type of graph is appropriate is useful. http://sunlightfoundation.com/blog/2014/03/12/datavizguide/

**Comment by elizbond** [comment]
+1 @amycesal when things settle down post-immersion I'll work with you to gather examples I've seen go out the door. We can loop in Erin Simpler from the data team too!

**Comment by amycesal** [comment]
Basically, I just want to start by compiling a list of stuff we've done. That way, we can look at trends, what's working, what isn't and start to make some decisions about standards going forward. This is my "crazy call for examples". 

## Maps

HMDA http://www.consumerfinance.gov/hmda/
![screen shot 2015-06-02 at 4 18 38 pm](https://cloud.githubusercontent.com/assets/1656046/7946220/6d60ae78-0943-11e5-967a-0c5d827bf8b6.png)

## Bar Graphs

HMDA http://www.consumerfinance.gov/hmda/
![screen shot 2015-06-02 at 4 22 20 pm](https://cloud.githubusercontent.com/assets/1656046/7946277/b2b065d6-0943-11e5-96fc-6e7eaeb29d33.png)

Owning a Home http://www.consumerfinance.gov/owning-a-home/check-rates/
![screen shot 2015-06-02 at 4 25 12 pm](https://cloud.githubusercontent.com/assets/1656046/7946326/036672d6-0944-11e5-81af-d67934ffae68.png)

Excel Templates/reports
![screen shot 2015-06-02 at 4 35 42 pm](https://cloud.githubusercontent.com/assets/1656046/7946585/792d2a4a-0945-11e5-9cbb-313e1a822d33.png)

Consumer Response 1 pager
http://files.consumerfinance.gov/f/201503_cfpb_complaints-by-the-numbers.pdf
![screen shot 2015-06-02 at 4 45 10 pm](https://cloud.githubusercontent.com/assets/1656046/7946790/cf971dfe-0946-11e5-8a57-c55273a4c296.png)

What else have we done @exafox @tanderegg @stephanieosan @ohsk @designlanguage @mebates ?

**Comment by stephanieosan** [comment]
What about Tableau visualizations? @elizbond

**Comment by exafox** [comment]
Yes @stephanieosan, at least the complaint topline reports should be under consideration. (There a number of other Tableau dashboards as well.) 

Also the Mortgage Chartbook would be something worth studying, as a lot of work that goes into it and it is pretty sharp. 

Send me an old fashioned email and we can see about getting you folks copies?

**Comment by elizbond** [comment]
I decided to go through some of the data-heavy reports and pull out any custom charts we did (i.e., outside of the excel template). Examples with the source material are below.

### Consumer credit reports: A study of medical and non-medical collections

[Report](http://files.consumerfinance.gov/f/201412_cfpb_reports_consumer-credit-medical-and-non-medical-collections.pdf)

![screen shot 2015-07-02 at 11 05 28 am](https://cloud.githubusercontent.com/assets/6798337/8480232/9583af08-20aa-11e5-89a0-8a27b16e0e7c.png)

![screen shot 2015-07-02 at 11 05 38 am](https://cloud.githubusercontent.com/assets/6798337/8480240/a18426f2-20aa-11e5-9a71-3f8b9ee6f7a5.png)

One color line graphs
![screen shot 2015-07-02 at 11 05 49 am](https://cloud.githubusercontent.com/assets/6798337/8480248/acdc2644-20aa-11e5-8c78-d5172c6e2be6.png)

![screen shot 2015-07-02 at 11 06 11 am](https://cloud.githubusercontent.com/assets/6798337/8480257/b16669d6-20aa-11e5-9445-15146ab6d98f.png)

### Arbitration

[Report](http://files.consumerfinance.gov/f/201503_cfpb_arbitration-study-report-to-congress-2015.pdf)

![screen shot 2015-07-02 at 11 12 57 am](https://cloud.githubusercontent.com/assets/6798337/8480570/75d0d5a8-20ac-11e5-9a82-8f615da5b104.png)

![screen shot 2015-07-02 at 11 14 13 am](https://cloud.githubusercontent.com/assets/6798337/8480573/7b3eb618-20ac-11e5-98c1-a1c5d9e55613.png)

![screen shot 2015-07-02 at 11 17 45 am](https://cloud.githubusercontent.com/assets/6798337/8480581/84df18d4-20ac-11e5-94f8-babe4a027a24.png)

![screen shot 2015-07-02 at 11 18 43 am](https://cloud.githubusercontent.com/assets/6798337/8480596/89b39a60-20ac-11e5-8f64-72cad31c760e.png)

### Strategic plan

[Report](http://www.consumerfinance.gov/strategic-plan-budget-and-performance-plan-and-report/)

![screen shot 2015-07-02 at 11 26 36 am](https://cloud.githubusercontent.com/assets/6798337/8480724/4f7565e4-20ad-11e5-99c3-6378e41be5f3.png)

### Card Act

[Report](http://files.consumerfinance.gov/f/201309_cfpb_card-act-report.pdf)

![screen shot 2015-07-02 at 11 29 00 am](https://cloud.githubusercontent.com/assets/6798337/8480804/cc63014c-20ad-11e5-9b0d-00842a2b287a.png)

![screen shot 2015-07-02 at 11 29 07 am](https://cloud.githubusercontent.com/assets/6798337/8480807/d15dffee-20ad-11e5-8fbd-17833e04f9ad.png)

![screen shot 2015-07-02 at 11 29 16 am](https://cloud.githubusercontent.com/assets/6798337/8480811/d70ed8be-20ad-11e5-9415-43dd47579a06.png)

![screen shot 2015-07-02 at 11 29 26 am](https://cloud.githubusercontent.com/assets/6798337/8480815/dbd14fbc-20ad-11e5-9b64-25bc242c606b.png)

Waterfall
![screen shot 2015-07-02 at 11 29 53 am](https://cloud.githubusercontent.com/assets/6798337/8480819/e143b750-20ad-11e5-83b9-b1d513d3d41a.png)

### Manufactured Housing White Paper

[Report](http://files.consumerfinance.gov/f/201409_cfpb_report_manufactured-housing.pdf)

![screen shot 2015-07-02 at 11 32 15 am](https://cloud.githubusercontent.com/assets/6798337/8480873/22b460d6-20ae-11e5-8bf1-cd8a4acd3921.png)

**Comment by amycesal** [comment]
This is a good set of examples to start with! If there's more, that would be great too. I'm planning a brainstorm in DC for Feb 18th to look at examples of what we've done, and to plan where we want to go with this. 

Recently there was a post (http://policyviz.com/style-guides) about other data visualization style guidelines that exist. Most relevant to us are probably: 
- Gov.uk (https://www.gov.uk/service-manual/user-centred-design/data-visualisation.html) 
- Urban Institute (http://urbaninstitute.github.io/graphics-styleguide)
- Dallas Morning News (https://knightcenter.utexas.edu/mooc/file/tdmn_graphics.pdf)
- Data visualization checklist (http://annkemery.com/wp-content/uploads/2014/05/DataVizChecklist_May2014.pdf) 

I'd like to go through those and talk about what they do well, and what sorts of guidelines could be applicable to what we are trying to create. 

There's also the question of scope, and when people should use the guide. I think it's unrealistic for every graph to fit standards because there's a lot of exploratory process that needs to happen when digging through data. My thoughts right now as a flowchart: 
![screen shot 2016-02-04 at 4 39 17 pm](https://cloud.githubusercontent.com/assets/1656046/12830561/ea4a1384-cb5d-11e5-8b13-b80dbcd05a38.png)

Anyways, this is moving! And hopefully scope and steps will be more defined soon.

**Comment by amycesal** [comment]
Note: a lot of our data comes in ALL CAPS. We should address this and decide what use and how much ALL CAPS is appropriate (hint: less than all).

good source to look at for text alignment and why:
http://www.storytellingwithdata.com/blog/2012/09/quick-tip-left-uppermost-align-title

**Comment by mebates** [comment]
@amycesal love your flow chart, makes perfect sense.

I think it's less important for us to have really aggressive and specific type and style standards for data viz than it is for an editorial publication. I'm most attracted to the checklist and gov.uk's standards. I wonder if we should start by forking gov.uk and just modifying slightly from there. Might speed things up and get us to an MVP very quickly.

**Comment by amycesal** [comment]
Yesterday @designlanguage @marteki @Ekellett Cesar Brittany and I met to brainstorm. 

We reviewed other data guidelines and ways to help creators figure out what chart type would be best. There was some dot voting as to what worked well, and could apply to us, and what didn't. 

| ![image2](https://cloud.githubusercontent.com/assets/1656046/13179246/068938f6-d6f1-11e5-9285-dcc646410297.JPG) | ![image1 3](https://cloud.githubusercontent.com/assets/1656046/13179259/17910782-d6f1-11e5-8f02-ac14b08c5855.JPG) |
| --- | --- |

We looked at a wall of charts made all over the bureau that was overwhelmingly green to get a sample of what is being created now, what was working well, and what could be improved. 

Then we brainstormed **where we want to be** and **how we get there**

| ![image4](https://cloud.githubusercontent.com/assets/1656046/13179655/d99372ce-d6f2-11e5-91cc-03d24d2c7e7d.JPG) | ![image3](https://cloud.githubusercontent.com/assets/1656046/13179653/d424d9cc-d6f2-11e5-9042-b4e4c8818ff7.JPG) |
| --- | --- |

with the creation of a guide being the first step. 

Based on our review of other guides and what we want to include, I created a draft outline of a guide.

## Draft outline

##### Help/Contact info
- housed internally. 

##### Intro and usage guidelines.
- flowchart. 
- why storytelling, audience and purpose are useful.
- guiding questions. 
- where to find templates.

##### Anatomy of a chart.
- define the terms. 

##### flowchart of chart suggestions.
- examples of chart types. 
- why each is useful

##### Color.
- define. 
- why it’s important. 
- show samples with hex, rgb, cmyk. 
- categorical vs. sequential. 
- show bad contrast with color blindness and grayscale.

##### Text.
- how titles should be used. 
- Font samples. 
- label samples. 
- show sample chart with title

##### Arrangement.
- Define visual hierarchy. 
- describe why important. 
- show example. 

##### Emphasis.
- define how used. 
- show label examples. 
- show color examples. 

##### accessibility.
- how we account for it. 
- what to check.

##### data integrity
- things should add up to 100%
- how to add sources. 

##### further resources

**Comment by amycesal** [comment]
Natalia brought up a good point about data integrity and things adding up to 100% that should probably also be addressed in these guidelines. I added it to the draft outline above. 

Once guidelines are established, we can create templates. Useful templates would probably include

#### Templates to create
- word/excel/ppt
- Creative Suite (illustrator/indesign) 
- Tableau
- d3.js
- R/ggplot2/R shiny

#### social sharing ideas
- greatest hits/ awesome examples collection
- office hours
- consult/education meetings
- speakers
- community of practice/ Friday brags 
- reaching out to other groups in the organization 

#### Next steps include:
- talking to @elizbond to set up a roadmap/plan to hit goals
- setting up a regular meeting with core members to checkin about progress
- figuring out where this sits in the design manual

**Comment by amycesal** [comment]
First up: bar charts! https://github.com/cfpb/design-manual/issues/401

**Comment by amycesal** [comment]
Next up: Line charts! https://github.com/cfpb/design-manual/issues/403

**Comment by amycesal** [comment]
passing the ball to @designlanguage to sort out typographic hierarchy for print, web, and social. 

starting to figure out the parts of a chart and how to call out what's important. 
![parts-of-a-chart_01](https://cloud.githubusercontent.com/assets/1656046/14301451/f67f4ec0-fb65-11e5-9e38-0f8e24b96cdf.jpg)

**Comment by designlanguage** [comment]
Here are some do-nots and ideas for recommendations. More to come.

![parts-of-a-chart_03gk](https://cloud.githubusercontent.com/assets/10562544/14388970/83f81420-fd7e-11e5-8cee-efaa7106522a.png)

@amycesal

**Comment by amycesal** [comment]
Issue about color: #405

**Comment by stephanieosan** [comment]
Amy took data viz standards on as a whole different project. I'm closing this issue!

**Comment by benguhin** [comment]
@amycesal @stephanieosan I'd love to see where y'alls have landed on this! Could be helpful to fork for our teams in Austin

**Comment by amycesal** [comment]
@benguhin this is where we landed: https://cfpb.github.io/design-manual/data-visualization/data-visualization.html
