### ISSUE TITLE
Grad Cap Iscocon (Paying for college)

### ISSUE THREAD

**Issue by duelj** [cfpb/design-manual#235]
Hey all, FJ is working on students office page as well as students and young Americans for the about section of the redesign and we were hoping to use the grad cap isocon on some pages but realized it still needs a little tweaking. Below is our proposed solution after some feedback in one of the design crits to bring it more inline with the grad cap's illustration style. Looking for feedback to get this ready for use on FJ and hopefully to add to our isocon library. 

![grad_cap_isocons](https://cloud.githubusercontent.com/assets/6873734/3472070/6805d714-02c8-11e4-9950-fff0f2480c7a.png)

**Comment by mebates** [comment]
I think your proposed solution is great! Just what we discussed a few weeks ago: bringing the nice shape of the illustration into the isocon. I also like that the cord covers that left edge fussiness. 
:star: :star: :star:

**Comment by jehlers** [comment]
+1 This looks great.

**Comment by stephanieosan** [comment]
Agreed!

**Comment by duelj** [comment]
Here is a version with a little knot added on the tassel to help make the transition a little better.

![grad_cap_isocon_1](https://cloud.githubusercontent.com/assets/6873734/3474174/8669fe66-02e0-11e4-9e67-e1df87881c2c.png)

**Comment by stephanieosan** [comment]
:boom:

**Comment by elizbond** [comment]
@ohsk can you add this to the isocon library?

**Comment by mebates** [comment]
Hey @ohsk has this been added to the Isocon library on Drive? Not sure who has the native files. Would be great to close this out by the Design Manual meeting on Monday.

**Comment by mebates** [comment]
@duelj if you have the native files, you could pull down the latest Isocon library from Drive and make the update.

**Comment by Dnpizarro** [comment]
10/20 Design Manual Review update: 
- @duelj will be updating the Isocon library from Drive. 
- A separate file will be generated for the update as a fall back. 
- If you have any questions regarding updating the library, please reach out to @ohsk.

**Comment by ohsk** [comment]
@duelj not sure if you've poked around that file before, but one thing to note is to make sure you include an **RGB** and **CMYK** version in their respective layers.

![image](https://cloud.githubusercontent.com/assets/1689222/4722311/1401185e-593f-11e4-8027-2972591c3cf9.png)

**Comment by duelj** [comment]
I have not. That is good to know, I would have missed that otherwise. I
will try to get it in the file today.

**Comment by duelj** [comment]
I have updated the brand 2.0  isocon file on Drive with the grad cap (both color profiles). It can be found here: 
https://drive.google.com/a/cfpb.gov/file/d/0B4tiYoNXw9SNa05KYjdhaEVnc0E/view?usp=sharing

**Comment by Dnpizarro** [comment]
Great! Thanks @duelj
