### ISSUE TITLE
Radio Button and Checkbox style

### ISSUE THREAD

**Issue by ell0ell0** [cfpb/design-manual#236]
I'd like to submit flapjack's radio and check box style to be entered into the design manual. The entire container of the selector and title for the button is touch/clickable. You can demo the checkboxes in action at flapjack blog demo, just pop open the filter menu. 

![checkradio](https://cloud.githubusercontent.com/assets/3589375/3626791/cc845ae8-0e81-11e4-8321-fa1e59c4f3bf.png)

We'll close this issue by Wednesday 7/23, so please have your thoughts in by then.

**Comment by jehlers** [comment]
@ell0ell0 In this mock up, you are using the lighter blue for the checked outer stroke, but in your prototype, the outer stroke is the darkest pacific blue:

![screen shot 2014-07-18 at 9 51 39 am](https://cloud.githubusercontent.com/assets/4267825/3626884/032636d8-0e83-11e4-8611-49d0dd50afe1.png)

I think keeping the darkest pacific blue for the whole element works best, and is consistent with what you have done for the radio buttons.

**Comment by ell0ell0** [comment]
I think that's just an optical thing. It's all darkest pacific blue, the outline when not hovered/focused is 1px and 2px when hovered/focus.

**Comment by Scotchester** [comment]
Perhaps your mocked-up boxes weren't precisely aligned on whole pixels, causing the fuzziness?

**Comment by mebates** [comment]
These look great. Do we think the user will understand that they can select more than one when it is a square?

I remember some discussion long ago that custom selectors would be a lot of effort. Do the FEWDs think that these are easy to deploy throughout all of our web products, internal and external? Or, do only certain pages get this level of polish?

**Comment by ell0ell0** [comment]
@Scotchester and @himedlooff have already implemented them and they are accessible, the development part isn't a problem.

**Comment by Scotchester** [comment]
Yeah, we fortunately found it to be easier than expected!

**Update:** Well, I should say, "_Mike_ found it to be easier than expected." All credit to him for the solution!

**Comment by ell0ell0** [comment]
@mebates Default checkboxes are simply squares (rounded squares, so I think it's possibly harder to distinguish check from radio), so I don't think it'll be a huge cognitive leap. The value of having them styled I think is valuable enough, but if you feel differently let us know.

![screen shot 2014-07-18 at 10 10 36 am](https://cloud.githubusercontent.com/assets/3589375/3627162/318b2da0-0e86-11e4-9da1-f456d4ee5b96.png)
![screen shot 2014-07-18 at 10 10 55 am](https://cloud.githubusercontent.com/assets/3589375/3627163/31912c6e-0e86-11e4-931f-3c0bad55b054.png)

**Comment by jehlers** [comment]
I think the large issue @mebates is bringing up is the lack of a check in the checkbox. The radio buttons make sense styled this way, its just an update. I like this style for the checkboxes as well, but its different and might be worth testing to make sure the filled in square communicates the same thing a standard check would.

**Comment by mebates** [comment]
Glad to hear that you guys have implemented it, but will it be easy for other teams to? (Digital A, Intranet, SES etc.)

**Comment by Scotchester** [comment]
We need to move the code into cf-forms, but once that's done, it should be rather easy. If it's not, we're not doing our job :)

**Comment by mebates** [comment]
:+1:

**Comment by himedlooff** [comment]
Demo: http://cfpb.github.io/cfgov-refresh/blog_static/landing.html

**Comment by nataliafitzgerald** [comment]
The radio button looks good. Regarding the checkbox, I have the same question that @jehlers and @mebates posed about whether the user will understand that this is a checkbox as opposed to a square radio button. If there's room to test it out, even just within the CFPB, it could be worthwhile.

**Comment by elizbond** [comment]
So @nataliafitzgerald just used me as a guinea pig and it wasn't really my first instinct to select multiple options. I selected one category and then played with all the drop downs and went back and asked her "oh, can I select more than one?"

**Comment by benguhin** [comment]
Using a check mark would definitely make it clearer that it's a checkbox. 

I also really like using light backgrounds to make the whole thing super-actionable. Gov.uk is a good example: http://govuk-elements.herokuapp.com/#guide-form-checkboxes

![screen shot 2014-07-24 at 12 33 26 pm](https://cloud.githubusercontent.com/assets/6953063/3691235/61d53310-1350-11e4-859e-49f26b6a03bd.png)

We tried this out for the checkboxes and radio buttons in our latest mobile version of the complaint form:

![screen shot 2014-07-24 at 12 35 21 pm](https://cloud.githubusercontent.com/assets/6953063/3691262/8b919766-1350-11e4-937e-b15716219998.png)

**Comment by ell0ell0** [comment]
![checkradio2](https://cloud.githubusercontent.com/assets/3589375/3692553/ae65eeb0-135d-11e4-9d69-307214b3bc71.png)

Ok here are a few alternative options, let me know what you think or what you may like to see added.

**Comment by jehlers** [comment]
@ell0ell0 These look great! Do you mind putting them on a gray background as well, since a lot of the time we use these UI elements on both gray and white backgrounds?

**Comment by ell0ell0** [comment]
![checkradio3](https://cloud.githubusercontent.com/assets/3589375/3703041/d8913098-1405-11e4-9eb3-d821315a83c9.png)

**Comment by ell0ell0** [comment]
@benguhin so the entire container is a tappable / clickable area. We just don't have a background color like in CR.

**Comment by mebates** [comment]
Nice @ell0ell0! @benguhin I didn't quite understand your request. May be something to consider for forms more than filters (but still would be part of this discussion).

I prefer 'c' or 'd'.

**Comment by duelj** [comment]
#### Checkboxes

I have an affinity to option "b" because it seems elegant and understated, but I think that for ease of checking over a large form to make sure you have all the checkboxes selected option "c" might be the best way to go. In either case I feel that the check mark seems like the more neutral representation as the x can often feel like a delete or close icon. 

#### Radio Buttons

This option seems like it's pretty well resolved. The thin white stroke of the selected state feels a bit fussy to me, especially if option "c" or "d" is used for the checkboxes but I understand that it may be necessary to set apart the selected state. My solution would be a solid blue circle for the selected state but have no idea how this would impact accessibility, and really only appeals to my desire for increase visual consistency.

**Comment by benguhin** [comment]
I still think it's worth trying some variations of a "checkbox button" – a clearly-marked box around the checkbox _and_ the text. With default checkboxes, even though the text is clickable, it doesn't look clickable, so the user is still gonna try to tap or click a pretty small area.

Adding boxes around each of them will take up more space, but it will also help keep the text from bleeding together. @mebates provides a fair point that it might not be the best use for filters, but I think it should be part of the toolkit.

I'll add the GDS example again for context:
![61d53310-1350-11e4-859e-49f26b6a03bd](https://cloud.githubusercontent.com/assets/6953063/3704069/3b7eab04-1410-11e4-91fa-34ffab279554.png)

http://govuk-elements.herokuapp.com/#guide-form-checkboxes

**Comment by ell0ell0** [comment]
@benguhin certainly, if a situation arises where this is more useful I'm all for it. We're just trying to solve for our current needs and sort of communicate out and let everyone else weigh in on this general direction.

**Comment by jehlers** [comment]
I think C is working really well. B is nice, but I think C matches more with the radio buttons, and I agree with @duelj that the X represents another interaction.

**Comment by benguhin** [comment]
ok @ell0ell0  and I are on the same page about backgrounds – we'll try it out during the next couple weeks for CR

for the check colors, I'm also a fan of B! 

Could the radio buttons also have black for the center/selection? It'd consistent with a black checkmark (similar to @jehlers point) and would also "protect the blue" (i.e., if blue is used less, the primary action links will pop out more)

**Comment by ell0ell0** [comment]
@benguhin I agree if we go with B we'll swap the radio "dot" to black.

Now opinion seems fairly split between B & C how do we conclude this :)

**Comment by mebates** [comment]
Hey guys - we're going to tee this up for discussion during Monday's Design Manual review. Any updates from flapjack (@ell0ell0) and CR (@benguhin)?

**Comment by ell0ell0** [comment]
I'm beginning work on CR form 3.0 since Ben has no design support. I will be exploring the big button option as i think it works for forms (possibly). That said, I think it'd be ridiculous to apply it to all radio and check boxes throughout the website.

My only update since is I've chosen option C for checkboxes and that's what we've been moving forward with.

**Comment by EmilieVM** [comment]
From a UX perspective, radio buttons are best used with 1 to 4 options and when the choice is one or the other. Checkboxes are best used with more than 4 options or multiple choices.

I agree Option C would be the best UI choice since it highlights the selected choice and gives a clear contrast from the unchecked boxes.

**Comment by Dnpizarro** [comment]
10/20 Design Manual Review update:
- FJ has moved forward with option C for the checkboxes and the proposed option for the radio buttons.
- A need was expressed by FJ to better streamline the approval process of UI elements. This will be an ongoing discussion. 

@nataliafitzgerald your approval is needed for the below options:

![screen shot 2014-10-20 at 5 42 52 pm](https://cloud.githubusercontent.com/assets/6852363/4709755/1cb62702-58a2-11e4-9a68-3e4eca346ec0.png)

**Comment by benguhin** [comment]
I strongly prefer options A & B because I think we should protect our use of blue. The blue is our link color and primary button color and should signify "OMG CLICK ME," and we actually _don't_ want users to select the checkbox that they've already selected.

**Comment by Dnpizarro** [comment]
@benguhin do you feel the same way about the radio button?

**Comment by benguhin** [comment]
Yeah, that definitely applies to the radio button as well. The selected radio button should actually look _less_ actionable than the other options :)

**Comment by mebates** [comment]
You bring up a good point @benguhin. Would the design be stronger if the hover was blue, but the final check or radio button was black or gray?

**Comment by Dnpizarro** [comment]
I want to queue this issue up again for Monday's Design Manual Review. @benguhin could you share some of your insights about the blue at the meeting? @nataliafitzgerald would it be possible to close this issue out after a discussion at Monday's meeting?

**Comment by ell0ell0** [comment]
I see this as strictly a personal taste issue. As I completely disagree, seeing how I made these options. 

Now where this goes from here on out is up to the rest of you though.

**Comment by nataliafitzgerald** [comment]
For the checkbox, option B is working well. I agree with @benguhin that we have to protect our use of blue. A remaining question I have is whether the box can go back to light gray after the check is present or whether we need the light blue border to indicate that you can go back and uncheck the box. Purely stylistically I would prefer the black check on the gray bordered checkbox. Hover could remain blue as it is shown. @benguhin what are your thoughts on this one? I feel we should be able to come to a conclusion on this at Monday's Design Manual Review meeting.

**Comment by nataliafitzgerald** [comment]
@Dnpizarro - Who will create the mock-up of the approved styling for a final review?

**Comment by mebates** [comment]
Here are our final designs, in black and gray. Any preferences? We can also leave it up to designer discretion. 

![screen shot 2014-11-25 at 2 00 35 pm](https://cloud.githubusercontent.com/assets/6223901/5189410/ac0af0fc-74ab-11e4-8a86-c16e254035ca.png)
![screen shot 2014-11-25 at 2 01 39 pm](https://cloud.githubusercontent.com/assets/6223901/5189411/ac0f9698-74ab-11e4-92b7-9f8f3791fc4a.png)

**Comment by Dnpizarro** [comment]
@benguhin and @nataliafitzgerald do you have any preference between the black and grey options @Mollie provided?

**Comment by stephanieosan** [comment]
Did we choose a final design here? Or are we leaving it open? What's getting coded into Capital Framework?

We'll need to add these to the design manual once they're in Capital Framework. Would we just include them under the "form fields" section of the "UI Toolkit"?

**Comment by nataliafitzgerald** [comment]
We are very close on this. For the sake of consistency, we should have one standard (black or gray). It would help to be able to see it in the context of an actual page though to see how it visually melds with other design elements. Do we have a current project that is using radio buttons or check boxes where we could test this out?  @stephanieosan @benguhin @mebates

**Comment by benguhin** [comment]
Note that there's a short thread about mobile radio buttons at #232 . I don't think it conflicts, but we should make sure that the standard closes out both :)

**Comment by nataliafitzgerald** [comment]
@mebates - Reading over this issue again, it sounds like @benguhin and I were recommending option B for the checkboxes. How did we end up with a modification of option C? Just trying to connect the dots.

**Comment by nataliafitzgerald** [comment]
@benguhin and I met this afternoon to push towards closing out this issue. 

For the checkboxes, let's go with what was shown in Option B above but change the box border in the selected state to black (rather than light blue). This will match what we are doing for radio buttons (see below). 
![screen shot 2015-03-09 at 3 15 01 pm](https://cloud.githubusercontent.com/assets/6887128/6562385/16fea420-c66f-11e4-9c86-c99dfb9387e7.png)

For the radio button, let's go with black for the selected state (rather than gray). 
![screen shot 2015-03-09 at 3 15 31 pm](https://cloud.githubusercontent.com/assets/6887128/6562393/26790ab2-c66f-11e4-9ce1-8dda4fbf8ad5.png)

Hover for both radio buttons and checkboxes would then be the pacific blue.

@mebates - Can you update the file to indicate these final changes or send the file to @benguhin and I so that we can update it?

**Comment by nataliafitzgerald** [comment]
Here's the final proposed solution: 
![screen shot 2015-03-09 at 4 38 53 pm](https://cloud.githubusercontent.com/assets/6887128/6563892/020dcc06-c67b-11e4-9bc2-6d084396f00c.png)

@benguhin - Can you take a look?

**Comment by benguhin** [comment]
I think this is solid! I've started #290 to extend the styling for mobile and more advanced forms.

**Comment by nataliafitzgerald** [comment]
I agree with Ben. Let's publish this!

**Comment by stephanieosan** [comment]
Works for me! Yay, publishing!

**Comment by JenniferHoran** [comment]
Hi, I'm sorry I'm so late to this thread, I was just alerted to it. As the 508 SME I would highly recommend not going with radio buttons, there are focus issues with JAWS (screenreader) when unselecting and re-selecting sets of radio buttons. Also, laying out your checkboxes in a horizontal fashion will require some effort to ensure that they are properly navigatable by assistive technology.

**Comment by stephanieosan** [comment]
@JenniferHoran Are you saying there aren't options for 508-compliant radio buttons? Are there any fixes for the focus issues with JAWS that we could make sure we always use?

We don't use radio buttons tons of places, but we do have specific use cases where we need a user to select only one option from a list of options. What are alternatives to radio buttons that you would recommend?

**Comment by JenniferHoran** [comment]
Not at this time - I can just advise, avoid radio button sets. We did report this failure issue to FreedomScientific, the makers of JAWS, and I have the newest version (15) awaiting certification, so hopefully this issue has been resolved but I won't know until I can test.

What happens is that the radio buttons are a set, and once the set is touched you can never really go back and change your answer with JAWS. You can shift + tab back with the screenreader, and visually you can see that you unchecked "yes" and checked "no", for example if you have changed your answer to a question after you had already answered it. It "looks" like you've updated you answer, but visually it never changes. Very quirky and we - the 508 community - have reported this to Freedom for some time. So let's hope there is a fix included in JAWS 15. 
Everyone out there have been on JAWS 14 still, and are just now upgrading to 15, so I haven't heard anything from my 508 peers yet on this focus issue.

On another note, we really need a Forms Manager here at CFPB.....

**Comment by marteki** [comment]
According to JAWS's website, version 16 was released in December 2014:
http://www2.freedomscientific.com/downloads/JAWS/JAWS-whats-new.asp

Avoiding radio button sets in situations where they are standardly used would greatly impact the usability of our forms for all our users. I cannot see how it would improve the accessibility of them either, to use other UI elements to try and work around a known and expected interaction model when those elements are not meant to work that way.

I found a survey by WebAIM detailing that 50% of the laptop marketplace uses JAWS, centered in Asia and North America. However, it is from January 2014, and through a self-reported survey (so standard caveats apply): http://webaim.org/projects/screenreadersurvey5/

Do we know through web analytics what percentage of our screen reader users are using JAWS, and what versions the general public are on _currently_ (or at least more recently)?

**Comment by JenniferHoran** [comment]
The majority of Blind users with screenreaders in the Federal Government use JAWS. I would say about 98%. I know of a few, very few, who use WindowEyes. Several legally blind employees use ZoomText with Reader, but that is not a robust screenreader to the level of JAWS or WindowEyes (or NVDA for that matter). Folks with Macs would probably use VoiceOver vs JAWS. I can't speak to what the public is using, since JAWS is so expensive ($1200ish), public users are often left to figure things out on their own unless they get their JAWS from voc rehab or another source. I've seen a lot of my blind friends move to accessing web content outside of the workplace on their iphones with voiceover the past few years since that combination of safari and voiceover with webcontent is just improving all the time. In fact, content that they try to access on their work PC with JAWS and have issues with, often they can access without a problem on their iPhone with voiceover. 
This is just my observation from 14+ years of doing 508 and working with my blind coworkers and users over the years, not any formal study or survey.
The radio button issue is a known issue so, just wanted to share that information with the group.

We need to test our forms for 508 before they go out, both PDF and HTML forms, once I have all my testing tools I'll start auditing, and when I find issues (like with the radio buttons) with focus I'll be asking for support to change and remediate. In on another note, we really really need a Forms Manager here at CFPB and we should be designing our PDF forms with LiveCycle and not InDesign.

**Comment by benguhin** [comment]
@JenniferHoran I just started issue #300 to discuss the guidelines that we should write for accessibility for PDFs – my guess is that we'll need to have different standards for form elements in PDFs vs HTML.

For HTML specifically, do you have any concerns about the [proposed solution](#issuecomment-77937580) above?

**Comment by JenniferHoran** [comment]
I think we will be OK in HTML, it is just in documents that there continue to be issues with radio button focus and screenreaders (particularly JAWS). We can test both again once I have my JAWS installed, it is still in the certification process.

**Comment by mebates** [comment]
This needs a shepherd to see it through to publish. Feel free to grab an item (or all three) on this checklist:
- [ ] Add to the Design Manual
- [ ] Update Capital Framework
- [ ] Update .ai template(s) to reflect new standard

**Comment by marteki** [comment]
I can't do everything on the list myself, but I can shepherd them. :smiley:

**Comment by ohsk** [comment]
@marteki @mebates @benguhin we'll be featuring a bunch of checkbox-based filtering options for the [CR Search interface](https://github.cfpb.gov/ConsumerResponse/complaint-analytics-search-tool). Would be happy to help follow-through with updating the Design Manual / .ai template side of things. I'm not sure if we have the FEWD bandwidth to contribute back to Capital Framework, though. 

Let me know how I can help!

#### Side note:

We may have a use case for a partial selection within a checkbox (sort of an indeterminate state). We have filters with sub-issues; you can select just a portion of their sub-issues. I believe the standard is to use [a horizontal bar to signify that state](https://css-tricks.com/indeterminate-checkboxes/), but let me know if y'all have other thoughts!

![image](https://cloud.githubusercontent.com/assets/1689222/8992060/71807740-36ca-11e5-9234-a36e232ec158.png)

**Comment by mebates** [comment]
USDS/18F is generally grouping together a bunch of things under 'Inputs'. Let's try to align with them as much as possible: https://pages.18f.gov/govt-wide-patternlibrary/elements/#inputs

**Comment by marteki** [comment]
@mebates - When you say "let's try to align with [the govt wide pattern library] as much as possible," what exactly does that mean?

**Comment by mebates** [comment]
Are there places in our standard (for radio and check boxes) where we deviate from USDS's standard? If so, why? Do we think our solution is better?

Would we want to consider including a more thorough 'Inputs' section like they have, grouping radio/checks with input text fields, drop downs, range slider, date picker? For the items we have missing from our Manual but they have, can we just take them and make small tweaks (or no tweaks)?

**Comment by KimberlyMunoz** [comment]
I was doing some testing with Voiceover on Safari and had some trouble selecting the custom-input radio buttons and checkboxes with VO/Safari. Can someone who has more screenreader experience want to re-test and confirm? I'd love to have a second pair of eyes on this.

I went through the USFWS radio buttons and checkboxes and those don't seem to have a problem with VO/Safari.

**Comment by JenniferHoran** [comment]
@KimberlyMunoz I can test in IE or Firefox with JAWS if you would like.

**Comment by KimberlyMunoz** [comment]
@JenniferHoran Yes. I'll email you a sample page right away!

**Comment by sonnakim** [comment]
Hey hey - Owning a Home was assigned Form Fields as part of the Design Manual foundation inventory. We're assuming checkboxes and radio buttons are an integral form fields component and as such are planning to include what's been agreed upon in this here github issue. 

Does this overlap with another team's effort? Are there any concerns? If not, we can go ahead and document specs as determined here for usage in HTML. We're also trying to wrangle accessibility and usability concerns and recommendations listed here and in other issues.

If we do take this, can someone pass us the final AI template so we can document specs?

**Comment by KimberlyMunoz** [comment]
Hey @sonnakim,

Flapjack did a lot of work on forms these last couple months and I'll be happy to hand off and point you to things so Owning a Home can carry it to the finish line. Just email me on collab because a lot of the links are in enterprise Github (sorry).

**Comment by sonnakim** [comment]
Just realized we are assigned this per Ben's github issue <a href="https://github.com/cfpb/design-manual/issues/339"> here</a>.  It's always great to post a question and then find the answer two seconds later!

But, my last question still stands—if someone could send us the AI template for the finalized checkbox and radio buttons, that would be great!

**Comment by sonnakim** [comment]
Will email you @KimberlyMunoz - thanks!

**Comment by KimberlyMunoz** [comment]
Update on screenreader and the custom-input radio buttons and checkboxes. Jennifer Horan says the buttons work on JAWS and I was able to find out that [Voiceover has just a general problem with reading radio buttons properly](http://www.tyack.net/2015/01/27/accessibility-frustrations-with-apple-voiceover-on-ios-8-1/). We should be able to get around the VO problem by using aria-labelledby whether we stick with the FJ inputs or adopt 18F's.

**Comment by JenniferHoran** [comment]
I wouldn't be surprised if it was the Voiceover screenreader - it seems to work really well on the iPhone and not as great on the Mac. Screenreaders in general also have a lot of issues with radio buttons on non-HTML forms

**Comment by caheberer** [comment]
Closing this issue, we're adding this to the manual as part of the form fields exploration in #346.
