### ISSUE TITLE
tiny word update

### ISSUE THREAD

**Issue by mebates** [cfpb/design-manual#238]
@Scotchester or someone else could you please add the word visual to the sentence on the home page? Sorry I don't have the environment set up to do it myself!

"The Manual includes our design principles, guidelines for user experience, **visual** identity standards, and code snippets for common user interface elements."

**Comment by benguhin** [comment]
updated in commit ebd1d1d7c9af670aa4b51370d291bdea86a40e76

**Comment by mebates** [comment]
This has been updated. :star:
