### ISSUE TITLE
Need an RSS icon

### ISSUE THREAD

**Issue by ell0ell0** [cfpb/design-manual#239]
Hey all we need an RSS icon added to the icon font for these sorts of uses.

![screen shot 2014-07-29 at 3 04 15 pm](https://cloud.githubusercontent.com/assets/3589375/3740257/50e78344-1753-11e4-87c3-364eff1ca718.png)

![rss](https://cloud.githubusercontent.com/assets/3589375/3740260/5d4f95b8-1753-11e4-88a8-0cb0cae059b4.gif)

**Comment by Dnpizarro** [comment]
@ell0ell0 I'm trying to gather all minicon requests so that I can make then next update. I will make sure to include this icon into the set. If you have already developed the artwork, make sure to email me the file.

**Comment by nataliafitzgerald** [comment]
I have approved this offline but posting the formal approval here to close out the issue.

**Comment by Dnpizarro** [comment]
This has been added to the Minicon Font already.

**Comment by mebates** [comment]
:star: !
