### ISSUE TITLE
Tier 2 Illustration Styling

### ISSUE THREAD

**Issue by nataliafitzgerald** [cfpb/design-manual#240]
In issue #208 we kicked off the discussion on illustrations inside of a circle. As we move forward with developing and implementing Tier 2 illustrations it will serve us well to start to define styling standards.

In issue #237, I kicked off this conversation: 

Some stylistic elements include:
- Bleeding the illustration to the edge of the circle versus objects in the center of the circle.
- A still life/scene/collection of objects versus an object. 
  I see this mainly in the "CFPB Internship" example (see #208) where a computer is shown sitting on a desk. My preference would be to preserve still life/scenes to the top tier illustration level. I feel that the tier two illustration level should be less complex given the smaller scale and where it falls in the visual hierarchy.
- Figure/ground inclusion versus an object floating in a color field.
- How do we determine background colors? Do we stick to a certain tint level or levels? In the Careers Page example we are only using the light tint of the green and the lighter teals and blues (the only exception is the White House where we go up one level in the blues). I don't know that we can determine any pattern with such a small set as a test group but we should keep this in mind as we move forward with developing more circle illustrations. 
- Sizing
  We should set the sizing so that it corresponds with the isocon sizing standards (for isocons in a circle). 

Are there other stylistic considerations?

**Comment by duelj** [comment]
#### Bleeding/Cropping:

I think it is nice to have the freedom to do both if the circle illustrations are all floating centered objects the distinction between those and isocons becomes more fuzz visually. I the visual variety that this offers makes the illustrations more interesting as the scale can really be played with. 

#### Still life/scene & figure/ground inclusion:

The Brandeis honor program, internship, and presidential management all used a still life or scene format. The scene style seems to be inline with our illustration style and as long as it doesn't make the smaller illustration overly complex compared to the rest of the set that it will be shown with it seems like it makes sense to use. I also like that it helps set the illustrations apart from the isocon style. 

#### Background colors:

I agree it makes sense to limit the background colors across a set or group of illustrations to be used on the same page. However, I think that limiting the background colors for all circle illustrations might be limiting. Perhaps we could just default to a green or teal and then go from there as needed? 

#### Sizing:

If we are limiting all of the on page illustrations to being in a circle I can see there being a  limited size or size range. I like the idea of them being icsocon size at their smallest scale and then maybe having a size range to be larger. I don't have a specific idea on what the upper end should be but it seems like they will start competing too much with heroes and other content if they get too big.

**Comment by stephanieosan** [comment]
For reference, we've been using illustrations in circles at the tops of our "tools" in owning a home:
![screen shot 2015-01-21 at 3 22 00 pm](https://cloud.githubusercontent.com/assets/6433178/5844351/4f05965c-a181-11e4-90b4-ee712924a98d.png)

**Comment by stephanieosan** [comment]
This issue has been covered by our Page Introduction standards and Wagtail components.
