### ISSUE TITLE
Illustrations of people

### ISSUE THREAD

**Issue by nataliafitzgerald** [cfpb/design-manual#241]
I am moving this conversation from issue #237 in order to better focus the discussion. 

People have been included in our illustration library for some time but we have been very careful about when we use them. The time seems right for discussing the use of people illustrations in CFPB offerings in order to better define what the concerns and limitations are and when using people makes sense as a solution. 
#### What are the concerns with using people in our illustrations?
- They add a lightheartedness to the content which may not always be appropriate.
- They can make our work look cartoony, particularly when used in excess. 
- They are not necessarily inclusive and global. 
  Are there other concerns or considerations worth discussing? 

We have typically tended towards object illustrations because they are more global and universal and can stand as archetypes rather than representations of specific groups. Objects can speak to a larger/diverse audience in a universal way. The limitation of object representations is that we lose the human element that people (illustrations or photography) can provide.  
##### Representation of a character

In terms of use cases, we originally created the people illustrations for the HMDA video. This video was about specific character, Emily. So, there was not the question of using an illustration of a person to represent a category or a larger group. This person represented one character. 
![screen shot 2014-07-31 at 4 28 17 pm](https://cloud.githubusercontent.com/assets/6887128/3770754/732f82a2-18ee-11e4-9b01-eaec6a36e529.png)
##### Conceptual

In terms of work that has not yet gone live, an example of people used in an illustration exists in issue #208, illustrations for the consumerfinance.gov jobs page. Here a collection of people are used to support the topic of "Who should apply." Here we are not using people to show a character but rather we are using people to illustrate a concept. In this case that concept could be diversity, for example. The key question here for discussion here is: Does this solution offer a key benefit that an object based illustration would not?  
![screen shot 2014-07-31 at 4 30 41 pm](https://cloud.githubusercontent.com/assets/6887128/3770789/c6d0de7e-18ee-11e4-9ba1-335f9a7542b2.png)

Are there other potential use cases?

**Comment by ReedOKelly** [comment]
I have been working on cleaning objects in the illustration library, and making sure rules are enforced regarding shading and color, and nothing has been more troublesome than the people illustrations. The issue is that our color palette does not allow for accurate representation of a range of skin tones commonly found in the American public. We can easily represent lighter skinned people, but not using our shades of neutral to represent darker skinned people, in lieu of a true brown or tan, looks unnatural or unhealthy. I suggest that if we are going to continue to use these illustrations, an exception to our color palette must be made allowing for skin tone(s) that accurately reflects a good percentage of the american population.

**Comment by ReedOKelly** [comment]
After discussing the issue with @nataliafitzgerald, we have determined a set of regulations for people addressing a number of variables. Here are some guidelines:
1. 3 hair styles; Long hair, short hair, or short hair + bun
2. 3 hair colors; Red Orange, Gold, or Black
3. 3 skin tones; Gold 20%, Gold 50%, or Neutral
4. 2 body types; broad or triangular
5. glasses optional
6. Neutral skin tone people have black eyes
7. Clothing color is up to designer's discretion, and should be composed of solid tones from within the palette, this means no opacity.

**Comment by ajbush** [comment]
We are editing a couple of the styling guidelines for the people illustrations:
1. When styling an illustration of a person, we suggest using the <a href="http://cfpb.github.io/design-manual/identity/color-principles.html" class="issue-link" title="Illustration hierarchy">CFPB color palette</a> to keep coloring for hair, eyes, clothing, and accessories consistent. Try to use solid tones as much as possible.
2. For skin tone, we suggest using Adobe Illustrator's default "Skintones" palette.
3. Designers can start with the .Ai document previewed below and customize.
4. Illustrations that include accessories outside of the document below will be discussed during Design approvals.

![people](https://cloud.githubusercontent.com/assets/6931351/5844301/ea7b221a-a180-11e4-8425-862c25f58a49.png)
