### ISSUE TITLE
live stream / online forum icon

### ISSUE THREAD

**Issue by ell0ell0** [cfpb/design-manual#242]
I've made an icon for live stream / online forum for our events page. Please discuss or if there are no objections it'd be great if we could add it to the icon font.

![screen shot 2014-08-01 at 10 14 02 am](https://cloud.githubusercontent.com/assets/3589375/3781124/cb1324b6-1992-11e4-9cae-ccb20a577401.png)
![screen shot 2014-08-01 at 11 43 07 am](https://cloud.githubusercontent.com/assets/3589375/3781125/cd0e81ac-1992-11e4-9c5e-568ab5d7054c.png)
![screen shot 2014-08-01 at 11 45 33 am](https://cloud.githubusercontent.com/assets/3589375/3781137/f002916c-1992-11e4-81a4-a30c8a2473a0.png)

**Comment by ohsk** [comment]
Looks pretty good to me!
Scales well: 
![image](https://cloud.githubusercontent.com/assets/1689222/3799386/abfeeb52-1bed-11e4-9ff4-c28ec848efa7.png)

And seems on par with general ideas around "broadcasting":
![image](https://cloud.githubusercontent.com/assets/1689222/3799374/9be9d5a6-1bed-11e4-8f14-7db53b78e113.png)

**Comment by nataliafitzgerald** [comment]
Looks good to me too!

**Comment by mebates** [comment]
Did anyone ask @dpizarro to add this to the minicon library? Reopening until we confirm that it's added.

**Comment by Dnpizarro** [comment]
10/20 Design Manual Review update:
- Issue #257 has been assigned to @Dnpizarro to add the live stream icon to the font.

**Comment by stephanieosan** [comment]
@Dnpizarro has this been added to the font? If so, close it!

**Comment by Dnpizarro** [comment]
Already added. Thanks!
