### ISSUE TITLE
Keyboard and top view of coffee mug & Saucer

### ISSUE THREAD

**Issue by ell0ell0** [cfpb/design-manual#243]
If any of you are making an illustration and need a keyboard or coffee (top down perspective) feel free to use these.

![keyboard_coffee](https://cloud.githubusercontent.com/assets/3589375/3906312/e134604e-22f1-11e4-8e09-3a69bd9ed568.png)

I created them for this upcoming events page.

![screen shot 2014-08-13 at 10 01 13 am](https://cloud.githubusercontent.com/assets/3589375/3906377/65970030-22f2-11e4-8133-d4beca180433.png)

**Comment by Dnpizarro** [comment]
@ell0ell0 before we add the "Add to asset library" label we have to seek approval from @nataliafitzgerald. 

Natalia, any thoughts on these illustrations before we include them into the library. 

Here are my thoughts:
- I vaguely remember some discussion about the ripple in the coffee mug. I'm ok either way. I like the addition of the saucer, gives it a nice touch, but I wonder if its too formal. I feel like most people just use the mug. 
- I'm thinking the keyboard coloring is feeling washed out. A bit more contrast could liven it up more.

**Comment by Dnpizarro** [comment]
Going to queue this up for the Design Manual Review on Monday.

**Comment by nataliafitzgerald** [comment]
@Dnpizarro - 

**Coffee mug**
- I prefer the coffee without the ripple.
- I hear what you're saying about the saucer. I don't know that I've seen this illustration without it, though. Have you? 
- We recently tested covers for the TILA-RESPA booklet and received consumer feedback on the coffee mug specifically. @mebates or @elizbond could provide these details.

**Keyboard**
I'm ok with the existing keyboard coloring but if you want to take a stab at changing up the grays to create a little more contrast (or brighten it up a bit) we can take a look at that. The keyboard looks good to go in terms of the styling and pending any last thoughts on the coloring.

**Comment by elizbond** [comment]
@mebates If I remember correctly it was the previous version that had the "ashtray" comment. It's what led to us eventually changing the coffee to a darker color. I don't think there's been any specific feedback about the recent version (included in Lee's illustration).

#### Previous version

![screen shot 2014-11-17 at 1 49 12 pm](https://cloud.githubusercontent.com/assets/6798337/5075430/b4631190-6e60-11e4-801c-1b92edf46e88.png)

#### Current version

![screen shot 2014-11-17 at 1 51 13 pm](https://cloud.githubusercontent.com/assets/6798337/5075444/cffa551c-6e60-11e4-882d-82975b8a4d06.png)

**Comment by mebates** [comment]
Here is a specific line about coffee from the user testing: "Another agent said she did not recognize the coffee cup graphic on the cover." Not very helpful, but that's all we've got.

**Comment by mebates** [comment]
The shadow IN the coffee looks more correct in my version (teal cup); the lip of the cup would cast a shadow from the top left.

**Comment by mebates** [comment]
@elizbond: I think the ashtray comment was on the white version. I changed it from teal to Lee's version because that one had been approved and I wanted to limit the number of colors dominating the illustration.

**Comment by Dnpizarro** [comment]
@mebates version of the coffee cup in the current version above seems to be working best. @nataliafitzgerald any thoughts?

![screen shot 2015-01-08 at 3 34 37 pm](https://cloud.githubusercontent.com/assets/6852363/5670204/e1c4bb16-974b-11e4-8b79-927bdb7d0953.png)

**Comment by nataliafitzgerald** [comment]
Do we have a mock up of the white coffee mug with the shadow casting in the top left (inside the cup) as @mebates mentions above? In terms of coloring I have a strong preference for the white coffee mug with the gray saucer.

**Comment by duelj** [comment]
I thought I'd share a couple of ideas I tried as I was looking at photos of how light reflects on a cup like this. I agree with @mebates that her cast shadow and highlight are working well in the teal cup version. I think that it could work just as well with the white cup and darker coffee color. I found the image below and then tried some other options in our style just to see how we might improve. 
![coffee-cup](https://cloud.githubusercontent.com/assets/6873734/5743497/996961dc-9be7-11e4-83c7-006ae6629253.jpg)
![screen shot 2015-01-14 at 12 16 44 pm](https://cloud.githubusercontent.com/assets/6873734/5743504/9f084c66-9be7-11e4-9dbb-e8352c7db407.png)

**Comment by klocraft** [comment]
I think the interior shadows help a lot. I feel the third option accomplishes this with a nice subtlety. The depth helps it read more as a mug.

Has anyone tried moving the mug's handle to another location? When I first saw the illustration my initial impression was "magnifying glass." I quickly figured out that it was coffee, but I'm wondering if moving the handle to a non-typical magnifying glass position would help readability?

**Comment by stephanieosan** [comment]
I agree with Kim about the third option!

**Comment by nataliafitzgerald** [comment]
For the handle, some added definition between the handle and the main part of the cup could help (as shown in the image below). I also like how the illustration below shows the depth of the coffee cup (to show that the cup isn't filled to the brim.   

![screen shot 2015-01-14 at 4 10 54 pm](https://cloud.githubusercontent.com/assets/6887128/5747687/f6d47418-9c07-11e4-956d-24e3acea6824.png)

From the 3 options above, I feel option 1 and 3 are working the best. I like the added coffee definition in option 1.  

I played around with this a little to see what the interior cup shadow would look like and what the handle would look like on a different side (this was to try and push away from the magnifying glass interpretation). I also wanted to see what a more angled (less curvy) shadow would look like. I still think the handle could use some added detail (like a subtle shadow) to set it apart from the main part of the cup. 

![screen shot 2015-01-14 at 5 37 46 pm](https://cloud.githubusercontent.com/assets/6887128/5749161/1dc43cd2-9c14-11e4-9f56-bda2d4e54d8d.png)

**Comment by nataliafitzgerald** [comment]
From @duelj's latest, my preference is this one. But, as noted above, the direction of the handle can start to make this feel like a magnifying glass. 
![screen shot 2015-02-20 at 3 26 08 pm](https://cloud.githubusercontent.com/assets/6887128/6308744/e3597e2c-b914-11e4-8f12-c8c36cc69882.png)

From the variations I shared above, this one is my preference. I have moved the handle to the left side to get away from the magnifying glass read. I have also played with the interior shading of the mug to give the mug a bit more weight.
![screen shot 2015-02-20 at 3 30 55 pm](https://cloud.githubusercontent.com/assets/6887128/6308817/8091a368-b915-11e4-81e3-e4551b5feb92.png)

Looking for thoughts from @Dnpizarro @duelj @klocraft @elizbond @mebates and anyone else who has ever wanted to use a coffee cup in their illustrations.

**Comment by klocraft** [comment]
Ahhh the coffee cup. Out of all the 6 designs you showed, I feel like the one you've chosen best represents the coffee cup. The shadowing feels the most realistic in terms of the shadows that would be created if light hit the cup from that angle. The circle around the lip of the cup gives the illusion of depth...I'm actually trying this same approach on another design. And the new location of the handle helps make it look less magnifying-glass like.

Maybe we should run this by a few eyes that have not seen the coffee cup before so we can get a fresh perspective?

**Comment by stephanieosan** [comment]
We don't approve illustration in the Design Manual repo anymore!
