### ISSUE TITLE
Isocon - Payment to Victims

### ISSUE THREAD

**Issue by duelj** [cfpb/design-manual#245]
For the landing page of the the "Civil Penalty Fund" section which is titled "Payment to Victims" we wanted to use an Isocon next to the introduction on the page. However, we are having some trouble finding an icon that can appropriately visualize such a complex subject. Wondering if others have ideas for better representations, or if this feels like something that shouldn't have and Isocon? 
##### A little background:

The "Payment to Victims" page will be the landing page for the civil penalty fun section and will have links out to civil penalty, bureau administered redress, and defendant victim redressing. This would live at the top of the page next to the  intro of the section like so: 
![screen shot 2014-09-08 at 12 26 30 pm](https://cloud.githubusercontent.com/assets/6873734/4188836/a8947208-3776-11e4-893d-bf8c2db73bad.png)
#### Here are some of the options we have considered so far:

![screen shot 2014-09-08 at 12 26 08 pm](https://cloud.githubusercontent.com/assets/6873734/4188841/bc438078-3776-11e4-8681-c46c59e2ca88.png)

**Comment by mebates** [comment]
@duelj, is still a need for the cf.gov refresh?

**Comment by stephanieosan** [comment]
We don't make and approve isocons in the design manual anymore!
