### ISSUE TITLE
Personal Check illustration

### ISSUE THREAD

**Issue by Dnpizarro** [cfpb/design-manual#246]
I wanted to introduce the option of a "personal check" & "checking book" because the check we currently have is based off of a business check #220 . The addition of the personal check could give us some flexibility depending on what the content is calling for (i.e. personal checking accounts or direct deposit). 

In addition, @nataliafitzgerald and I recently worked on a handout and we played with the idea of a check book. The illustration didn't make the cut, but our explorations could prove useful at some point. Below are some of the options we juggled. 

![screen shot 2014-09-08 at 5 23 04 pm](https://cloud.githubusercontent.com/assets/6852363/4193054/5afb0e62-379e-11e4-8b88-8151113504b5.png)

**Comment by mebates** [comment]
I think a closed checkbook would be nice to see, maybe with a pen at the top or something? You could layer a paper check on top so people know what it is. Hoping we can get the check in #220 approved.

**Comment by nataliafitzgerald** [comment]
Out of the options above, the checkbook with the ledger - no. 3 - feels the most resolved/looks good. @Dnpizarro - Have we had a need for a checkbook in a checking book thus far?

**Comment by nataliafitzgerald** [comment]
I still like no. 3 but I don't know what how often we would have a use case for this. I could see maybe in a motion graphics video where you open up a check book and reveal the check and the ledger. In that scenario we would need to have an illustration of the outside of the checkbook (along the lines of what @mebates mentioned in her comment.

**Comment by Dnpizarro** [comment]
To my knowledge we've never actually shown or really talked about personal checks, but we have developed a handout or two on checking accounts and direct deposit. Though like you mentioned, it could be something that we might use in a video down the line. I think it would be useful to have this option even if we don't really have a need for it at the moment.

**Comment by klocraft** [comment]
In the pro checkbook department, I've done a few handouts that could benefit from this style...I've used the single check illustration with a pen, which has a more formal feel; whereas the above illustrations would do a lot to make the handout feel more personal. I'm also leading towards number 3.

**Comment by Dnpizarro** [comment]
Here is a version with the personal check in front of the checkbook. Also, pending on where we land in #220 with the personal check, I will adjust this option.

![screen shot 2015-01-15 at 10 27 50 am](https://cloud.githubusercontent.com/assets/6852363/5760251/36b9ddfe-9ca1-11e4-8d8e-26f39db95d9c.png)

**Comment by jehlers** [comment]
@Dnpizarro The check looks really good! (Jumping in from the outside :smile: ) The only thing is the check looks like it is floating above the checkbook to me. Maybe if it was a little closer, or more on top of the checkbook?

**Comment by mebates** [comment]
Closing this issue, as it is covered in issue #220
