### ISSUE TITLE
askCFPB minicon

### ISSUE THREAD

**Issue by ell0ell0** [cfpb/design-manual#251]
So, we'll be needing a minicon to signify an askCFPB question. We shoudln't use the base question mark as that's being used for tooltips.

Here's an example of use case we'd like to use the minicon for.

![screen shot 2014-09-22 at 4 25 32 pm](https://cloud.githubusercontent.com/assets/3589375/4363763/285f1588-4299-11e4-9780-527c5b01d454.png)

Here's a few options for the minicon.

![screen shot 2014-09-22 at 4 41 25 pm](https://cloud.githubusercontent.com/assets/3589375/4363770/3b6c6d42-4299-11e4-9640-d4c6e2683dc4.png)

Please weigh in so we can try and revise and pick something by 9/28

**Comment by stephanieosan** [comment]
I like 1 and 3.

The fourth seems too similar to the complaint minicon. 
I assume the second means Q&A? But, QA by itself can mean quality assurance, so that might not be clear enough without an ampersand or "and".

**Comment by ell0ell0** [comment]
agreed about the QA. 3 is my personal favorite.

**Comment by stephanieosan** [comment]
Me too!

**Comment by ajbush** [comment]
Yea 3 is nice and it still uses the question mark that is used at the isocon level.

At first glance I liked 1 the most, then I wondered why that shape is familiar and it kinda looks like either the Apple power icon or a magnifying glass that outside of this context would be used for "search".

**Comment by mebates** [comment]
@duelj Is this still a need for the cf.gov refresh design?

**Comment by nataliafitzgerald** [comment]
I like 3 the most. I think we'd have to see 1 in the mock-up to know if it works. I agree that QA doesn't read as Questions and Answers for me.

**Comment by Dnpizarro** [comment]
My only concern with option 3 is that when its in a circle it doesn't work as well. A circle within a circle seems redundant. With that said, @duelj how often do we use the circle versions on cf.gov refresh?

**Comment by duelj** [comment]
Not often but I would imagine we would want the option just in case. And
yes we do still need this minicon for the refresh. Sorry just catching up
on the discussion here.

**Comment by mebates** [comment]
Try the square with a question mark, matching the style of the complaint minicon. 

Is it different enough from the 'complaint' minicon? From the 'help' icon?

**Comment by stephanieosan** [comment]
We don't think this is a relevant use case for us anymore, and it's not worth creating a minicon for Ask.
