### ISSUE TITLE
Design Manual Review

### ISSUE THREAD

**Issue by doguin** [cfpb/design-manual#252]
@mebates @elizbond @benguhin @nataliafitzgerald @dnpizarro

Hi Gang,

Let’s get the monthly Design Manual Review off the ground. Daniel has graciously stepped up to guide the process. I'm going to schedule the first meeting for the week October 20th. Let’s validate the following and also determine an agenda for the first review:
- The purpose of these meetings will be to officially announce changes to the Design Manual that have been reviewed and discussed on Github during the month. 
- This is the time to “test the standards".
- 1-2 issues will be discussed during the review. Those issues should be announced on the agenda prior to the meetings so the appropriate stakeholders attend.
- Management and leads should attend. Who is required at the monthly review?
- Identity, UI, and Dev are encouraged to attend, especially if they've been heavily involved in the decisions and relevant issues for that month.
- Daniel Pizarro will manage the agenda and readouts, working with Elizabeth, Ben, Natalia, and Mollie until it becomes more routine.

**Comment by mebates** [comment]
All of the above points sound right to me! 

It may be helpful to use Huboard to manage the monthly backlog and status. The issues list is so, so long that we will need to prioritize

I think it would be great for us to take a look and see if we can prod a few issues along to make progress before the first meeting.

**Comment by doguin** [comment]
Just following up on this. The first review is a week from Monday. What will be on the docket and who should be invited?

**Comment by mebates** [comment]
Daniel is in town this week so we could sit down and look at the backlog together.

I think the Outlook invite should go out ASAP to all of Design & Dev, as optional. I see Daniel, Elizabeth, Natalia, JP, and Audrey as required, with Bill strongly encouraged. People deeply involved with past Design Manual work and Capital Framework should also attend, especially Scott, Mike, Lee, Justin, Stephanie, Ben and myself.

**Comment by Dnpizarro** [comment]
Update:

It seems that these meeting can handle more than just 1-2 issues. With that said, some issues could take much more time to resolve than others. I will try to determine the amount of time we spend on an issue based on how much discussion was generated on github.

**Comment by mebates** [comment]
I think we can close this issue; the Design Manual Review meetings are going well so far!
