### ISSUE TITLE
Update front-end build process to current CF workflow

### ISSUE THREAD

**Issue by Scotchester** [cfpb/design-manual#256]
The Design Manual's front-end build process needs to be overhauled to follow the current recommended Capital Framework workflow.

This could potentially be a good small project for the fellowship immersion in January.

**Comment by mebates** [comment]
Hey @Scotchester - I remember that this was a big blocker for many of the DM updates we may want to make. Do you think it's something that could be accomplished during immersion, before new folks start contributing? (Or, by a new fellow, or group of fellows?)

**Comment by mebates** [comment]
@Scotchester and @himedlooff to attack this during our working session on 1/21! :tada:

**Comment by mebates** [comment]
Is this finished?

**Comment by Scotchester** [comment]
So so close. Just have to update some of the HTML on the UI toolkit examples, and then we'll be done.

**Comment by mebates** [comment]
:+1: 

Will we need to update the ReadMe as well?
