### ISSUE TITLE
New Minicon: Live Stream

### ISSUE THREAD

**Issue by Dnpizarro** [cfpb/design-manual#257]
@Dnpizarro will update the minicon font to include the live stream icon designed by @ell0ell0 in issue #242.

**Comment by mebates** [comment]
@Dnpizarro has this been added?

**Comment by mebates** [comment]
@duelj will send assets to @Dnpizarro and he will update the font this week.

**Comment by stephanieosan** [comment]
Is this done?

**Comment by duelj** [comment]
Daniel has the file, not sure if he has had time to update the font though.

**Comment by stephanieosan** [comment]
:+1:

**Comment by Dnpizarro** [comment]
This is completed. Steve Shane will be pushing the new minicon font to everyone's computers.

**Comment by stephanieosan** [comment]
Wonderful!

**Comment by Dnpizarro** [comment]
Steve Shane will be pushing the font to everyone's computers later in the week or early next week. But in the meantime you can access the .ttf file from our [google drive](https://drive.google.com/a/collab.cfpb.gov/?tab=mo#folders/0BwfCv4ilI0WgLWFvcThYU3hYWGc).
