### ISSUE TITLE
Adding padding into the Design Manual

### ISSUE THREAD

**Issue by stephanieosan** [cfpb/design-manual#258]
Thanks to Flapjack, we have many more rules about padding between sections and pages than are currently represented in the Design Manual.

Right now we just have padding between headers and body paragraphs documented. (Also, are those reflective of the latest flapjack spacing?) 

How do we start to get these padding standards documented in the design manual? I'm thinking of guidelines about padding after a section and around rules, and at the beginning and ends of pages, etc. 

Does it make sense to add these to the typography section?

**Comment by nataliafitzgerald** [comment]
@stephanieosan - I feel that it does make sense to start documenting this so that we can add it to the design manual.

**Comment by stephanieosan** [comment]
Maybe the first step is for me to do a writeup of my understanding of the rules and then @ell0ell0 and @duelj can edit and add anything I've missed.
