### ISSUE TITLE
Tables: Create Capital Framworke Table Repo

### ISSUE THREAD

**Issue by danny8000** [cfpb/design-manual#26]
Create Table repo, use digital product guide as a starting point. There is a tables less file in the repo as well.

**Comment by mebates** [comment]
Hey Dan - I'm not sure if these issues need action from others or if you're creating them for yourself. Can you elaborate a bit? Thanks!

**Comment by danny8000** [comment]
This was just for me to keep track of the open issues.

**Comment by himedlooff** [comment]
Empty repo is here: https://github.com/cfpb/cf-tables

**Comment by iuloshi** [comment]
Related to #153
