### ISSUE TITLE
Check / Checkbook illustration

### ISSUE THREAD

**Issue by mebates** [cfpb/design-manual#261]
I think someone has illustrated a check in the past (AJ) but it's not in the illustration library. Does someone have it? Is it approved? Can we move it into the library of approved objects?

**Comment by Dnpizarro** [comment]
I opened up issue #246 a while back. It could use some discussion, but I think the need for the illustration would be a good addition to our library.

**Comment by mebates** [comment]
Oh great, I'll close this one then and use #246. Thanks @Dnpizarro !
