### ISSUE TITLE
Are Avenir links medium or regular weight?

### ISSUE THREAD

**Issue by mebates** [cfpb/design-manual#262]
All of cf.gov refresh uses Avenir links at medium weight (when not inline with a block of copy). 

Much of current cf.gov, including OaH, use links at regular weight. The Design Manual doesn't specify, though the links are regular. 

You can review our original (throwback!) discussion of link styles [on GitHub Enterprise](https://REPLACE THIS WITH OUR GHE DOMAIN/CFPB/digital-product-guide/issues/24). I don't think we got specific about the weight of the type. 

I am working on templates for cf.gov refresh and OaH, so would love to resolve this by 1/12/15.

**Comment by duelj** [comment]
Yes, Flapjack uses medium weight Avenir for all its links. I think we kept this style when the style guide was still in the works, because we liked the subtle differentiation and emphasis that it created with the added weight. It has, so far, seemed to work well in both desktop and mobile formats for us. Below is a quick comparison of a Flapjack page with a decent number of links with both weights:

| Medium Links | Regular Links |
| --- | --- |
| ![about_med_links](https://cloud.githubusercontent.com/assets/6873734/5572041/ca9deb84-8f66-11e4-9992-ff86ed094928.png) | ![about_reg_links](https://cloud.githubusercontent.com/assets/6873734/5572043/d09c643e-8f66-11e4-9bef-d7851dec6784.png) |

**Comment by Dnpizarro** [comment]
For our print styles, we are styling most links as medium. We have also had discussions in the past about merging both print and web styles, not necessarily in size but rather styling. The "medium" weight is consistent across both areas, so I would keep that styling for links.

**Comment by mebates** [comment]
We will finalize this decision at the Design Manual Monthly Meeting on 1/12. So far, I haven't heard an argument for keeping the links regular.

**Comment by nataliafitzgerald** [comment]
For the sake of tomorrow's discussion, here are some screen grabs from current use cases: 

**Owning a Home**
![screen shot 2015-01-13 at 7 00 32 pm](https://cloud.githubusercontent.com/assets/6887128/5731851/9207debe-9b56-11e4-9664-d3e18a53a7b3.png)
**Home Mortgage Disclosure Act (HMDA)**
![screen shot 2015-01-13 at 7 02 32 pm](https://cloud.githubusercontent.com/assets/6887128/5731863/c7947b3c-9b56-11e4-9edc-a83142b103d8.png)

![screen shot 2015-01-13 at 7 02 39 pm](https://cloud.githubusercontent.com/assets/6887128/5731899/3c60ed24-9b57-11e4-9e9e-6f6bdf68264a.png)

**Submit a Complaint**
![screen shot 2015-01-13 at 7 05 24 pm](https://cloud.githubusercontent.com/assets/6887128/5731890/29450d06-9b57-11e4-8c3a-80f09ee35b84.png)

![screen shot 2015-01-13 at 7 05 16 pm](https://cloud.githubusercontent.com/assets/6887128/5731895/33ce2ea6-9b57-11e4-8259-6d40fb9e639e.png)
**Our current homepage**
![screen shot 2015-01-13 at 7 04 11 pm](https://cloud.githubusercontent.com/assets/6887128/5731902/4204ae00-9b57-11e4-896f-f49b896277c3.png)

**Paying for College**

![screen shot 2015-01-13 at 7 08 25 pm](https://cloud.githubusercontent.com/assets/6887128/5731921/9890e28e-9b57-11e4-81b1-91005e9c2e10.png)

**Everyone Has a Story**
![screen shot 2015-01-13 at 7 17 12 pm](https://cloud.githubusercontent.com/assets/6887128/5731988/d3ca1db0-9b58-11e4-9931-d123396c9d39.png)

**Comment by mebates** [comment]
We need a bit more exploration on links within paragraph, let's look at both OaH and flapjack. 

But we all agree that links should be Avenir Next Medium in print and on the web, for links outside of paragraphs. The Design Manual should be updated before this issue can be closed. 

If users don't get Avenir Next on the web, the links will default to Arial Regular.

**Comment by stephanieosan** [comment]
Okay, here's Owning a Home's Rate Checker with Regular and Medium links:

#### Regular

![reglinksratechecker](https://cloud.githubusercontent.com/assets/6433178/5843598/9c751134-a17b-11e4-969a-1d9fc37d8b48.png)

#### Medium

![medlinksratechecker](https://cloud.githubusercontent.com/assets/6433178/5843599/9c753d76-a17b-11e4-9a8a-bc4f8927e10a.png)

**Comment by Dnpizarro** [comment]
@Mollie will take this on for the March Sprint.

**Comment by mebates** [comment]
Here's where we're at: I think we agree that links could be Avenir Medium weight, when not in a paragraph. 

I think the links look best as Regular when they are in a paragraph, as seen in the OaH examples above. I'd like some feedback from front-enders (@scotchester) to know how complicated it would be to differentiate consistently between the two in capital framework. 

I found a few examples of Flapjack using Regular weight links throughout the refresh. We'd need to consider whether we want these medium across the board:

![screen shot 2015-03-16 at 9 56 30 am](https://cloud.githubusercontent.com/assets/6223901/6667993/0a77890e-cbc6-11e4-8e2f-e38ce2c88a06.png)

![screen shot 2015-03-16 at 9 56 37 am](https://cloud.githubusercontent.com/assets/6223901/6667995/0a8343de-cbc6-11e4-8a57-625fab86924a.png)

![screen shot 2015-03-16 at 9 57 44 am](https://cloud.githubusercontent.com/assets/6223901/6667994/0a7e8330-cbc6-11e4-962b-d7ee8df01cdd.png)

**Comment by duelj** [comment]
@mebates — I agree, links in paragraphs seem to work best at regular weight. I think that the examples you noted from FJ could both be medium weight for consistency if others felt it was appropriate. 

##### Side note:

We had considered the navigation links as a separate instance to a degree as we were exploring both color and weight to best suite many links living together in the navigation vs. on a page. Navigation links  also adjust differently for mobile widths as compared to a standard link. The navigation example on both flapjack and refresh demos do not fully convey our intentions for the new site navigation styles. Building in pieces, with further navigation exploration to be done, what is seen on the demo are not our final solutions. The example below is a more recent exploration for the "Policy & compliance" section and uses Avenir Next Medium 16px for the links. So I think as we move forward having medium in the nav. is certainly something we could integrate.
![navigation_description_v2_b](https://cloud.githubusercontent.com/assets/6873734/6672911/e211c31a-cbe5-11e4-9662-df254e906231.png)

**Comment by mebates** [comment]
:+1: that looks really nice @duelj !

**Comment by mebates** [comment]
Can we hear from some Capital Framework gurus on this topic?
@Scotchester @jimmynotjim @anselmbradford

**Comment by Scotchester** [comment]
It's no big deal, whatever is chosen :)

In my person opinion, I agree with leaving links regular in paragraphs. :+1:

**Comment by jimmynotjim** [comment]
Same as @Scotchester. Medium weight already defaults to regular for Arial so I don't see any issues here.

**Comment by benguhin** [comment]
Ok awesome. I support updating the standard so that links are Avenir Medium weight except when in a paragraph. @nataliafitzgerald ?

**Comment by mebates** [comment]
Once this gets approved I will see it through to the Design Manual and Illustrator templates! Thanks for all the input.

**Comment by nataliafitzgerald** [comment]
I also support updating the standard so that links are Avenir Medium weight except when in a paragraph. Thanks for pushing this through @mebates!

**Comment by Dnpizarro** [comment]
Moved this to the April sprint.

**Comment by mebates** [comment]
Steps to close out this issue: 
- [ ] Add to the Design Manual 
- [x] Update Capital Framework
- [x] Update .ai template(s) to reflect new standard

**Comment by mebates** [comment]
I've updated the cf.gov refresh template on Drive with this change. It is dated 042315. The new character style is called "hyperlink (in paragraph)" for the regular weight avenir links in the paragraph.

**Comment by mebates** [comment]
@Scotchester, what will we need to do to the Capital Framework to include this standard?

**Comment by keelerr** [comment]
@mebates, I'm working to show how this change would be reflected in the text of the design manual.

**Comment by mebates** [comment]
Hey @keelerr - can you share any progress if you've made? (Okay if it isn't much; others can build on where you're at!)

**Comment by Scotchester** [comment]
This is effectively implemented in Capital Framework by way of the [`.styled-link`](https://cfpb.github.io/cf-typography/docs/#styled-link) and [`.jump-link`](https://cfpb.github.io/cf-typography/docs/#jump-link) patterns. It's difficult to make this a "default" behavior that doesn't involve adding these classes to links, but as long as these classes are employed consistently, links set in Avenir outside of paragraphs can be styled in the medium weight.

If anyone knows of a specific reoccuring situation where Avenir links are not being set in medium, let me know, and we can investigate how to make it more consistent.

(Checked the "Update Capital Framework" box above.)

**Comment by nataliafitzgerald** [comment]
@Scotchester 
I took a quick look across our site pages and see that there are many instances of links not being set to Medium. There seems to be more consistency on Wagtail pages (Medium weight link text) but there are instances of Regular links there as well. Here is a sampling of some situations:

http://www.consumerfinance.gov/askcfpb/
http://www.consumerfinance.gov/your-story/
http://www.consumerfinance.gov/paying-for-college/
http://www.consumerfinance.gov/owning-a-home/
http://www.consumerfinance.gov/retirement/before-you-claim/
http://www.consumerfinance.gov/adult-financial-education/ (mix of medium and regular in page body)
http://www.consumerfinance.gov/consumer-tools/prepaid-cards/ (mix of medium and regular in page body)
http://www.consumerfinance.gov/policy-compliance/guidance/
http://www.consumerfinance.gov/policy-compliance/rulemaking/ (Regular in breakout sidebar)
http://www.consumerfinance.gov/policy-compliance/enforcement/  (mix of medium and regular in page body)
http://www.consumerfinance.gov/policy-compliance/amicus/ (links are Regular in page body)

**Comment by jimmynotjim** [comment]
@Scotchester now that avenir is the default, could we globally set all links to avenir medium, and use the same parent selector we use for georgia running text to set those links as georgia?

**Comment by Scotchester** [comment]
@jimmynotjim Hmm... I suppose so, if we override it to keep links inline within body copy as Regular, which seems to have been the most recent consensus.

**Comment by jimmynotjim** [comment]
Ok, maybe we add it as something to explore after v4 is live.

**Comment by stephanieosan** [comment]
Status: 
I believe the standards are Medium when they're on their own; and matching the paragraph they're in if they fall within a paragraph. 

We need to follow up and see if this is appropriately documented somewhere.

**Comment by stephanieosan** [comment]
Follow up: The weight is not included on the design manual Links page. We should add a link or two.

**Comment by Scotchester** [comment]
Content update deployed: http://cfpb.github.io/design-manual/page-components/links.html

I'll transfer the idea about a better CF implementation to a new issue there.
