### ISSUE TITLE
Links - when to use the arrow minicon

### ISSUE THREAD

**Issue by duelj** [cfpb/design-manual#264]
This was an issue  that I believe had surfaced before but I could not find any documentation on a finalized solution, no do I remember one. So, I thought it would be good to bring up and try to resolve! 
#### The issue:

There are currently a a couple of link style variations depending on use cases but some of them are not standardized on when to or to not use them. The design manual just states that icons can be used to add emphasis when needed. Wanted to test the water to see if others were using them more specifically than this or if there was a desire to refine the use cases? 
#### Examples

We have been developing the justification that an arrow is used when the link takes someone further within the section of the site they are currently on and doesn't have one when the link goes to another section of the site. Additionally, a link that has an arrow on desktop keeps the arrow in mobile format, and likewise for a link without an arrow. I have attached some examples below. 

![screen shot 2015-01-16 at 10 10 48 am](https://cloud.githubusercontent.com/assets/6873734/5778270/082610da-9d68-11e4-8bd7-7a888c406cdb.png)

Here is also an image to show how those same links would be handled in a mobile format:

![screen shot 2015-01-16 at 10 13 24 am](https://cloud.githubusercontent.com/assets/6873734/5778334/7688a556-9d68-11e4-8da5-d95519b36f15.png)

**Comment by duelj** [comment]
### When shalt thou arrow?!

![selfie-3](http://i.imgur.com/wmtvnXl.gif)

**Comment by stephanieosan** [comment]
ohhhhhh, @duelj that selfie made me burst out laughing. 

I'm glad we're talking about this issue, and when I get a minute later today I'll post what we're up to with owning a home. But, fair warning, I think we've been using arrows a bit haphazardly over here.

**Comment by schaferjh** [comment]
I've been mulling this over for a bit, poking around refresh examples, the current site and the published OAH pages and arguing with myself about it various ways. Here's what I think:

##### Remove the arrow minicon following links, full stop.

_The reason that won me over:_
1. Having a minicon following every link, diminishes our ability to catch the user's attention with a PDF minicon or outbound link minicon. If all links have some little icon after them, the icons that convey more significant information are easier to miss.

Check out the example below:

| With link arrows | Without link arrows |
| --- | --- |
| ![screen shot 2015-03-19 at 10 32 37 am](https://cloud.githubusercontent.com/assets/10562545/6733017/d1346dd0-ce25-11e4-8bd8-8ad8071800da.png) | ![screen shot 2015-03-19 at 10 32 37 am copy](https://cloud.githubusercontent.com/assets/10562545/6733029/e25b917e-ce25-11e4-88ea-5840c3c00dc9.png) |

In example without link arrows, it's more evident to someone scanning the page that the two PDF links are PDF links.

_My other two reasons:_
2. The difference between intra-section links and inter-section links as outlined by @duelj is not a familiar distinction for most users and instead will read as haphazard application of the design.
1. On a page (or in a sidebar) with a lot of intra-section links, the arrows become visual clutter.

_However_
This does circle back to how we use underlines. If we have no underline and no arrow on links, then we're depending on color alone to highlight the link, which could raise accessibility issues. For this reason I would support more general use of the underline for link text.

**Comment by stephanieosan** [comment]
I support this. 

We've been using arrows all willy nilly on Owning a Home, and I don't see a strong argument for not using underlines for links.

**Comment by duelj** [comment]
I think the underline could be argued to create visual clutter just like the arrows, especially in areas like Navigation (including drop downs, left side, header, and footer) and sidebars. My argument for not having them in the sidebar is that often sidebars are home to modules with related content and are labeled as such. I believe that having a section labeled "related links" with an underline on hover (with a color change) would be enough for a user to understand interaction. 

**_I am all for underline in main content sections of the page when uses inline with body, in list format, or otherwise. I also don't have that strong of feelings about the arrow.**_

**Comment by benguhin** [comment]
This is a song about arrows falling: https://www.youtube.com/watch?v=ph6fmk27grc

I agree that the intra-section vs inter-section difference between links will probably look haphazard to most users, so it makes sense to use just one solution for the standalone/non-inline links. 

But I do like the arrows! I like how they make the standalone links seem more actionable, and @schaferjh I think that with a bit more leading the example that you posted could look less cluttered. They also give more emphasis to internal links over external and pdf links, which _I think_ is what we want.

So, I propose
For standalone links, blue + underline _and_ arrows
For inline links, blue + underline

The underline should probably stay regardless of background color. I don't think we can rely on hover states because they pretty much don't exist on touch screens.

**Comment by schaferjh** [comment]
I agree re: the underline and I think perhaps the underline should happen in the sidebar as well so it feels consistent across the page. But underlines in the navigation seem unnecessary.

I certainly like making things seem actionable, but I'm not sure we _do_ want more emphasis on internal links over external and pdf links. And I think the external and pdf icons are more important because they signal that the link is different: when I click on a link in a web site, I expect it to take me somewhere in that web site -- if it's gonna initiate a download or take me to a new web site, that's important information to know. More important, I would argue, than "this link will do what you expect it to do."

**Comment by benguhin** [comment]
@schaferjh that's fair. Nothing like blue text and a simple underline to communicate "this link will do what you expect it to do."

I guess the arrows just have to pass away, through the sky. A karaoke memoriam may be in order.

**Comment by duelj** [comment]
I just wanted to round up the latest thinking on this thread to make sure I was following the discussion. 

**It sounds like the UX designers are leaning towards:**
• all links (including sidebar and sub-footer) being pacific blue with a dashed underline and the 50% pacific on hover. 
• Arrow use is undecided. General feeling seems to be people like the emphasis for standalone links but it makes lists feel overwhelming. It is unclear when arrows are and are not used. 
• Navigation is undecided, but stands as a separate case that will likely vary from this pattern. 

Does that sound right? 

I wanted to add this example to show the sidebar with a number of links in the format above with the lines:
![related_modules_lines](https://cloud.githubusercontent.com/assets/6873734/6906096/8d1fc0bc-d6fa-11e4-998f-9b2ef7d6064a.png)

**Comment by mebates** [comment]
My favorite arrow-related song: https://www.youtube.com/watch?v=kQ8xqyoZXCc

I always understood the arrow to be for designers discretion for adding _emphasis_. So not all standalone links would have arrows, but only those we thought most important. However, that does result in haphazard application. I am not against the UX opinion to eliminate them entirely. (Though they'd still be in our toolbox for some other use or something _really, really_ important.) 

I am generally pro-underline as much as possible, for accessibility reasons. But, I think the sidebar works without it too, so I'm neutral.

**Comment by benguhin** [comment]
@duelj I agree with everything you bulleted

@schaferjh do you think it's possible to have a non-haphazard-seeming rule for when to use arrows? I agree with @mebates that there will be times when we really want to emphasize one link over others, and those times _might_ correspond with specific regions in the templates that y'alls are working on

**Comment by schaferjh** [comment]
Yep, I agree with @duelj's bullets as well. 

@benguhin @mebates When it comes to arrows, the simplest way to achieve consistency and decrease haphazardness across the site is eliminating them. If we _really, really_ want to emphasize one link over others, that should be handled by copy and placement (not in a list or grouped with a bunch of other links/content).

BUT....a little thinking "out loud" about how one would phrase a rule with an exception that doesn't leave folks scratching their heads/using arrows at will:
- "Links on cf.gov do not have arrows, except in hero spaces."  _[I'm not sure why an arrow would be necessary, it's already in a hero.]_
- "Links on cf.gov do not have arrows, except when the link is taking the user to the the next required step in a prescribed set of tasks." _[Actually think this would be a button according to our current guide?]_
- "Links on cf.gov do not have arrows, except navigation links on landing pages." 

My original position on eliminating the arrows stands, but if we were to use them I think we'd have to clearly define the exception.

**Comment by benguhin** [comment]
@schaferjh I agree that any exceptions should be clearly defined, and that the simplest way to achieve consistency is removing them.

Of the three you listed, I think the "hero spaces" exemption could be a good rule. This is a good question for the conversation that's starting up about hero standards: #301 

@mebates any other areas where the arrows should be allowed?

**Comment by stephanieosan** [comment]
Do we have any resolution on this? I'm making tiny updates on our landing page, and was wondering whether I should be doing anything to remove or streamline how we're using the arrow minicons.

**Comment by schaferjh** [comment]
I would love some resolution as well! I stand by my original position but would be interested to know if there are new thoughts out there or if we can get some consensus on this.

**Comment by mebates** [comment]
Moving this into the July sprint so it gets some attention at the meeting on Monday, 6/29.

I think we should default to no arrow but still have it in our toolbox for designers discretion. We should actively try to eliminate them as we update pages, and question each other as to 'why?' when people are adding them in.

**Comment by duelj** [comment]
+1 to @mebates comment, to eliminate them as we update, default w/o them, and leave them for fringe cases at designer discretion.

I believe FJ has internally taken the stance to try and remove link arrows as we have been building out new pages. We have not updated old pages though. Does this sound correct @schaferjh ?

**Comment by schaferjh** [comment]
Yep, FJ has started to adopt a no-link arrow stance in our design work, but the work our devs are doing right now is still often based on arrow-fied documents. I figured I would wait til this issue was resolved one way or the other to ask our devs to make a change. So, there are still link arrows on our newer published pages. :disappointed: 

Anyway, I also like @mebates comment and am happy to move forward under a no-arrows direction and backlog cleaning up our published pages. Woot.

**Comment by mebates** [comment]
I think discussion on this issue has wrapped up, and we just need approval from @benguhin and @nataliafitzgerald before we implement on the Design Manual.

**Comment by benguhin** [comment]
Ok I approve the death of arrows at the ends of hyperlinks for newly updated pages going forward!

The one _possible_ exception is for links in heros. Watch #301 for updates on that front. 

We will check back in about closing this at our July review

**Comment by nataliafitzgerald** [comment]
Approved. Looking forward to seeing where we land on the hero angle with regards to this.

**Comment by benguhin** [comment]
In our Design Manual meeting on October 19th, 2015, we agreed to never use arrows at the ends of hyperlinks, even in headers. 

You're free, little arrows. Fly far.

**Comment by mebates** [comment]
Let's close this baby!
