### ISSUE TITLE
Updating the print Subheader

### ISSUE THREAD

**Issue by klocraft** [cfpb/design-manual#267]
The current manual Subheader is Avenir Next 18/22 regular. 

The problem: This size has consistently been too large to use for traditional subhead text and does not provide enough variation from the current Header 2 (18/20 demi-bold) and Header 3 (16/18, demi).

Designers have been using 16/20 regular as the alternative in handouts, manuals, and other print documents. This smaller size can be consistently applied across templates 4 x 6 through 8.5 x11.

Suggest updating the manual so the official Subheader style is Avenir Next 16/20 Regular, Black

**Comment by stephanieosan** [comment]
This is for print? How do we finalize this decision?

**Comment by Dnpizarro** [comment]
@klocraft  can you post some screen shots of the comparison so we can all see what you are referring to?

**Comment by klocraft** [comment]
@stephanieosan, good questions. Yes, this is for print.

We wanted to post the issue for formal documentation and any final feedback. Because the suggested change has been pretty widely tested and works in a variety of documents, this issue really just needs the official ok from @nataliafitzgerald and then we can begin the process of updating the manual.

@Dnpizarro, ah ha, visuals would help! I'm posting an example of the design manual's current H2, subhead, and H3, to show their similarity. To the right, you'll see the suggested updates. (As an FYI, I chose to post the suggested H2 update as a separate issue, as it might need more testing/feedback than the subhead, see #268).

![screen shot 2015-02-03 at 6 31 54 pm](https://cloud.githubusercontent.com/assets/8646678/6032094/04bc9c1a-abd3-11e4-90c0-19d99362ade4.png)

Here is the current design manual's subhead in an 8.5x11 Handout.

![screen shot 2015-02-03 at 6 13 03 pm](https://cloud.githubusercontent.com/assets/8646678/6031795/53ba8e38-abd0-11e4-9b79-a50bf9409b3a.png)

Here is the suggested new subhead in that same document.

![screen shot 2015-02-03 at 5 51 28 pm](https://cloud.githubusercontent.com/assets/8646678/6031658/29f62964-abcf-11e4-9914-eb7551eaff3a.png)

**Comment by nataliafitzgerald** [comment]
This change is approved.

**Comment by mebates** [comment]
Pulling this into the July sprint. It has been approved but needs to be executed upon. 
- [ ] Add to the Design Manual @Dnpizarro 
- [x] Update .indd templates to reflect new standard @klocraft

**Comment by nataliafitzgerald** [comment]
@Dnpizarro, It does not look like the approved change to the Subhead was ever pushed to the Design Manual. The Subhead style for print should be 16/20, Avenir Next Regular. Can you go ahead and make that update? Perhaps you can do it tomorrow when you're in the office so that I can take a look at how it's done?

The H2 update was already pushed in July. We ended up landing on: 26/28 Avenir Next Regular https://github.com/cfpb/design-manual/issues/268

**Comment by jimmynotjim** [comment]
@Scotchester merged this last week, I think you can close this issue
