### ISSUE TITLE
Skip to content link janks when tabbing to it

### ISSUE THREAD

**Issue by himedlooff** [cfpb/design-manual#270]

**Comment by elizbond** [comment]
@himedlooff can you provide a bit more context?

**Comment by himedlooff** [comment]
To replicate:
1. Go to https://cfpb.github.io/design-manual/
2. Press the tab key
3. You should see a "Skip to main content" link appear that wasn't there before.

Here is a screenshot, notice how it breaks the header layout:

![screen shot 2015-02-15 at 1 28 27 pm](https://cloud.githubusercontent.com/assets/1093373/6204367/bdad39fe-b516-11e4-9f36-74643e2300f1.png)

**Comment by stephanieosan** [comment]
This is still a problem. But maybe a low priority?
