### ISSUE TITLE
Search minicon

### ISSUE THREAD

**Issue by nataliafitzgerald** [cfpb/design-manual#271]
There is an inconsistency in the styling of the search minicon throughout our product offerings when compared with what is in the minicon library. The difference in styling is specific to the length of the handle. In our font the handle is longer. In all use cases I can find (from a quick scan) we are using a search minicon with a shorter handle.  

I propose that we update our search minicon to reflect the version with the shorter handle. This will work better for actual use cases as the longer handle means we have to make the minicon smaller (i.e. it just doesn't fit as well in the types of spaces where we will use this minicon). 
##### Search (minicon font)

![screen shot 2015-02-03 at 12 29 06 pm](https://cloud.githubusercontent.com/assets/6887128/6025412/4ba14fa0-aba0-11e4-9315-1ed3e27ea6b2.png)
![screen shot 2015-02-03 at 12 29 11 pm](https://cloud.githubusercontent.com/assets/6887128/6025413/4e7e9b24-aba0-11e4-942e-002dd6ed2a54.png)
##### use cases

intranet
![screen shot 2015-02-03 at 12 23 42 pm](https://cloud.githubusercontent.com/assets/6887128/6025347/c2e67a5a-ab9f-11e4-8432-23acb453a9f4.png)
consumerfinance.gov refresh 
![screen shot 2015-02-03 at 12 25 10 pm](https://cloud.githubusercontent.com/assets/6887128/6025350/c65cfce0-ab9f-11e4-8ec1-86b4a4601d83.png)
responsive intranet mock-up
![screen shot 2015-02-03 at 12 27 02 pm](https://cloud.githubusercontent.com/assets/6887128/6025373/02875634-aba0-11e4-8773-c2023ca97348.png)
consumerfinance.gov (current site)
![screen shot 2015-02-03 at 12 28 15 pm](https://cloud.githubusercontent.com/assets/6887128/6025399/31ecb108-aba0-11e4-86c9-07d0863de081.png)

Adding 
@Dnpizarro
@duelj

**Comment by Dnpizarro** [comment]
This is most likely an outdated minicon that slipped through the cracks. @duelj if you could send me the short handle version then I can make the update.

**Comment by Dnpizarro** [comment]
@Scotchester and @himedlooff how are you guys using the search icon on cf.gov? Seems like it might be a .png since its not being pulled from the minicon font.

**Comment by himedlooff** [comment]
I don't think we've used it yet but if we did it would be using whatever the icon font is using.

**Comment by Scotchester** [comment]
If you're referring to the live consumerfinance.gov, neither of us coded that :) But yeah, it's using a PNG background image.

**Comment by nataliafitzgerald** [comment]
I did just look through the Flapjack design files on Github and noticed that on the events page for mobile, the longer handle version is being used and on the events page for desktop the shorter handle version is being used. Regardless of inconsistency, I am still in support of the shorter handle. 

![screen shot 2015-02-03 at 12 56 11 pm](https://cloud.githubusercontent.com/assets/6887128/6025942/471bad1e-aba4-11e4-9411-7af053bf55a5.png)
![screen shot 2015-02-03 at 12 56 21 pm](https://cloud.githubusercontent.com/assets/6887128/6025943/4988bede-aba4-11e4-9328-b40162d56cde.png)

**Comment by stephanieosan** [comment]
:+1: for the shorter handle to be used everywhere!

**Comment by Dnpizarro** [comment]
This should be updated in the next couple of days. I'll post an update with a link to the new font soon.

**Comment by Dnpizarro** [comment]
Search minicon was added to the font. An email was sent out to the group about accessing the updated .ttf file on the drive.
