### ISSUE TITLE
Update typography hierarchy to include web subheader

### ISSUE THREAD

**Issue by mebates** [cfpb/design-manual#273]
H4 is being used as a style similar to the print 'subheader' on most of our web products these days. OaH used H4 but in Regular, while Flapjack uses H4 as defined in Medium. I think we should add an option in our web type hierarchy to match our print type hierarchy option of 'subheader'.

OaH H4 in Regular starts with "The kind of mortgage..."
![screen shot 2015-02-03 at 2 30 38 pm](https://cloud.githubusercontent.com/assets/6223901/6027655/8db753d8-abb1-11e4-8bd1-1193355eb831.png)

Flapjack H4 in Medium starts with "We officially..."
![screen shot 2015-02-03 at 2 30 47 pm](https://cloud.githubusercontent.com/assets/6223901/6027656/8db85a12-abb1-11e4-9ec1-d84dfad4bb8a.png)

**Comment by nataliafitzgerald** [comment]
@mebates - The use of the H4 Medium as a subheader has bothered me from a hierarchy perspective for quite some time. The weight feels too heavy for copy that supports a Regular weight header. I am in full support of adding a Regular H4 (aka. subheader) option to our hierarchy. From a naming perspective, would we call it H4 Regular or would we call it Subheader? @duelj @ajbush @Scotchester  - Would we be able to incorporate this into FJ as well? I see this as an important change that will improve the type hierarchy on the FJ site.

**Comment by Scotchester** [comment]
@nataliafitzgerald From a front-end perspective, whatever is decided can certainly be accomplished.

**Comment by nataliafitzgerald** [comment]
@mebates - Where are we on this issue? Do we need more discussion?

**Comment by mebates** [comment]
I don't think we need more discussion. I think we can name it 'Subheader' to match the print hierarchy and get it added to the Design Manual, the Illustrator template, and Capital Framework.

**Comment by duelj** [comment]
+1

**Comment by nataliafitzgerald** [comment]
+1

**Comment by mebates** [comment]
So this has been approved and is in the same spot as #269. Whoever is addressing that issue in the code could probably make this change too.

Steps to close out this issue: 
- [x] Add new level in the Design Manual 
- [x] Update hierarchy built into Capital Framework
- [x] Update .ai template(s) to reflect new standards (@mbates)

@ajbush - should we update the template on Drive with your latest Flapjack template? Or should I continue making updates to the one that's currently on there? Would appreciate your thoughts too, @duelj.

**Comment by ajbush** [comment]
Hey @mebates I'd update the current template for now.

We need to regroup as a team and discuss feedback from the Design Working session.

**Comment by duelj** [comment]
I just want to make sure I understand, this is to add an subheader style (which is essentially H4 in regular weight) not change the existing H4 to regular rather than medium right?

**Comment by mebates** [comment]
Yes, correct!

**Comment by mebates** [comment]
I've updated the cf.gov refresh template on Drive with this change. It is dated 042315. The new paragraph style is called 'subheader'.

All that remains to finish this issue is @Scotchester's help on updating Capital Framework and subsequently the Design Manual with the new standard. There is an open PR on this topic: https://github.com/cfpb/design-manual/pull/310

**Comment by mebates** [comment]
working on this here: https://github.com/cfpb/design-manual/pull/310

**Comment by mebates** [comment]
THIS IS FINISHED. In the template, in capital framework, and in the design manual. :boom:

**Comment by Scotchester** [comment]
Woohoo! :metal:

**Comment by Dnpizarro** [comment]
Great job @mebates !
