### ISSUE TITLE
Sizing of minicons that appear with text

### ISSUE THREAD

**Issue by nataliafitzgerald** [cfpb/design-manual#277]
I have uncovered what is at most an inconsistency and at least a need for more defined standards in how we size minicons in relation to the text that appears beside them.

In the _Design Manual - Visual Identity - Minicons_ section we state “that the following primary benchmark (minicon) sizes should be used for web”

16px: inline with text
20px: on buttons
25px: social media sharing sets
30px: inline with large text links
40px: paired with primary headers

In the _Design Manual - UI Toolkit - Links_ section we state “…The color and font size of icons should be the same as the adjacent text, including state changes.

![screen shot 2015-02-03 at 4 52 58 pm](https://cloud.githubusercontent.com/assets/6887128/6030747/a1d47bd2-abc7-11e4-894a-fa766d03b1fe.png)

The problem? The sizes in our web type hierarchy do not correspond to the standard minicon sizes. 

![screen shot 2015-02-03 at 5 12 57 pm](https://cloud.githubusercontent.com/assets/6887128/6030783/f15b375e-abc7-11e4-96e2-d82a034ed524.png)

Additionally, the sizing description in the minicon section is vague. We should better define (using header names) what is considered “large” text and what is considered a primary header (“Header 1? Display header?).
- @Dnpizarro @mebates @duelj @stephanieosan @ajbush @Scotchester @caheberer @KimL

**Comment by Dnpizarro** [comment]
@klocraft and @Scotchester will work together to correct this issue.

**Comment by duelj** [comment]
It seems like on the web we have currently been using minicons at the same font size as the corresponding labels. @Scotchester does this seem right?  

If this is the case it seems like it would create a lot of extra code to have just the one character of the minicon font be a different size than the text next to it (I do not know if this is actually the case but would love to hear some FEWd perspective on this). If it does add a lot of additional code, it seems like for the web it would make sense to update our scaling to match the header sizes. I can't really speak to what would work best for print.

**Comment by klocraft** [comment]
From the conversations I have been hearing, @duelj is correct. In most cases the minicons follow the size of the font they are accompanying. Depending on feedback from more FEWD folks, updating the manual makes sense.

I will continue to explore minicons for print and providing more concise standards suggestions, if needed.

**Comment by Dnpizarro** [comment]
@klocraft will work on posting a mock up of the updated page.

**Comment by klocraft** [comment]
## Web mock-up r1

Please let me know if there are minicon sizes you know shouldn't be used. Example, does the display text ever use minicons?

Are there best practices that should be included here? Any set spacing between minicons and text?

I will edit design once text is finalized. Thank you for feedback!

![screen shot 2015-05-05 at 10 56 30 am](https://cloud.githubusercontent.com/assets/8646678/7475407/6cf1afb2-f315-11e4-987a-9ea88ab8f954.png)

**Comment by duelj** [comment]
@nataliafitzgerald - Just didn't want this issue to get lost since Kim is not heading it up anymore. 

My impression is that this is pretty much final but was waiting on some thoughts around the heading sizes. Could we just button this up so that the DM reflects what is currently going on in Capital Framework? Minicon size matches the corresponding text size that it accompanies. This way you wouldn't have to give a set size to the minicons, but maybe just frame it as, " scale should match the text that it is next to, but should be no less than 12px or greater than 48px in size." 

Wondered what your thoughts were on this and if you think we could finish it up or what work is left to get there?

**Comment by stephanieosan** [comment]
Recommendation: Seems like someone should update the minicons page to note that minicon sizing in relation to text occurs automatically in Capital Framework, and remove the list of defined sizes.

**Comment by jimmynotjim** [comment]
With the update to svg-icons the icons were drawn with the canvas of Avenir Next in mind. When paired with text (as all icons should be) they are automatically sized to match the text. This is modifiable, but creates a standard to start from.
