### ISSUE TITLE
Main nav: Make responsive

### ISSUE THREAD

**Issue by danny8000** [cfpb/design-manual#28]
Main nav needs responsive styling

**Comment by Scotchester** [comment]
Do you mean that it needs to be styled on smartphone-sized devices? There's an internal thread open about that already. Will email you the link.

**Comment by Scotchester** [comment]
Nevermind, you've already commented on it :)

**Comment by iuloshi** [comment]
## What it looks like now

![screen shot 2014-04-16 at 11 25 50 am](https://cloud.githubusercontent.com/assets/1676307/2721476/a98646ae-c57b-11e3-9d9d-6c177e1802aa.png)

## Comps

### Header

![screen shot 2014-04-16 at 11 33 03 am](https://cloud.githubusercontent.com/assets/1676307/2721566/78969dcc-c57c-11e3-86fd-e62dcc100e3f.png)

### Leftside nav drawer, option 1

![screen shot 2014-04-16 at 11 33 12 am](https://cloud.githubusercontent.com/assets/1676307/2721570/8122c3bc-c57c-11e3-93dc-5d6a3b865293.png)

### Leftside nav drawer, option 2

![screen shot 2014-04-16 at 11 33 16 am](https://cloud.githubusercontent.com/assets/1676307/2721571/83b016e8-c57c-11e3-9c87-3ddd00b5cbd4.png)

Where did the discussion last end on this? Thanks! cc: @ohsk @mebates @stephanieosan @benguhin
