### ISSUE TITLE
include links to incomplete issues on the manual site

### ISSUE THREAD

**Issue by benguhin** [cfpb/design-manual#282]
cfpb.github.io/design-manual/ is how most non-employees are viewing our design manual work, but there's so much more work that hasn't been published yet, living in our issues. 

I propose two updates:
1. Include links to the related github issues on each page of the design manual site
2. Create pages on the design manual site for incomplete issues. This will make it easier for the public to know what we're working on and join our conversations

**Comment by mebates** [comment]
I think it's a great idea. We could use some form language for each, such as:
1. Follow the discussions that led to this standard, an chime in if you see something that needs to be fixed /link
2. We're still working on this standard, join in the conversation to help us finalize it. /link

**Comment by schaferjh** [comment]
This sounds like a great idea. 

I'm curious -- have we ever had someone outside the team submit a new suggestion or ask for a standard not already included either by creating an issue or emailing the tech@ email shown on the Manual's home page?

![screen shot 2015-02-24 at 2 11 40 pm](https://cloud.githubusercontent.com/assets/10562545/6356976/1b1b9990-bc2f-11e4-9eae-e219159e8f4d.png)

**Comment by benguhin** [comment]
For example, scroll to "4. Detailed Help" on this page: https://www.gov.uk/service-manual/user-centred-design/resources/patterns/help-text.html

**Comment by benguhin** [comment]
Ok I started a pattern with the existing pages:
![screen shot 2015-03-23 at 12 05 02 pm](https://cloud.githubusercontent.com/assets/6953063/6784235/ee892b50-d154-11e4-8e6e-c6261b863457.png)

View it here: https://benguhin.github.io/design-manual/ui-toolkit/form-fields.html#issues

**Comment by Dnpizarro** [comment]
@Scotchester will work on automating the github page on manual.

**Comment by Scotchester** [comment]
Looking good, Ben!

As just discussed on the review call, we will use the GitHub API to pull all issues with a label corresponding to each page of the manual.

**Comment by Dnpizarro** [comment]
@Scotchester at this point do we need to open up a separate issue for the "API pulling all issues"?

**Comment by Scotchester** [comment]
@Dnpizarro I think we can continue to use this issue to track it. I don't see the need for another one.

**Comment by stephanieosan** [comment]
This is a lovely idea, but it seems like it's not in line with the newly defined audience/focus for the manual. 

We are recommending closing this issue.
