### ISSUE TITLE
structure and IA for manual

### ISSUE THREAD

**Issue by benguhin** [cfpb/design-manual#283]
I think there are some closed issues that we should reference for background

**Comment by benguhin** [comment]
Specifically, the UI section may need to be reformatted in order to fit future content.

For historical perspective, the current layout was formed from this sitemap from October 2013: 
![screen shot 2015-02-23 at 2 05 35 pm](https://cloud.githubusercontent.com/assets/6953063/6334845/32d57936-bb65-11e4-9f07-e0313f02f920.png)

Google Material Design is a great example of how we could build this out further:
http://www.google.com/design/spec/material-design/introduction.html

IBM recently released their design guide as well:
http://www.ibm.com/design/language/

**Comment by keelerr** [comment]
@benguhin @elizbond what happened to the content of the whiteboard we brainstormed for this?

**Comment by Dnpizarro** [comment]
@benguhin these are great references. Generally, I really like Google style guide and its emphasis on illustrating concepts.  With that said, I'd be curious to see what your thoughts are on how they are treating the menu. Everything seems hidden for the most part so I don't imagine that being a good user experience. Excited about these prospects though!

**Comment by elizbond** [comment]
@keelerr here are the notes!
https://[GHE]/design-ops/team/wiki/Design-Manual-Brainstorm-Notes-2-12

**Comment by Dnpizarro** [comment]
In #288 there was mention of creating a wireframe library. Something to consider for the new AI of the Design Manual.

**Comment by benguhin** [comment]
I meant to post this a while ago. Here is a proposed IA! https://gist.github.com/benguhin/6817f9610e82d88e00bd

**Comment by Scotchester** [comment]
@benguhin Can you do something on that Gist to indicate which things are actual pages and which things are sections of content on a page?

Also, Stephanie left you a comment there. I don't think Gist comments send notifications.

**Comment by elizbond** [comment]
I just had the most exciting meeting with some CEE folks. Spanish and Chinese glossaries are in the works. Think the last couple of pages of the English editorial style guide, commonly used phrases and words with their proper translations.

Could we add the glossaries as sub-pages to the Editorial Style Guide? They would need to be downloadable.

I think the first hurdle is going to be getting the editorial style guide ready to go, starting another issue for that.

**Comment by mebates** [comment]
Hey @benguhin, I reviewed your gist and it looks good. My only comment is that cf.gov's layout section might look quite different from what you've prosed, based on their 'browse, explore, something, something' model. I can't remember what all the stages are but I think that's the thing they want to show.

**Comment by benguhin** [comment]
Yeah I'm not sure if it'll be better to show those different template types on a single page or to break them out into separate pages. 

Another open question is where we fit "text handling" things like formatting for pull quotes, because it doesn't really fit in the Identity section. In the diagram below, I've included them in a UI Toolkit section called "Formatting text," though they might fit better in the Layout sub-section for consumerfinance.gov. As @stephanieosan mentioned in the gist comments, it looks a bit odd.

![cfpb_design_manual_sitemap_150508](https://cloud.githubusercontent.com/assets/6953063/7546306/59a4164c-f5aa-11e4-9a7b-d42fe4b8ea1c.png)

**Comment by stephanieosan** [comment]
It feels strange for our lists, pull quotes, etc to be separated from our type hierarchy (what we're currently calling typography). As a designer laying out a page, those are all part of a typography toolkit I would use to figure out how to best structure text information on a page. 

But, I can see why it might be counter-intuitive for all of that to live under the Identity section.

Question: Why do we call it "UI patterns" instead of something like "web patterns"? Maybe then we could put all of the web typography under that section, and leave the print typography under visual identity? Just an idea.

**Comment by benguhin** [comment]
Good points @stephanieosan – calling the UI section "Web patterns" would also help clarify that these aren't necessarily our styles for PDF interaction. There may be a day when we're developing native apps that use the same styles but aren't technically part of the "web," but we can consider adjusting for that later.

The bigger issue is making our web typography rules easily findable for staff and vendors who are creating web pages, so I agree that we should add type hierarchy to the "Formatting text" area of the UI/Web patterns section, to keep everything in the same general area. This could also allow us more space to address how the different tiers may adjust across breakpoints (which isn't addressed in the current typography section).

Note that "Formatting text" is just a working title for that grouping, and it should probably be a noun like the other areas in that section. The grouping includes type hierarchy, lists, pull quotes, and truncation.

**Comment by Dnpizarro** [comment]
@benguhin to get a better idea of the video section I will loop in our new Multimedia lead Bryce. @duelj and I will work with him to better define this section and any emerging design patterns for motion and live footage. @elizbond could we coordinate a meeting with Bryce later in the month to go over the video section on the Design Manual?

**Comment by mebates** [comment]
Any progress @benguhin? @elizbond and @Dnpizarro can we get Bryce's eyes on the video section?

**Comment by mebates** [comment]
Where would an animated saving indicator fit on the IA? Re: Issue #227

**Comment by stephanieosan** [comment]
Where do our hero standards fit into this IA? 

Under Grid & Layout? Is that level below intended to be separate pages? Is someone planning to update the navigation of the design manual to be able to include that third level?

**Comment by benguhin** [comment]
@stephanieosan here's a pass at updating the structure for the pages that we're adding and including this month - this does require that we update the navigation for a third level:

![cfpb_design_manual_sitemap_15050910](https://cloud.githubusercontent.com/assets/6953063/9795795/b938ea2e-57c0-11e5-857e-7967cf151514.png)

**Comment by stephanieosan** [comment]
@benguhin @kurzn FYI, we were planning for Heros and Featured Content Modules to be separate design manual pages.

**Comment by stephanieosan** [comment]
This issue is no longer the most up to date place to look for information on the IA. Also, we've implemented a new IA!
