### ISSUE TITLE
Icon placement with links 

### ISSUE THREAD

**Issue by duelj** [cfpb/design-manual#285]
I wanted to start a discussion about how we are using minicons with links in the website, whether there is the freedom to use them on either side of the text, and if so, should be some type of system for when they are used on a given side. 
### Design Manual - currently

The design manual shows that minicons should only follow link text and not precede them, even in a list format or despite the type of icon it is. 
![screen shot 2015-02-25 at 9 50 32 am](https://cloud.githubusercontent.com/assets/6873734/6372913/304158f4-bcd5-11e4-8bd3-219f19f8b331.png)
### Flapjack

We have often used minicons with links in two formats.
##### Icon left

This is often done in the context of the icon being used as an organizational element. The link may be an email address and to help orient the user scanning a page having the email minicon first on the link as they are scanning seemed to make sense. 
##### Icon Right

This is typically used when the mincon represents an action. The arrow is used right when the link will take you to another page in the section, or the download/pdf icon shows that a download action is about to take place, etc.

**An example of both cases being shown next to each other can be seen here:**

![screen shot 2015-02-25 at 10 04 18 am](https://cloud.githubusercontent.com/assets/6873734/6373022/01ed759a-bcd6-11e4-81ad-a116133e479d.png)
##### OAH

![screen shot 2015-02-25 at 9 54 30 am](https://cloud.githubusercontent.com/assets/6873734/6373071/87e46cc6-bcd6-11e4-9f79-53900a3c90fe.png)
##### Consumer Response

![screen shot 2015-02-25 at 9 54 51 am](https://cloud.githubusercontent.com/assets/6873734/6373082/95d73f0c-bcd6-11e4-8f54-231458cb9952.png)
### Summary

• I wanted to see if there were other cases of people using minicons to the left of links in their projects. 
• Do people feel that using minicons on either side is acceptable?
• Should there be use cases for minicons to exist on a certain side of a link?

**Comment by Scotchester** [comment]
I didn't interpret the design manual to be prescriptive (proscriptive?) or to be a good example of a link list with minicons. I think it was originally intended to be about adding icons to links that appear within a paragraph.

In a vertical list, I feel pretty strongly that the minicons should be on the left, so they all appear in the same vertical line. The `list__icons` pattern in Capital Framework currently provides support for this.

**Comment by duelj** [comment]
Maybe this conversation should be do we want to add examples of links with left icons to the design manual and should there be a reason to use one or the other?

**Comment by duelj** [comment]
If no one else has input on this topic than I will assume that it is OK to use icons on either side of a link and it is at the designer's discretion where to place icons.

To follow up I still have a couple of questions that I was thinking about: 
1. Does this need to be shown in the design manual to avoid future confusion? 
2. Should there be any logic behind where the icon is placed with the link?

**Comment by Scotchester** [comment]
I think that they should only appear to the right if:
1. It's an inline link (i.e., there is other text directly to the right or left of the link).
2. It's a right arrow icon.

It would definitely be good to add an example with icons to the left.

**Comment by mebates** [comment]
Thanks for the exploration @duelj. Seems like there are use cases for both. I think we should add some examples of icons on the left to the design manual.

One more spot where they can appear on the right: expandables
![screen shot 2015-03-04 at 9 01 53 am](https://cloud.githubusercontent.com/assets/6223901/6484829/3aaa5d72-c24d-11e4-8685-fb0f920aa6a8.png)

**Comment by duelj** [comment]
So far with Flapjack we have identified ~~two~~ three use cases for having left icons. 

##### 1) Contacts _(especially lists)_

it is easier to identify the icon as an organizational visual aid if the icon is to the left of the contact link. 
![screen shot 2015-03-06 at 2 44 13 pm](https://cloud.githubusercontent.com/assets/6873734/6535007/ae0961d2-c40f-11e4-8a79-7d955f4e5015.png)

##### 2) Link lists -

this goes along with the use case above to a degree. In this instance the icon serves a dual purpose of acting as a bullet and also an organizational visual aid. This works especially well if the link breaks on two lines, in those cases the icons seem to get a bit lost. We would propose this for document downloads, and external links but not the right arrow style link. 
![screen shot 2015-03-06 at 3 02 45 pm](https://cloud.githubusercontent.com/assets/6873734/6535299/eb9b8d98-c411-11e4-98a4-3395b3ff6f56.png)
![screen shot 2015-03-06 at 3 02 53 pm](https://cloud.githubusercontent.com/assets/6873734/6535305/f1896ef0-c411-11e4-91f3-6cdffaa69ad0.png)

##### 3) Mixed bag

When there are lists with internal links (right arrow style) and external or document links, we propose promoting the internal links to the top of the list and keeping the arrow icon and the end of the link then putting the document and external links below that with  the icons left. In my mock up I was experimenting with spacing as well to see if that could help. 
![screen shot 2015-03-06 at 4 27 26 pm](https://cloud.githubusercontent.com/assets/6873734/6536822/d1552680-c41e-11e4-8ed2-9e189495f01a.png)

**Comment by nataliafitzgerald** [comment]
@duelj 

The minicon on the left works well for the **Contacts**, where the minicon is a more of a symbol/bullet. This is also consistent with how we use minicons for contacts in print. 

For the second and third examples, I see the minicons more as a for reference than as a bullet (i.e. additional information on the type of link it is and what's going to happen when you click on it), so there I feel they make more sense to the right. Also, the minicon on the left there makes the read a little less clean for me.  

I'm interested to hear a UX perspective on this. @benguhin any thoughts?

**Comment by juidai** [comment]
I think example #2 should also be on the left side to make it easier to read as a list/bullet-point. It's especially true when text wrap to the next line. We've treated them like bullet-points since we've indented the second line of text.

**Comment by benguhin** [comment]
whoa minicon _bullets_

For Case 1 / Contacts, the left alignment definitely works better, possibly because none of those are hyperlinks to web pages. Would you ever need to add internal or external links to that list? (I think you could probably avoid it)

For the other two cases, I've usually seen the pattern of the external link and download icons at the end of the link, but I agree with @juidai that it's easier to read through the links in Case 2 / Lists with the icons at the beginning, functioning as bullets. That definitely breaks down for Case 3 / Mixed Bag, though, when you're communicating internalness with an icon at the end and externalness with an icon at the beginning. (thanks for adding that variation, btw) 

Can you add a Case 4 showing inline links (eg, an external link within paragraph text)? My guess is that those will also be better with the icon at the end of the link.

**Comment by duelj** [comment]
@benguhin  — I put together a mock up to look at inline links with icons before and after. I think they both can work, I don't know that I immediately have a preference. Thinking more about the "mixed bag" case, I do think that I would be odd of us to put all the links on the right if there is a list of links in _only_ this case. I do think it helps separate internal section links with outside links and documents. I think grouping those types of links together is the key to making it work.

##### 4) Inline external links (left or right?)

![screen shot 2015-03-18 at 12 02 55 pm](https://cloud.githubusercontent.com/assets/6873734/6713237/73b588a6-cd67-11e4-8d11-1bd402269160.png)

**Comment by benguhin** [comment]
Yeah leading with the external icon for inline links looks pretty whack. 

I'm thinking that the best rule is to continue having the icons on the right in links, but to add an exception for email addresses and phone numbers.

This is mostly post-rationalization, but with links for external sites, PDFs, and downloads, the icon is more of an FYI for the user that the link will take them to a different type of page in the web browser. Phone numbers and email addresses can _look_ like links, but the interaction after they select it is different.

**Comment by duelj** [comment]
I could see that system working well. I do still like the look of the icons as bullets in a list of links and think that given the title length's of some of our download documents it's be likely that users might skip over the icon at the end of the link (especially with multiple lines). Perhaps this is just some thing to be conscious of as we movie forward? 

![screen shot 2015-03-26 at 12 05 31 pm](https://cloud.githubusercontent.com/assets/6873734/6850615/9b5b3aaa-d3b0-11e4-9705-0fca06984664.png)

Icons to the right doest make it easier from a consistency standpoint which I value as well. The contact info. makes sense as a different use case and doesn't seem to cause consistency issues whether we use the link icons left or right, which is nice.

**Comment by Dnpizarro** [comment]
To summarize the conversation, we've sighted several uses cases for how to position minicons in junction with links. Below is a summarized list (please feel free to add to this):
1. Contacts (Left align)
2. Links in lists (Right align)
3. Standalone links (Right align)
4. Inline links (Right align)

Moving forward, I think for the Design Manual's purposes I would echo the sentiments of the thread that we should illustrate these use cases. It would help much with providing clarity around this issue. 

Thanks @duelj for providing lots of examples!

**Comment by stephanieosan** [comment]
This is well covered in the design manual now, between the Links page, and the Contact information module page!
