### ISSUE TITLE
Updating Header 1 for print documents

### ISSUE THREAD

**Issue by klocraft** [cfpb/design-manual#286]
The current H1 print standard in the Design Manual is Avenir Next **Medium** 38 pt / 40 pt. As part of the design team's effort to soften the headers, we've updated the standard, in practice, from Medium to Regular.

This is a case where the change has already been tested and is in use; we just need to document the change, then update the Design Manual to match.

Please see examples below:
### Header 1 medium vs regular

![screen shot 2015-02-27 at 10 52 56 am](https://cloud.githubusercontent.com/assets/8646678/6415774/1475422a-be6f-11e4-92e3-52a6ecd9ffc5.png)
### Example of medium header in use

![screen shot 2015-02-27 at 10 44 56 am](https://cloud.githubusercontent.com/assets/8646678/6415783/2c5f2a40-be6f-11e4-9b8c-ada4acb343f6.png)
### Example of regular header in use

![screen shot 2015-02-27 at 10 44 39 am](https://cloud.githubusercontent.com/assets/8646678/6415789/311f8908-be6f-11e4-9c04-c5d7458b9a86.png)

**Comment by nataliafitzgerald** [comment]
This update is approved.

**Comment by nataliafitzgerald** [comment]
Design Manual update assigned to @Dnpizarro.

**Comment by mebates** [comment]
Pulling this into the July sprint. It has been approved but needs to be executed upon. 
- [ ] Add to the Design Manual @Dnpizarro 
- [x] Update .indd templates to reflect new standard @klocraft

**Comment by klocraft** [comment]
Update. Looks like the description has been changed on the Design Manual. Just need to update the CSS.

**Comment by Scotchester** [comment]
On it.
