### ISSUE TITLE
Icons for eRegs

### ISSUE THREAD

**Issue by Dnpizarro** [cfpb/design-manual#287]
eRegs is currently using its own subset of icons. In order to transition eRegs into the current Minicon font we need to add the [toc icon](https://github.com/cfpb/cf-icons/issues/40) and a [history icon](https://github.com/cfpb/cf-icons/issues/38) addressed in these two issues.

**Comment by ascott1** [comment]
:+1: Pretty pretty please.

**Comment by bijalsp** [comment]
@Dnpizarro any updates on the icon additions?

**Comment by Dnpizarro** [comment]
@bijalsp looking to complete this today at some point.

**Comment by Dnpizarro** [comment]
Sorry for the delays. I realized there were some minicons I forgot to include in this update, so I had to go back and revise. I'll be posting an update in the next couple of days.

**Comment by Dnpizarro** [comment]
@bijalsp @ascott1 I finalized the update to the minicon font, which includes the toc and history icons. Below is the unicode for the new additions (highlighted in pink). I have updated the design asset folder, which I emailed to you both. Please reach out to me if you have any questions. As for everyone else, I will be sending out an email with a link to the asset folder. 

![screen shot 2015-03-19 at 6 08 13 pm](https://cloud.githubusercontent.com/assets/6852363/6742426/0d7df384-ce66-11e4-96eb-888f0749fcd8.png)

**Comment by KimberlyMunoz** [comment]
Can you email it to me too, @Dnpizarro?

**Comment by Dnpizarro** [comment]
@KimberlyMunoz I sent it to your collab email.

**Comment by KimberlyMunoz** [comment]
🎆 🎆

**Comment by ascott1** [comment]
Thanks for this @Dnpizarro!
