### ISSUE TITLE
CFPB Capital Framework-specific wireframe library

### ISSUE THREAD

**Issue by caheberer** [cfpb/design-manual#288]
Let's make creating wireframes quick and brand/platform-friendly by building our own library.

**Comment by marteki** [comment]
:+1: 

There's been talk among the UX folks about this already. What would we need to determine in order to decide whether or not to move forward on this, and if so, how? I think I heard concerns around the ability to take up the creation of widget libraries alongside other projects.

**Comment by Dnpizarro** [comment]
@caheberer good point. It would be easier to critique as well since we'd have a baseline to judge it from.

**Comment by benguhin** [comment]
:+1: 

That said, I'm gonna put this in the backlog for now as we're waiting for licenses for a new wireframing tool. Once that's procured I think we can get a few people to spend an afternoon on the library-building effort and then establish a cadence for maintaining it.

**Comment by keelerr** [comment]
We already have an Axure library, and expanding it is no no longer be necessary since we have Wagtail for easy prototyping.
