### ISSUE TITLE
checkbox & radio button style with visibly larger hit area

### ISSUE THREAD

**Issue by benguhin** [cfpb/design-manual#290]
Starting this out as a separate issue from #236 

I've been pushing this specifically for mobile devices (see #232 ), but it's also so much nicer on desktop to have big, spaced options to select from when the primary task is choosing between options in a list.

Here's a screenshot of a not-very-styled prototype we built for our complaint forms, which tested really well: 
![screen shot 2015-03-09 at 7 21 54 pm](https://cloud.githubusercontent.com/assets/6953063/6566572/a0328b54-c691-11e4-9ad4-85e9560ebfde.png)
## 

Gov.uk has their style for this documented here: http://govuk-elements.herokuapp.com/#form-radio-buttons
![screen shot 2015-03-09 at 7 07 24 pm](https://cloud.githubusercontent.com/assets/6953063/6566409/8d9dfdd6-c68f-11e4-9601-f6ff98ff7a8f.png)

If we go forward with this as an optional variation for checkboxes and radio buttons, there are a few things to define:
- [ ] Default state on a white background
- [ ] Default state in a fieldset (gray background)
- [ ] Hover state
- [ ] Selected state
- [ ] Placement and rules for helper copy within each option
- [ ] Rules for width, stacking, and columns across breakpoints

I think @ajbush has already given this some thought

**Comment by caheberer** [comment]
This is standard practice for us now. Closing this issue, we're adding this update to the manual as part of the form fields exploration in #346.
