### ISSUE TITLE
PDFs interaction

### ISSUE THREAD

**Issue by juidai** [cfpb/design-manual#293]
CF.GOV have many PDF documents. We would like to handle the interaction in the same way. There are two interaction method and we would like to get feedback. 
1. Load PDF into a new window/tab
2. Load PDF in the same window

Discuss…

**Comment by benguhin** [comment]
@juidai you may not have given folks enough time to discuss this one.

**Comment by benguhin** [comment]
see #294

**Comment by juidai** [comment]
sorry, i was having trouble documenting the issue.
