### ISSUE TITLE
Using 5% instead of 10% Grey (accessibility)

### ISSUE THREAD

**Issue by duelj** [cfpb/design-manual#295]
#### Issue:

While addressing some feedback for the related links/posts/articles/ module the team realized that the pacific blue was not accessible on the 10% grey background. Here are a couple of other cases that we might need to consider if we change the sidebar background color.

• Footer
• Content wells
• Filters
• Forms
• Sub-footer sections (or how sidebars react in narrower widths)
• Expandables (in some cases)
#### Examples

I have included two versions of some other potential 5% use cases. The alternate version has a 1px 50% grey stroke to help define the areas. I think this could be especially helpful on lower resolution and quality screens that may not render the 5% grey as well (this had been an issue in the past).

| 5% no stroke | 5% with 50% stroke | 5% sidebar |
| --- | --- | --- |
| ![5106d7b6-c8e8-11e4-96b4-3e6cde4e9161](https://cloud.githubusercontent.com/assets/6873734/6920751/6833df1a-d78e-11e4-8be0-a1abfe06703a.png) | ![55e99d2c-c8e8-11e4-80c3-3e418447ec58](https://cloud.githubusercontent.com/assets/6873734/6920759/6d45fd58-d78e-11e4-906d-ad27dafaa435.png) | ![related_modules_lines](https://cloud.githubusercontent.com/assets/6873734/6920981/e5a2a6ec-d78f-11e4-9914-68902dfc9ac3.png) |

**Comment by stephanieosan** [comment]
:+1: I'm in favor of introducing grey lines as well. 

In Owning a Home, we currently often use rules when we use the 10% (soon-to-be 5%) grey for wells or expandables. I don't think we're being totally consistent in how we're using them or what color the rules are, though. So, that's something we could tighten up.

![screen shot 2015-03-31 at 10 30 20 am](https://cloud.githubusercontent.com/assets/6433178/6921177/1f624b8e-d791-11e4-822d-60897cfba0d8.png)
![screen shot 2015-03-31 at 10 30 25 am](https://cloud.githubusercontent.com/assets/6433178/6921178/2274d8a0-d791-11e4-9163-0e7606560e7d.png)

**Comment by duelj** [comment]
Nice! I like the way you you all have been using the lines in different contexts. I feel like if we were going to make rules around the lines maybe standardizing size and color would be enough, and allowing freedom on whether the line is top and bottom, just bottom, all the way around, etc. Does that sound like what you had in mind @stephanieosan ?

**Comment by stephanieosan** [comment]
Yes, I think that makes sense!

**Comment by stephanieosan** [comment]
To summarize, we're switching from using 10% to 5% grey in all backgrounds of modules like Footer, Content wells, Filters, Forms, Sub-footer sections (or how sidebars react in narrower widths), Expandables (in cases where we use grey backgrounds). 

Because 5% is so light that it can be hard to see on lower-quality screens, we are also recommending the grey be accompanied by a 50% grey 1 px rule. The placement and extent of the rule is up to the designer to decide, based on the specific context (for example, you might just want a left-hand rule on a sidebar, or top and bottom on a content well, or all the way around for a filter box, etc). 

I'd say let's resolve this as quickly as possible, since it's a matter of 508 compliance and affects stuff both Flapjack and Owning a Home are currently designing and building. 

Any one have any concerns about this proposal? If nothing comes up, let's kick it over to @nataliafitzgerald for review tomorrow or Thursday.

**Comment by mebates** [comment]
Sounds great. I like the flexibility on the placement of the rules.

**Comment by duelj** [comment]
The summary above sounds perfect to me. I'll update the label to pass it on to @nataliafitzgerald for approval. I agree sooner rather than later would be great.

**Comment by Dnpizarro** [comment]
@stephanieosan I'm not clear on how the "left-hand rule on a sidebar" would work. Why wouldn't we want a rule on the right? Can you show some examples of that to clarify?

**Comment by nataliafitzgerald** [comment]
This sounds like a good solution and a good step towards greater 508 compliance!

**Comment by stephanieosan** [comment]
Hey @Dnpizarro I was mentioning the kind of sidebar like the one found on this page: http://www.consumerfinance.gov/owning-a-home/loan-options/special-loan-programs/

It's a pattern used in flapjack (like on the blog) and owning a home.

**Comment by stephanieosan** [comment]
Is there anything else that needs to happen in order for this to be considered approved?

**Comment by duelj** [comment]
+1 on getting this approved, sounds good to me!
 @nataliafitzgerald, @elizbond, or @Dnpizarro  **— thoughts on getting us there?**

**Comment by elizbond** [comment]
Seems like @nataliafitzgerald has approved it. Do @JenniferHoran or @benguhin want to chime in? If not, consider it approved.

Next steps would be suggesting content edits to the manual itself and updating the web template.

FYI - this is already being put to use for the Practitioners landing page.

**Comment by duelj** [comment]
Yes I am happy to mock up a design to work it into the design manual will try to post here ASAP, thanks for the help @elizbond

**Comment by benguhin** [comment]
I think this is great!

**Comment by duelj** [comment]
@JenniferHoran if you are on board with the updates we have made in this issue can you give us your A-OK and remove the 508 label on the issue to confirm approval?

**Comment by JenniferHoran** [comment]
We would always be using bold black text on the grey backgrounds? I'm perfectly fine with this as long as we maintain a contrast ratio of 4.5:1 for normal text and 3:1 for large text. Consistency is great for 508!

**Comment by duelj** [comment]
@JenniferHoran Or original goal was to update the grey background color to a shade that would allow us to use our blue standard link style and still be accessible. There would also be cases for using black on the grey background in various levels of our type hierarchy. Below is a screenshot from the [accessibility checker](http://accessibility.oit.ncsu.edu/tools/color-contrast/accessible-color-palette.php?&colors=101820,f8f8f8,0072ce&main=f8f8f8&level=AA) showing that both black and blue text on a small non-bold style work on the updated 5% grey. 

**_Please let us know if there is anything else we should consider, otherwise sounds like we are ready for approval**_

![screen shot 2015-04-27 at 10 59 31 am](https://cloud.githubusercontent.com/assets/6873734/7350403/0df90648-eccd-11e4-855a-1c8c454e3c11.png)

**Comment by JenniferHoran** [comment]
Great - as long as we meet the contrast ratio and are consisitant. Thank you!

**Comment by JenniferHoran** [comment]
I'm new to Github so not sure how to approve/remove the 508 tag off this issue, thanks!

**Comment by Scotchester** [comment]
@JenniferHoran You didn't have the permissions to be able to do that yet. Sorry! You should now see a gear menu next to the **Labels** heading near the top-right of this issue. (You may need to refresh the page.) Click that, then click the 'x' icon next to the 508 label.

**Comment by JenniferHoran** [comment]
Great, thank you!

**Comment by Dnpizarro** [comment]
Looks like we have full approval from all the necessary parties. @duelj could you update the section below within our typography tab to include the blue link style on the 5% grey background.

![screen shot 2015-05-04 at 11 51 30 am](https://cloud.githubusercontent.com/assets/6852363/7456638/021fa016-f254-11e4-824e-f2bd2435d83b.png)

**Comment by duelj** [comment]
After the design manual meeting it sounds like a combination showing the pacific blue on the 5% grey needs to be shown in the example above from the design manual. I will try to do this myself and will update this issue once I have it included on the DM website. If any FEWDs have time to do this or can help please contact me.

**Comment by duelj** [comment]
Tried making the updates on the design manual but didn't get all the way. Waiting on help, reached out to @Scotchester and CC'd @Dnpizarro

**Comment by duelj** [comment]
### Edits were made on the design manual [typography page](http://cfpb.github.io/design-manual/identity/typography.html#type-accessibility)

![screen shot 2015-05-12 at 10 39 56 am](https://cloud.githubusercontent.com/assets/6873734/7589871/6187da9c-f893-11e4-913f-aa5d9ea7ad41.png)

**Comment by mebates** [comment]
:tada:  :tada:  :tada:  :tada:  :tada:  
Thanks @duelj !
