### ISSUE TITLE
Illustration sizing on web across breakpoints

### ISSUE THREAD

**Issue by stephanieosan** [cfpb/design-manual#296]
I think there are a few interrelated questions and topics here to unpack.

**Topics**
1. Hero illustrations
2. Page illustrations in circles
3. Page illustrations outside of circles
4. Blog illustrations ??? (just throwing this in here in case this is already decided and might influence the other categories)

**For these three categories of illustrations, I have the following questions:**
1. Do we have (or want to have) standard sizes?
2. What happens across breakpoints?
3. Do illustrations disappear on mobile? Always, never, sometimes?

I will update this issue with examples I'm seeing later today.

**Comment by ajbush** [comment]
:+1:

**Comment by nataliafitzgerald** [comment]
@stephanieosan - 
1. I would love to establish standard sizes for this. No need to reinvent the wheel each time. So, YES, to your first question. 
2. I think what happens at breakpoints would depend on whether we are talking about the hero illustration, circle illustrations, non-circle illustrations, etc. but setting standards would be a good thing. 
3. With regards to illustrations, I prefer keeping what we can at the mobile size. Looking at a FJ example it looks like they keep the hero illustrations at the mobile width. 
   ![screen shot 2015-04-09 at 4 04 32 pm](https://cloud.githubusercontent.com/assets/6887128/7075712/261e0560-ded2-11e4-86b5-7f07415dcdb5.png)

On OaH, the mobile sizes looses the part of illustration that really relates to the page. I see this as unfortunate. 
![screen shot 2015-04-09 at 4 09 39 pm](https://cloud.githubusercontent.com/assets/6887128/7075859/2fb7af44-ded3-11e4-80de-e725c6cd4a33.png)

**Comment by stephanieosan** [comment]
I like the hero image popping below the text in your first example. 

Right now our rate checker page removes the image entirely on mobile:

| Mobile | Desktop |
| --- | --- |
| ![screen shot 2015-04-09 at 5 05 27 pm](https://cloud.githubusercontent.com/assets/6433178/7076895/af4303d8-deda-11e4-9a1e-3645f6653611.png) | ![screen shot 2015-04-09 at 5 05 33 pm](https://cloud.githubusercontent.com/assets/6433178/7076896/af45d7fc-deda-11e4-9722-4c95eb545fcd.png) |

But, we're nearly finished building our journey pages, and they're currently built with the illustrations remaining on mobile.

| Mobile | Desktop |
| --- | --- |
| ![screen shot 2015-04-09 at 5 06 29 pm](https://cloud.githubusercontent.com/assets/6433178/7076928/df6c3016-deda-11e4-9761-11c038c14819.png) | ![screen shot 2015-04-09 at 5 06 38 pm](https://cloud.githubusercontent.com/assets/6433178/7076927/df6b3e2c-deda-11e4-9939-6200641b224a.png) |

I think it can get tricky if the illustrations aren't contained in a rectangle that goes full-bleed across the mobile screen to figure out what to do with illustrations on mobile.

**Comment by nataliafitzgerald** [comment]
On the CFPB identity page we are using single object illustrations. At the mobile size the illustration is centered and the type is aligned left. 

| Mobile |
| --- |
| ![screen shot 2015-04-09 at 5 56 01 pm](https://cloud.githubusercontent.com/assets/6887128/7077803/ff97f3f0-dee1-11e4-85da-cefd9e18f6c9.png) |

| Desktop |
| --- |
| ![screen shot 2015-04-09 at 5 41 52 pm](https://cloud.githubusercontent.com/assets/6887128/7077650/ab90fb5e-dee0-11e4-9a44-a9780aaa16ef.png) |

**Comment by keelerr** [comment]
Now that wagtail elements have been included, this is documented in the design manual.

**Comment by keelerr** [comment]
Add to color palette and will be complete.
