### ISSUE TITLE
Add more color contrasts under web type accessibility

### ISSUE THREAD

**Issue by elizbond** [cfpb/design-manual#299]
Update color contrast options on the Design Manual for all colors at all levels (small, normal, large).

Could look something like this:
![screen shot 2015-04-02 at 4 13 35 pm](https://cloud.githubusercontent.com/assets/6798337/6972658/45ac84d0-d953-11e4-934d-e96b09544693.png)

@klocraft

**Comment by Scotchester** [comment]
I don't feel this needs to be documented that extensively in the Design Manual. The page would be gigantic. We should be linking to this tool that makes it pretty easy: 

http://accessibility.oit.ncsu.edu/tools/color-contrast/accessible-color-palette.php?&colors=2cb34a,addc91,dbedd4,101820,43484e,75787b,919395,babbbd,e3e4e5,f1f2f2,f8f8f8,d12124,da6750,e8a091,f6d9d3,ff9e1b,ffb149,ffce8d,ffecd1,796e65,948b84,bcb6b2,e4e2e0,002d72,33578e,7f96b8,ccd5e3,0072ce,328ed8,7fb8e6,cce3f5,005e5d,337e7d,7faeae,ccdfdf,ffffff&level=AA

But some of the ways it outputs things are not great. (For example, it only gives font size values in points, not pixels.) I could see adding a bit more guidance for common combinations with our specific type hierarchy sizes. Or, it would be kinda cool to borrow from the _idea_ of the tool above and improve the output to suit our hierarchy.

**Comment by nataliafitzgerald** [comment]
@Scotchester - I think the idea is that we check everything first and then we decide what to include in the Design Manual as a standard (as in combinations). The results are at 14 points or greater. Do you think that for super large type on something like a poster the results would be the same (as in fail is fail for our green on white or reversed out regardless of size)?

**Comment by Scotchester** [comment]
It does seem that CFPB Green / white combinations fail at any size. The contrast ratio is 2.74, when it would need to be 3.0 for larger sizes.

One thing I'm not sure about is whether these numbers apply directly to ink on paper color contrast. The numeric guidelines were developed specifically for screen display. So, to your question of whether or not it's acceptable to use it on a poster, I don't know. My hunch is that contrast is generally better in print (meaning it could be acceptable at larger sizes), but I don't have anything to back that up at the moment.

**Comment by JenniferHoran** [comment]
The CPFB green fails with white text at all sizes, the green really needs to be just one Pantone shade darker. Also CFPB green on white, fail. This is a bigger issue, changing the branded green. Who wants to go there? I know it is a very slight change but a large one at the same time. I would suggest the change for 508 and usability. I knew before I started here in October just looking at the printed materials that the green was a little off for 508, and now that we've tested it we know this to be true.   

For print it is always suggested that you print out in B&W (essentially, greyscale) to measure for contrast. There's not a specific tool other then measuring the contrast electronically in the source document before it is actually printed. I can ask around, but I'm certain that there's really not a tool to test print contrast after the materials are actually printed. Possibly a CCTV and ZoomText hookup if anything, just a strange thought off the top of my head, but again that would be a manual test.

**Comment by Dnpizarro** [comment]
@klocraft can you update this post?

**Comment by mebates** [comment]
It seems like this issue has stalled. @klocraft @elizbond @nataliafitzgerald, do you feel that 1) we need to add more color examples to the Design Manual, or 2) do you think that linking to the color contrast tool is enough? My vote is for 2. 

If we go with 2, we will want to update the link currently on the design manual to match Scott's detailed link above. We will also want to update it as we add more colors (see #327)

**Comment by stephanieosan** [comment]
I'm in favor of linking to the color contrast tool, it saves us work.

**Comment by mebates** [comment]
We agree to link to the color contrast tool.
- [ ] Update color contrast link on the Design Manual

@nataliafitzgerald has further concerns about acceptable combinations, more from a design perspective than accessibility. Please use this issue to spell out how the Design Manual should be updated to reflect those changes.

**Comment by keelerr** [comment]
Add to color palette and will be complete.
