### ISSUE TITLE
Shrink Primary Nav pixel size

### ISSUE THREAD

**Issue by mebates** [cfpb/design-manual#30]
The primary nav (Overview, Guides...) should be 18 px, not 20.

**Comment by danny8000** [comment]
I just changed the code to:

``` css
font-size: 1.125em; /* 18px */
```

@mebates please review my fork:

http://danny8000.github.io/design-manual/identity/photography.html

**Comment by himedlooff** [comment]
@danny8000 if you're using Less there is the `unit()` function that can help you convert to em's. I find it helpful as a way of self documenting the px size without having to add a CSS comment. The benefit of not using a CSS comment is you can comment out the whole declaration if you need to. When you add CSS comments after properties it makes commenting the entire declaration much harder. Here's a related post on this: https://github.com/cfpb/capital-framework/issues/10

**Comment by mebates** [comment]
Size looks good @danny8000. Why doesn't 'Overview' alight to the left though?
