### ISSUE TITLE
Accessibility guidelines for PDFs

### ISSUE THREAD

**Issue by benguhin** [cfpb/design-manual#300]
Starting this issue to discuss how we approach best standards for accessible PDFs. 

Two primary questions at this point:
1. For which areas should we write guidelines? Here are some suggestions – we can create additional issues for each:
    - Basic text formatting
    - Form fields
    - Links
    - Interactivity
    - Others
2. Are there existing guidelines that we can fork from other organizations?
3. Where should these guidelines live in the IA?
    - This might be better discussed at #283 

@JenniferHoran

**Comment by JenniferHoran** [comment]
-size (how to save without a huge file size)
-protection/saving to ensure access to assistive technologies
-what authoring tools to use – NEVER word if there are fillable/interactive fields, prefer LiveCycle if it is a dynamic fillable form
-document properties
-when to hide graphic elements as background, when to provide alt text description
-planning for complex table support for assistive technology. All table headers tagged to repeat header row in original authoring tool.
-how to test your final PDF for 508 with keyboard, screenreader software and the built in checker (built in checker alone does not provide a full 508 test)

I have some checklists but I think ours will wind up being more robust then any others I have seen.

**Comment by elizbond** [comment]
Adding @klocraft

**Comment by nataliafitzgerald** [comment]
We are taking an Accessibility for InDesign class now. For all those interested, we're taking notes here: https://docs.google.com/document/d/1qWbZbPDNGvNWjuHOcPn9HzLyw31j9v7TfwLNths-qlI/edit#

**Comment by JenniferHoran** [comment]
I can never seem to get access to our google docs. Do I need to set up a separate CFPB gmail account for this and hangouts? I've been meaning to ask for a while. Thanks!

Hope you are enjoying the class!

**Comment by keelerr** [comment]
Add to graphic design back log instead of publishing to Design Manual.
