### ISSUE TITLE
American Flag

### ISSUE THREAD

**Issue by designlanguage** [cfpb/design-manual#302]
@nataliaf pointed out that the American flag isn't in our illustration library, so let's see if we can change that. There is this flag that had been used before in a couple instances:

![293ab6e4-d892-11e4-8d56-c5d440c218d5](https://cloud.githubusercontent.com/assets/10562544/6983664/93db7a8a-d9ee-11e4-8f20-08063b48babb.png)

We wanted to update the flag to the correct number of stars and stripes, and also use our star minicon for the stars. So here is where we landed:

![12b35d7a-d894-11e4-949e-b7dced4e3358](https://cloud.githubusercontent.com/assets/10562544/6983668/9a5c0eec-d9ee-11e4-8711-9ab42adbb38c.png)

We also have this version of the flag that isn't in our library. If we go forward with this new flag, this would also have to be updated.

![201503_cfpb_how-small-businesses-play-a-role-in-the-rulemaking-process](https://cloud.githubusercontent.com/assets/10562544/6983670/a5ad6ce6-d9ee-11e4-9217-045680ab45fb.png)

Should we update our library to include this flag as an illustration?

**Comment by Dnpizarro** [comment]
I would agree with @designlanguage that having both versions of the flag (outdoor & indoor) would be good additions to our illustration library. I don't think that our rounded star is working as nicely as the pointed stars. I think that for this illustration we can be closer to the real thing, meaning sticking with the original pointed stars, versus making it look more illustrated.

**Comment by ajbush** [comment]
Thanks for doing this @designlanguage I'm in need of these for something we're working on.

I'd vote to use the normal pointed stars as well.

**Comment by duelj** [comment]
I would advocate for keeping the standard star version as the rounded star seems to get kinda "muddy" if the flag is housed in a 200px circle (like it is used on the you have a right page). This was a screenshot taken at actual size on citrix (which views at the lower resolution). I think not having the rounded corners on all the stars might make for a crisper image. 

![screen shot 2015-04-23 at 2 30 14 pm](https://cloud.githubusercontent.com/assets/6873734/7304425/5fca3a88-e9c5-11e4-810e-e0e00022fb1e.png)

**Comment by nataliafitzgerald** [comment]
@duelj - Could you post what the current flag illustration looks like when viewed through Citrix - for comparison? Regardless of where we land on the star style, we will still require the update to the number of stars and stripes.

**Comment by duelj** [comment]
@nataliafitzgerald I don't have an image of your flag illustration with the correct number of stripes and stars in a format without the rounded stars so I'm afraid I can't share that. But I agree it would be nice to see. I just took a screen shot of the current illustration at http://www.consumerfinance.gov/you-have-the-right/

**Comment by Dnpizarro** [comment]
@designlanguage are you working on the updated file with the correct number of stars? @duelj not sure if it was you that created the draping flag version in George's first post, but if so could you share that file with him so that he can update that version as well. 

@nataliafitzgerald do you have any further thoughts on the star styling (pointed vs rounded)?

**Comment by duelj** [comment]
@Dnpizarro  Just sent some flag files to @designlanguage which contains the draping version.

**Comment by Dnpizarro** [comment]
Thanks @duelj for forwarding those files.

**Comment by designlanguage** [comment]
The reason we wanted to try a flag with rounded stars is because many of the details in our other illustrations are rounded. Here's just a sampling:

![screen shot 2015-05-05 at 9 55 35 am](https://cloud.githubusercontent.com/assets/10562544/7474140/6633fec6-f30d-11e4-88cc-68c4f04cec9c.png)

The calculator buttons and screen are rounded, so is text on the cellphone and dog tags; the dollar sign on the bill is also rounded. I haven't found many sharp elements in our illustrations (edges beyond 90 degrees), so rounded stars on the flag feel more harmonious with other illustrations to me.

Here's the 50 pointed-star flag:

![screen shot 2015-05-05 at 9 25 22 am](https://cloud.githubusercontent.com/assets/10562544/7473392/e1a453d0-f308-11e4-8cc4-53e6fc468dfe.png)

Justin brought up a good point with low resolutions. The rounded stars read more as circles when they're lo-res. In a 200 pixel circle, the pointed star flag reads a little better, but not significantly:

![screen shot 2015-05-05 at 9 25 09 am](https://cloud.githubusercontent.com/assets/10562544/7473399/ee75d020-f308-11e4-97a5-3df11af6260a.png)

I thought finding a middle ground might solve the lo-res issue. In other words, having the stars be a bit rounded, but not as dramatically as we first showed. Here are slightly rounded stars:

![screen shot 2015-05-05 at 10 36 55 am](https://cloud.githubusercontent.com/assets/10562544/7475174/04532b4e-f314-11e4-8459-fba3e2a6f4ef.png)

And here it is in lo-res:

![screen shot 2015-05-05 at 10 39 13 am](https://cloud.githubusercontent.com/assets/10562544/7475197/248826da-f314-11e4-9844-a73956676c77.png)

What do you all think? What are the merits of pointed stars vs rounded?

**Comment by duelj** [comment]
Yea, rad. If everyone likes the rounded corners that's cool, figured not everyone is blessed by the retina displays like we are and thought the hard edges would render better. In your low res examples I think the rounded stars might actually view better at smaller sizes, the pixel hinting seems to make larger white shapes which seems helpful.

**Comment by Dnpizarro** [comment]
@designlanguage I see your point about the sharp edges and I think the in between version works much better. @duelj made an interesting observation about the rounded stars rendering better, but I'm still leaning towards the in between version since at larger scales the viewer will pay more attention to details.

**Comment by designlanguage** [comment]
Thanks @duelj & @Dnpizarro. Any other thoughts on rounded vs pointed? @nataliafitzgerald - What do you think?

**Comment by duelj** [comment]
I am pro the "in between rounded" star after seeing it at small size and I think at larger sizes it was working as well. Funny that the rounding actually worked better at low-res, thanks for taking the time to explore it! It seemed like Daniel was also on board with your modified rounded version. 

**Sounds like this could be ready for design approval from @nataliafitzgerald**

### George's modified rounded version

| hi-res | low-res |
| --- | --- |
| ![04532b4e-f314-11e4-8459-fba3e2a6f4ef](https://cloud.githubusercontent.com/assets/6873734/7589382/57c02440-f890-11e4-8f16-0fe1b7bb9acf.png) | ![248826da-f314-11e4-9844-a73956676c77](https://cloud.githubusercontent.com/assets/6873734/7589386/5c5ac104-f890-11e4-82c3-51077fdb8930.png) |

**Comment by mebates** [comment]
Hiiii - I'd like to use this in a social graphic for Monday. Can we get approval, @nataliafitzgerald? And get it on the Google Drive? Thanks!

**Comment by Dnpizarro** [comment]
@nataliafitzgerald do you think we can get final approval for this graphic at today's Design Manual meeting?

**Comment by Dnpizarro** [comment]
@designlanguage will be adding the flag to the illustration library.

**Comment by stephanieosan** [comment]
During the design manual meeting, we decided to use the minicon stars.

**Comment by designlanguage** [comment]
I've added the minicon flag to the illustration folder in CMYK and RGB. Let me know if you have any questions.

**Comment by Dnpizarro** [comment]
Thanks @designlanguage for finalizing this work!!

As a general question to everyone, are we no longer updating the [illustrator file](https://drive.google.com/drive/#folders/0BwfCv4ilI0WgLTA0UWNDLXVVT0k/0BwfCv4ilI0WgRHlXSjNtR2NvbGM) with all of the illustrations? Or are we moving towards just updating the [approved objects](https://drive.google.com/drive/#folders/0BwfCv4ilI0WgLTA0UWNDLXVVT0k/0BwfCv4ilI0WgRHlXSjNtR2NvbGM/0B-uPKMMBzQnXRnVheUJKdWgwLWc) folder? Or are we updating both?

**Comment by stephanieosan** [comment]
I'm fine with either, but I do like the illustrator file with all the illustrations. As a person who doesn't do a ton of illustrating, it's really convenient to be able to open a single file and scan the landscape of what's already been built to see if anything fits my needs.

**Comment by mebates** [comment]
I haven't used the all-illustration file in a long time. Let's discuss this quickly at the Design Manual meeting on 6/29.

Otherwise, I believe that this issue is closed. Nice work everyone!
