### ISSUE TITLE
Blog minicons – updated labels

### ISSUE THREAD

**Issue by duelj** [cfpb/design-manual#305]
The blog section is now live on [Beta](http://beta.consumerfinance.gov/blog/) with live content. In getting this section live and up on beta some of the category labels were updated to better reflect the types of content within the section. Some of the existing minicons in use no longer made sense for the revised labels so we went about sorting some new ones. Our hope was to use existing minicons if possible and only make a new one if we felt that the label could be best reflected by something new. Below shows the proposed icons for the new labels and more detail on the two sections that we focused most of our attention "at the CFPB" and "policy & compliance."
#### Description for each section:

**At the CFPB:** Bureau wide activities or announcements that is not related to a specific department. Examples of these blog post may be - New leadership hires, Ombudsmans report, strategic relationship with another federal agency, recruiting for new talent, live event announcements, etc.

**Data, research, and reports:** Information we release by the bureau that can help other users to prove their case. Users interested in this information may be - scientist, researchers, non-profit, corporations, etc. Examples of blog post would be: CFPB's recent report on pay-day-lending loans, updates to our HMDA data information, Project catalyst report on their pilot program for credit counseling, etc.

**Info for consumers:** Blog posts geared towards consumer finance. Posts usually consist of tips to finance, advice on how to purchase a home, or how to collect payments from financial institutions we have fined.

**Policy & compliance:** Posts that target financial professionals interested in CFPB's policies. Our policies affect their financial institution and they would like know what CFPB is thinking. Typical blog posts would be - Recent fines levied against a financial institution, manage consumers, updates rule making agenda, propose changes to a rule, etc.

![screen shot 2015-04-06 at 2 31 45 pm](https://cloud.githubusercontent.com/assets/6873734/7009646/b19f9736-dc69-11e4-8a71-3255145d98c0.png)
##### At the CFPB

We had also tried the announcement icon here since that is one of the major content type of this section but felt that the "at" symbol was easily identifiable and spoke to the idea of it being more internal CFPB news. 
##### Policy & compliance

This label will also act as the name for what had, in the past,been referred to as "for industry" in the FJ navigation. Since its primary goal is to speak to financial institutions we felt the building might be the strongest representation. However, we had also explored an option focusing more on the policy and regulation side of the category. 

![screen shot 2015-04-06 at 2 17 44 pm](https://cloud.githubusercontent.com/assets/6873734/7009759/831b4350-dc6a-11e4-807c-d8b0b58ba751.png)

**The two examples in context of the blog role:**
![screen shot 2015-04-06 at 2 14 25 pm](https://cloud.githubusercontent.com/assets/6873734/7009767/994cea48-dc6a-11e4-839b-8da69a4fba95.png)

**Comment by ajbush** [comment]
Some other things we considered before landing on the options Justin posted above include:

**For "At the Bureau":**
• a drop pin
• reusing the basic Blog minicon

**For "Policy & Compliance":**
• a government building

**Comment by mebates** [comment]
These seem to fit to me! Nice work. Have to say that I prefer "Consumer Information" over "Info for Consumers".

**Comment by nataliafitzgerald** [comment]
For the "At the Bureau" category I am getting stuck on the @ symbol meaning more of an online location/having a specifically online meaning. @ajbush - Do we already have a drop pin designed and if so, could you post it? The megaphone says announcements so I would only use it if that is what we are intending for this category (if it is, then the megaphone is a quick read). Are we currently using the megaphone anywhere else?  

The info minicon is working well. The government building for "Policy and Compliance" seems fine (and I much prefer it to the gavel and paper). The only alternative I can quickly come up with is the pen.

**Comment by duelj** [comment]
To answer @nataliafitzgerald the megaphone is also being used on newsroom currently for the "press release" category. I don't think it would cause any conflict for them both to use this icon but I too am in support of having a different one. Here's the list between both blog and newroom:
![screen shot 2015-04-07 at 12 44 17 pm](https://cloud.githubusercontent.com/assets/6873734/7028474/035a6082-dd24-11e4-8733-7e37f753f232.png)

**Comment by ajbush** [comment]
@nataliafitzgerald we worked on a drop pin way back but it was for the Find a Housing Counselor tool. It needed to be able to include a number so I think that was a special case. I'm sure @ohsk has a more current solution than that but here's a screenshot of the old one in use:

![screen shot 2015-04-07 at 12 38 22 pm](https://cloud.githubusercontent.com/assets/6931351/7028477/083846dc-dd24-11e4-8879-1689aa85beb2.png)

If we were to use a drop pin for "At the Bureau" it could look something like below. The team seemed to think the @ sign worked better though.

![guess](https://cloud.githubusercontent.com/assets/6931351/7028646/2bffa442-dd25-11e4-9dd7-f5aa2a933574.png)

**Comment by schaferjh** [comment]
I liked the @ symbol but Natalia raises a good point -- the dropped pin is a decent alternative that I could see working.

**Comment by duelj** [comment]
I would be on board with the drop pin as well if people think that is working better. I can see that speaking well to the type of announcements that are mentioned in the description even if it is a little physical location specific: 

"At the CFPB: Bureau wide activities or announcements that is not related to a specific department. Examples of these blog post may be - New leadership hires, Ombudsmans report, strategic relationship with another federal agency, recruiting for new talent, live event announcements, etc."

**Comment by elizbond** [comment]
I think @mebates and @klocraft did an update to the drop pin for the mortgage toolkit.

**Comment by elizbond** [comment]
Also, just scrolling through this quickly and the Speeches and Op-eds icons look very similar at the smaller level.

**Comment by duelj** [comment]
@elizbond – I think that is something we can take note of for down the road but there was a lengthy discussion to get those approved and I don't think that is something we are looking at readdressing at this point. That issue can be found [here](https://github.com/cfpb/design-manual/issues/166)

**Comment by klocraft** [comment]
Here's the drop pin we used for the mortgage booklet.

![screen shot 2015-04-08 at 11 13 01 am](https://cloud.githubusercontent.com/assets/8646678/7048302/3fc53cb0-dde0-11e4-9ad4-df5b4a6b55a9.png)

**Comment by duelj** [comment]
I think I like the simplified version AJ was showing as the shape seems easier to distinguish at small sizes. I tried a version closer to what @klocraft shared but tried to optimize it for the smaller use cases of minicons. I tried to simplify the transition between the circle and pointed bottom as the transition above did not translate well for the smaller size. Also, I made the star larger in the circle so that it could be seen more easily at the 16px size. Lastly, I was debating in my head whether the bottom should be pointed or rounded to best match the other minicons. 

![screen shot 2015-04-08 at 12 28 18 pm](https://cloud.githubusercontent.com/assets/6873734/7049819/c58de20c-ddea-11e4-89a5-c166b4196336.png)

**Comment by ajbush** [comment]
We are looking at wrapping up this issue and will be sharing this during today's working session (04/09/15).

Here's the simplified drop pin at 40 px and 16 px.

![ddd](https://cloud.githubusercontent.com/assets/6931351/7073421/69d92caa-dec1-11e4-956a-7597c5d3df13.png)

**Comment by schaferjh** [comment]
Very nice. Let's use it!

**Comment by juidai** [comment]
I like the pointed tip and the circle inside the pin works better. I think the star is too distracting. Tend to overlook the pin and focus on the star.

Otherwise, I think using pin also works.

**Comment by duelj** [comment]
+1 to moving forward with AJ's pin and the building

**Comment by anselmbradford** [comment]
**Don't feel like this comment has to hold anything up**, but first thing I saw with the pin in the circle is a rotated eyeball with eyelids, but maybe that's just me.

![screen shot 2015-04-09 at 3 12 47 pm](https://cloud.githubusercontent.com/assets/704760/7074916/0af78780-decc-11e4-8752-0095a69ad115.png)

Just wonder if moving the pin down slightly within the circle could help against this image.

Also, with the building... the steps make it look a little like it's low-res, like it's [a pixelated curve](http://i.imgur.com/n6B8rl.jpg). 
![screen shot 2015-04-09 at 3 23 36 pm](https://cloud.githubusercontent.com/assets/704760/7074969/7b6e8734-decc-11e4-9f4b-f385f9cb3029.png)

Perhaps a single step would work just as well, or a slant and then a step. 

Anyway, food for thought. I think they're great. These are just two minor associations you may want to minimize if there is time.

**Comment by ajbush** [comment]
**Feedback from today's Design Working session:**
- Everyone seemed cool with moving forward with the drop pin for "At the Bureau" and the building minicon for "Policy & Compliance".

We'll still need to add the drop pin to the minicon font and Design Manual.

**Comment by juidai** [comment]
now 'eye ball' is all i can see.

**Comment by nataliafitzgerald** [comment]
I am also seeing the eye ball face a lot now but the pin with the circle is a nice solution. Looks great! 

Did you try out any of the potential adjustments mentioned by @anselmbradford for the "Policy & compliance" minicon? I agree that at the smaller size the extra step may not be needed or a slant could work. But, I don't know how this would read at the larger minicon sizes.

**Comment by duelj** [comment]
@nataliafitzgerald  @Dnpizarro 
Since the building is already an approved minicon in the font is this an issue that we need to address here or should the be another issue added to the design manual for down the road? I think we could move forward knowing using the building will work with the policy & compliance label, does that sound right?

**Comment by ajbush** [comment]
Ok great...I'll let Daniel know you were cool with the drop pin.

Wondering if the building issue is separate though?

**Comment by nataliafitzgerald** [comment]
Pin approved.

**Comment by nataliafitzgerald** [comment]
The building issue should be documented for backlog in the design manual. @ajbush - Can you add it and we can discuss it there?

**Comment by ajbush** [comment]
**Quick update regarding the minicon for "At the Bureau".**

After checking in with Audrey at our Sprint review yesterday she pointed out that there might be confusion with using the drop pin for "At the Bureau" since all of the posts that fall under this category may not happen physically at the Bureau.

**Just to reiterate the "At the Bureau" category will include:**

> Bureau wide activities or announcements that are not related to a specific department. Examples of these blog posts may be - New leadership hires, Ombudsman report, strategic relationships with another federal agencies, recruiting for new talent, live event announcements, etc.

**So, in the meeting she suggested reusing the megaphone that we are currently using for Press releases in the [Newsroom](http://beta.consumerfinance.gov/newsroom/cfpb-takes-action-against-military-allotment-processor-for-charging-servicemembers-hidden-fees/)**

The drop pin could be a good minicon to keep in our library for other uses that may come up.

Here's a quick summary of where we landed.

![bin](https://cloud.githubusercontent.com/assets/6931351/7277134/25b68e30-e8dc-11e4-8e92-6ca4c9178d5b.png)
