### ISSUE TITLE
Palette section links to deprecated codebase

### ISSUE THREAD

**Issue by anselmbradford** [cfpb/design-manual#306]
[View code](https://github.com/cfpb/design-manual/blob/b55592ed738a5b04920ea61796f180d3f0deb2cc/identity/color-principles.md#paletteview-code-) https://cfpb.github.io/design-manual/identity/color-principles.html#palette links to https://github.com/cfpb/cf-colors, which appears to have been deprecated.

**Comment by jimmynotjim** [comment]
We don't currently have our branded palette in the Capital Framework repo. We've debranded the project and use a theme file in the project generator. Not sure if we should link to that or remove the link altogether or wait [till this gets hashed out](https://github.com/cfpb/capital-framework/issues/265#issuecomment-272277172).

**Comment by jimmynotjim** [comment]
This is fixed.
