### ISSUE TITLE
Adding the Spanish and Chinese glossaries to the Design Manual

### ISSUE THREAD

**Issue by elizbond** [cfpb/design-manual#307]
Jumping off of issue #283 

@jameshupp and @harrisqureshi what can we do to get the editorial style guide added to the Design Manual? I know it's going through a few updates now but we think it makes sense to host with the brand so the Design Manual acts as a "one stop shop." I had a meeting today with Carmen Cruz and Cassandra Tatum about adding the Spanish and Chinese glossaries to the Design Manual. It would be such an exciting addition to get it all published at once. Is there a timeline for the updated editorial style guide? If not, could we go with the current version in the interim?

**Comment by mebates** [comment]
@elizbond, is this realistic for the June or July sprint? I think it may be a backlog item. Lauren Johnson is doing some work on this on the CE side but I'm not sure of the status.

**Comment by elizbond** [comment]
It's been decided to not to move forward with this since we cannot include the English version. Closing this issue.
