### ISSUE TITLE
Swap out illustration on Design Manual landing page 

### ISSUE THREAD

**Issue by nataliafitzgerald** [cfpb/design-manual#308]
This is not a top priority but we should swap in a new image for the Design Manual landing page. The black minicon on the green background goes contrary to our Design Manual. On our web and print offerings we do not show black minicons on the brand green background. And, since minicons typically appear in line with text I view them as text/type elements for all intents and purposes. The illustration we show on the landing page of our design manual should be 100% on brand.

Undesirable combinations - "Even though CFPB Green and CFPB Black are accessible for large scale type, this color combination should never be used for web type."

![screen shot 2015-04-13 at 11 36 21 am](https://cloud.githubusercontent.com/assets/6887128/7119066/57a73672-e1d1-11e4-8701-da6d1c66cc81.png)

![screen shot 2015-04-13 at 11 38 52 am](https://cloud.githubusercontent.com/assets/6887128/7119133/b55bd804-e1d1-11e4-99fb-9627304710d2.png)

**Comment by Scotchester** [comment]
Related: #275

**Comment by mebates** [comment]
@nataliafitzgerald I'm going to close this, since we're already talking about it in #275!
