### ISSUE TITLE
Eliminate repetitive titles

### ISSUE THREAD

**Issue by mebates** [cfpb/design-manual#31]
Using this page as an example: 
http://cfpb.github.io/design-manual/identity/illustration.html

Eliminate 'Identity' from above the side nav; no title needed there.
Eliminate the work 'Identity' from 'Identity: Illustration'

The only signal for the section should be the primary nav.

**Comment by danny8000** [comment]
@mebates  please verify:

http://danny8000.github.io/design-manual/identity/illustration.html

**Comment by mebates** [comment]
Looks good!

**Comment by ascott1** [comment]
#69 should remove the last few of these

**Comment by mebates** [comment]
Nice. Closed.
