### ISSUE TITLE
Typography page: anchor link error

### ISSUE THREAD

**Issue by ohsk** [cfpb/design-manual#313]
The Web Accessibility anchor link isn't correctly matching the section id.
http://cfpb.github.io/design-manual/identity/typography.html#web-type-accessibility

Section:
`<h2 id="type-accessibility">Type accessibility</h2>`

**Comment by Scotchester** [comment]
Oops :flushed: That's my fault for an insufficient code review of #312.

**Comment by Scotchester** [comment]
Closed in #318.

**Comment by mebates** [comment]
:tada: done before july!!
