### ISSUE TITLE
Add Events package to Design Assets

### ISSUE THREAD

**Issue by Dnpizarro** [cfpb/design-manual#314]
The Events Package for External Affairs was recently completed. I will be adding all of the associated files to our design assets folder.

![screen shot 2015-05-04 at 3 18 33 pm](https://cloud.githubusercontent.com/assets/6852363/7460420/e6bd42e8-f270-11e4-8e35-88aa572676cf.png)

**Comment by Dnpizarro** [comment]
The Events Package was added to our "Templates" library under "Print."

**Comment by mebates** [comment]
Whats up with the mirrored beam shape on the 'folder spread'?

Otherwise, this looks awesome! So extensive/thorough @Dnpizarro.
