### ISSUE TITLE
Small copy error on form fields page

### ISSUE THREAD

**Issue by Scotchester** [cfpb/design-manual#321]
The UI toolkit form fields page states that inputs with focus/error/success states should have 1px borders, but the actual standard (and what is implemented in cf-forms) is 2px.

![screen shot 2015-05-12 at 10 50 39](https://cloud.githubusercontent.com/assets/1044670/7590180/1f632408-f895-11e4-821d-1d2ea8641ee0.png)

**Comment by caheberer** [comment]
This should be fixed with the update happening in #346.
