### ISSUE TITLE
Level of detail in illustrations

### ISSUE THREAD

**Issue by designlanguage** [cfpb/design-manual#324]
For the most part, the level of detail in our illustrations in pretty consistent. There are a few outliers though. For example, the check and fountain pen (that are in progress) compared to the dollar bill:

![screen shot 2015-06-01 at 2 58 42 pm](https://cloud.githubusercontent.com/assets/10562544/7920700/b9ccbe26-086e-11e5-917a-c0faa9119c9a.png)

If these items were combined in a scene, they wouldn't feel like they belonged together. Here is a simplified check that we are proposing for use in the reverse mortgage booklet diagrams and that same dollar:

![screen shot 2015-06-01 at 3 03 21 pm](https://cloud.githubusercontent.com/assets/10562544/7920814/62454b4a-086f-11e5-97d6-2877f870e86d.png)

Here are a few other examples of different levels of detail along with quick attempts to bring them a bit closer together:

![screen shot 2015-06-01 at 3 42 03 pm](https://cloud.githubusercontent.com/assets/10562544/7921624/cd622a9c-0874-11e5-9400-2101d0960a55.png)

If we can see individual links in the chain, there should be a lot more visible on the dollar. The text on the dog tag can also be thicker.

![screen shot 2015-06-01 at 3 33 46 pm](https://cloud.githubusercontent.com/assets/10562544/7921462/abb52062-0873-11e5-928f-b8e8c775bf65.png)

We shouldn't be able to see the keyhole of the lock on the car keys when there's so little detail in the credit card. 

![screen shot 2015-06-01 at 3 35 05 pm](https://cloud.githubusercontent.com/assets/10562544/7921492/d73185e6-0873-11e5-925c-67b5c531e357.png)

The wallet doesn't need that fine line on the metal button for us to register what it is.

These explorations aren't based off any guidelines for level of detail, but I think we should attempt to formalize some. A declared level of detail would allow us to easily combine illustrations into compositions in the future and it would also bring consistency across our materials.

Doing this may not be easy with vector illustrations because they can be created at any size and scaled as needed. In other words, if we determine that "the minimum point size for a line should be 2pt," but two illustrations are created at different sizes, this is what you'll get when they are sized similarly:

![screen shot 2015-06-01 at 3 58 56 pm](https://cloud.githubusercontent.com/assets/10562544/7921991/5474c6aa-0877-11e5-8fd0-ca5d77822e5a.png)

Likewise, if we determine that all illustrations should be created at a defined size, And one item is shown larger next to another (coin vs tablet, for example) will look less detailed when scaled up:

![screen shot 2015-06-01 at 4 02 15 pm](https://cloud.githubusercontent.com/assets/10562544/7922101/ee3bf592-0877-11e5-9342-e7e5e9368db1.png)

Additionally, and I'm not sure this is a factor, but if some illustrations are shown very large and on their own, while others are a small part of a larger composition, there may need to be two levels of detail (hero and component). 

I've just started thinking about this and I'm open to ideas, including the idea that formalizing detail level isn't necessary. If anyone has any thoughts please share below.

**Comment by nataliafitzgerald** [comment]
@designlanguage - I never saw this post before and it looks like it's been in the backlog for a while. This would be a perfect issue to move over to our Graphic Design repo so that we can continue to see it through. Then once we have some defined standards we can move it over to the Design Manual in order to add it to our standards. I like where you're going with the examples you posted. Great start!
