### ISSUE TITLE
multi-column alignment of blurbs with isocons/illustrations, sometimes with buttons or links

### ISSUE THREAD

**Issue by benguhin** [cfpb/design-manual#326]
Here's one example. Please add examples!

![screen shot 2015-06-11 at 3 56 12 pm](https://cloud.githubusercontent.com/assets/6953063/8116845/7bcfc03c-1052-11e5-8fbd-4d8b1fb3cf5f.png)

**Comment by nataliafitzgerald** [comment]
Issue https://github.com/cfpb/design-manual/issues/296 starts to get into the treatment of illustrations across breakpoints.

**Comment by mebates** [comment]
![screen shot 2015-06-11 at 4 11 05 pm](https://cloud.githubusercontent.com/assets/6223901/8117216/941591d8-1054-11e5-86fc-e550ddc1ea1e.png)
![screen shot 2015-06-11 at 4 11 18 pm](https://cloud.githubusercontent.com/assets/6223901/8117215/9414620e-1054-11e5-8bc5-8b3797039a38.png)
![screen shot 2015-06-11 at 4 11 34 pm](https://cloud.githubusercontent.com/assets/6223901/8117217/9423a606-1054-11e5-81f3-424aef23b3e0.png)

**Comment by nataliafitzgerald** [comment]
To show how this changes across breakpoints, here's another image: 

| Mobile |
| --- |
| ![screen shot 2015-04-09 at 5 56 01 pm](https://cloud.githubusercontent.com/assets/6887128/7077803/ff97f3f0-dee1-11e4-85da-cefd9e18f6c9.png) |

| Desktop |
| --- |
| ![screen shot 2015-04-09 at 5 41 52 pm](https://cloud.githubusercontent.com/assets/6887128/7077650/ab90fb5e-dee0-11e4-9a44-a9780aaa16ef.png) |

**Comment by nataliafitzgerald** [comment]
I would say that HMDA, as a general rule, is a standards outlier. So, we should always take it with a grain of salt when thinking through standards.

**Comment by nataliafitzgerald** [comment]
We don't use circles here but the alignment is left for the text. It's not responsive so I can't show the mobile view. But it's easy to imagine what the mobile layout would look like (i.e. the same as the desktop but instead one column). 

| Desktop |
| --- |
| ![screen shot 2015-06-11 at 4 32 43 pm](https://cloud.githubusercontent.com/assets/6887128/8117630/9db1ec02-1057-11e5-99ef-9d3750ffbbd4.png) |

**Comment by nataliafitzgerald** [comment]
I support left aligning the text blurbs. The only example so far that is centered is the CFPB Open Tech blurb text and that text would work just as well left aligned. For circles, I support centering at all screen sizes when we have a multi-column layout. I imagine we still have more examples to collect, however. @caheberer Can you post the Claiming Social Security example?  

Another question we raise in https://github.com/cfpb/design-manual/issues/296 is when illustrations should appear or not appear on mobile.

**Comment by mebates** [comment]
@nataliafitzgerald will always think of hmda as 'the one that got away' :wink:

**Comment by nataliafitzgerald** [comment]
Yes @mebates, indeed I will. It was a different time. Even a different place. The landscape was wild then and we were all cowboys...and ladies, lighting the dark paths of the western frontier with our simple beam.

**Comment by stephanieosan** [comment]
<3

**Comment by Scotchester** [comment]
I'd vote centered, personally. Due to extra space on the right side of the text blocks, the ones on CCDB look kinda misaligned.

Perhaps if we put vertical dividers between the columns to visually anchor the left-aligned blocks, it would look less awkward?

**Comment by caheberer** [comment]
Addressed with wagtail.
