### ISSUE TITLE
Tab Use Cases (Content & Navigation)

### ISSUE THREAD

**Issue by duelj** [cfpb/design-manual#328]
#### Issue

Since we have now embraced the use of tabs and [standardized their formatting](https://github.com/cfpb/design-manual/issues/233) I thought it would be nice to create a bit more of a framework for use cases. It seems there are two major camps for how tabs might be implemented, as a means of auxiliary navigation within their section, and moving through "panels" of content in the main content of a page. The latter being the likely use case will probably not need much defining, but with projects using tabs as a means of navigation, it seems more relevant to create some framework around when/how this happens in order to minimize redundant navigation modules or conflicting navigation patterns. 
#### Tabs as nav.

If the product (tool, page, guide, etc.) will live on consumerfinance.gov the [navigation patterns](https://github.com/cfpb/design-manual/issues/291) developed for the CF Refresh should be utilized as much as possible (this would require teams to mould their products IA to align with the user journey that informs the FJ navigation). If there is a unique need for deeper auxiliary navigation (example: [OAH Know the Process](http://build.consumerfinance.gov/owning-a-home/process/prepare/) ) where tabs (or other interactions) might be used there should be clear reasoning why the default navigation patterns can't be used. 
##### OAH Know the process (ordered process)

![screen shot 2015-06-25 at 10 32 56 am](https://cloud.githubusercontent.com/assets/6873734/8356817/935592bc-1b25-11e5-8f57-bee8ffc9636d.png)
##### Know Before You Owe - Real Estate

![tabs_as_nav](https://cloud.githubusercontent.com/assets/6873734/8356867/cf5a0fb8-1b25-11e5-9a48-ad56ecbbdf65.png)

**Comment by stephanieosan** [comment]
I wholeheartedly agree.

As a team, we had a ton of heartburn about moving away from the flapjack navigation in the case of our Know the process, and deliberated with the Flapjack team a lot about it.

Our reasons are this: 
Our 5 Know the process pages represent a single linear process, and it's important for users to understand both the overall process and where they are currently located within the process.

We tried a variation of the FJ left-hand navigation that included phase numbers, which we hoped could work, but in testing the top-tab navigation outperformed the side navigation. Users better grasped the mortgage process when it was across the top of the page.

---

I still feel uneasy about breaking from the FJ nav, and I definitely don't want our departure from the FJ nav to lead to everyone starting to use (or not use) navigation patterns all willy-nilly, and bring about a lawless wild west of navigation to cf.gov-land! 

So, I'm in favor for talking about when (if ever) is the right time to break from the left-hand nav (for that level page) or no nav (for the learn pages). I don't think it should be because our clients prefer tabs or something else. And we might want to also talk about our case, when users say they prefer tabs. Maybe that's a valid reason to depart, and maybe not.

**Comment by duelj** [comment]
@stephanieosan I think the testing that you and I believe the KBYO team have done with the tabs navigation is really important, I totally agree on that. Hopefully, as FJ gets our updated multi-level side nav. and breadcrumbs on beta we can begin to test that more formally as well. I think it would be great to test that against an option more like the tabs approach to get another data point, as there is a very good chance we didn't build the perfect navigation. 

**I think the discussion between OAH and FJ was a good model for approaching an alternate nav. discussion and something we should strive for in the future.** I do hope that the [DM layout page](https://github.com/cfpb/design-manual/issues/291), Refresh design temple, and [FJ sitemap(s)](https://github.cfpb.gov/flapjack/sitemap) can help to alleviate situations where aux. nav. might be needed as I think modeling the IA on those navigation patterns early on can help remove navigation roadblocks down the road. Granted, these resources are new and teams didn't have access to the same documentation in the past (nor was it as resolved). It will equally be nice to test and see how these resources help in the future.

**Comment by mebates** [comment]
I would be interested in hearing some UX voices in here with thoughts about advantages and disadvantages of tabs. We had discussions about this early on in the Digital Product Guide; check out the conversation at [internal git hub]/digital-product-guide/issues/23. 

Glad we've finalized a style, but definitely need to solidify UX rules. 

Also, we still use tabs on the Intranet in an entirely different way:
![screen shot 2015-06-26 at 2 57 38 pm](https://cloud.githubusercontent.com/assets/6223901/8385099/bfd5b7f6-1c13-11e5-9034-66b2689c3950.png)

**Comment by mebates** [comment]
CCDB uses tabs as well:

![screen shot 2015-07-08 at 3 02 54 pm](https://cloud.githubusercontent.com/assets/6223901/8579421/829993b2-2582-11e5-8baf-b1c05bf926ac.png)

**Comment by mebates** [comment]
Notes from our working session. UX will take on further standards/ best practices.

### Tabs as ordered, progressive navigation
- Owning a Home is doing this in the Journey
- Loads a new page or URL
- OaH tested the tab solution versus a numbered left hand nav, and users preferred the tabs
- Should we call this something different than tabs? Wizard or step through?
- Needs a progressive step through, in a specific order
- Nice to have next and previous buttons at the bottoms

### Tabs as organizing content on a page
- CCDB and OaH Rate checker use this model
- Tabs should organize content on a page. 
- Especially if it's very similar content and no level of importance, or either/or.
- Doesn't load a new page or URL
- Interactivity encourages exploration

All tabs need attention to 508 accessibility.

**Comment by mebates** [comment]
Another tab use:

![screen shot 2015-07-08 at 3 18 37 pm](https://cloud.githubusercontent.com/assets/6223901/8579792/aae373ae-2584-11e5-9791-41f9497c56d0.png)

**Comment by nataliafitzgerald** [comment]
Here's another instance of that same tab use case (toggle):
<img width="1126" alt="screen shot 2015-07-08 at 3 20 02 pm" src="https://cloud.githubusercontent.com/assets/6887128/8579827/e25decc4-2584-11e5-850e-73ed37bf76f1.png">

**Comment by keelerr** [comment]
UXers are discussing tabs and hopefully coming up with some solid guidelines around usage, I've captured my thoughts (and will continue to edit based on the feedback I receive) here.
https://docs.google.com/document/d/1m1UIb_DplE7i719rwozFb6vVGmOmyLwYFkmYMNyazAc/edit#

**Comment by Dnpizarro** [comment]
@keelerr lets set some time apart to go over your document. I had some questions particularly around word count for the Tab labels. Also, lets plan for an update to the group at this Monday's Design Manual meeting.

**Comment by keelerr** [comment]
Draft content [here](https://docs.google.com/document/d/1_nkqDqFYu2RnwbiR1w2TcRRNIjeC8t-68-s18Z2w4mg/edit).

**Comment by Dnpizarro** [comment]
I opened up a new issue for the Tabs design manual page. #352 

Stay posted for updates on designs...

**Comment by caheberer** [comment]
Use cases already considered in #352
