### ISSUE TITLE
Web Type Hierarchy - Header 5 and 6 exploration

### ISSUE THREAD

**Issue by nataliafitzgerald** [cfpb/design-manual#329]
On some of our recent web projects we have identified a need for something in between 14 px and 18 px. It would be great to hear whether other designers are having the same need or whether this is more of an isolated case. Here are some proposed adjustments: 

Option 1: My issue with this option is that H6 feels bigger, and more substantial than H5. 
![screen shot 2015-06-25 at 7 41 07 pm](https://cloud.githubusercontent.com/assets/6887128/8367937/2a8e5866-1b72-11e5-9ae5-d6f0a295252e.png)

Option 2: Here H6 is notably smaller, but I wonder if the small size is too small to get a lot of game time. 
![screen shot 2015-06-25 at 7 39 20 pm](https://cloud.githubusercontent.com/assets/6887128/8367920/f7f98150-1b71-11e5-81f1-3eac32cd1806.png)

Thoughts? @duelj @amycesal @Scotchester @stephanieosan

**Comment by duelj** [comment]
I have not had any issues with the current type hierarchy, it seems to be working well in the types of pages that we are building in FJ so far (not sure if @ajbush feels differently about this). 

If there are other teams that are finding issues with the current set up it would be nice to see some examples to see if there is a way to make the current hierarchy work better for them. If we find it isn't working in these upcoming cases I am all for exploring. However, I would vote for trying to make what we have already developed work for us first. I know for flapjack, if we were to edit H5 & H6 it could make for a substantial time investment to revisit modules using those levels to make sure they are still working.

**Comment by nataliafitzgerald** [comment]
@duelj - For now we aren't making any changes, just trying to gather use cases in order to determine whether this is an isolated example or whether there is a larger need. Can you post a screenshot to show how you are currently using H6? What are the typical use cases?

**Comment by Scotchester** [comment]
@amycesal Could you post the expandable group example (Library program ideas) that prompted this?

**Comment by amycesal** [comment]
![screen shot 2015-06-25 at 12 55 13 pm](https://cloud.githubusercontent.com/assets/1656046/8381991/8dce146c-1bfd-11e5-96ba-958b174bd1f7.png)

The expandable titles are H4. and there are long category titles in each expandable, that would be an H5, but were too many words to make a smaller all caps title feel right. The main line length offender being "Organizations that can help spread the word".

**Comment by caheberer** [comment]
Type hierarchy conversations happening within wagtail documentation and should continue there.
