### ISSUE TITLE
Design Patterns for Page Intros

### ISSUE THREAD

**Issue by kurzn** [cfpb/design-manual#337]
This is to continue the UX portion of the "hero" conversation. 

Rather than limiting the conversation to just discussing heros, the conversation has pivoted to discussing creating design patterns for how introductory content is handled on pages. 

There are "heros" and then there are "expanded intro" - an example of an expanded intro would be this: http://www.consumerfinance.gov/owning-a-home/check-rates/ 

The goal of this discussion/issue is to determine: 
- When a page should include a hero or expanded intro
- What uniquely defines each of those types of page intros
- What elements belong on each of those page intros

Referencing following issues: 
https://[internalGH]/flapjack/Getting-started-with-Flapjack/issues/35
https://github.com/cfpb/design-manual/issues/301

**Comment by benguhin** [comment]
I'm gonna add screenshots of our google doc here – I think it's ready to for some visual design input! Props to @kurzn for taking the lead on this

Doc: https://docs.google.com/a/cfpb.gov/document/d/120S1FyRaIAefcVgODGhnaO99ycigH_-5_4cI5KAfE4A/edit?usp=sharing

![screen shot 2015-07-16 at 10 20 31 am](https://cloud.githubusercontent.com/assets/6953063/8725864/b75b2110-2ba4-11e5-87fb-8a9e5a002533.png)

![screen shot 2015-07-16 at 10 20 42 am](https://cloud.githubusercontent.com/assets/6953063/8725903/e75ded66-2ba4-11e5-824b-8f101e40cfd5.png)

![screen shot 2015-07-16 at 10 27 45 am](https://cloud.githubusercontent.com/assets/6953063/8725980/52917ada-2ba5-11e5-8adc-d138fbfcfb8b.png)

**Comment by kurzn** [comment]
Google Doc with Full Recommendations: 

https://docs.google.com/document/d/120S1FyRaIAefcVgODGhnaO99ycigH_-5_4cI5KAfE4A/edit#

We will be discussing these at the next design manual meeting and handing off to visual design to take the next steps in defining standards. 

Two action items from this discussion: 
- UX will create a new design manual issue to hash out rules around use of buttons vs links
- Visual design should include "card" design standards and guidelines as part of this hero conversation

Comment from Lauren Locraft re: the use of "card" design in a hero: 

"Using KBYO as an example, there are multiple "correct" ways to set up this space--it just comes down to content and how you want that content to connect between the hero space and main page. Here's what I've found:

Card Hero: Use when the main goal of the full hero space is to feature a resource or tool. This approach allows us to highlight a specific tool without overshadowing the information on the page. The right-alignment of the Card Content does not compete with the main introduction of the page, allowing the two spaces to work together without being reliant on one another.

Traditional hero: Use when the main goal of the hero space is to introduce the page. The left alignment of content serves as a natural intro the content of the page. The hierarchy works together as the hero serves as the context for the page content.

There are, of course, exceptions and problems with my blanket statement. But having general guidelines gives a much stronger starting point and will help keep the logic behind our choices consistent across the full site.

It will also help teams have a more productive conversation with stakeholders about the main goals of each page; and help stakeholders better prepare content so that content and design serve as complements to each other."

**Comment by kurzn** [comment]
The google Doc is complete with the UX team's recommendations. This is officially ready for the visual design team to take on. 

@Dnpizarro

**Comment by duelj** [comment]
As the visual discussion begins I wanted to share some of the documentation we have done mainly on the [card hero](https://github.cfpb.gov/flapjack/Getting-started-with-Flapjack/issues/35)

#### Should we include introduction sections in the conversation as well?

I think it is also worth noting the [intro section](https://github.cfpb.gov/flapjack/Getting-started-with-Flapjack/issues/35#issuecomment-44404) exploration. I know a lot of other teams (such as OAH and KBYO) have explored the intro section an when to use it, and for flapjack we trying to consistently use a basic intro section for most pages. Some exceptions are [blog](http://beta.consumerfinance.gov/blog/), [newsroom](http://beta.consumerfinance.gov/newsroom/), and [activity log](http://beta.consumerfinance.gov/activity-log/), which are content feeds and just use a title. We have also explored a modified intro section that we have used for learn level pages such as a [blog post](http://beta.consumerfinance.gov/blog/americans-with-disabilities-have-the-right-to-improve-their-financial-lives/), [news article](http://beta.consumerfinance.gov/newsroom/cfpb-study-finds-electronic-mortgage-closings-can-benefit-consumers/), or event post that better suit the needs of an individual piece of content.

**Comment by stephanieosan** [comment]
@duelj I was just thinking about that today! I'm going to open up separate issues about the visual design  for the three cases Natalie outlined in her document. 

Because it seems like the three cases have different levels of discussion necessary before we can call the visual design final and approved (like, the card hero should be really quick and simple to close out).

**Comment by kurzn** [comment]
After several discussions with the team, we have evolved the definitions of hero further, as documented below.

# New Decisions

1.To simplify the definition and narrow the possible usage of heros, we updated the language used to discuss page introductions.

You can have: 
- Hero
- Module
  - Featured content
  - Expanded intro

This helps reinforce the idea that a hero is not removable from the content. 

2.Heros will have more visual weight than modules (full width, potentially taller) to better provide visual page hierarchy. 

Heros will be limited to landing page types (1st/2nd level), although we need a bit more discussion/exploration to lock this down. 

3.The “card style” will not be relegated to a specific type of page intro, but instead be implemented as a design solution to having a video or photograph in a hero or module. Currently, we agree that there isn’t a strong use case presented for a video/photographic hero, and will not be exploring a card style for heros. When/if that use case is presented, we will be open to exploring design patterns to accommodate it. 

Thus far, all presented video content would fall under a featured content or expanded intro module based on the purpose of the video and how it fits into the context of the page.  

## Current Document Tracking Guidelines

https://docs.google.com/document/d/1t-cf7aELAE5ejS74SPo6r70xxpP-MnPB-W6T2LiA-Bo/edit# 

@stephanieosan @nataliafitzgerald @Dnpizarro @sonnakim @heutig

**Comment by kurzn** [comment]
This issue dovetailed into Hereos https://github.com/cfpb/design-manual/issues/348 and Featured Content Modules https://github.com/cfpb/design-manual/issues/351

**Comment by kurzn** [comment]
This issue dovetailed into Heroes https://github.com/cfpb/design-manual/issues/348 and Featured Content Modules https://github.com/cfpb/design-manual/issues/351
