### ISSUE TITLE
Remove/edit pages in nav

### ISSUE THREAD

**Issue by mebates** [cfpb/design-manual#34]
Identity:
Remove 'Brand Guidelines' (I'm not sure what this is)
Remove the word 'principles' from Color and Typography. All of these have principles, right? I think this was a remnant of when we had color and typography repeated in the UI section. 

UI elements:
Remove 'Markdown' and 'HTML Elements' and 'Typography' (appears in Identity section)
Hide 'Grid and layout'. Not currently on the sitemap but could come up later

Would love for @dezzie and @stephanieosan to confirm that they agree with these requests. Thanks!

**Comment by mebates** [comment]
Also, I know @danny8000 arranged these alphabetically for now, but it may be helpful to rearrange the menu items in a more logical order. (Match Style Guide order for Identity, pair like-elements in UI)

**Comment by ascott1** [comment]
@mebates pull request #69 removes/renames the nav sections and orders the identity section as described by @ohsk in #67, but I wasn't sure of an order for the UI toolkit nav.

**Comment by mebates** [comment]
I don't think we've thought about this. I would suggest, arbitrarily via my own logic:

Buttons
Links
Expandables
Tables
Pagination
Modals
Tooltips
Form fields

Any other thoughts?

**Comment by Scotchester** [comment]
I think I would try to order them from simplest to most complex. Here's what I'd suggest:
- Links
- Buttons
- Form fields
- Tables
- Pagination
- Expandables
- Tooltips
- Modals

**Comment by mebates** [comment]
I'm fine with that.

**Comment by iuloshi** [comment]
Per chatroom discussion, decided to keep the UI toolkit sub-nav ordered alphabetically so it's more easily navigable and scalable. Will reorder the Identity sub-nav to be alphabetical also.
