### ISSUE TITLE
Clarify leading for web headers

### ISSUE THREAD

**Issue by mebates** [cfpb/design-manual#349]
There's some disagreement about what the leading for web headers should be. We need to clarify the standard and then update the hierarchy.

The section of the Design Manual below led me to set all headers with leading at 1.375 em:
![screen shot 2015-08-14 at 10 28 21 am](https://cloud.githubusercontent.com/assets/6223901/9276000/429f8474-426f-11e5-82a4-f60b60a1814a.png)

@Scotchester says that he interprets that rule as only for body copy, and has set other leading settings in the Capital Framework for headings:

| level | font-size | line-height |
| --- | --- | --- |
| h1 | 34px | 44px |
| h2 | 26px | 33px |
| h3 | 22px | 28px |
| h4 | 18px | 22px |
| h5 | 14px | 22px |
| h6 | 12px | 22px |

(I think we left h5 and h6 at the same line-height as the body because they are unlikely to ever wrap, and it helps maintain good vertical rhythm.)

@nataliafitzgerald has made some new recommendations for leading for another project, but it may be helpful here:
![5952e690-41f5-11e5-815c-4c45da336ea2](https://cloud.githubusercontent.com/assets/6223901/9276027/7ccfb4e8-426f-11e5-93ee-a820cff909b3.png)

**Comment by nataliafitzgerald** [comment]
It is important that we include the line spacing in the web type hierarchy the way we include leading in print. Currently there is a rule of thumb, that @mebates mentioned above and some examples in the line height section but no clear size/line spacing measurement included. 

This is the way the web type hierarchy section appears on the Design Manual. Size is specified but line spacing is not included:
<img width="700" alt="screen shot 2015-08-14 at 12 50 51 pm" src="https://cloud.githubusercontent.com/assets/6887128/9279101/27752a78-4283-11e5-8f02-499e82e9086d.png">
So, we are left with the rule of thumb which really doesn't work for headers in many cases, however (i.e. the line spacing is too loose). 

And it looks like Capital Framework doesn't reflect this rule (for header line spacing). 

Additionally, in looking at the refresh template, leading is not specified in the paragraph styles for the headers (it should be added) however when I click on the type and open the character palette I find the following to be true (for the template):

| level | font-size | line-height |
| --- | --- | --- |
| display | 48px | 57.6px |
| h1 | 34px | 40.8px |
| h2 | 26px | 31.2px |
| h3 | 22px | 26.4px |
| h4 | 18px | 21.6px |
| h5 | 14px | 16.8px |
| h6 | 12px | 14.4px |

**Comment by duelj** [comment]
This looks like great exploration, I after reading through the posts is the recommendation to update the spacing to the leading specified by @Scotchester? The 1.2 ratio that is in the design template seems to be working well for FJ so far but does seem to be tighter than some of the other recommendations. Is there any perspective on whether fluctuating spacing (like the example by @Scotchester) would work better than a set interval (like the design template)?

**Comment by duelj** [comment]
### Update from 10/22/15 working meeting with @Scotchester, @nataliafitzgerald, @doguin, @jimmynotjim, and myself.
- Header leading (for all levels): 1.25 ratio 
- This ratio translates to the following px measurements for each level:
  - display: 48/60
  - h1: 34/42
  - h2: 26/32
  - h3: 22/28
  - h4: 18/22
  - h5: 14/18
  - h6: 12/15
- illustrator file will use these pixel amounts and coding will use ratio
- Decision was made on this during the #269 discussion because the line height would impact the spacing between headers, paragraphs, etc. so we couldn't decide one without the other

**Comment by jimmynotjim** [comment]
PR for Capital Framework side of things here https://github.com/cfpb/cf-core/pull/53

**Comment by mebates** [comment]
Awesome. So can we build these new standards into the Design Manual? I will bring them into the editorial template right now.

**Comment by mebates** [comment]
The leading standards have been added to the design manual. :fire:

**Comment by Scotchester** [comment]
The new standards can be demoed at http://cfpb.github.io/cf-type-testing/dist/

**Comment by Scotchester** [comment]
Previous comment updated with a correctly-pasted URL.
