### ISSUE TITLE
All caps vs. sentence case in form field labels 

### ISSUE THREAD

**Issue by sonnakim** [cfpb/design-manual#354]
Opening this issue to discuss the use of all caps vs sentence case in form labels.
## The issue

OaH would like to propose changing form label styles from all caps (H5) to sentence case (possibly H4) for the following reasons -

1) Usability.  It's been documented that all caps are slower to read than sentence case. Here is a nice <a href="https://www.digitalcookie.com.au/blog/writing-readable-content-and-why-all-caps-is-so-hard-to-read.html">summary of the issues</a>. 

2) Shoutiness. Probably our biggest two-way engagement with the general public is through Submit a Complaint, a form that has very long questions for labels. Using all caps here turns a moment where we want to instill trust and confidence in our users into an unpleasant, shouty sort of experience

![image](https://cloud.githubusercontent.com/assets/9451445/9620930/32c44e80-50ee-11e5-9fea-5fccdbaa6dcf.png)

3) Consistency. What we're trying to do with this style guide is establish well-thought-out general rules for  better consistency. It's hard to come up with a use case where all caps labels are okay just some of the time...we really need to try to be consistent :-\ 

EDITED TO ADD:
4) Accessibility: All caps text is <a href="http://www.dyslexia.ie/information/computers-and-technology/making-information-accessible-dyslexia-friendly-style-guide/">especially difficult for people with dyslexia to read </a> (estimated at 10% of the population).
## The proposed change

We'd like to propose changing the existing label style from H5, all caps, to H4, sentence case.  Also, for accessibility reasons, we had to lighten the fieldset background from Grey 10 to Grey 5 and darken helper text to Dark Grey. 

This causes minor hierarchy repercussions for certain lower type styles—inline helper text ("this field is optional"), block helper text and error text—which we think we resolved. 

This is what the Flapjack FOIA form could look like with all the tweaks taken together. @nataliafitzgerald @benguhin @duelj we'd love your feedback. 

![submit_request_sk_4 2-13](https://cloud.githubusercontent.com/assets/9451445/9631361/53aa81cc-514e-11e5-9237-15426218cc25.png)
## Considerations

We do want to keep the form fields DM page on track for September 30, and we're hoping to get final approval on this very soon. If this issue proves too controversial, we can backlog this and document the existing all-caps label style.

**Comment by benguhin** [comment]
This example page is great – I think the H4 in sentence case for form labels works well in terms of visual hierarchy while also making the form easier to read. 

@nataliafitzgerald what do you think?

**Comment by ohsk** [comment]
Yikes! I'm not sure how those all caps labels got in there... Here's what I had in last comps from two years ago, haha. I think what you're proposing with H4 sentence case feels very appropriate.

![image](https://cloud.githubusercontent.com/assets/1689222/9764862/50549774-56df-11e5-881f-b4e9509cdce7.png)

![image](https://cloud.githubusercontent.com/assets/1689222/9764907/89deed50-56df-11e5-992d-d2125c75cb1d.png)

**Comment by sonnakim** [comment]
@ohsk No worries and sorry, the live submit a complaint site does in fact use sentence case! We just hacked the CSS on the site to show the worst-case scenario, why we would want to recommend sentence case as the gold standard for all forms going forward (i.e. in case someone decides down the road that the all-caps label style is appropriate for long questions...).

**Comment by ohsk** [comment]
PHEW ok I thought I had gone crazy :D

**Comment by sonnakim** [comment]
haha sorry stephen!

**Comment by sonnakim** [comment]
@nataliafitzgerald Hey Natalia - We are looking to close Form Fields up by the end of the week if possible. Any way you could give your final blessing or objections on this all caps issue and on the <a href="https://docs.google.com/document/d/1SvgJ2hIyUVo2BzCvoV95NOKtr8ylv2TIdkkYzAXexj0/edit#">form fields wireframe</a> by Friday Sep. 11? If all caps labels is still controversial, we can backlog it.

**Comment by nataliafitzgerald** [comment]
I think we're all squared away on this as documented here. https://github.com/cfpb/design-manual/issues/346 Is there anything else you need on my end?

**Comment by sonnakim** [comment]
Nope, we are good to go. Thanks!
