### ISSUE TITLE
Filter Minicon

### ISSUE THREAD

**Issue by ohsk** [cfpb/design-manual#355]
#### CR Search will probably need to make use of an icon to represent Filter / Filtering.

Starting a thread to document it's design. The most common image seems to be a funnel, but feel free to share any other options you've come across!
##### Initial search on [Noun Project](https://thenounproject.com/search/?q=filter&i=184692)

![image](https://cloud.githubusercontent.com/assets/1689222/9764583/dc7d9130-56dd-11e5-90f1-2b9108860a82.png)
##### Funnel on [Iconic](https://useiconic.com/icons/funnel/)

![image](https://cloud.githubusercontent.com/assets/1689222/9764644/373f9af0-56de-11e5-9e44-139ca52f8148.png)

**Comment by nataliafitzgerald** [comment]
@ohsk - Can you post the filter minicon design you are proposing?

**Comment by ohsk** [comment]
Nothing finalized, but here are few things we've been playing with. The bar-like version is a bit more abstract, and is what [Material Design](https://www.google.com/design/icons/#ic_filter_list) uses. The funnel is the more conventional, although perhaps a bit anachronistic, approach.

One question might be any sort of indication we want to design in that demonstrates "filtered" vs. "unfiltered". Two options below. Note: This isn't a real use case for us yet, so we may not worry about it in the near term.

![image](https://cloud.githubusercontent.com/assets/1689222/10673089/f8e9d53a-78c1-11e5-9c42-5fa94f02084a.png)

**Comment by caheberer** [comment]
We don't approve minicons through the Design Manual anymore. Moving to design repo.
