### ISSUE TITLE
Folder Minicon

### ISSUE THREAD

**Issue by ohsk** [cfpb/design-manual#356]
## CR Search will probably need to make use of an icon of a folder (to represent Collections, in our use case).

Starting a thread to document it's design. Some initial directions for Collections / Bookmarking that have us leaning in the folder direction.

![image](https://cloud.githubusercontent.com/assets/1689222/9792011/fc43c3bc-57ab-11e5-8985-90967e68933d.png)

**Comment by iuloshi** [comment]
@ohsk Your icons are pretty.

**Comment by ohsk** [comment]
MISS U @IULOSHI

**Comment by ohsk** [comment]
Latest version of the folder icon we're using as a selector for exporting specific complaints. We also have some state-based explorations (add, remove, etc), but those don't necessarily have to be a part of the font.

![image](https://cloud.githubusercontent.com/assets/1689222/10620413/f6478478-7748-11e5-9e34-929f5c9cc185.png)

![image](https://cloud.githubusercontent.com/assets/1689222/10620102/4a9fbf24-7747-11e5-8469-a85666c1810f.png)

**Comment by caheberer** [comment]
We don't approve minicons through the Design Manual anymore. Moving to design repo.
