### ISSUE TITLE
List (bulleted, numbered, plain) spacing

### ISSUE THREAD

**Issue by Scotchester** [cfpb/design-manual#357]
We need to set a standard or two for list spacing. I feel like I see much inconsistency in how we set the spacing between list items, whether they are bulleted, numbered, or unstyled lists. Does anyone else feel this way?

I'd like to propose:
- For regular bulleted/numbered lists appearing in a section of body copy: **15px** margin (baseline-to-cap-height)
- For unstyled lists (most often used for a set of links under a little blurb): **30px** margin (baseline-to-cap-height)

Maybe it's more consistent than I perceive, but I'd like to make an affirmative decision and codify it in the DM.

**Comment by Scotchester** [comment]
Semi-related: We should establish standard styles for definition lists. (The `dl`, `dt`, and `dd` elements.)

**Comment by Scotchester** [comment]
Oh, directly related: We also need to address how far bullets and numbers should be indented.

**Comment by amycesal** [comment]
I think 30 can be too much when there aren't paragraphs of text, but single lines of unstyled lists. With so much spacing the list no longer feels like part of the same chunk of text:

![screen shot 2015-09-14 at 11 10 23 am](https://cloud.githubusercontent.com/assets/1656046/9854384/9b5a3ecc-5ad6-11e5-910e-b7f0b2e7973d.png)

Same text but at 15px:
![screen shot 2015-09-14 at 11 14 06 am](https://cloud.githubusercontent.com/assets/1656046/9854423/d0f24070-5ad6-11e5-9363-d9f6587874c8.png)

I'd advocate for it being **15px across the board** unless there's a good example of where 30px is effective.

**Comment by marteki** [comment]
I like the look of 15px across the board in the example given, but it might create issues on touch devices  in lists with heavy linkage. Would there be enough space to confidently engage with a finger or thumb on a small screen?

**Comment by KimberlyMunoz** [comment]
We usually set different rules for mobile and touch devices on beta. Our links tend to have more spacing on mobile for exactly that reason.

![image](https://cloud.githubusercontent.com/assets/1860176/9858026/3a1c3cbc-5aec-11e5-9afc-d96a5ad61a53.png)

**Comment by Scotchester** [comment]
That kind of thing doesn't work for the example Amy showed above, though, where there are two links together on the same line.

**Comment by KimberlyMunoz** [comment]
That's the kind of thing we've been trying to go in and break into two lines for touch devices when we see it.

**Comment by Scotchester** [comment]
What kind of techniques have you used to do that?

**Comment by KimberlyMunoz** [comment]
So we're revamping and simplifying our patterns across v1. @duelj pointed out that in cases like [this](http://beta.consumerfinance.gov/budget/strategic-plan/), we might need to just break them out into two lines so that they're clearer.

**Comment by Scotchester** [comment]
Ahah. Unfortunately, I don't think that's practical in the example given by @amycesal. The list would be massively tall. Maybe it demands a different kind of approach.

**Comment by nataliafitzgerald** [comment]
@Scotchester - I'm following this issue but not sure what to weigh in on at this point. Do you have an update?

**Comment by Scotchester** [comment]
Sure thing, @nataliafitzgerald. To recap, here are the things we need to decide most immediately:
- Spacing between items in regular bulleted/numbered lists appearing in a section of body copy
  - Current proposal: **15px** (baseline-to-cap-height)
- Spacing between items in unstyled lists (most often used for a set of links under a little blurb)
  - Current proposal: **15px** (baseline-to-cap-height)
- Indentation from the left edge for bulleted and numbered lists
  - First proposal for _bulleted_ lists: **15px** from edge to center of bullet, **15px** from bullet to text
  - First proposal for _numbered_ lists: Numbers right-aligned at **30px** from left edge. **15px** from number to text.
- Spacing above/below a bulleted/numbered list appearing in a section of body copy
  - First proposal: Same as the spacing between paragraphs, whatever that is.

We probably don't _need_ this as urgently, but we also need to decide:
- Standard styling for definition lists
  - Example of default browser styling: http://codepen.io/anon/pen/NGbEKX
  - One common approach is to bold the titles, add vertical spacing between items, and reduce or eliminate the fairly-large default indentation.

**Comment by nataliafitzgerald** [comment]
@Scotchester - This is looking good. Is there a good place where I can see these proposed standards coded out. Perhaps one of the recent pages that Design Ops has worked on?

**Comment by Scotchester** [comment]
@nataliafitzgerald I'll put something together soon.

**Comment by schaferjh** [comment]
@ajbush is also working on some bulleted list specs for v1 templates this sprint. From what I know this looks similar to what we've got going on, but just pinging him here in case there's anything he's encountered that should be incorporated.

**Comment by Scotchester** [comment]
Ah, thanks @schaferjh!

**Comment by Scotchester** [comment]
Remembered something else we need to define: margin above and below a list. Added to the recap post above.

**Comment by ajbush** [comment]
Thanks @schaferjh for adding me. I am working on the bulleted lists aspect of this issue for V1. For the most part things are pretty similar. Wanted to share some mockups I had put together. Let me know what you all think.
<br>

---

#### Bulleted lists beneath headers (no paragraph introductory text before list

I had wondered if we could have a slight tweak to not include any indentation before the bullets when bulleted lists are the only content beneath a header.

*\* _Edit: [Scott mentioned](https://github.com/cfpb/design-manual/issues/357#issuecomment-143859041) this would require a class for each occurrence, which may not be V1 friendly_

**Here's a mockup of this with...** 
- 30px spacing between items
- 15px spacing between items to compare
- Text 15 px from the left edge (something we were doing in .ai doc that was slightly different. It actually means theres 9px spacing after the 6x6 px bullet. It seemed like the text is a little far away from the bullet when there's 15 px spacing after the bullet.)  
  <br>

| Specs | No specs |
| --- | --- |
| <img width="737" alt="screen shot 2015-09-28 at 2 43 16 pm" src="https://cloud.githubusercontent.com/assets/6931351/10145902/f7c5ea62-65f3-11e5-8842-a00ee6e2cfc0.png"> | <img width="749" alt="screen shot 2015-09-28 at 2 44 30 pm" src="https://cloud.githubusercontent.com/assets/6931351/10145916/04b3a570-65f4-11e5-873c-1c2531a85596.png"> |

<br>

---

#### Bulleted lists within paragraph text

The difference here would be that there would be a 15 px indent before the bullets.

**Here's a mockup of this with...** 
- 30px spacing between items
- 15px spacing between items to compare
- Text 30 px from the left edge (something we were doing in .ai doc that was slightly different. It actually means theres 9px spacing after the 6x6 px bullet. It seemed like the text is a little far away from the bullet when there's 15 px spacing after the bullet.)  
  <br>

| Specs | No specs |
| --- | --- |
| <img width="754" alt="screen shot 2015-09-28 at 2 49 03 pm" src="https://cloud.githubusercontent.com/assets/6931351/10146001/7fea444c-65f4-11e5-8744-35c84fa96db3.png"> | <img width="757" alt="screen shot 2015-09-28 at 3 23 26 pm" src="https://cloud.githubusercontent.com/assets/6931351/10146095/ebca5f6c-65f4-11e5-8199-60ca7092f0ae.png"> |

<br>

---

#### I would vote to...
- use 30px between items
- not indent bulleted lists when they appear immediately beneath headers if possible. (I do think the 15 px indent is nice beneath paragraph text though)
- keep the space after bullets a little closer to the text.

Let me know what you all think.

**Comment by Scotchester** [comment]
Thanks, @ajbush!

There's not going to be a very reliable way on the front-end to change the indentation styling of lists that are the only content following a header. We can apply it with a class, but lists that are created by content editors would not likely be able to apply that.

The other concern I have with it (one easily fixed) is that, as shown in your example, the left alignment of the first letter in a heading is somewhat mushy. In the example you provided, looking at it without the gridlines, the bullets appear to be outside the left edge of the heading above, because when seeing it without the gridlines, your only point of reference is the vertical bar of the `L`. If we want to go the route of creating a special class for this use case, I suggest nudging the bullets in by probably 2px.

One other minor comment: The square bullet character for 16px type is 5x5, and we can't easily make it 6x6. It doesn't make a huge difference, obviously, but just so you know.

**Comment by ajbush** [comment]
Ok cool that's good to know @Scotchester thanks for your quick response.

Sounds like it's probably not a good idea to add the class then. It would create inconsistencies between pages with the class and pages created by content editors that wouldn't have it.

**Comment by nataliafitzgerald** [comment]
Let's stick to black for the bullets (as shown on the Design Manual - see image below). The green is more decorative than functional and makes it harder to follow along with your eye from bullet to bullet, particularly when lists get longer. We can find other ways to work in the green.

<img width="752" alt="screen shot 2015-09-28 at 6 14 15 pm" src="https://cloud.githubusercontent.com/assets/6887128/10150309/caa392b4-660c-11e5-8683-3b6d1184274c.png">

**Comment by ajbush** [comment]
I think the green bullets were a really nice touch especially since it was a way to sneak in some brand green and they really livened up the black text a little. I also wonder if a darker/accessible green from the new palette could work?...but I really don't want to hold up progress on this.

**Here's an update to the mockups I posted above showing black bullets and removing the option with styling specific to bullets under headers. Also corrected the bullet size to 5 x 5.**

| Specs | No specs |
| --- | --- |
| <img width="770" alt="screen shot 2015-09-29 at 11 01 54 am" src="https://cloud.githubusercontent.com/assets/6931351/10168189/b5fa1f3a-6699-11e5-9e31-55a6a7b04638.png"> | <img width="730" alt="screen shot 2015-09-29 at 11 02 07 am" src="https://cloud.githubusercontent.com/assets/6931351/10168193/bbc23024-6699-11e5-800a-e495293feb7e.png"> |

**Comment by benguhin** [comment]
Reminder of @Scotchester's summary of what needs to be decided:
- [ ] Spacing between items in regular bulleted/numbered lists appearing in a section of body copy
- [ ] Spacing between items in unstyled lists (most often used for a set of links under a little blurb)
- [ ] Indentation from the left edge for bulleted and numbered lists
- [ ] Spacing above/below a bulleted/numbered list appearing in a section of body copy
- [ ] Standard styling for definition lists (e.g. glossaries)

@mebates @ajbush

**Comment by nataliafitzgerald** [comment]
@ajbush - I would like to work this into some other DM-Typography updates that I would like to make. Can you send me your ai file so that I can pull it in the master layout I am building? That will also give me an opportunity to review your options.

**Comment by Scotchester** [comment]
Preview is available at http://cfpb.github.io/cf-type-testing/dist/

It uses 30px above and below the list, and 15px between each list item.

I feel that 30px above the list detaches it too much from the preceding paragraph, which typically introduces the list. I'd propose going to 15px above the list.

**Comment by Scotchester** [comment]
The [preview page](http://cfpb.github.io/cf-type-testing/dist/) has been updated this morning.

After looking at it in more detail and exploring options yesterday, @nataliafitzgerald and I have an updated proposal. The main problem we found with @ajbush ##'s current proposal is:
- Given the decision to no longer base our spacing on baseline-to-cap-height, and
- Given that the spacing between paragraphs is now proposed to be 15px,
- **30px above the list separates the list too much** from the preceding paragraph, which is often directly introducing (or is at least related to) the list.

To solve this, we first tried reducing the space before the list to 15px. This looked pretty good, but then that separation was equal to the proposed 15px margin between list items, so it felt like the items were separating from each other too much. Also, again given the decision to no longer base our spacing on baseline-to-cap-height, 15px between items just felt like too much, anyway. It renders out to 25px from baseline to cap height.

Additionally, given the fact that bulleted/numbered lists are almost always preceded by paragraphs or headings that introduce them, we decided to try reducing the space above the list to only 10px.

## All that said, here's our latest proposal:
- **10px** above bulleted/numbered lists
  - Assumes they are almost always preceded by paragraphs or headings that introduce them. If you have other examples, please share!
- **8px** between list items
- **15px** below bulleted/numbered lists

## Before/after screenshot

![screen shot 2015-11-10 at 09 49 00](https://cloud.githubusercontent.com/assets/1044670/11065828/791b4b32-8793-11e5-9bbf-fad73cf1c758.png)

## Feedback wanted

Please let us know if you foresee any problems with this proposal. I'm happy to add new examples to the demo page too!

Attn: @nataliafitzgerald @ajbush @duelj @jimmynotjim

**Comment by nataliafitzgerald** [comment]
Here's how the proposed spacing looks with Avenir Next paragraph text: 
<img width="551" alt="screen shot 2015-11-10 at 10 17 07 am" src="https://cloud.githubusercontent.com/assets/6887128/11066008/4a70aab0-8794-11e5-988c-d00dce4db8e6.png">

**Comment by ajbush** [comment]
LGTM! (I just learned what that meant and wanted to use it) haha.

**Comment by nataliafitzgerald** [comment]
Apparently I just learned what it meant too. :)

**Comment by stephanieosan** [comment]
Sorry if this is a dumb question, but how will the spacing above a list work if it's preceded by a header? Will it include whatever amount of bottom spacing the header has + the 10 pixels above bulleted/numbered lists? Or will it just be the header spacing, or just be 10px?

**Comment by Scotchester** [comment]
Not a dumb question at all; I didn't address that in my post.

I'm actually not certain that @nataliafitzgerald and I thought about that out loud. My gut reaction would be that it should use the header's designated bottom margin only.

**Comment by nataliafitzgerald** [comment]
Good question @stephanieosan 
@Scotchester - Can we add that to our coded out sample to make sure it works?

**Comment by nataliafitzgerald** [comment]
@stephanieosan - To confirm, when a bullet or a numbered list is preceded by a header, the space above the bullet list will be determined by the spacing that is set below the specific header. 

Here's a visual of a bullet list after a paragraph and a bullet list after a header: 
![screen shot 2015-11-17 at 3 22 57 pm](https://cloud.githubusercontent.com/assets/6887128/11223667/220d239a-8d3f-11e5-8ac2-11abb5d30f05.png)

The code sample has been updated: 
http://cfpb.github.io/cf-type-testing/dist/

**Comment by designlanguage** [comment]
Is there a reason we're indenting bullets? I'm not sure about web conventions, but in my experience, bullets often align with the text preceding it. They always relate to the text above them, so they should align to the same place. This also helps hierarchy/clarity when there are multiple levels of indentation.

To think about it another way, the text after a bullet is already indented. The bullet itself is a vehicle for indenting text that belongs to the larger idea preceding it. It shouldn't need indenting itself.

Another reason to not indent bullets is that our print style doesn't do it. Here's one vote for consistency.

@ajbush - I agree with you that bullets following a heading should be aligned, but I don't think that needs to be the exception.

(same applies to numbered lists)

**Comment by Scotchester** [comment]
@designlanguage I've heard people say you should hang bullets fully out in the margin, but I honestly don't think I've ever seen someone advocate for left-aligning bullets with the text above.

Bullets being indented is a default in I think every word processor I've ever encountered, in all default Web browser styles, and on probably 99% of the websites I've ever encountered.

I do see that in InDesign if you just turn on bullets and adjust nothing else, they're aligned left. But the text it also spaced way far to the right, so I don't think they intended for anyone to just turn on bullets and let it fly without adjusting the spacing parameters.

![screen shot 2015-11-17 at 16 33 01](https://cloud.githubusercontent.com/assets/1044670/11225934/eb751200-8d4a-11e5-8c8b-8c54708bcc74.png)

The other question is, let's say you do align bullets to the left. What do you do with numbered lists? InDesign's defaults seem to do a good job carefully tweaking first 9 numbers on a proportional typeface so that they look very well aligned with the left margin and with each other, but if you have to go to 10 or more, eep.

![screen shot 2015-11-17 at 16 48 52](https://cloud.githubusercontent.com/assets/1044670/11226020/4d07858e-8d4b-11e5-80e1-e4b8722d9ea9.png)

I would personally be in favor of not left-aligning them in print, too, and am surprised that that's the case in our print styles. I had not noticed that.

**Comment by designlanguage** [comment]
@Scotchester - Aligning with the text above has been my experience, but I don't have any documentation advocating for it. Above all, whatever we choose to do, I think it should be consistent between web and print. Currently, this is what our print style for bullets looks like:

![screen shot 2015-11-17 at 5 24 21 pm](https://cloud.githubusercontent.com/assets/10562544/11226854/9e729cc4-8d50-11e5-9157-7c7bdeb4cfe4.png)

And here's when we get into double digits:

![screen shot 2015-11-17 at 5 30 55 pm](https://cloud.githubusercontent.com/assets/10562544/11226925/0cf5383c-8d51-11e5-80ee-507eab493775.png)

**Comment by Scotchester** [comment]
Why are second-level bullets indented?

**Comment by designlanguage** [comment]
Because it's inconsistent in our print styles.

**Comment by designlanguage** [comment]
Let me add that I think we should be consistent between print and print as well.

**Comment by nataliafitzgerald** [comment]
I agree that we should be consistent between print and web (but we should determine what that consistent approach should be). I have found contradictory standards as to whether bullets should fully hang outside of the margin (I don't think any of us want this), left aligning bullets, or slightly indenting the bullets. I did a little bit of poking around and here's what I found (I'm still researching): 

Here's the standard from UK.gov. They do not indent. https://www.gov.uk/guidance/style-guide/a-to-z-of-gov-uk-style
<img width="879" alt="screen shot 2015-11-18 at 8 34 43 am" src="https://cloud.githubusercontent.com/assets/6887128/11242373/493ef3c2-8dcf-11e5-99f3-96121bd1b16c.png">

Here's the "Lists" page from Google. They appear to have a slight indent. It doesn't seem to talk about bullet or numbered lists but there are visual examples within the content for the page.
<img width="991" alt="screen shot 2015-11-18 at 8 44 54 am" src="https://cloud.githubusercontent.com/assets/6887128/11242599/b4ddfff0-8dd0-11e5-9d03-0ba5e6963223.png">

Comparing the two above, the Google one is styled in a more appealing way but there are certainly multiple variables (not just the indent).

**Comment by caheberer** [comment]
I'll add that I'm with @designlanguage here, I've always aligned bullets to the left margin of the content above it. I, similarly, don't have documentation, just the voices of art directors past.

@Scotchester brings up a good point about numbers, but with all instances of numbers, aligning to the decimal or comma are better conventions than aligning left or right.

**Comment by mebates** [comment]
+1 to left aligning bullets

**Comment by nataliafitzgerald** [comment]
I agree that consistency between print and web is the right approach.

On the surface, left aligning the bullets sounds fine to me, unless there are front end or other considerations that we need to discuss further. @Scotchester - I am definitely interested in talking through your thoughts. 

Our report template has bullets indented so I am wondering how consistent we are on the print side of things. We may need to do a bit of an audit/update to get all our ducks in a row.

**Comment by Scotchester** [comment]
The extent of my thoughts is just that people are used to indented bullets by default. It's the default style in browsers, it's the default in Microsoft Word and Google Docs, that's what people know.

From a front-end code perspective, it doesn't really matter to me.

**Comment by nataliafitzgerald** [comment]
From a purely design perspective, I support left aligning bullets, particularly because of how narrow our width gets at mobile. Speaking to @caheberer's comment about numbered lists, can we align to the decimal or comma in code?

**Comment by nataliafitzgerald** [comment]
In the interest of closing out on this issue, I reached out to the Graphic Designers for consensus on the remaining question of whether or not we should indent lists. A majority of the Graphic Designers (100% of those that chimed in) are in support of left aligning lists. 

Supporters include @nataliafitzgerald @stephanieosan @designlanguage @caheberer @huetingj 

@Scotchester are there any remaining questions that need ironing out?

**Comment by Scotchester** [comment]
There are still two open questions:
1. Alignment of nested bulleted lists
   - Align the second-level bullets with the left edge of the first-level bullet's text?
2. How to handle numbered lists. Yes, we can align to the period, if the numbers get right-aligned.

**Comment by nataliafitzgerald** [comment]
Ah yes. So for double digit numbers we run into the issue that if the ordered list is not indented then the double digit numbers will hang over to the left. 

### Order list (No indent)

<img width="664" alt="screen shot 2016-10-14 at 2 06 42 pm" src="https://cloud.githubusercontent.com/assets/6887128/19397854/9ec45952-9217-11e6-8c3c-b27e864af480.png">

### Order list (indent)

<img width="710" alt="screen shot 2016-10-14 at 2 07 40 pm" src="https://cloud.githubusercontent.com/assets/6887128/19397860/a6cfc0b4-9217-11e6-8a6e-2b30054b11a2.png">

I prefer the "no indent" approach for the sake of consistency. My thought is that double digit ordered lists will occur infrequently so we should create a pattern that works best for most of the scenarios.

**Comment by nataliafitzgerald** [comment]
With regard to the alignment of nested bulleted lists, yes we would align the second-level bullets with the left edge of the first-level bullet's text. 

Like this: 
<img width="339" alt="screen shot 2016-10-14 at 2 56 41 pm" src="https://cloud.githubusercontent.com/assets/6887128/19399230/78553fa0-921e-11e6-9cb2-a5992b8fbe80.png">

@Scotchester Would it be possible to see what this looks like in code?
- Align the second-level bullets with the left edge of the first-level bullet's text. 
- Left align primary unordered lists and numbered lists.

**Comment by Scotchester** [comment]
@nataliafitzgerald Yeah, I'll try to get that up today.

**Comment by Scotchester** [comment]
@nataliafitzgerald 

Have a look: http://codepen.io/Scotchester/pen/rrokQE?editors=1100

Are you cool with hollow circles as the nested list bullet character? Hollow squares are not natively supported, and would require some finagling.

**Comment by Scotchester** [comment]
@nataliafitzgerald Bumping this, since I last updated it right before regroup, and it probably got lost.

**Comment by nataliafitzgerald** [comment]
@Scotchester 
Thanks for the heads up! I'm meeting with the GD's today so I will share this with the larger team. 

I feel comfortable with the hollow circles for the nested bullets (if what I am hearing is that it will save us headaches and prevent us from having to create workarounds for different browsers). My hope is that the secondary (nested) bullets won't come up all that often.

If we happen to have an ordered list with sub-bullets would it render like this (with the secondary bullet character)?
<img width="637" alt="screen shot 2016-11-02 at 12 18 33 pm" src="https://cloud.githubusercontent.com/assets/6887128/19937175/8b1b3a86-a0f6-11e6-89cf-f6767a49e7e2.png">

**Comment by nataliafitzgerald** [comment]
I spoke to @Scotchester. We have two options when it comes to the nested bullets within an ordered list.

<strong>Option 1.</strong> Solid, square bullets
<img width="640" alt="screen shot 2016-11-02 at 3 23 40 pm" src="https://cloud.githubusercontent.com/assets/6887128/19944051/7ae1b6ee-a110-11e6-9338-4e824d9f7030.png">

<strong>Option 2.</strong> Open, circular bullets
<img width="637" alt="screen shot 2016-11-02 at 12 18 33 pm" src="https://cloud.githubusercontent.com/assets/6887128/19944065/8668d04c-a110-11e6-9469-e6912a55a5b0.png">

**Comment by nataliafitzgerald** [comment]
@Scotchester 
I shared this with the GD's at our team meeting and we have consensus
- For bullets that are nested in an ordered list, we would like to use the solid rectangle bullets
- The bullets (solid) and nested bullets (open circles) appear to be slightly overhanging to the left. Can we make sure that they are flush left to line up with the text?

**Comment by Scotchester** [comment]
Interesting. The left alignment renders differently in Chrome and Firefox. I'll check it in all browsers and try to get it as close as possible to left-aligned in every browser.

**Comment by Scotchester** [comment]
Ok, sorrry for the delay. I've arrived at what I think is the best solution. It's dead on in Chrome, Safari, and Internet Explorer (though IE gets off on a nested unordered list within an unordered list), and a few pixels indented in Firefox.

Once again, you can view it here: http://codepen.io/Scotchester/pen/rrokQE?editors=1100

Here's how it looks in Firefox:

![screen shot 2016-11-04 at 16 56 43](https://cloud.githubusercontent.com/assets/1044670/20022226/f69f648e-a2af-11e6-8481-d08f45625b5c.png)

FWIW, Firefox currently accounts for about 5% of our traffic. IMO, it's not far enough off to warrant hacky workarounds (along the lines of doing hollow squares on the second level) to get it consistent in Firefox, and those workarounds would probably have negative consequences for older IEs.

**Comment by nataliafitzgerald** [comment]
@Scotchester 
This looks great to me! What's the next step?

**Comment by Scotchester** [comment]
@nataliafitzgerald I'll make these updates in Capital Framework v4, which should be released in the next week or so. From there, it needs to get integrated into cfgov-refresh, which will take about a month, probably. Maybe longer, given the holidays.

**Comment by caheberer** [comment]
@Scotchester could you provide an update on this?

**Comment by caheberer** [comment]
Update print templates issue is being added to the Design repo.

**Comment by jimmynotjim** [comment]
CF PR is open at https://github.com/cfpb/capital-framework/pull/450

**Comment by jimmynotjim** [comment]
Merged and awaiting release.

**Comment by marteki** [comment]
Reopening this, since it hasn't been published on the actual Design Manual yet.

**Comment by jimmynotjim** [comment]
@marteki @nataliafitzgerald now we can close this right?

**Comment by Scotchester** [comment]
The standard still needs to be more extensively documented.

**Comment by marteki** [comment]
I'll adjust the incorrect label on this issue, since the CF part is long done.

Then I'll draft up the written changes to the standard, post it here for a quick review, and then post a PR to publish it on the manual. Target deadline to complete: by Friday COB next week.

**Comment by nataliafitzgerald** [comment]
@marteki - To confirm, you'll be working on updating the DM pages to include nested lists and update any content related to that?

**Comment by marteki** [comment]
@nataliafitzgerald Yes, I'll be updating the Typography page to reflect what was decided in https://github.com/cfpb/design-manual/issues/357#issuecomment-257983230 and https://github.com/cfpb/design-manual/issues/357#issuecomment-258546763 for both web and print sections. Sound good?

**Comment by nataliafitzgerald** [comment]
@marteki - Yep! Thanks for confirming.

**Comment by marteki** [comment]
I flaked on this, and never updated the pages. I've blocked out time on my calendar and will be working on getting this done over the next two weeks.

Sorry to all, but especially to @nataliafitzgerald and @Scotchester.

**Comment by nataliafitzgerald** [comment]
@Scotchester 
I'd like to move forward with adding bullet lists (standard and nested) to the Design Manual. Does this reflect where we landed on the spacing for standard bullet lists? 
https://github.com/cfpb/design-manual/issues/357#issuecomment-155447435
<img width="693" alt="screen shot 2018-02-22 at 12 45 57 pm" src="https://user-images.githubusercontent.com/6887128/36554887-7cc2d78c-17ce-11e8-88af-6b6b06056086.png">

I looked in [Capital Framework](https://github.com/cfpb/design-manual/issues/357#issuecomment-155447435) and I don't actually see the default list and default nested list there. I only see the modifiers (unstyled list modifier, spaced list modifier (includes spaced nested list), horizontal list modifier, and link list modifier). Shouldn't we include the default list and nested list as the first item in the Capital Framework list section?

**Comment by jimmynotjim** [comment]
@nataliafitzgerald check here https://cfpb.github.io/capital-framework/components/cf-core/#lists. It doesn't include a nested list but if you add an issue and assign it to me I'll try to remember to do it soonish.

**Comment by nataliafitzgerald** [comment]
@marteki - Can I get your review on this when you have a moment? 
<img width="502" alt="screen shot 2018-02-22 at 6 49 16 pm" src="https://user-images.githubusercontent.com/6887128/36570669-25e9fac0-1801-11e8-9e48-15a7e4799b7e.png">

**Comment by marteki** [comment]
@nataliafitzgerald Some typoes and questions around style in the paragraph text, but it's hard to do a line review of an image. I'll try my best.

* First sentence is a little weird and veers towards being seen as a run-on. "Scanning and readability" is connected to "organize information" with another "and," which makes me a little twitchy in terms of clearly reading and understanding the sentence clauses.
* Typo: "they can be begin" should probably be "they should begin.
  * Actually, this whole paragraph is a bit confusing. I think what we're trying to say is "If the list items are a group of short fragments that each work to complete an introductory clause, begin with that introductory clause, followed by a colon; list out each of the list items on a separate list with a separate bullet, and do not end the list with any punctuation. However, if the items are each full sentences, the introductory clause should also be a full sentence; the introductory clause and each list item should each end in a period." (On a review of what I wrote, we might even want to break this paragraph into two paragraphs or something.)
* The bullets for the top-level list items aren't aligning with the left margin of the preceding text, but that's probably the fault of the underlying code right now.
* Could we add spacing guidelines around the left margin indent for nested bullets? Maybe it's as simple as "flush left aligned with the start of the preceding line of text," if a numeric guideline doesn't make sense (and I suspect it might not).
* Could we add a visual example under the nested bullet category for numbered or alphabetical lists, to show that their second-level bullets are solid squares instead of the circles used for non-numbered lists?

**Comment by nataliafitzgerald** [comment]
@marteki 
Here's an update to the list section. I think I've captured most, if not all of your feedback. I think I'll move forward with opening up a PR. If there are small remaining tweaks we can make them there. For larger tweaks we can open another PR next week (if needed).
![screencapture-0-0-0-0-4000-brand-guidelines-typography-html-1519423142199](https://user-images.githubusercontent.com/6887128/36619850-5417344a-18be-11e8-9194-68119773876c.png)

**Comment by marteki** [comment]
@nataliafitzgerald Sounds great to me! :+1:

**Comment by nataliafitzgerald** [comment]
Capturing @Scotchester's feedback from the PR here. 

"A few questions/comments:

1. Similar to what I suggested to Jimmy in the Capital Framework docs, is it necessary to break out the nested styles into separate sections, or could we just include a nested list within each of the main list sections?
2. Is it worth showing a nested numbered list? (I.e., an example where both parent and child lists are numbered.)
3. The "16px / 8px" is somewhat confusing to me. Typically that kind of construction would represent type size / leading, but the 8px here is intended to represent the extra margin between list items, correct? I think it'd be good to be more explicit about that."

**Comment by nataliafitzgerald** [comment]
@Scotchester @marteki 
I addressed 1 and 3 below. Let me know what you think.
<img width="687" alt="screen shot 2018-02-23 at 6 45 02 pm" src="https://user-images.githubusercontent.com/6887128/36622145-bac23590-18c9-11e8-86c1-0a57bc28f02d.png">
<img width="661" alt="screen shot 2018-02-23 at 6 45 08 pm" src="https://user-images.githubusercontent.com/6887128/36622146-bad3b8e2-18c9-11e8-9ca5-07fad7d5a2a9.png">
<img width="684" alt="screen shot 2018-02-23 at 6 45 14 pm" src="https://user-images.githubusercontent.com/6887128/36622147-baed6ce2-18c9-11e8-9541-d09316d29aa2.png">


For the question about whether we should include the nested numbered list, I have concerns with including it if it's something we wouldn't recommend, from a content strategy perspective. I don't know of any existing use cases on the site and when I try to come up with an example it seems overly complicated (and contrary to our general approach). But, I'd be interested to hear from @sarahsimpson09 and @kurzn.

**Comment by Scotchester** [comment]
That looks like a good update, Natalia. One more question: We should probably say something about the horizontal alignment of top-level lists, yes?

**Comment by nataliafitzgerald** [comment]
@Scotchester - How's this (note: we're having some issues with the styling of the H5, hence it looking so bold in this screenshot - I'm looking into it)?
<img width="693" alt="screen shot 2018-02-27 at 2 51 54 pm" src="https://user-images.githubusercontent.com/6887128/36751308-d5563c92-1bcd-11e8-9a6c-ee59077bf66f.png">

**Comment by nataliafitzgerald** [comment]
@Scotchester @marteki 
Do you think we've completed this or is there still pending work to be done? Here's the live page: https://cfpb.github.io/design-manual/brand-guidelines/typography.html#web-hierarchy

One type of list that's in CF but not captured in the DM is the "Unstyled list", basically a list without bullets. Do you think we should add it the DM? 
<img width="476" alt="screen shot 2018-02-28 at 3 35 58 pm" src="https://user-images.githubusercontent.com/6887128/36811825-1c6ab8c2-1c9d-11e8-8860-439c5ca06ba1.png">

As for the other list modifiers (in Capital Framework), I don't think it's necessary to add them to the DM. I think that will just cause confusion.

**Comment by Scotchester** [comment]
I don't think it's necessary to include the Unstyled List in the DM. I can't think of a time it's used in any content, other than as a building block to get to a Link List.

Given the existence of a separate Hubcap issue for dealing with Definition Lists, I think this is ready to be closed! 🎊

**Comment by nataliafitzgerald** [comment]
Ok. Closing now. Thanks to all for helping to push this to the finish line!
