### ISSUE TITLE
Add Branding guidelines content to its page within identity section

### ISSUE THREAD

**Issue by stephanieosan** [cfpb/design-manual#36]
This content is already written in our brand guidelines (pgs 6 & 7) and good-to-go. Someone just needs to add it.

**Comment by mebates** [comment]
Hey - I asked for it to be removed from the 'Identity' section in issue #34. I think it might fit better under the 'Guidelines' section. What do you think?

**Comment by stephanieosan** [comment]
I'm not sure. All the rest of the content within the "guidelines" section is (although wordy) still pretty actionable. Where as, the content in the brand style guide that I'm referring to (which the style guide calls "Design principles") is more global and less actionable. It describes how we think about design at the CFPB. 

At one point, Ben and I talked about it living in the overview section, as the introduction for the whole Design Manual. Do we have any other content planned for that space?

**Comment by stephanieosan** [comment]
But, I do think it makes sense to remove the branding guidelines from the identity section. The "Design principles" section I was thinking of aren't really "brand guidelines" and shouldn't live within Identity.
