### ISSUE TITLE
Master launch coordination thread

### ISSUE THREAD

**Issue by Scotchester** [cfpb/design-manual#361]
There's a lot of stuff happening right now, so we should talk about the order of operations for getting this stuff out there.

The big thing to note is that **Capital Framework updates need to be made and incorporated into the manual's dependencies before merging any new content**. Otherwise, we'll have new content out there without the code it needs for live examples.

I'm going to create a bunch of individual posts below to track what needs to be done for each component. Post with any questions or comments you have.

**Comment by Scotchester** [comment]
## Form fields

(@cfarm, @sonnakim, @virginiacc, @stephanieosan, @cafescience, @huetingj)
- cf-core updates:
  - [ ] `fieldset`
  - [ ] `label`
  - [ ] `input`
  - [ ] New version tagged and released
- cf-forms updates:
  - [ ] Helper text
  - [ ] Validation
  - [ ] New version tagged and released
- design-manual updates
  - [ ] Update cf-core dependency
  - [ ] Update cf-forms dependency
  - [ ] Update manual content

**Comment by Scotchester** [comment]
## Heros and featured content modules

(@cfarm, @sonnakim, @virginacc, @stephanieosan, @cafescience, @huetingj)
- cf-layout updates:
  - [ ] Hero
  - [ ] FCM
  - [ ] New version tagged and released
- design-manual updates
  - [ ] Update cf-layout dependency
  - [ ] Update manual content

**Comment by Scotchester** [comment]
## Tabs

(@Dnpizarro, @keelerr, @Scotchester)
- cf-tabs creation
  - [ ] Base styling
  - [ ] Base JavaScript
  - [ ] Numbered process tabs variant
  - [ ] New version tagged and released
- design-manual updates
  - [ ] Add cf-tabs dependency
  - [ ] Update manual content

**Comment by Scotchester** [comment]
## Responsive grid

(@mebates, @Scotchester)
- Decisions
  - [x] Max width
  - [x] Breakpoint values
  - [x] Breakpoint names
- Code updates
  - [x] Max width update in generator-cf
  - [ ] Max width update in capital-framework
  - [ ] Breakpoints update in cf-core
- design-manual updates
  - [x] Update manual content

**Comment by Scotchester** [comment]
## Expandables

(@Dnpizarro, @benguhin, @Scotchester)
- cf-expandables updates
  - [ ] Optional background color
  - [ ] Optional divider between header and content
  - [ ] New version tagged and released
- design-manual updates
  - [ ] Update cf-expandables dependency
  - [ ] Update manual content

**Comment by Scotchester** [comment]
## Color palette

(@designlanguage, @nataliafitzgerald, @Scotchester)
- Decisions
  - [x] RGB values
  - [ ] CMYK values
  - [ ] Naming scheme
- Code updates
  - [ ] Variables updated in generator-cf
  - [ ] Variables updated in capital-framework
- design-manual updates
  - [ ] Update manual content

**Comment by Scotchester** [comment]
## Tooltips

(@marteki, @caheberer, @niqjohnson, @kurzn, @mistergone)
- cf-tooltips creation
  - [x] Base styling
  - [ ] Base JavaScript
  - [ ] New version tagged and released
- design-manual updates
  - [ ] Add cf-tooltips dependency
  - [ ] Update manual content

**Comment by Scotchester** [comment]
## Tables

(@marteki, @caheberer, @niqjohnson, @kurzn, @mistergone)
- cf-core updates:
  - [x] Tweak border, background, padding rules
  - [x] New version tagged and released: [1.0.3](https://github.com/cfpb/cf-core/releases/tag/1.0.3)
- cf-tables creation
  - [ ] Base styling
  - [x] JavaScript for sorting
  - [ ] New version tagged and released
- design-manual updates
  - [ ] Add cf-tables dependency
  - [ ] Update cf-core dependency
  - [ ] Update manual content

**Comment by Scotchester** [comment]
## Modals

(@marteki, @caheberer, @niqjohnson, @kurzn, @mistergone)
- cf-modals creation
  - [ ] Base styling
  - [ ] Base JavaScript
  - [ ] New version tagged and released
- design-manual updates
  - [ ] Add cf-modals dependency
  - [ ] Update manual content

**Comment by Scotchester** [comment]
## Tags

(@ohsk, @ascott1, @ielerol)
- cf-tags creation
  - [ ] Base styling
  - [ ] Removable variant
  - [ ] New version tagged and released
- design-manual updates
  - [ ] Add cf-tags dependency
  - [ ] Update manual content

**Comment by Scotchester** [comment]
## Filters

(@ohsk, @ascott1, @ielerol)
- cf-filters creation
  - [ ] Base styling
  - [ ] New version tagged and released
- design-manual updates
  - [ ] Add cf-filters dependency
  - [ ] Update manual content

**Comment by Scotchester** [comment]
## Pagination

(@ohsk, @ascott1, @ielerol)
- cf-pagination updates
  - [ ] Base styling
  - [ ] Example AJAX scripting?
  - [ ] New version tagged and released
- design-manual updates
  - [ ] Update cf-pagination dependency
  - [ ] Update manual content

**Comment by Scotchester** [comment]
If anyone has any questions, wants to change what's on any of their checklists and doesn't have permissions, or whatever else, just shoot me a note. I'm traveling with questionable internet access all day tomorrow, but will be checking in periodically during the summit the rest of the week.

**Comment by caheberer** [comment]
This is old.
