### ISSUE TITLE
Placeholder js

### ISSUE THREAD

**Issue by cfarm** [cfpb/design-manual#364]
Older browsers that don't support the placeholder attribute need JavaScript to make our placeholders the default value.

Currently the Design Manual has no such JS so text input examples are just empty:

![image](https://cloud.githubusercontent.com/assets/702526/10179025/5feb40fa-66d1-11e5-8f89-cbcb8c3d2383.png)

**Comment by cfarm** [comment]
Here's an example from Owning a Home https://github.com/cfpb/owning-a-home/blob/master/src/static/js/modules/placeholder-polyfill.js

**Comment by caheberer** [comment]
@cfarm is this still an issue? Or is it addressed with the new form fields work?

**Comment by jimmynotjim** [comment]
We've stopped sending JS to IE8 in cfgov-refresh. We should probably ensure we're using proper labels and let placeholder support fall where it may. Not sure if that should be explored here or this issue can be closed.

**Comment by Scotchester** [comment]
I agree with @jimmynotjim. Placeholder text should be considered a progressive enhancement that we can do without if it's not supported by the browser.
