### ISSUE TITLE
[illustration] Magnifying glass

### ISSUE THREAD

**Issue by Dnpizarro** [cfpb/design-manual#368]
I recently worked on a share graphic and saw a need for a magnifying glass. This isn't the first time I've seen a use case for this particular object, so I figured lets add this to our illustration library.

https://drive.google.com/drive/folders/0BzwhO_55BsNGdnNKSmNOaVIycTg

Thoughts?

@nataliafitzgerald 

<img width="856" alt="screen shot 2015-10-15 at 10 21 26 am" src="https://cloud.githubusercontent.com/assets/6852363/10516762/d946e7ee-7327-11e5-8108-0e945dc5ed49.png">

**Comment by ohsk** [comment]
Ohhhh... can i have that?? Seems pretty solid to me.

**Comment by ohsk** [comment]
Hey Daniel, after putting the magnifying glass in place, we noticed that having the split shadow on the top, circular part of the object gives it a strange "folding" or "bending" effect. The split shadow works well on the handle, though. Maybe it just feels odd on the top part b/c it's one flat surface, rather than a curved surface.

![magnifyingglass_v1](https://cloud.githubusercontent.com/assets/1689222/10544369/ff693af2-73f0-11e5-8223-a4ce4eef3361.png)
![magnifyingglass_v2](https://cloud.githubusercontent.com/assets/1689222/10544370/ff7247dc-73f0-11e5-8b30-0d666940e530.png)

**Comment by caheberer** [comment]
Cool @Dnpizarro!
One other comment...seeing the inner side of the magnifying glass (the darker inner semi circle) goes against the idea that we are looking straight down on the object. That would only show up if we were looking at it from an angle. To follow our standards, I would suggest removing it. Or to create the illusion of depth you could try it as a complete circle at an equal stroke/width.

**Comment by Dnpizarro** [comment]
Yeah I hear what you are saying @caheberer . I wasn't sure about that element for the same reasons you highlighted. There are some existing approved illustrations I was referencing regarding that slight depth shadowing.

<img width="1426" alt="screen shot 2015-10-16 at 11 15 04 am" src="https://cloud.githubusercontent.com/assets/6852363/10545546/43c2633a-73f7-11e5-8b84-4d8fc630d5a0.png">

**Here is a version with the suggested changes**
I think it can still work. @ohsk do you think you can try out the revised version for your mock-up. Let us know your thoughts (revised file below).

https://drive.google.com/drive/folders/0BzwhO_55BsNGdnNKSmNOaVIycTg

<img width="931" alt="screen shot 2015-10-16 at 11 19 52 am" src="https://cloud.githubusercontent.com/assets/6852363/10545710/1e49c91c-73f8-11e5-80e0-d82967b73313.png">

**Comment by caheberer** [comment]
@Dnpizarro good points. Hmm. The keys make slightly more sense, because you could argue that the straight vertical object is straight-on and the object on top/to the left is slightly at an angle? But the coins feel like they shouldn't have them. But I guess I never really noticed it before. Upon seeing the magnifying glass it felt off.

**Comment by ohsk** [comment]
Sure thing, here's what ours looks like without an internal drop shadow:

![magnifyingglass_v3](https://cloud.githubusercontent.com/assets/1689222/10547168/ba6e6462-7400-11e5-8aba-1ad508cf744d.png)

This is what it currently looks like in the context of our demo homepage (still has dropshadow):

![image](https://cloud.githubusercontent.com/assets/1689222/10547190/d7793096-7400-11e5-80a6-36b7dc1634bc.png)

**Comment by Dnpizarro** [comment]
@ohsk I like where you are going with the hero! 

Regarding the internal shadow, I'm ok with either direction. I think we should hear from @nataliafitzgerald to get her thoughts on these details. One question regarding the hero, was it intentional not to magnify the speech bubbles? Zooming in could help reinforce that its supposed to magnify.

**Comment by designlanguage** [comment]
I like @caheberer's idea of filling in the inner circle. Even if it's not representing the illusion of depth, it could just be the seam where the metal meets the glass. Another idea would be to make the handle a different color. Here it is both ways:

![screen shot 2015-10-16 at 2 12 55 pm](https://cloud.githubusercontent.com/assets/10562544/10549604/19fce138-7410-11e5-88da-e5c7551e03fb.png)

Also @Dnpizarro, I think you're right that the speech bubbles should be larger inside the glass.

**Comment by Dnpizarro** [comment]
Now that I'm seeing it I think it works! Thanks for illustrating that @designlanguage

**Comment by nataliafitzgerald** [comment]
I like the addition of the color to the handle @designlanguage. It's starting to feel less abstract and more like an object.
