### ISSUE TITLE
[illustration] Desk lamp - top facing

### ISSUE THREAD

**Issue by Dnpizarro** [cfpb/design-manual#369]
This was a recent desk lamp exploration that didn't get approved, but there could be a potential use case in the future especially with our expanding top facing illustrations. 

https://drive.google.com/drive/folders/0BzwhO_55BsNGMjRmRHJmMFNZX2c

Thoughts?

<img width="916" alt="screen shot 2015-10-15 at 10 23 21 am" src="https://cloud.githubusercontent.com/assets/6852363/10516929/82b89552-7328-11e5-9328-af30deb28fe5.png">

**Comment by nataliafitzgerald** [comment]
@Dnpizarro - This is an interesting exploration but I don't think we should go in the direction of zooming that far out in our top facing illustrations. The perspective that we are trying to create is of someone looking down at a desk that they are sitting at. The perspective here feels like it's farther away.
