### ISSUE TITLE
Stylistic tweaks to Photography page

### ISSUE THREAD

**Issue by ohsk** [cfpb/design-manual#37]
Documenting minor stylistic tweaks to be made to the Photography page prior to replicating to other sections of the Design Manual.
### Type hierarchy:
- [x] `<h1 class="page-title">` should be set to `font-family: "Avenir Next"`, to match our H1 standards.
- [x] `<h2>Stylistic guidelines</h2>` should be set to `font-family: "Avenir Next"`, to match our H2 standards.
### Horizontal rule colors:
- [x] `<hr>` below anchor links at the top should be Pacific 20% (`#CCE3F5`)
- [x] `<hr>` between content (ie. between photos) should be Gray 20% (`#E3E4E5`)
### Content sizing / spacing:
- [ ] Increase spacing between `<ul class="toc">` anchor links and blue horizontal rule below to 20px.
- [x] Make feature image same number of columns wide as the section descriptions, like [the red tints here indicate](https://github.com/cfpb/design-manual/issues/37#issuecomment-37230311). Adjust intro paragraph width to match the gold tint. 
- [ ] 30 px vertical spacing between section title and horizontal rule, and 20 px vertical spacing between horizontal rules and section content, [as shown here](https://github.com/cfpb/design-manual/issues/37#issuecomment-37230414).

**Comment by ohsk** [comment]
Introductory section column widths:

![screen shot 2014-03-10 at 4 15 50 pm](https://f.cloud.github.com/assets/1689222/2378762/dc7e1308-a892-11e3-99d7-9d44eb4f19f5.png)

**Comment by ohsk** [comment]
Vertical spacing with horizontal rules:

![screen shot 2014-03-10 at 4 32 07 pm](https://f.cloud.github.com/assets/1689222/2378775/14654098-a893-11e3-8d6e-35c11446ca3d.png)

**Comment by mebates** [comment]
:+1:

**Comment by ohsk** [comment]
@danny8000 I think this was everything we could think of that needed a bit of love from a stylistic standpoint!

**Comment by danny8000** [comment]
I made most of these changes. I need to discuss with @himedlooff how to collapse margins at the top of a grid.

**Comment by ohsk** [comment]
Thanks @danny8000, looking good. Yeah, seems like we just need to reduce the margins a bit in some places.

@mebates, I also exported the feature image. Where are we placing visual content now?

![photography0_ 2](https://f.cloud.github.com/assets/1689222/2401414/be384f60-aa15-11e3-8a04-b5f2e00da7d9.jpg)
