### ISSUE TITLE
[Minicons] Next batch of updates

### ISSUE THREAD

**Issue by ohsk** [cfpb/design-manual#371]
Documenting any new minicons for @Dnpizarro to include in the next Minicon font update
- [ ] [Folder](https://github.com/cfpb/design-manual/issues/356)
- [ ] [Filter](https://github.com/cfpb/design-manual/issues/355)
- [ ] [Download](https://github.com/cfpb/design-manual/issues/274#issuecomment-130359052) (replacing current icon)

**Comment by caheberer** [comment]
Will add a download icon issue to the design repo.
