### ISSUE TITLE
Complaint Minicon - small use update

### ISSUE THREAD

**Issue by duelj** [cfpb/design-manual#380]
It was noted by @sonnakim that the complaints minicon was had to tell what the symbol is in the bubble when used inline with text at 16px size. This was note in reference to the minicons use in a [submit a complaint CTA](https://github.cfpb.gov/flapjack/Modules-V1/issues/64#issuecomment-59697) in the V1 global header. Wanted to create an issue to see if we might adjust the exclamation mark to render better at small sizes. 
#### Hard to read example

![60b55aea-86eb-11e5-9f30-cfcd02a6e7a9](https://cloud.githubusercontent.com/assets/6873734/11194885/c47f8492-8c7c-11e5-8526-2ba0b2940b00.png)

**Comment by benguhin** [comment]
tagging @ohsk

**Comment by caheberer** [comment]
Moving to design repo.
