### ISSUE TITLE
Updated Design Manual structure

### ISSUE THREAD

**Issue by caheberer** [cfpb/design-manual#383]
Hey ya’ll
As you heard during the last Design Manual meeting. I’m planning to pick up where Daniel’s awesome work left off and lead you into the next phase of the Design Manual. 

I’ve been thinking about an alternative structure to our current format that hopes to address 2 specific questions:
1. How do we translate the collaboration and, most importantly, focus of our in-person meetings into a remote setting?
   and
2. How do we continue to make progress on Design Manual issues, especially the issues that require a large fewd dependency?

Based on the success of the recent addition of the foundational components by each project team, I personally think the best way to make the manual an effective living resource would be to designate a team to not only champion the issues that arise, but also to work on incorporating those new or revised elements into Capital Framework. But, considering we do not currently have the resources to make this happen, I’m hoping the following suggestions might provide us a way to move forward and make progress in a consistent and timely fashion.

I think we all face the challenge of not having enough free time to tackle Design Manual issues that are important to us, to the completion of our project work, and to the success of our standards as a whole.

I’m suggesting that we continue to make updating, maintaining (and making our standards better!) a priority for all disciplines. The manual, and specifically the web patterns that make up a large majority of the issues, are important to the team as a whole, not just designers. I’ve gotten feedback from a few team members who are in agreement on this, and that includes front-end developers as well. With that in mind, I’m proposing that we continue to work in a similar format to the larger foundations surge, where project teams incorporate manual work into their sprints. I think this is our only current solution to equally distribute the work and to minimize the overwhelming growth of a fewd issue backlog and to keep our standards up to date. 

Some of you might be panicking right now, but have no fear. I’m thinking that we would distribute just one issue per team and to extend deadlines to once a quarter, with regroups marking the completion of an issue and a time for high-fives. Additionally, to ease the burden on individual teams, I suggest we use Design Manual meeting time to get to work. Issues will be prioritized and assigned by the backlog grooming crew of Ben, Natalia, Scott and myself before each meeting and ongoing as needed. You can help this process by alerting your team leader of important issues during your discipline-specific meetings. And if a project team finds a new issue that takes precedence in order to complete their project work, the ability to swap issues or change priority is an option.

Back to the meeting time, aside from quick updates from each team and to take care of any blockers at the beginning of the meeting, we would split off in our teams and work via hangouts. If a blocker is brought up that needs large group consensus, we can work as a group for the remainder of the time to discuss and problem solve, otherwise we will break off into our teams. (Using github as usual for documentation and feedback.) Approval will happen in the same method that we use now, using approval tags for design, ui, fewd and 508. 

I’m hoping this will help us make continued improvement and I look forward to trying it out. If we find that we’ve taken care of the majority of the issues, and this level of commitment isn’t necessary anymore, we can reassess a new structure at that time. I’m new to this too, so if it doesn’t work, we’ll figure out something that does. Please use this issue as a place to post any immediate thoughts or questions as well as a place to leave feedback going forward.

I’m looking forward to continued Design Manual problem solving!

**Comment by jenn-franklin** [comment]
Thanks for your thoughts, @caheberer! I support the idea of dividing DM work up by team with the expectation of the work being built into teams' sprints. Also like the idea of regroup marking the completion of work and perhaps also serving as time to brainstorm and set up the next quarterly sprint. 

It might be helpful for us to spend a little time thinking about how best to work alongside V1 as they continue to develop patterns. What should the collaboration process be? And how do we ensure patterns are up-to-date both in the design manual and the atomic wiki?

Oh also, I love the idea of splitting off into team hangout work sessions!

**Comment by kurzn** [comment]
:+1: to all of the above. I propose we have a DM meeting during regroup to figure this out, and during which the DM content strat team can present our work to date. 

We also think we can hand over the work we've done to be continued by an assigned project team, per the suggestions above. And that team can then take on updating existing DM content to the proposed new content standards.

**Comment by caheberer** [comment]
In case you missed today's meeting, attached is the presentation as well as links to the information @kurzn presented on content strategy progress.

Project team assignments:
**Complaint Analytics**
Tags

**Design Ops**
Color palette DM page, Design Manual homepage, Tabs

**Dynamic Disclosures**
Tables, Print CSS styles

**Rara + Natalie**
Content strategy for individual DM pages

**V1**
Expandables

[design_manual_regroupSpring2016.pdf](https://github.com/cfpb/design-manual/files/105403/design_manual_regroupSpring2016.pdf)

Content Strategy update:
https://github.com/cfpb/design-manual/issues/370

**Comment by KimberlyMunoz** [comment]
Has the design manual synced up with all the work with Capital Framework? It seems like we're getting assigned stuff that we aren't ready for there.

**Comment by KimberlyMunoz** [comment]
Tagging @Scotchester since he's our bridge, but raising a flag that we're in the middle of a large month-long sprint to depreciate all our module repos and creating one large repository with a whole docs overhaul. Most of V1 is working on this project, but we're pulling a lot of developers for it as well. 

It's going to have some impact on the timing of all of this stuff, especially since we might not have a "home" for that until our Capital Framework foundational stuff is done.

**Comment by Scotchester** [comment]
A couple thoughts:
- Varying project workloads is one reason why we're doing quarterly "sprints" now. Hopefully, with almost three months to work, each team will be able to find the time to do the fairly small amount of work they've been assigned.
- Your team's specific assignment was suggested by me, because I know you've already done a lot of work on Expandables to get them set up in your atomic design format, and I was hoping that it might be a good first experiment with how we might begin to bring the two approaches into alignment. If that proves to be too much to deal with, I think at the very least it shouldn't be _too_ much work to get the expandable page content updated to the current standards and existing cf-expandable code updated to match.

Finally, all this stuff is flexible. I'd propose we check in with you at the end of your month-long sprint and see what the outlook is like at that time with the remaining 2+ months in the DM sprint.

**Comment by KimberlyMunoz** [comment]
Adam just let me know that the sprints have been lengthened! Hopefully, that helps, but do we have a place for the work to go while we do foundational CF stuff?

Is your "you" a plural you? I haven't done any expandables work. :confused:

**Comment by Scotchester** [comment]
> [D]o we have a place for the work to go while we do foundational CF stuff?

I may not completely be understanding the foundational stuff you're talking about, but I don't see why the expandable updates work can't go exactly where the cf-expandables component lives now (capital-framework/src/cf-expandables).

Yes, "you" meaning "your team" :)
