### ISSUE TITLE
Content guidelines for component page type

### ISSUE THREAD

**Issue by stephanieosan** [cfpb/design-manual#390]

**Comment by kurzn** [comment]
Next steps
- @sonnakim is working to apply the proposed guidelines for components to Tables by utilizing the outline from Modals
- @nkurz is working on completing the written component guidelines based on feedback from Modals and Tables

**Comment by sonnakim** [comment]
Here is the tables page rewrite: https://docs.google.com/document/d/1pHipfZ6uh4I2VUNMFeqF82tycJaWKaqyY5_MPYksc-M/edit# 

I've sent this to @niqjohnson to get his feedback.
