### ISSUE TITLE
Plan for how code snippets / capital framework integration will work with the new content templates

### ISSUE THREAD

**Issue by stephanieosan** [cfpb/design-manual#391]
- Stephanie to gather up and read through existing conversation
- Stephanie to catch up with Marteki and Cat
- Lorelei to investigate how we could chunk and automatically pull in pieces of content to make the design manual more maintainable (for example, can we pull in the hex values for colors automagically across different pages when we say what colors to use for components, so that if we change the hex value we only have to do so in one place, but we still get the benefit of having the hex value written out on the components pages)

**Comment by marteki** [comment]
Closing as not required for standards creation
