### ISSUE TITLE
Rewrite, code and push live two pages for the components page type

### ISSUE THREAD

**Issue by stephanieosan** [cfpb/design-manual#394]
- Dependent on the guidelines being written in #390 
- Have we already identified which two pages we'll use as test cases? If so, edit this and write them here.

**Comment by stephanieosan** [comment]
We're doing Modals and Tables.

**Comment by kurzn** [comment]
Here is the modals page 

http://kurzn.github.io/design-manual/ui-toolkit/modals.html ready for a pull request. Waiting on word from backlog grooming board on the approval process needed for this one since it's not a new standard.

**Comment by sonnakim** [comment]
Here is the tables page rewrite: https://docs.google.com/document/d/1pHipfZ6uh4I2VUNMFeqF82tycJaWKaqyY5_MPYksc-M/edit# 

@niqjohnson says looks good so far. He suggests these eminently-sensible-sounding next steps.
1.  DM content strategy team gather feedback and incorporate any revisions.
2.  After the draft is in a good place, Niq will put the revised tables content into his branch of the Design Manual (with all the assets and configurations for the tables page).
3.  Niq and DM content strategy team all review.
4.  Once we’re all happy with the page, Niq will submit a pull request to the Design Manual for everything tables.
5.  Tables page is done!

**Comment by niqjohnson** [comment]
Tables page is ready for review at https://github.com/cfpb/design-manual/issues/153#issuecomment-233148525
