### ISSUE TITLE
Finalize and release the new Information Architecture for the design manual

### ISSUE THREAD

**Issue by stephanieosan** [cfpb/design-manual#395]

**Comment by kurzn** [comment]
Working document

https://docs.google.com/document/d/15Me36x_6AQda6lOFRC7JaIG8zEXsvnxUz9njwBvOTW8/edit#heading=h.p8fv4wajeneb

**Comment by kurzn** [comment]
I took a stab at regrouping/renaming the buckets to help better delineate between the sections and remove some overlaps.

TOP NAVIGATION 
- Overview
- Style
- Global elements
- Page components
- Best practices

See page 3 (option 2) of this doc for the groupings. I also took a stab at taking V1 molecules and including them here. I didn't include every molecule, but ones that felt the most likely to repeat or need guidance about on an ongoing basis. For instance, "post preview" probably didn't need to be specifically defined. 

https://docs.google.com/document/d/15Me36x_6AQda6lOFRC7JaIG8zEXsvnxUz9njwBvOTW8/edit#heading=h.p8fv4wajeneb 

@ajbush @duelj @schaferjh @huetingj

**Comment by kurzn** [comment]
After our meeting today, the revised recommendation for IA is: 
- Overview 
- Brand guidelines
- Global elements
- Page components
- Best practices

**Comment by schaferjh** [comment]
@kurzn thanks for tagging V1 folks on this -- we are working on an idea for integrating V1 components into the IA recommendation. Once we have that together, it'll be great to touch base. Will you remind me what kind of timeline you're working on?

**Comment by kurzn** [comment]
@schaferjh We'd love to have this IA nailed down in the next week so we can continue moving forward. It would be good to touch base for sure. Looking through the V1 elements, we thought that some of them should not be incorporated into the design manual, for instance "global eyebrow" or "post preview" as these aren't elements that a designer would likely have to design from scratch. 

We had already pulled the elements/molecules we thought were most important to include into the google doc. If there were things we missed or that the V1 team should be included, please flag that on the doc. 

Looking forward to a follow up! I can set up a meeting for mid-late next week if that works for you?

**Comment by kurzn** [comment]
@schaferjh 

The new has been updated in code here for your approval.  https://huetingj.github.io/design-manual/  

All existing content has been moved under the correct corresponding umbrella. We will hide "Data visualization" until there is content to display under that. 

Let us know if you have any questions!
@huetingj @stephanieosan

**Comment by schaferjh** [comment]
Apologies for the massively long lag time, folks. Looks great to me and I look forward to filling it in further! :+1:

**Comment by kurzn** [comment]
Thanks @schaferjh. I see you updated the tag. What else do we need to do to get this into production?
