### ISSUE TITLE
Figure out where the content guidelines documents live and stand them up there

### ISSUE THREAD

**Issue by stephanieosan** [cfpb/design-manual#397]
- Where will the living content guidelines documents live? 
- Publish the guidelines wherever we decide

**Comment by nataliafitzgerald** [comment]
@stephanieosan @marteki @kurzn 
Is this issue the same as this one? https://github.com/cfpb/design-manual/issues/404

**Comment by nataliafitzgerald** [comment]
@stephanieosan 
Here, you are referencing the content guidelines for our site as a whole, yes? What would you think of an internal GitHub page like what we have here: https://[GHE]/pages/flapjack/wagtail-documentation/
