### ISSUE TITLE
Where will the DM content strategy guidelines live? 

### ISSUE THREAD

**Issue by kurzn** [cfpb/design-manual#404]
Team proposed creating wiki pages to communicate the content strategy for the DM here: 

https://github.com/cfpb/design-manual/wiki

Each navigational "bucket" would have its own page.

We would also link to the wiki pages from the read.me. 

Please share if you have a concern with this approach or have a better idea!

**Comment by marteki** [comment]
Wiki pages can get lost in GitHub repos, even if linked to from the readme. This is even truer if the person looking at the manual isn't a developer, or doesn't work with developers often.

If we go the wiki route, could we also link it to them from the DM Overview page? It'd almost be part of a "how to use the manual" section, and would be more transparent to non-D&D-ers or non-current-contributors who would be looking for guidance on contributing.

Side note: y'all probably already know this, and it's probably out of scope for this sprint, but almost all the content on those wiki pages are out of date. A non-exhaustive list of what I found, for when it's time for the content to be updated:
- The process described isn't what we're following anymore,
- The recommended editor for non-coders asks for permissions that we've decided as an org not to allow, so I don't think it'd be usable or encouraged, and
- @benguhin is still on the list of approvers. :cry:

**Comment by kurzn** [comment]
@marteki We realize the wiki in GH isn't the most obvious place. However, there is some potential opposition to publishing a link to the guide so publicly on the DM itself. We'll still pursue that route, as it's the best one, but it may not be an option we can implement. Thanks for your feedback and suggestions!
