### ISSUE TITLE
Templates (DM pages)

### ISSUE THREAD

**Issue by duelj** [cfpb/design-manual#408]
The V1 team is looking to document atomic design elements that will be found in Wagtail for other project teams. We feel the best way to do this is to incorporate this information into the CFPB Design Manual, so that it is available to all project teams (and the rest of the bureau). These pages are intended to fit within the updated [Design Manual IA](https://docs.google.com/a/cfpb.gov/document/d/15Me36x_6AQda6lOFRC7JaIG8zEXsvnxUz9njwBvOTW8/edit?usp=sharing). The intended page additions for atomic documentation can be found [here](https://docs.google.com/document/d/1dDuaPCiS9MqECsprNdjptJdYHxBN9shMi_CMpoHSt8w/edit#heading=h.p3o7hbn278x9)

Content is not fully resolved still would like @schaferj or @sarahsimpson to give input.
### Page Summary

Template pages will love in the global elements section of the updated IA for the Design manual. They will introduce the IA used on consumerfinance.gov pages through the use of different page layouts to serve different needs. These template pages align with new page templates found in Wagtail, and can be used as a foundation fro new project teams to build pages on cf.gov.

 *\* There are multiple template pages that will live in the global elements section. The landing page example is the format most pages will take. The document detail template page below introduces some unique additions so we looked at the design of that as well.**
#### Other template pages

[Document detail](http://duelj.github.io/design-manual/ui-toolkit/document-detail.html)

**Comment by duelj** [comment]
### For Review

Request review by @huetingj or @sosan (only probably need one) on design and @schaferjh or  @sarahsimpson09 for content.
- [ ] Jen
- [ ] Stephanie
- [ ] Sarah
- [x] Jess

#### Deadline: Monday May 16 noon

**Feedback needed:** Can you check over these new design manual page layouts for atomic components to make sure they are ready to be added. 
Reviewed by
- [ ] Brand Execution
- [ ] Approved
- [ ] Content

---

### Depending on Needs

**Summary:** Atomic compontents from V1 work need to be added into the design manual. These pages will show the foudational templates that inform the IA of cf.gov. These templates contain different groupings of elements to help them serve specific purposes for users. 
**Audience:** Design and dev. @ CFPB
**Phase of Project:** execution (we want to start building these so they are ready for the DM update)
**Background Information:** background information in post above. Happy to share more in a call/HO.
**Feedback Format:** GH feedback would be great but happy to have a meeting to go over things if it feels right.

**Comment by schaferjh** [comment]
@duelj should we close this issue now in favor of the issues that we've posted?

**Comment by schaferjh** [comment]
closing this as it was rendered moot by the individual issues @ajbush has finished working on.
