### ISSUE TITLE
Additions to illustration library

### ISSUE THREAD

**Issue by elizbond** [cfpb/design-manual#41]
During the latest regroup, our illustration guidelines went through a tedious exploration. As we began updating our illustration library to include the latest guidelines, we recognized the need for a few financial items to add to our assets for a fully functioning library. Each item will be addressed in its own issue.

High priority
1. Car @ajbush [https://github.com/cfpb/design-manual/issues/46]
2. Calendar @duelj [https://github.com/cfpb/design-manual/issues/43]
3. Purse @duelj [https://github.com/cfpb/design-manual/issues/45]
4. Wallet (womens / men’s) (@ajbush) [https://github.com/cfpb/design-manual/issues/48]
5. House keys @ohsk
6. Car keys @ohsk
7. Safe @duelj [https://github.com/cfpb/design-manual/issues/44]
8. Getting out of debt [https://github.com/cfpb/design-manual/issues/40]
9. Desktop computer [https://github.com/cfpb/design-manual/issues/207]

Backlog
1. Debt collection [https://github.com/cfpb/design-manual/issues/39]
2. Folded documents
3. Pay stubs
4. Retirement [https://github.com/cfpb/design-manual/issues/47]

**Comment by stephanieosan** [comment]
New illustration styling issue #50
