### ISSUE TITLE
50/50 Image and text

### ISSUE THREAD

**Issue by ajbush** [cfpb/design-manual#413]
#### What is it?

V1 is looking to add its atomic element documentation to the DM for the use of other teams. Because the primary touchpoint with these elements is through the Wagtail CMS we have focused on the components that will be encountered there. This component is actually a grouping of smaller page components and therefore the page abides by the content guidelines as much as possible but has a few differences. This page will live in the "page components" section of the updated DM.

**Comment by nataliafitzgerald** [comment]
@ajbush @duelj 

<strong>Content edits</strong>
- Change "2-column" to "two column"

<strong>Design edits</strong>
- Can we include more vertical space above the "Style" heading. The content feels crowded there.
- Should "Landing page template" in the first paragraph have the capital "L" or should it be lowercase? Let's be sure to be consistent with what we do across all these pages.

**Comment by sonnakim** [comment]
@schaferjh 

Overall I think this works as an MVP page for the D&D audience. I have a few suggestions; feel free to take or leave!

#### Intro section
- I found myself spending a few minutes trying to understand how this component compares to similarly-named components like the 25/75 and the half-width link blob. Maybe it would help to add something up front about the fact that this component has related alternates that the reader should also keep in mind to check out (“Similar to: the 25/75…"). 
- Something in the introductory paragraph that states that this is essentially the half-width link blob, but with images. This wasn't revealed till the bottom of the use case section, and is probably something that's good to have up front, so the reader can register that as a point of comparison. 
- I didn’t immediately understand the significance of pointing out that the "2-columned layout utilizes extra screen real estate found on larger breakpoints.” Is this a comment on how the component will behave as the viewport gets wider? Is this important to know up front? I’m sure there’s a reason but I just wasn't getting it immediately...waah.  

#### Use case section
- I found the last bullet under “when to use”, "To help establish a hierarchy of linked content on this page,” a little confusing. Does this mean that one should use this component when one wants to make the linked content the visually predominant feature on the page? EDIT: Looked at the half width link blob page, and realized this might refer to when we are implying a parent/child relationship between the current page and the linked page. If so, the language there is a little clearer for me.

**Comment by schaferjh** [comment]
@ajbush looks good, ready to publish!
