### ISSUE TITLE
Filterable list pages

### ISSUE THREAD

**Issue by ajbush** [cfpb/design-manual#420]
#### What is it?

V1 is looking to add its atomic element documentation to the DM for the use of other teams. This documentation includes page templates as well.

This specific page will live in the "global elements" section of the updated DM.

**Comment by nataliafitzgerald** [comment]
@ajbush @duelj 
The design looks good! Just a few copy edits:
- In this sentence, add a comma after "documents": Filterable list page types are used to house searchable lists of articles, documents, or other resources and publications. 
- Change to sentence case: "Sublanding page with Filterable List" to "Sublanding page with filterable list"
- We are inconsistent in how we refer to certain terms: "sub-landing" or "sublanding" 
- In this sentence we should use consistent casing: "Required elements: filter control panel, list of items (displayed as post preview items) and pagination."

**Comment by marteki** [comment]
Reviewing this for UX in @schaferjh's stead. I'm focusing on usability, minor content tweaks, and ease of explanation.

Suggestions:
- Add a link or explanation in the intro paragraph for what a "document detail" page is.
- The second bullet point under "When to use" feels like less of a bullet point phrase, and doesn't answer the question of when this should be used. It should maybe be its own paragraph after the bullet point list.
- Move list of page components to be included out of the skinny sidebar. It's harder to read than if it was in the main content flow under "When to use".
- The second bullet point of the "Content guidelines" section is confusing, and possibly needs grammar work? I can't understand what it is describing.

As I've said elsewhere and communicated in different design working sessions: I really like the visualization of the major breakpoints, and that y'all included a listing of the possible page components. 😄

**Comment by schaferjh** [comment]
@ajbush Two tweaks needed: 
- Change the intro paragraph to add a paragraph break and change the final sentence:

> Filterable list page types are used to house searchable lists of articles, documents, or other resources and publications. 
> 
> Most filterable list pages use the browse page template layout, though in rare cases they can be housed on a sublanding page template layout. The filterable list itself is composed of [post preview components](http://ajbush.github.io/design-manual/global-elements/document-detail.html#behavior) that link to individual document detail pages.
- The link in the [style paragraph](http://ajbush.github.io/design-manual/global-elements/filterable-list-pages.html#style) doesn't currently lead anywhere.

**Comment by ajbush** [comment]
Updated!

**Comment by schaferjh** [comment]
@ajbush great, ready to publish!
