### ISSUE TITLE
Sub-landing page template

### ISSUE THREAD

**Issue by duelj** [cfpb/design-manual#424]
#### What is it?

V1 is looking to add its atomic element documentation to the DM for the use of other teams. Because the primary touchpoint with these elements is through the Wagtail CMS we have focused on the components that will be encountered there. 

This page will live in the "global elements" section of the updated DM.

**Comment by nataliafitzgerald** [comment]
@ajbush @duelj 

Design edit: 
- Based on the pattern used throughout the DM, we should use Avenir Next for the intro text. Georgia is currently being used on this page instead. 

Copy edits:
- Change "Landing page template" to "landing page template" (sentence case). So: "The sub-landing page template should always be used as a child page to the landing page template." This is consistent with how we apply casing on the landing page template template page. http://duelj.github.io/design-manual/ui-toolkit/landing-page.html
- Change "Content Guidelines" to "Content guidelines" (sentence case)

**Comment by keelerr** [comment]
Does contact information belong in area 2? You mention it last in the "recommended hierarchy of components" but I would have thought it would have gone solely in area 3. 

Also providing UX feedback/review, but most of my questions are based on my own personal questions from other projects.
- In general, could you include an example or two of excellent sub-landing pages? I know you're not trying to be overly prescriptive in the text, but personally, I'd love to see a few examples from different parts of the site that—in your mind—are great examples.
- Other than the (obvious) difference in placement within the site, is there significant differentiation between landing and sub-landing pages? I see that some modules cannot be used within the landing page, but in general they seems almost identical. I wonder if there are any design or content strategy nuances that would be helpful to identify.
- Any limitations on whether or not this needs to have multiple child pages or if some of the links can be to PDFs?

**Comment by schaferjh** [comment]
Responding to @keelerr's feedback, I've updated the page intro to clarify the difference between this page type and the landing page type. Certainly welcome more feedback from @sarahsimpson09, but I think this will be serviceable as the page introduction for now:

**Sub-landing page types provide an overview of a topic and/or group of related content within a main navigation area. The sub-landing page template should always be used as a child page to the landing page template.**

**Similar to landing pages, the focus of these pages is enabling users to quickly understand a topic area and select the specific information that meets their need. Unlike the landing page, this template allows for lengthier content components to allow for further explanation of a topic if needed.**

Contact information can go in Area 2 if it is a contact that is critical to the purpose of the page or topic of the page. For example, the [Enforcement](http://www.consumerfinance.gov/policy-compliance/enforcement/) has whistleblower info in the main area of the page. @ajbush how about we add this language to the Content guidelines: "The default placement for contact information should be in the sidebar. Only use the main content area when contact information is of extra significance or directly ties into the main objective of the page."

For the MVP version of this page, we're going to hold off on loading up on specific examples while folks try out all these new pages. We'll gather feedback and if they still feel necessary in a few months, compile examples.

If the only content we have for a topic that lives at a sub-landing page level is PDFs, then I suppose PDF links are acceptable -- I'd like to resist setting a rule around this kind of usage until we see how things are playing out.

**Comment by schaferjh** [comment]
@ajbush Looks great, ready to publish!
