### ISSUE TITLE
Learn page template

### ISSUE THREAD

**Issue by duelj** [cfpb/design-manual#426]
#### What is it?

V1 is looking to add its atomic element documentation to the DM for the use of other teams. Because the primary touchpoint with these elements is through the Wagtail CMS we have focused on the components that will be encountered there. 

This page will live in the "global elements" section of the updated DM.

**Comment by nataliafitzgerald** [comment]
@ajbush @duelj

Design edit:
- Based on the pattern used throughout the DM, we should use Avenir Next for the intro text. Georgia is currently being used on this page instead.
- Can we include more vertical space above the "Style" heading. The content feels crowded there. 

Copy edits:
- Change "Learn page" to "learn page" (sentence case - last sentence of first paragraph) 
- Change "Content Guidelines" to "Content guidelines" (sentence case)
- Suggested change: Change "chunk" to "group" - "Use sub-headers to group sections of content"
- We could lose the word "to users" at the end of the first sentence. "Learn page types provide focused, detailed information about a specific topic."

**Comment by marteki** [comment]
Reviewing this for UX in @schaferjh's stead. I'm focusing on usability, minor content tweaks, and ease of explanation.

Suggestions:
- Break up the intro paragraph into two paragraphs, for ease of understanding:

> Learn page types provide focused, detailed information about a specific topic to users. These pages may contain lengthy text passages or interactive content that require more engagement from the user.
> 
> Generally, this should be the page template used for most new information and content; other higher-level page templates are mostly aimed at navigating users to the right Learn page.
- Rephrase the long sentence containing "Generally, this should be the page template used for most new information and content". The language in this portion is very, very soft; it feels like "should" and "mostly" is used too often here. If it should be the default or first template considered for most new content, say so and make that clear.
- I agree with @nataliafitzgerald that "learn page" should be lowercase in the intro paragraph.
- Move list of page components to be included out of the skinny sidebar. It's harder to read than if it was in the main content flow under "When to use".
- Move the second bullet point from the "Content guidelines" section out of the bullet point list, and lead with it in this section as a paragraph. 

Repeating what I've already expressed elsewhere: kudos for the visualization of the major breakpoints, and listing the page components that could be included. 🎉

**Comment by schaferjh** [comment]
@ajbush Looks great, ready to publish!
