### ISSUE TITLE
Guidance Around Opening Links in New Tabs

### ISSUE THREAD

**Issue by KimberlyMunoz** [cfpb/design-manual#430]
There's currently an unspoken rule that we use "_blank" in web applications, that should be updated to be included in the design manual at first and we should include additional guidance to address two security and accessibility issues.

> We might want to look into adding rel="noopener" to "_blank" links as a way to counteract a [common security issue](https://mathiasbynens.github.io/rel-noopener/) with pages we don't control.
> 
> We should look into adding some screenreader-only text to warn users with visual impairments that this will open in a new tab to [meet guideline 3.2 that webpages should work in a predictable way](https://www.w3.org/TR/WCAG20-TECHS/G201.html). A lot of users at the last accessibility conference I attended mentioned this as a common pain point when websites don't give any indication of new tab behavior.

First brought up: https://github.com/cfpb/college-costs/pull/187#discussion_r67728602

**Comment by Scotchester** [comment]
:+1:

Work can begin at any time on updating the language at the bottom of [the Links page](http://cfpb.github.io/design-manual/page-components/links.html) to add these recommendations.

**Comment by marteki** [comment]
Addressed in PR #616 for [the Links documentation](https://cfpb.github.io/design-manual/page-components/links.html). Closing issue as resolved! 🎉
