### ISSUE TITLE
Expedited review: Allow Social Media molecule in Browse page content areas

### ISSUE THREAD

**Issue by Scotchester** [cfpb/design-manual#439]
As we prepare to launch the Spanish version of Money as You Grow in Wagtail, the team would like the ability to add a Social Media module within the main content area of a Browse page.

On [a current English age-level page](http://www.consumerfinance.gov/money-as-you-grow/middle-childhood/) (which is hand-coded in the fin-ed-resources repo), the featured activities have a share links adjacent, which specifically share details about the activities themselves.

How we'd like to do it:

![screen shot 2016-08-23 at 17 34 30](https://cloud.githubusercontent.com/assets/1044670/17910669/e2605a28-6957-11e6-8611-513c41508ce8.png)

If this proposal were rejected, we'd be left with putting the module in the pre-footer area:

![screen shot 2016-08-23 at 17 32 43](https://cloud.githubusercontent.com/assets/1044670/17910619/a11c468a-6957-11e6-93f3-18d0e910eb8f.png)

Adding the module within the pre-footer area would separate it significantly from the activities content, and it wouldn't make sense for them to share about the activities specifically anymore.

For extra credit, it'd be nice to add a new field to the module to customize the heading – in this case, to "Share activities" (or the Spanish translation).

@schaferjh @nataliafitzgerald @JenniferHoran

**Comment by schaferjh** [comment]
@Scotchester could you show a larger screenshot of the proposed/how we'd like to do it page? I can't tell whereabouts on the page the share buttons are being added with the slice you've included.

What is the goal of adding the share buttons somewhere in the middle of content on a page? Just to place them higher up than in the prefooter? Or to associate them with a specific piece of text or other content?

My inclination is to say that we want to be purposeful in our use of share buttons and if we do expand how and where they are added, we might want to put some thinking/limits around _where_ they can be added. I hear you saying that the sidebar/prefooter is not a sufficient solution. But I hesitate to add a module to the main content of the page that could mean share buttons show up anywhere in the main content area.

@sarahsimpson09 or @kurzn I'd be curious what your thoughts are around placement of share buttons.

**Comment by Scotchester** [comment]
Here's a zoomed-out screenshot of most of the page showing both placements:

![screen shot 2016-08-24 at 18 14 01](https://cloud.githubusercontent.com/assets/1044670/17950039/9dafd8ac-6a26-11e6-99b7-40cdf76e9db0.png)

> What is the goal of adding the share buttons somewhere in the middle of content on a page? Just to place them higher up than in the prefooter? Or to associate them with a specific piece of text or other content?

Yes, the desire is to have the share buttons specifically associated with the featured activities, rather than the page as a whole.

> My inclination is to say that we want to be purposeful in our use of share buttons and if we do expand how and where they are added, we might want to put some thinking/limits around where they can be added. I hear you saying that the sidebar/prefooter is not a sufficient solution. But I hesitate to add a module to the main content of the page that could mean share buttons show up anywhere in the main content area.

That's certainly an understandable perspective. In that vein, another route we could consider is something like adding an option to the Image Text 50-50 module that flips on share buttons within that module. It would only be marginally more complicated than making the Social Media module available anywhere, and it would probably improve the spacing, actually.

**Comment by Scotchester** [comment]
Hey @schaferjh @sarahsimpson09 @kurzn any more thoughts on this? Our ideal launch date is EOD Thursday.

**Comment by schaferjh** [comment]
I know Natalie is not available for the next few days, so if @sarahsimpson09 and @nataliafitzgerald don't have any further comments, then I would like to recommend we go with the integration of share buttons to an existing module, rather than adding a social media module to the options for content areas. I think the added context and improved spacing will improve the usage and layout.

It sounds like the module you need it on right now is Image Text 50-50 -- how about starting there? We can see how it performs and perhaps backlog a broader discussion around the strategy of inserting share icons associated with specific content across more modules?

**Comment by Scotchester** [comment]
Works for me!

**Comment by Scotchester** [comment]
PR is open: https://github.com/cfpb/cfgov-refresh/pull/2365

**Comment by Scotchester** [comment]
PR approved. Will leave the issue open until I update the Design Manual page for Image and Text 50/50.

**Comment by kurzn** [comment]
Reviewing tasks associated with "share buttons" for another project...  given the research outlined in #483 I'm wondering if this is still a good idea? Should we close this as unchanged? @schaferjh  @Scotchester

**Comment by Scotchester** [comment]
Well, the change is already implemented in the Wagtail Image and Text 50/50 module. I think that unless we intend to reverse course and remove the option, it should still be documented as an available option.

**Comment by schaferjh** [comment]
#483 raises some interesting points and I've asked Jon to think about some additional research we could collect to have effective conversations with internal stakeholders. For the moment though, we'll keep the page-specific share buttons.

**Comment by Scotchester** [comment]
Closing as this will be included in my forthcoming work to document Info Unit Groups.
