### ISSUE TITLE
Purse Illustration

### ISSUE THREAD

**Issue by duelj** [cfpb/design-manual#45]
Here is a first attempt at the purse, I will do some other options but I wanted to see how people felt about using the stitching pattern strokes or if I should abandon that approach. This also seems like we would stylize the shoulder strap like this but the radius of the curves have to be more substantial for the thickness of the strap to seem right. Interested to hear your thoughts.
![purse_1](https://f.cloud.github.com/assets/6873734/2401603/fbad058c-aa17-11e3-9837-e96b472499cb.png)

**Comment by ajbush** [comment]
I really like where you are headed with this. I wonder if adding more details like a buckle and/or a flap would help?

**Comment by mebates** [comment]
I would try a less symmetrical shape for the strap, more irregular. One hump could be lower than the other. I agree that more detail on a flap would help add some depth.

**Comment by mebates** [comment]
Any updates?

**Comment by duelj** [comment]
Nope, no updates. Kinda been tied up with the Idea 42 animation stuff so maybe someone else can pick up where I left off here?

**Comment by nataliafitzgerald** [comment]
This looks like a designer purse. If we are trying to show a standard purse, we should pull back on the designer elements (namely the pattern). I agree about simplifying and shortening the handle.

**Comment by vz3** [comment]
I share the concern with the designer purse. In addition to removing the stitching, I'd suggest changing the strap clasps to silver.

**Comment by mebates** [comment]
I took a shot at the purse:
![screen shot 2014-03-18 at 4 49 54 pm](https://f.cloud.github.com/assets/6223901/2453499/ec93b2a0-aede-11e3-975c-a1a2154afb4c.png)

**Comment by nataliafitzgerald** [comment]
Hi @mebates. I'm linking the overall shape and footprint of the purse. The handle looks a bit like a magnet. Is there any alternative styling that would remove that likeness. The silver clip is a confusing in terms of the depth. Perhaps you can look at a different type of clip, maybe something more decorative?

**Comment by mebates** [comment]
Totally see the magnet. Here's an update, with more of a toggle closure:

![screen shot 2014-03-24 at 3 54 52 pm](https://f.cloud.github.com/assets/6223901/2504510/4ad59262-b38e-11e3-868c-87d5146158c4.png)

**Comment by elizbond** [comment]
@ohsk add to the library.
