### ISSUE TITLE
Add "Data visualization" as main nav / vertical

### ISSUE THREAD

**Issue by caheberer** [cfpb/design-manual#453]

**Comment by jimmynotjim** [comment]
Open for review in #455

**Comment by caheberer** [comment]
👍

**Comment by Scotchester** [comment]
I just reverted this change, because the page has no content yet. We shouldn't make a page live with no content.

**Comment by jimmynotjim** [comment]
Since the item is there and only commented out, lets still keep this issue closed. There's no real dev effort needed to show it again
