### ISSUE TITLE
Car illustration

### ISSUE THREAD

**Issue by ajbush** [cfpb/design-manual#46]
Here are my initial thoughts for the car to be used in industry facing graphics. I first started below with the restricted green color palette to keep within the style we are developing.

![old](https://f.cloud.github.com/assets/6931351/2401554/7e4e8034-aa17-11e3-9b78-abc9f32fb050.png)
I received feedback from @mebates to try a few tweaks. Her feedback was that the... 

> - wheels seem a bit small and the spokes a bit too prominent
> - main bulk of car seems a bit high or thick, compared to the windows section
> - Like the shapes you're using for windows and headlights. 
> - Like the simple shading back to front

---

I took a second pass at incorporating her feedback and those updates are below. The wheels are enlarged but I added detail to the spokes after looking throughout the illustration style and noticing that the tires could use more fidelity to fall in line with everything else.

![industry](https://f.cloud.github.com/assets/6931351/2401630/4a6c3bfc-aa18-11e3-8fd2-2b15964d34c5.png)

**Comment by ajbush** [comment]
I then took a pass at bringing the car into the normal illustration style that has more detail in the windows, doors, lights, handles, and side view mirror. I've colored the car using greys for now so that we can focus on ironing out the framework of the car.

![car](https://f.cloud.github.com/assets/6931351/2401730/4cabaeba-aa19-11e3-926d-a44f6916f40d.png)

**Comment by ohsk** [comment]
Hey AJ, I think that the general forms seem a bit too organic still... like the fact that the bottom of the car has some curvature and the back of car doesn't have clear shape that I could backtrack and pull out as the starting geometric elements.

Here were a few examples that I found that had some interesting forms that seemed a bit more inline with the latest approaches for our illustrations:

![deloreanagain](https://f.cloud.github.com/assets/1689222/2402702/77918346-aa25-11e3-8957-81ba2da7c323.png)

![bm-final](https://f.cloud.github.com/assets/1689222/2402703/7b0a37f2-aa25-11e3-9444-1d7e51ea9c4e.jpg)

![captura_de_pantalla_2012-12-11_a_las_13 42 47](https://f.cloud.github.com/assets/1689222/2402704/7e107858-aa25-11e3-956e-854e46a26e46.png)

![beaverwack](https://f.cloud.github.com/assets/1689222/2402705/8102d970-aa25-11e3-996b-5bc6ebd5fdb5.png)

**Comment by duelj** [comment]
I couldn't resist the chance to make a car... it would still need some love but I was trying to keep our shapes and shadows going to see how it was feeling maybe it helps influence something else?
![car_1](https://f.cloud.github.com/assets/6873734/2411399/067bb68e-aac7-11e3-8ab5-7a7a75e6fecc.png)

**Comment by ajbush** [comment]
NIcee. I really like the handles and the contour details you have added. The glare in the glass is nice too. I'm still working on a version too but you guys have set the bar pretty high. This seems pretty solid to me. Would the front lights be viewable from this angle?

**Comment by duelj** [comment]
Thanks! Great point, I was trying to sort out the headlight situation, I tweaked a couple things and tried to refine some details on this one. 
![car_2](https://f.cloud.github.com/assets/6873734/2412132/03759eca-aacf-11e3-97c0-30dc449de32d.png)

**Comment by ajbush** [comment]
Yea those updates are really looking sharp. I'd vote to use this. Curious to see what @ohsk and others think.

**Comment by mebates** [comment]
The front nose seems too narrow and pointy. Looks like a concept car. Love everything else.

**Comment by duelj** [comment]
rounded car - less concept more 'family?'
![car_3](https://f.cloud.github.com/assets/6873734/2413396/c2d1e70c-aadd-11e3-9589-19987dcefb38.png)

**Comment by duelj** [comment]
After our conversations during crit. I made a couple of minor tweaks to the car I had been working on. 

#### 1 Same overall shape, removed lower detail line and tried adjusting colors just to see if it helped the feeling of the overall car.

![car_4](https://f.cloud.github.com/assets/6873734/2415320/dbacfeae-aaf3-11e3-9437-5e4251996ec0.png)

#### 2 Adjusted the hood shape, and front body to be a less harsh angle and trying to keep a more simple shape. Also, tried to pull back on the stroke detailing and shadow lines to make the overall feel a little more simple/subtle.

![car_5](https://f.cloud.github.com/assets/6873734/2415349/28152f32-aaf4-11e3-8057-0ce412f2d1ac.png)

**Comment by mebates** [comment]
Nice. Looks like my sister's old royal blue Ford Focus. :smiley:

**Comment by duelj** [comment]
Nailed it then. haha. Still interested in other peoples ideas if its not
feeling right.

**Comment by nataliafitzgerald** [comment]
I'm liking the back of the car and the lower part of the car. The hood and front lights still seem a little off. Is the front part coming out too far? I like the hubcaps but could we look at some simpler style hubcaps for comparison?

**Comment by vz3** [comment]
This is something Hantz and I went back and forth on in one of our earlier animations (the original version had one of those smart cars). The long hood in particular reads big engine V8 luxury to me as well as the low-profile tires — BMW M5 or Chrysler 300M. I think this could be tweaked to look more like a lower to mid-range vehicle like the Focus @mebates mentions or Chevy Malibu by bringing in proportions of the front end.

M5
![image](https://f.cloud.github.com/assets/582918/2440359/ef1a968e-ae06-11e3-894c-a783e583a11c.png)
300M
![image](https://f.cloud.github.com/assets/582918/2440426/8be28b0c-ae07-11e3-84c2-5476c30e929e.png)

Focus
![image](https://f.cloud.github.com/assets/582918/2440439/b9eeb5a2-ae07-11e3-8aa3-9a5d969e714d.png)

Pardon the Ford bias.

**Comment by duelj** [comment]
It was actually based off the original proportions of a Subaru Impreza which is a budget minded family car. The edits that were made have pushed it into Volkswagen Passat territory (circa 01-05) but in the end it is none of these cars and only roughly based on the proportions of any existing model. I think the ambiguity is our ally on this one and I think it would be helpful to see others ideas on this one as well since cars carry so much meaning to so many people. Thoughts? 
![subaru-impreza-630](https://f.cloud.github.com/assets/6873734/2441075/8dfe01fc-ae0f-11e3-923c-597c656bec0d.jpg)

**Comment by duelj** [comment]
Here are some adjustments to the car to bring it in line with the suggestions @nataliafitzgerald and @vz3 made. Shorter front hood, lights adjusted to match, simple shadow lines, simple wheel style, and smaller radius wheel. 
![car_6](https://f.cloud.github.com/assets/6873734/2449850/8288928c-aeb5-11e3-9ec2-e65a7b02b80e.png)

**Comment by nataliafitzgerald** [comment]
@duelj Can you share the latest illustrator file for the car?

**Comment by nataliafitzgerald** [comment]
@duelj , this is getting really close. 

To soften this up a bit, lets the black in the hubcaps to the 80% grey. Also, there are some jagged areas in the space around the tires and the shadow under the car. Before finalizing, let's remove some of those points and clean up the edges. Let's remove the highlights from the hubcaps and the tire. That level of detail feels like too much. 

In addition to the above edits, the one remaining area of the car that still needs some final adjustments hood shape and the lights. First off, let's move the lights over to the edge so that there is no blue showing to the right. Also, make sure the shape along the left of the lights follows the curve of the tires. For the hood shape, what shapes were used to build it - a curved rectangle and a circle?

**Comment by duelj** [comment]
Here are some of the tweak you requested. I rebuilt it trying to keep the body shape as simple as possible. I think it looses something but I it could be an interesting point of comparison. This means no angle from the back to the front hood and the front shape is an arc all the way.  It makes the windows kinda wonkey and the more complex shape I think makes for a more legible car overall. 
![car_7](https://f.cloud.github.com/assets/6873734/2504731/da5e8f4a-b390-11e3-98ac-2562c522b041.png)
![car_8](https://f.cloud.github.com/assets/6873734/2504732/dfa99184-b390-11e3-8281-450b6725d1c0.png)

**Comment by mebates** [comment]
I think the bottom one is looking great. Just took your files and cleaned up the jaggedy edges around the hubcaps. Trying it in green/grey for the FinEd video:

![screen shot 2014-03-24 at 4 47 27 pm](https://f.cloud.github.com/assets/6223901/2505076/a953872a-b395-11e3-9349-7dc93722f093.png)

**Comment by duelj** [comment]
Looks good to me! I like it in green. Thanks for cleaning it up. Glad
you're on board.

**Comment by ohsk** [comment]
Yeah this is looking great!

**Comment by vz3** [comment]
agreed!

**Comment by nataliafitzgerald** [comment]
We are using the car in a current video project. When placed with other illustrated objects from our library, the car was standing out in terms of the level of detail. Removing the hubcap detail on the wheels helped simplify the car illustration to bring it closer to our other illustrations. 

![screen shot 2014-03-26 at 10 16 38 am](https://f.cloud.github.com/assets/6887128/2525643/75d32e16-b4f1-11e3-9562-1515406c0f92.png)

In instances where we do choose to use the hubcaps, I recommend decreasing the contrast on the hubcaps as shown below. 

![screen shot 2014-03-26 at 10 20 48 am](https://f.cloud.github.com/assets/6887128/2525688/f66c2672-b4f1-11e3-8359-6c70a5919f96.png)

**Comment by elizbond** [comment]
@ohsk add both car options to the library.
