### ISSUE TITLE
Modals page is broken

### ISSUE THREAD

**Issue by marteki** [cfpb/design-manual#473]
Placing this here so I don't forget about it, since I can't address it right now: the Style section of the Modals page is broken, and isn't displaying hexadecimal color codes.

![screen shot 2017-04-06 at 2 42 07 pm](https://cloud.githubusercontent.com/assets/1183435/24770279/5d49bd2a-1ad7-11e7-8225-fc6fe6bc3a52.png)

**Comment by nataliafitzgerald** [comment]
@marteki 
@anselmbradford is working on bringing this pattern into Capital Framework and we too noticed that the page is in need of some attention. Unfortunately we don't have the bandwidth to take this on right now. 

@anselmbradford - In building this pattern could you document the specs here so that someone can easily pick up this task when they have the time?

**Comment by anselmbradford** [comment]
What should the space between the modal and left/right edge of the window be? I'm using 5% for the top, left, and right. Which means it's narrower when the page is small, and wider when the page is large:

![screen shot 2017-09-11 at 3 29 32 pm](https://user-images.githubusercontent.com/704760/30293008-20be7b92-9706-11e7-9fcb-a3dcedcd0a2d.png)

![screen shot 2017-09-11 at 3 29 42 pm](https://user-images.githubusercontent.com/704760/30293009-20c40d28-9706-11e7-8b96-7755e8e7f3eb.png)

**Comment by nataliafitzgerald** [comment]
@anselmbradford 
- For large screen widths we should be sure that we aren't exceeding 670px for the text block. This is our max width for paragraph text. It looks like the text in the above example is expanding to the full width of the box. 
- What padding are you using for the small screen view? Our padding for wells at small screen widths is 15px left and right. It seems like we should use that here too. 
- It doesn't look like Avenir Next is loading in the above examples.  

I believe @kurzn worked on the development of this pattern. @kurzn - Can you take a look and provide feedback?

**Comment by nataliafitzgerald** [comment]
Also, it looks like there are some design specs on the design manual page: https://cfpb.github.io/design-manual/page-components/modals.html
<img width="402" alt="screen shot 2017-09-11 at 7 43 13 pm" src="https://user-images.githubusercontent.com/6887128/30301568-89236404-9729-11e7-90a2-9bfd5331eb8e.png">

If the max width is 630px for large screens that would mean the text block is 570px and there is 30px of padding on the left and right for a total of 630px width. Makes sense.

**Comment by anselmbradford** [comment]
Heh, yeah, I realized the specs had them after all, sorry about that!

**Comment by marteki** [comment]
Came across this old, still open bug report I made. It's been fixed! 🎉 

![screen shot 2018-08-27 at 7 23 04 pm](https://user-images.githubusercontent.com/1183435/44691957-b95e9080-aa2e-11e8-86a2-78710c00f103.png)
