### ISSUE TITLE
Problem with current Tables guideline for fixed width columns on mobile screen sizes

### ISSUE THREAD

**Issue by marteki** [cfpb/design-manual#477]
### Current guideline

Right now on our [Tables page](http://cfpb.github.io/design-manual/page-components/tables.html), there is the style option to use fixed width columns, with the following guideline given:

> Column widths are automatically set by browsers by default. If needed, some or all columns can be set to specific widths instead to accommodate longer data or labels.

Examples are then shown with columns fixed to specific percentages of the table width:

![screen shot 2017-04-11 at 3 37 24 pm](https://cloud.githubusercontent.com/assets/1183435/24927383/d33f2a30-1ecc-11e7-9969-72bbe653f150.png)

### Discovered issue

However, at small device widths, the current guideline (and front-end code implementation) has the columns stay fixed to a specific percentage, even though the table now has a smaller width.

The following examples are of desktop and mobile views of the same table. The first table column's width is automatically set by the browser, while the last two are set to 25% width each.

Desktop:
<img width="1216" alt="screen shot 2017-04-11 at 2 02 30 pm" src="https://cloud.githubusercontent.com/assets/1183435/24927524/438299e4-1ecd-11e7-80f0-8f605c3ae17a.png">

Mobile:
<img width="285" alt="screen shot 2017-04-11 at 2 03 21 pm" src="https://cloud.githubusercontent.com/assets/1183435/24927538/4d11fc3e-1ecd-11e7-985b-fe8bcd855b8a.png">

#### Recommendation

* Modify the Tables fixed width column guideline to state that fixed width columns expand to full width for mobile breakpoints, as done for columns whose width is automatically set by the browser.
* Modify Capital Framework to implement the updated guideline.

(Thanks to @ajbush @pjpdesigns @StephanieLevy for working on the design that nicely uses fixed width columns, and @mistergone for demoing the code that revealed the problem on smaller screens.)

**Comment by jimmynotjim** [comment]
Nice catch on this. @mistergone did you want to take on making the code changes to Capital Framework since you're already familiar with the tables code?

**Comment by Scotchester** [comment]
Yep, this should definitely get fixed. Shouldn't be too hard. @jimmynotjim FWIW, @mistergone is out the rest of the week, but I don't think it's too urgent to wait for his return. @marteki?

**Comment by marteki** [comment]
Yep, this can definitely wait for his return. Wanted to check with the whole design/dev crew here, since it would also mean a change in the Design Manual copy to be more explicit about what happens at smaller sizes.

Does anyone else have concerns with this proposal moving forward, before we draft new content or make any code changes? @caheberer @schaferjh

**Comment by caheberer** [comment]
👍  Makes sense to me.

**Comment by schaferjh** [comment]
👍  sounds good

**Comment by marteki** [comment]
Update: thanks to @mistergone, the fix for this has been merged into both [Capital Framework ](https://github.com/cfpb/capital-framework/pull/470) and [our Wagtail codebase](https://github.com/cfpb/cfgov-refresh/pull/2852).

We'll be submitting a pull request to clarify the Design Manual guideline next week.

**Comment by marteki** [comment]
And with the merging of https://github.com/cfpb/design-manual/pull/485, I think this bug is fully resolved. Thanks all!
