### ISSUE TITLE
Wallet illustration

### ISSUE THREAD

**Issue by ajbush** [cfpb/design-manual#48]
Hey team, here is a pass at the wallet. Let me know your thoughts. I tried small variations in the spine and the stitching around the i.d. slot.

![spine_no_lines](https://f.cloud.github.com/assets/6931351/2424187/0e3b903c-aba4-11e3-90d8-6b41d8dd5d9f.png)

The version below has horizontal lines in the spine to add detail. Seems like it may not be necessary but wanted to share this option.

![spine_lines](https://f.cloud.github.com/assets/6931351/2424196/2c564440-aba4-11e3-8bfa-800c5bd27403.png)

And the version below removes the stitching around the i.d. slot. This version also removes the dark imprint of the credit card.

![flat](https://f.cloud.github.com/assets/6931351/2424221/8e0c6372-aba4-11e3-9066-845dcccb630b.png)

**Comment by mebates** [comment]
Nice AJ. I think the last one, the simplest, is best. I would simplify the ID 'type' a bit, maybe just three solid lines? Will we have a need for closed wallet?

**Comment by ohsk** [comment]
Hey AJ, looking great!

I would second Mollie's comments, and also suggest perhaps trying a slightly smaller radius for the outside corners of the wallet.

**Comment by Dnpizarro** [comment]
Looking good!
- 1 on the comment about the corners. I'm gravitating towards your 3rd option, its simpler and I don't think the stitching in the previous versions is necessarily adding much.

**Comment by nataliafitzgerald** [comment]
This is looking really nice, AJ. I agree that the simpler (last version) is best and with Mollie's other comments. As far as relative sizing goes, the dollar bill feels slightly too large when compared with the credit cards and IDs. Looking at what I have in my wallet here, IDs/credit cards seem to be just short of the same height as a dollar bill and a bit over half the width.

**Comment by ajbush** [comment]
Here is an update. I think I touched on everyone's feedback. Let me know if this is working better and I'll get started on a closed version of this like Mollie suggested.

![wallet_](https://f.cloud.github.com/assets/6931351/2425877/515c02d0-abbc-11e3-9f81-82906f7aa3a5.png)

**Comment by nataliafitzgerald** [comment]
Looks good to me!

**Comment by ajbush** [comment]
Hey all, here is a closed version of this wallet.

![closed](https://f.cloud.github.com/assets/6931351/2450460/bf8080ea-aebb-11e3-9c1a-e397d925a6a1.png)

Below I added a button snap to add more detail to help it read more as a wallet.
![closed_button](https://f.cloud.github.com/assets/6931351/2450490/fa8a6a2a-aebb-11e3-9981-63bdd2292fe1.png)

Here would be the look of the open wallet with the flattened button snap
![open_snapp](https://f.cloud.github.com/assets/6931351/2450500/0ddf3de4-aebc-11e3-944f-9cf294d1875c.png)

And below is one more option with the button snap curled back over the open wallet.
![open_snapp_folded](https://f.cloud.github.com/assets/6931351/2450551/8116541e-aebc-11e3-94f7-e2a389beaab9.png)

Let me know your thoughts.

**Comment by ajbush** [comment]
Here are some slight tweaks based off of the discussion in #50 . I added a slight shadow on the dollar bill. I also removed the stitching since it isn't included on the open wallets interior. 

![wallet_button_snap](https://f.cloud.github.com/assets/6931351/2452678/65bf32cc-aed4-11e3-902a-4b32934fd9f7.png)

..or without the button snap

![wallet_plain](https://f.cloud.github.com/assets/6931351/2452680/73261cbe-aed4-11e3-9673-985c47c03c4a.png)

**Comment by Dnpizarro** [comment]
I feel like without the strap the object is more difficult to identify. Also, is this wallet supposed to be gender neutral or gender specific? This could be better understood if we had some sort of context, nonetheless I think it is something we should consider before we finalize.

**Comment by stephanieosan** [comment]
I think whenever it makes sense, we should be gender neutral.

**Comment by ajbush** [comment]
Yea I'd say either version is gender neutral. But I agree with @Dnpizarro I think it needs the strap for the closed version to read as a wallet.

Changing the strap color may make it more gender neutral if the thinking was that the lighter strap wasn't as neutral.

![wallet_closed_darker](https://f.cloud.github.com/assets/6931351/2453015/179e92ae-aed9-11e3-980b-c36c009774b7.png)
![darker](https://f.cloud.github.com/assets/6931351/2453017/1b99e0e8-aed9-11e3-9f5e-79e39233d64f.png)

**Comment by elizbond** [comment]
@ohsk Add to library

**Comment by stephanieosan** [comment]
At what point should we close issues here? Once they're done enough to be added to the library or after they've been added?

**Comment by ohsk** [comment]
Would help me to leave them open until they've been added!
Sorry I've been lagging. I can close out upon addition.

**Comment by stephanieosan** [comment]
No worries! Just wanted to make sure someone was monitoring and closing when appropriate :)
