### ISSUE TITLE
Remove social media "share" icons based on UX test

### ISSUE THREAD

**Issue by jdrubin** [cfpb/design-manual#483]
Here's another one: On our 2nd top Task test, we got feedback on the Social Media icons at the top and bottom of lots of pages, especially on the blog and press releases:

<img width="468" alt="screen shot 2017-04-20 at 11 19 54 am" src="https://cloud.githubusercontent.com/assets/5712493/25238436/6f5d92b8-25bb-11e7-8b0f-4cebfd3045ef.png">

Problem: Our participants weren't able to tell the difference between "following" (on the bottom of the page) and "sharing" (on top). Moreover, most never even noticed the bottom row.

But wait - there's more: 
There's [research](https://bigmedium.com/ideas/no-mobile-share-buttons.html) that says that people on mobile never use the share buttons; they use their apps or cut and paste instead. I know I do. 
And even more than that, after checking with the data team, we found both top and bottom social share icons receive very low traffic - all of the social shares across the whole site, added up, only equal .3% of page-level interactions. And it's even less than that since half of that is probably related to email sign ups.
And another possible reason for the lack of shares is because lots of our content is related to assisting yourself in financial crises - not normally the thing you want to share.

Solution: The easy win is just to cut either the top or the bottom share icons. Since the lower row is already on every page, you could make the argument to cut the top so every page still has the icons. You could also make the reverse and say since most people missed the icons at the bottom, we could cut those.
The harder win, but probably a more forward-thinking one, is to cut BOTH. But either decision would remove clutter on the page and ensure people are actually interacting with what we put out.

**Comment by jimmynotjim** [comment]
The gov.uk team [found similar results](https://insidegovuk.blog.gov.uk/2014/02/20/gov-uk-social-sharing-buttons-the-first-10-weeks/) when they experimented with sharing buttons three years ago. I'm pretty sure they ended up removing them, but I can't find that post now (a quick look across the site seems to confirm though).

**Comment by Scotchester** [comment]
Interesting stuff. I have a hard time getting onboard with removing the links at the bottom, though, which are not intended to be sharing icons but links to our official accounts on those services. I think it would be a mistake not to link to our official accounts from our official website, regardless of how little traffic those links might get.

**Comment by jimmynotjim** [comment]
A simple solution to that could be to add a label like "Find us on" to the left of the footer icons. Might be people aren't clicking those because they're afraid it'll share the page, not open the profile.

**Comment by ajbush** [comment]
I like the idea of keeping it solely in the footer too. @jimmynotjim really like that idea of adding the "Find us on" label too. I feel like we may have explored something like that at some point but at any rate seems like we should definitely add that in.

**Comment by ielerol** [comment]
When we reviewed the test results, Jon and I discussed moving the links to our own social media accounts to the "contact us" page to keep them available somewhere. In any case, adding a label to clarify those buttons as long as they're in the footer would help resolve the confusion.

**Comment by kurzn** [comment]
I agree with removing them at the top of the blog. Who would share anything they haven't read yet? 

I think there could be value in having the social media links in the footer still. It doesn't hurt/ detract from the rest of the footer. Agree that adding a label at the bottom brings clarity to those buttons - they aren't actually share buttons, but rather links to our presence on social media.

**Comment by jimmynotjim** [comment]
> Who would share anything they haven't read yet?

Surprisingly, a lot of people. I remember seeing a not insignificant stat on the number of people that share something without reading more than 10% of it.
