### ISSUE TITLE
Post-CF4 punch list

### ISSUE THREAD

**Issue by Scotchester** [cfpb/design-manual#486]
These may not all be directly related to the CF4 upgrade (#466), but I wanted to record everything semi-notable that I saw in testing that, without making a new issue for each of these minor things.

- [x] Buttons with icons need their markup adjusted on the Buttons page
- [x] The first expandable in an expandable group is missing its top border
- [x] The copy about possible FCM categories is not correctly formatted as a nested list
- [x] Examples for links with icons on the Links page need to be updated to the current markup
- [x] Fix text | icon separator in disabled buttons

**Comment by jimmynotjim** [comment]
1. https://github.com/cfpb/design-manual/pull/488
2. https://github.com/cfpb/capital-framework/pull/477

**Comment by jimmynotjim** [comment]
Discovered this border color issue just now, added to the list above.

![screen shot 2017-04-28 at 1 58 00 pm](https://cloud.githubusercontent.com/assets/1280430/25543131/e3069bd2-2c1a-11e7-8776-495b84c17c52.png)

**Comment by jimmynotjim** [comment]
3. #492 
4. #493 
5. #494

**Comment by Scotchester** [comment]
Since these are all taken care of, I'll go ahead and close this issue.
