### ISSUE TITLE
Code snippets misaligned

### ISSUE THREAD

**Issue by awolfe76** [cfpb/design-manual#506]
Example: https://cfpb.github.io/design-manual/best-practices/accessibility-best-practices.html

### Screenshot

![code](https://user-images.githubusercontent.com/2932572/29192685-4ab4892a-7df0-11e7-91b7-83a45fb2aff9.png)

It looks like the bottom margin is set to `1.375em`. Resetting it to `0` seems to be ok.

### Screenshot `0`

![code-0](https://user-images.githubusercontent.com/2932572/29192795-c8b53b80-7df0-11e7-8c1f-1927d278a299.png)

But a `-.375em` seems to be even better.

### Screenshot `-.375em`

![code-neg](https://user-images.githubusercontent.com/2932572/29192810-d6c7d3cc-7df0-11e7-9e48-c0887e5cd18c.png)

_FYI - there's also a class there, `highlighter-rouge`, which doesn't do anything. Maybe it used to handle this?_

**Comment by marteki** [comment]
@awolfe76 Yep! I reported this same bug on the Capital Framework repo: https://github.com/cfpb/capital-framework/issues/555

Seems to be a conflict between the CSS files for the two systems that are supposed to work together.

**Comment by awolfe76** [comment]
Thanks @marteki! Sorry about that. I'll close this one.
