### ISSUE TITLE
Identify subsets of icons

### ISSUE THREAD

**Issue by jimmynotjim** [cfpb/design-manual#548]

**Comment by jimmynotjim** [comment]
Icons identified by:

line weights
sizes with and without circles
relationship to inline text, both with and without circles

**Comment by designlanguage** [comment]
Here are the 3 groupings I put together of the current icon set: Style, Area, and Detail level. 

![screen shot 2017-12-19 at 10 07 46 am](https://user-images.githubusercontent.com/10562544/34163397-9c1d6adc-e4a4-11e7-9266-4956225e2da4.png)
