### ISSUE TITLE
Collect all missing minicons

### ISSUE THREAD

**Issue by jimmynotjim** [cfpb/design-manual#549]
Some minicons have been updated or created since the last release. Sort through all our resources to ensure we've captured all of them.

**Comment by jimmynotjim** [comment]
@designlanguage @Dnpizarro Should we do this and #550 before #548? Do you think there's a chance the subsets could change after the additional icons are collected?

**Comment by designlanguage** [comment]
I think an audit of missing and new minicons first makes sense.

**Comment by designlanguage** [comment]
Here's what I've been able to pull together for new icons that don't exist in the typeface currently. Some are vectors, and others are concepts that would need to be drawn:

![screen shot 2017-12-19 at 10 14 32 am](https://user-images.githubusercontent.com/10562544/34163755-9cd4893c-e4a5-11e7-980d-51b7420a5072.png)
