### ISSUE TITLE
Update hypothesis for canvas size, icon size, and line weight changes.

### ISSUE THREAD

**Issue by jimmynotjim** [cfpb/design-manual#562]
Based on feedback from testing the initial draft set, make adjustments for another round of in-place testing.

**Comment by Dnpizarro** [comment]
### Updated Artboard

I updated the artboard template to reflect the 1200pt height. @jimmynotjim @designlanguage 
https://drive.google.com/drive/folders/1A8u5GzmxH357bbK9N8pAn9LCoaLB0HpF

<img width="630" alt="screen shot 2018-01-12 at 2 56 51 pm" src="https://user-images.githubusercontent.com/6852363/34892969-3b492422-f7a9-11e7-8dc2-8d5032ed4354.png">

**Comment by jimmynotjim** [comment]
@Dnpizarro I think there was a miscommunication, the extra 200pts should just be empty white space above the ascender. The round icons were sized correctly but needed the extra whitespace for them to maintain their relationship with the rendered canvas of Avenir at 16px.

**Comment by Dnpizarro** [comment]
Here is the updated file with the correct measurements:
https://drive.google.com/drive/folders/1A8u5GzmxH357bbK9N8pAn9LCoaLB0HpF

<img width="461" alt="screen shot 2018-01-16 at 10 14 57 am" src="https://user-images.githubusercontent.com/6852363/34995958-20512e12-faa6-11e7-8097-0fc044125e92.png">

**Comment by jimmynotjim** [comment]
@Dnpizarro cool, that looks right to me. Thanks for the quick fix.

**Comment by designlanguage** [comment]
The gap at the top is more than 200 px (it's larger than the descender which 240 px). I made an update:

![screen shot 2018-01-16 at 11 23 55 am](https://user-images.githubusercontent.com/10562544/34999474-c35673b6-faaf-11e7-9d6c-515b9f3e49d7.png)

**Comment by designlanguage** [comment]
@Dnpizarro - For open icon sizing within the artboard, here's what I'm thinking:

![screen shot 2018-01-16 at 12 15 14 pm](https://user-images.githubusercontent.com/10562544/35002438-abf07de0-fab7-11e7-9b1a-d635b2f8102d.png)

Circle icons fill the artboard, so we can treat the open icons similarly. I've kept these aligned with the baseline until they get taller than the ascender height, then they fall below the baseline.

Here's how that would play out with our current test set:

![screen shot 2018-01-16 at 12 19 46 pm](https://user-images.githubusercontent.com/10562544/35002443-af6994d4-fab7-11e7-94b6-f52c3b8225ff.png)

@jimmynotjim - I'm wondering if for the web it makes sense to align these to the right edge of artboard. Would that make it easier to have a consistent amount of space between the icon and type? The downside is that the minicons would start at different places on the lefthand side.

| Centered | Flush-right |
| --- | --- |
| ![screen shot 2018-01-16 at 12 39 21 pm](https://user-images.githubusercontent.com/10562544/35003270-507a24a4-faba-11e7-9f8d-f3578a0f735c.png) | ![screen shot 2018-01-16 at 12 39 13 pm](https://user-images.githubusercontent.com/10562544/35003269-50689310-faba-11e7-9ee2-8935844e57ac.png) |

**Comment by jimmynotjim** [comment]
@designlanguage I think these are working a lot better. 

For the alignment, we currently remove the left and right whitespace as part of the cleanup process and the spacing between the icon and the text is controlled via CSS. While right aligning the icons would make it easier to stay consistent, it creates a new issue with icons that fall after the text, like links to documents or external websites. I think we should continue removing left and right whitespace and figure out a container solution with CSS and markup for instances where there's a list of icons and text.

**Comment by designlanguage** [comment]
Makes sense to me @jimmynotjim . I'll assemble our test set at this size/alignment. I'll try to have that for you by EOD.

**Comment by jimmynotjim** [comment]
Awesome. Let's move this one to done and use #563 for discussion around the icons

**Comment by Dnpizarro** [comment]
@designlanguage the only issue I foresee is the space between lines. The example below has a consistent 60px height between the lines. I went with 60px because the lines tend to blend together at small sizes. Let me know your thoughts. 

<img width="881" alt="screen shot 2018-01-18 at 12 46 18 pm" src="https://user-images.githubusercontent.com/6852363/35112914-a43ef026-fc4d-11e7-9791-5f69985119fc.png">

**Comment by designlanguage** [comment]
Thanks @Dnpizarro, that looks good!
