### ISSUE TITLE
Tweak the icons for the web font canvas discrepancies and rework line weight fidelity.

### ISSUE THREAD

**Issue by jimmynotjim** [cfpb/design-manual#563]
Using the updated canvas in #562, redraw the draft set of icons

**Comment by designlanguage** [comment]
@jimmynotjim -

Here are the revised SVGs: https://drive.google.com/open?id=1B6pawMHd3ku5WXXaVLwnmb90re-5kBAz

As mentioned in #562, sizing for the non-circled icons is larger and related to the baseline of Avenir Next. The icons in the circle are centered within it.

Here's what the latest sample icons look like:

![screen shot 2018-01-16 at 5 13 25 pm](https://user-images.githubusercontent.com/10562544/35015131-0e1c4e26-fae1-11e7-9209-8b625202f49a.png)

**Comment by jimmynotjim** [comment]
Awesome. I'll get these into the web docs tomorrow
