### ISSUE TITLE
Export the tweaked icons for print testing.

### ISSUE THREAD

**Issue by jimmynotjim** [cfpb/design-manual#564]
After the icons are redrawn, export them for print testing.

**Comment by Dnpizarro** [comment]
I have the print test ready to export, but I wanted to get your thoughts on an alternative to the paper and stop watch "Payday-Loan". Let me know your thoughts. 

<img width="368" alt="screen shot 2018-01-18 at 3 22 32 pm" src="https://user-images.githubusercontent.com/6852363/35119604-7eb7ce7a-fc63-11e7-85de-6ae349a2be84.png">

**Comment by jimmynotjim** [comment]
I think this is a lot clearer concept and works far better at smaller sizes but will definitely defer to @designlanguage.

**Comment by Dnpizarro** [comment]
## Print Test Update
<img width="785" alt="screen shot 2018-01-18 at 3 55 49 pm" src="https://user-images.githubusercontent.com/6852363/35121041-1db3e7c6-fc68-11e7-8fb2-995082256938.png">
<img width="507" alt="screen shot 2018-01-18 at 3 55 35 pm" src="https://user-images.githubusercontent.com/6852363/35121042-1dcff24a-fc68-11e7-871a-988d1c76cb89.png">
<img width="508" alt="screen shot 2018-01-18 at 3 55 22 pm" src="https://user-images.githubusercontent.com/6852363/35121043-1defe866-fc68-11e7-9f42-6ab43cb2d257.png">
<img width="508" alt="screen shot 2018-01-18 at 3 55 09 pm" src="https://user-images.githubusercontent.com/6852363/35121044-1e0f74ba-fc68-11e7-9fd0-ace80e7e27a9.png">
<img width="507" alt="screen shot 2018-01-18 at 3 54 53 pm" src="https://user-images.githubusercontent.com/6852363/35121045-1e4cdef4-fc68-11e7-93a7-75d5304a13e2.png">
