### ISSUE TITLE
Update group 3 icons - Document

### ISSUE THREAD

**Issue by jimmynotjim** [cfpb/design-manual#575]
Update the third group of icons and export for print and web. Ensure the file names match the names used in the Design Manual, the paths are grouped into a top-level group, and everything is converted to outlines.

**Comment by designlanguage** [comment]
| Name | Symbol | In circle | Notes |
| --- |  --- |  --- |  --- |
| Upload | ![screen shot 2018-01-24 at 4 17 03 pm](https://user-images.githubusercontent.com/10562544/35358040-52a7cd70-0123-11e8-9402-e0ac4a6b0083.png) | ![screen shot 2018-01-24 at 4 17 08 pm](https://user-images.githubusercontent.com/10562544/35358041-52b73076-0123-11e8-8f47-2d67953f7d46.png) |  |
| Download |![screen shot 2018-01-24 at 4 16 52 pm](https://user-images.githubusercontent.com/10562544/35358038-528607ee-0123-11e8-911c-bb2f02cc6735.png) | ![screen shot 2018-01-24 at 4 16 56 pm](https://user-images.githubusercontent.com/10562544/35358039-52994c50-0123-11e8-89e3-66007f4f76cb.png) |  |

**Comment by jimmynotjim** [comment]
That no-name icon is "download" in [the Capital Framework docs](https://cfpb.github.io/capital-framework/components/cf-icons/#document-icons)

**Comment by designlanguage** [comment]
More icons for this group:

| Name | Symbol | In circle | Notes |
| --- |  --- |  --- |  --- |
| PDF | ![screen shot 2018-01-26 at 5 14 56 pm](https://user-images.githubusercontent.com/10562544/35463045-be3f3ae2-02bc-11e8-8c22-b97d5ba99236.png) | ![screen shot 2018-01-26 at 5 15 00 pm](https://user-images.githubusercontent.com/10562544/35463046-be54f1b6-02bc-11e8-838e-d5712c1342db.png) | Removed the text from this icon |
| Copy | ![screen shot 2018-01-26 at 5 15 06 pm](https://user-images.githubusercontent.com/10562544/35463047-be600da8-02bc-11e8-9392-84ee5c6012f4.png) | ![screen shot 2018-01-26 at 5 15 09 pm](https://user-images.githubusercontent.com/10562544/35463048-be71f900-02bc-11e8-8835-073bd9758a75.png) |  |
| Document | ![screen shot 2018-01-26 at 5 15 21 pm](https://user-images.githubusercontent.com/10562544/35463049-be7db2c2-02bc-11e8-9858-794dc3e2dfb2.png) | ![screen shot 2018-01-26 at 5 15 25 pm](https://user-images.githubusercontent.com/10562544/35463050-be8fcd5e-02bc-11e8-849a-815a3731939d.png) |  |
| Print | ![screen shot 2018-01-26 at 5 15 31 pm](https://user-images.githubusercontent.com/10562544/35463051-bea39f0a-02bc-11e8-974a-63d530b22e37.png) | ![screen shot 2018-01-26 at 5 15 35 pm](https://user-images.githubusercontent.com/10562544/35463052-bec0bbe4-02bc-11e8-9081-f3baa076a921.png) |  |
| RSS | ![screen shot 2018-01-26 at 5 15 41 pm](https://user-images.githubusercontent.com/10562544/35463053-bed43098-02bc-11e8-866a-dde7007f2d27.png) | ![screen shot 2018-01-26 at 5 16 15 pm](https://user-images.githubusercontent.com/10562544/35463054-bee36f86-02bc-11e8-84c5-26d1661e6cbd.png) |  |

**Comment by designlanguage** [comment]
More icons for this group:

| Name | Symbol | In circle | Notes |
| --- |  --- |  --- |  --- |
| Save | ![screen shot 2018-01-29 at 10 27 53 am](https://user-images.githubusercontent.com/10562544/35518308-33f81e4c-04df-11e8-9507-16bcb1f3740b.png) | ![screen shot 2018-01-29 at 10 27 59 am](https://user-images.githubusercontent.com/10562544/35518309-340a0bb6-04df-11e8-8056-b91ffb49d544.png) |  |
| Attach | ![screen shot 2018-01-29 at 10 28 07 am](https://user-images.githubusercontent.com/10562544/35518310-34229f1e-04df-11e8-8ecc-d71b33fc8eb4.png) | ![screen shot 2018-01-29 at 10 28 11 am](https://user-images.githubusercontent.com/10562544/35518311-34320f94-04df-11e8-9b32-25878bc96349.png) |  |
| Edit | ![screen shot 2018-01-29 at 10 57 56 am](https://user-images.githubusercontent.com/10562544/35520337-bdfb6388-04e4-11e8-8dca-bf9bacc91b48.png) | ![screen shot 2018-01-29 at 10 58 01 am](https://user-images.githubusercontent.com/10562544/35520338-be0c9914-04e4-11e8-91ec-93f44b956d9d.png) |  |
| Appendix | ![screen shot 2018-01-29 at 11 07 54 am](https://user-images.githubusercontent.com/10562544/35520361-cdbf5e82-04e4-11e8-907e-80f4a4464b00.png) | ![screen shot 2018-01-29 at 11 07 59 am](https://user-images.githubusercontent.com/10562544/35520362-ce23b332-04e4-11e8-8954-a78d63ec9741.png) | Made the box behind the document into a full-size document, but I'm not sure what this icon would be used for. |
| Supplement | ![screen shot 2018-01-29 at 11 08 06 am](https://user-images.githubusercontent.com/10562544/35520363-ce36f14a-04e4-11e8-8b15-9f9f780db7d7.png) | ![screen shot 2018-01-29 at 11 08 10 am](https://user-images.githubusercontent.com/10562544/35520364-ce8714b8-04e4-11e8-80cd-41c0de7488e5.png) | Made the box behind the document into a full-size document, but I'm not sure what this icon would be used for. |

**Comment by Scotchester** [comment]
If you're going to remove the text from the PDF icon, let's rename it to `blank-document` and create an alias for `pdf`, probably do the standard `document` icon.

**Comment by designlanguage** [comment]
I think the `document` icon would be a good replacement for `pdf`. Maybe we don't need a blank document.

**Comment by designlanguage** [comment]
SVGs are in this folder: https://drive.google.com/open?id=1swnwgBL9GOlQAyqSz8nFt3Ac83kqnbw0

**Comment by Scotchester** [comment]
I've already fixed it in Drive, but in case it matters for the font: `edit.svg` was misnamed as `dit.svg`.
