### ISSUE TITLE
Update group 4 icons - Communication

### ISSUE THREAD

**Issue by jimmynotjim** [cfpb/design-manual#576]
Update the fourth group of icons and export for print and web. Ensure the file names match the names used in the Design Manual, the paths are grouped into a top-level group, and everything is converted to outlines.

**Comment by designlanguage** [comment]
@Dnpizarro - Documenting what we've already done here. I think the envelope should be white inside the circle.

| Name | Symbol | In circle | Notes |
| --- |  --- |  --- |  --- |
| Fax | ![screen shot 2018-01-24 at 4 16 37 pm](https://user-images.githubusercontent.com/10562544/35357920-f3ae8070-0122-11e8-811f-33b15b3166dc.png) | ![screen shot 2018-01-24 at 4 16 43 pm](https://user-images.githubusercontent.com/10562544/35357921-f3c0dc52-0122-11e8-8d99-9fe2585dbf8c.png) |  |
| Mail | ![screen shot 2018-01-24 at 4 17 37 pm](https://user-images.githubusercontent.com/10562544/35357922-f3dab7ee-0122-11e8-9772-d9699b8f4d4c.png) | ![screen shot 2018-01-24 at 4 18 39 pm](https://user-images.githubusercontent.com/10562544/35357924-f3f20f0c-0122-11e8-960a-fc5d6f417388.png) |  |

**Comment by Dnpizarro** [comment]
Below are the Communication icons and svg versions.
https://drive.google.com/drive/folders/13fKGQtPZ92WuFyh5g-vwkv-31Pgytg3i

@Scotchester @jimmynotjim @designlanguage 

| Name | Symbol | In circle | Notes |
| --- |  --- |  --- |  --- |
| Email | ![email](https://user-images.githubusercontent.com/6852363/35537126-2728835e-0517-11e8-9bbc-416c3d3f54f9.png) | ![email-round](https://user-images.githubusercontent.com/6852363/35537135-2f7495f2-0517-11e8-9474-30553ced423f.png) |  |
| Mail | ![mail](https://user-images.githubusercontent.com/6852363/35537149-3da2fa2e-0517-11e8-9baa-c630cf292c88.png) | ![mail-round](https://user-images.githubusercontent.com/6852363/35537163-46e33720-0517-11e8-9c53-fab4f75a8c3e.png) |  |
| Fax | ![fax](https://user-images.githubusercontent.com/6852363/35537205-67ec355c-0517-11e8-8583-d454e67c024f.png) | ![fax-round](https://user-images.githubusercontent.com/6852363/35537218-6f4b63f4-0517-11e8-874f-a99b708fe6d4.png) |  |
| Phone | ![phone](https://user-images.githubusercontent.com/6852363/35537247-8ab7cdf8-0517-11e8-91ec-78dceb087cc0.png) | ![phone-round](https://user-images.githubusercontent.com/6852363/35537254-900e566e-0517-11e8-900f-759d0050df6b.png) |  |
| Technology | ![technology](https://user-images.githubusercontent.com/6852363/35537277-a74b4e18-0517-11e8-815b-cf4256f1d921.png) | ![technology-round](https://user-images.githubusercontent.com/6852363/35537286-ad99001c-0517-11e8-9f88-ce5bf8f2f6fd.png) |  |
| Web | ![web](https://user-images.githubusercontent.com/6852363/35537316-c404ee06-0517-11e8-8b51-6f161dda493c.png) | ![web-round](https://user-images.githubusercontent.com/6852363/35537321-c87e310e-0517-11e8-89e1-23897167a449.png) |  |

**Comment by designlanguage** [comment]
@Dnpizarro - I think both envelopes should be white rather than black with a white outline (in the circle).

**Comment by Dnpizarro** [comment]
@designlanguage good catch. @jimmynotjim @Scotchester the updated round icons are below:
https://drive.google.com/drive/folders/13fKGQtPZ92WuFyh5g-vwkv-31Pgytg3i


<img width="557" alt="screen shot 2018-01-30 at 11 27 32 am" src="https://user-images.githubusercontent.com/6852363/35578086-1ea03ce6-05b1-11e8-94fb-d29121488e1c.png">

**Comment by Dnpizarro** [comment]
I made a minor update to the email icon. I basically rounded the tip of the envelope.
https://drive.google.com/drive/folders/13fKGQtPZ92WuFyh5g-vwkv-31Pgytg3i

@Scotchester @jimmynotjim @designlanguage 

<img width="199" alt="screen shot 2018-01-30 at 1 22 11 pm" src="https://user-images.githubusercontent.com/6852363/35583683-bab2e610-05c0-11e8-8926-31e05b28642f.png">
