### ISSUE TITLE
FEWD - Update the canvas resizing script

### ISSUE THREAD

**Issue by jimmynotjim** [cfpb/design-manual#577]
Update the script to only remove the left and right whitespace, leaving the top and bottom white space and the path sizes intact.

**Comment by jimmynotjim** [comment]
@Scotchester Don't forget to drop a comment in here with the Ai script when you get a chance.

**Comment by Scotchester** [comment]
Here's the final script we arrived at:

```jsx
#target illustrator
#targetengine main

var doc = app.activeDocument;
var artboard = doc.artboards[0];
var art = doc.pageItems[0];
var coordinates = art.position;
var desiredW = art.width;

art.position = [ 0, coordinates[1] ];
artboard.artboardRect = [
  artboard.artboardRect[0],
  artboard.artboardRect[1],
  desiredW,
  artboard.artboardRect[3]
];
```

Note: This script requires that all of the art in the Illustrator document be collected together in a **single group**.
