### ISSUE TITLE
FEWD - Develop a centered icon pattern for stacked icons

### ISSUE THREAD

**Issue by jimmynotjim** [cfpb/design-manual#578]
Develop a pattern in markup and CSS to center icons within a canvas so that they are aligned when stacked and don't affect the left justification of the pairing text.

**Comment by jimmynotjim** [comment]
Scott and I realized we dropped the icon list pattern because it was overly complex and not a pattern currently in use. Due to time, we'd like to defer it further and add it to the designers follow up items.

**Comment by Scotchester** [comment]
_Developers'_ follow-up items?

**Comment by jimmynotjim** [comment]
I figured we'd put them all together and this would go with the designers _other_ follow up items.
