### ISSUE TITLE
Update group 5 icons - Status

### ISSUE THREAD

**Issue by jimmynotjim** [cfpb/design-manual#580]
Update the fifth group of icons and export for print and web. Ensure the file names match the names used in the Design Manual, the paths are grouped into a top-level group, and everything is converted to outlines.

**Comment by designlanguage** [comment]
| Name | Symbol | In circle | Notes |
| --- |  --- |  --- |  --- |
| Left | ![screen shot 2018-01-24 at 11 00 57 am](https://user-images.githubusercontent.com/10562544/35342539-56b08844-00f6-11e8-87ef-ec6175585f8c.png) | ![screen shot 2018-01-24 at 11 01 03 am](https://user-images.githubusercontent.com/10562544/35342540-56c01908-00f6-11e8-88b1-270b02fe30ba.png) |  |
| Right | ![screen shot 2018-01-24 at 11 01 17 am](https://user-images.githubusercontent.com/10562544/35342541-56d4a7b0-00f6-11e8-840e-3666e873fdbe.png) | ![screen shot 2018-01-24 at 11 01 22 am](https://user-images.githubusercontent.com/10562544/35342542-56eab2ee-00f6-11e8-97f6-74061a714597.png) |  |
| Up | ![screen shot 2018-01-24 at 11 01 29 am](https://user-images.githubusercontent.com/10562544/35342543-57275ff0-00f6-11e8-9d75-991c6b49f03d.png) | ![screen shot 2018-01-24 at 11 01 34 am](https://user-images.githubusercontent.com/10562544/35342544-5751fd00-00f6-11e8-8b4e-ebb9d03aae19.png) |  |
| Down | ![screen shot 2018-01-24 at 11 01 38 am](https://user-images.githubusercontent.com/10562544/35342545-575fb242-00f6-11e8-8fd0-bf5ced24827f.png) | ![screen shot 2018-01-24 at 11 01 44 am](https://user-images.githubusercontent.com/10562544/35342546-577129c8-00f6-11e8-8461-715521e7a2a4.png) |  |
| Arrow-left | ![screen shot 2018-01-24 at 11 01 55 am](https://user-images.githubusercontent.com/10562544/35342958-6e1e9eac-00f7-11e8-9248-722e103a23f3.png) | ![screen shot 2018-01-24 at 11 02 01 am](https://user-images.githubusercontent.com/10562544/35342959-6e36f024-00f7-11e8-94db-40400644f2ae.png) |  |
| Arrow-right | ![screen shot 2018-01-24 at 11 02 08 am](https://user-images.githubusercontent.com/10562544/35342550-57c71680-00f6-11e8-8065-2ad6d5f4e0d3.png) | ![screen shot 2018-01-24 at 11 02 16 am](https://user-images.githubusercontent.com/10562544/35342551-57da6c6c-00f6-11e8-8a2f-999fe8cae016.png) |  |
| Arrow-up | ![screen shot 2018-01-24 at 11 02 42 am](https://user-images.githubusercontent.com/10562544/35342552-582130d4-00f6-11e8-8e2b-d5cebe3566bd.png) | ![screen shot 2018-01-24 at 11 02 47 am](https://user-images.githubusercontent.com/10562544/35342553-58383a68-00f6-11e8-9857-b536c40e2610.png) |  |
| Arrow-down | ![screen shot 2018-01-24 at 11 02 54 am](https://user-images.githubusercontent.com/10562544/35342554-58528710-00f6-11e8-9b8c-3774d640b121.png) | ![screen shot 2018-01-24 at 11 02 59 am](https://user-images.githubusercontent.com/10562544/35342555-588c2cb8-00f6-11e8-99eb-94d666869e16.png) |  |

**Comment by designlanguage** [comment]
| Name | Symbol | In circle | Notes |
| --- |  --- |  --- |  --- |
| Approved | - | - | Not created yet. |
| Error | ![screen shot 2018-01-24 at 11 14 18 am](https://user-images.githubusercontent.com/10562544/35343284-4aaab9be-00f8-11e8-8f93-4308387e17b7.png) | ![screen shot 2018-01-24 at 11 14 24 am](https://user-images.githubusercontent.com/10562544/35343285-4b6cdb8e-00f8-11e8-8e65-966d25d025a0.png) | Matched the stroke weight of the other symbols for this, which is a departure from the original. |
| Help | - | - | Not created yet. |
| Delete | ![screen shot 2018-01-24 at 11 14 44 am](https://user-images.githubusercontent.com/10562544/35343286-4b8b0df2-00f8-11e8-99fb-a99e495098af.png) | ![screen shot 2018-01-24 at 11 14 48 am](https://user-images.githubusercontent.com/10562544/35343287-4bb22cc0-00f8-11e8-9eab-40d82bcd9123.png) |  |
| Plus | ![screen shot 2018-01-24 at 11 14 56 am](https://user-images.githubusercontent.com/10562544/35343288-4bc0deaa-00f8-11e8-8247-f1f3f39aac44.png) | ![screen shot 2018-01-24 at 11 15 02 am](https://user-images.githubusercontent.com/10562544/35343289-4be493fe-00f8-11e8-8774-186c16daf492.png) |  |
| Minus | ![screen shot 2018-01-24 at 11 15 15 am](https://user-images.githubusercontent.com/10562544/35343291-4c169ef8-00f8-11e8-9790-04623f004adf.png) | ![screen shot 2018-01-24 at 11 15 20 am](https://user-images.githubusercontent.com/10562544/35343292-4c67d80e-00f8-11e8-9c40-9c987ca2fcd1.png) |  |
| Update | - | - | Not created yet. |
| _Not specified in design manual_ | ![screen shot 2018-01-24 at 11 15 51 am](https://user-images.githubusercontent.com/10562544/35343293-4c801306-00f8-11e8-97a0-2d650286cb4b.png) | ![screen shot 2018-01-24 at 11 15 58 am](https://user-images.githubusercontent.com/10562544/35343294-4c9adcc2-00f8-11e8-9265-abce594485e6.png) |  |
| _Not specified in design manual_ | ![screen shot 2018-01-24 at 11 16 04 am](https://user-images.githubusercontent.com/10562544/35343295-4cae6ddc-00f8-11e8-8ed8-fc882110033e.png) | ![screen shot 2018-01-24 at 11 16 09 am](https://user-images.githubusercontent.com/10562544/35343296-4cc37218-00f8-11e8-958b-1de6e644fd90.png) | Two stroke weights here. The circles are the new 100pt weight we added. |
| _Not specified in design manual_ | ![screen shot 2018-01-24 at 11 16 38 am](https://user-images.githubusercontent.com/10562544/35343297-4cd27358-00f8-11e8-96ca-a17a255e21c9.png) | ![screen shot 2018-01-24 at 11 16 43 am](https://user-images.githubusercontent.com/10562544/35343298-4cef63e6-00f8-11e8-844b-7d0f3979ce9d.png) |  |
| _Not specified in design manual_ | ![screen shot 2018-01-24 at 4 12 43 pm](https://user-images.githubusercontent.com/10562544/35357419-7882ff76-0121-11e8-9565-576da15d7086.png) | ![screen shot 2018-01-24 at 4 12 48 pm](https://user-images.githubusercontent.com/10562544/35357420-78904082-0121-11e8-8867-454aff7e2b24.png) |  |

**Comment by designlanguage** [comment]
Here are the remaining status group icons:

| Name | Symbol | In circle | Notes |
| --- |  --- |  --- |  --- |
| Approved | ![screen shot 2018-01-30 at 9 37 46 am](https://user-images.githubusercontent.com/10562544/35571872-4a9b4454-05a1-11e8-8f66-9c97ec6c85cf.png) | ![screen shot 2018-01-30 at 9 37 50 am](https://user-images.githubusercontent.com/10562544/35571873-4aadc692-05a1-11e8-86c1-18a6ff2b0897.png) |  |
| Help | ![screen shot 2018-01-30 at 9 37 56 am](https://user-images.githubusercontent.com/10562544/35571874-4abacaae-05a1-11e8-9598-69cf3ada077c.png) | ![screen shot 2018-01-30 at 9 38 01 am](https://user-images.githubusercontent.com/10562544/35571878-4b4f8a40-05a1-11e8-85ec-130e2393b523.png) |  |
| Update | ![screen shot 2018-01-30 at 9 36 15 am](https://user-images.githubusercontent.com/10562544/35571832-359217a4-05a1-11e8-94f2-aaa02f119a73.png) | ![screen shot 2018-01-30 at 9 36 22 am](https://user-images.githubusercontent.com/10562544/35571833-35a1b59c-05a1-11e8-8025-0988c45faad2.png) | Our standard stroke weight inside the circle is a bit thick. |

**Comment by Dnpizarro** [comment]
The SVG version are uploaded below:
https://drive.google.com/drive/u/0/folders/1LXWcmIrUsfekSrOw9ohyu6bHuGT1ydRI

@jimmynotjim @Scotchester

**Comment by Scotchester** [comment]
`approved-round` and `help-round` look off-center in the delivered SVGs.

**Comment by jimmynotjim** [comment]
@Scotchester Those two icons were updated correct?

**Comment by Scotchester** [comment]
Yes, they were.
