### ISSUE TITLE
Update group 6 icons - Navigation

### ISSUE THREAD

**Issue by jimmynotjim** [cfpb/design-manual#581]
Update the sixth group of icons and export for print and web. Ensure the file names match the names used in the Design Manual, the paths are grouped into a top-level group, and everything is converted to outlines.

**Comment by designlanguage** [comment]
| Name | Symbol | In circle | Notes |
| --- |  --- |  --- |  --- |
| Left | ![screen shot 2018-01-24 at 11 00 57 am](https://user-images.githubusercontent.com/10562544/35342539-56b08844-00f6-11e8-87ef-ec6175585f8c.png) | ![screen shot 2018-01-24 at 11 01 03 am](https://user-images.githubusercontent.com/10562544/35342540-56c01908-00f6-11e8-88b1-270b02fe30ba.png) |  |
| Right | ![screen shot 2018-01-24 at 11 01 17 am](https://user-images.githubusercontent.com/10562544/35342541-56d4a7b0-00f6-11e8-840e-3666e873fdbe.png) | ![screen shot 2018-01-24 at 11 01 22 am](https://user-images.githubusercontent.com/10562544/35342542-56eab2ee-00f6-11e8-97f6-74061a714597.png) |  |
| Up | ![screen shot 2018-01-24 at 11 01 29 am](https://user-images.githubusercontent.com/10562544/35342543-57275ff0-00f6-11e8-9d75-991c6b49f03d.png) | ![screen shot 2018-01-24 at 11 01 34 am](https://user-images.githubusercontent.com/10562544/35342544-5751fd00-00f6-11e8-8b4e-ebb9d03aae19.png) |  |
| Down | ![screen shot 2018-01-24 at 11 01 38 am](https://user-images.githubusercontent.com/10562544/35342545-575fb242-00f6-11e8-8fd0-bf5ced24827f.png) | ![screen shot 2018-01-24 at 11 01 44 am](https://user-images.githubusercontent.com/10562544/35342546-577129c8-00f6-11e8-8461-715521e7a2a4.png) |  |
| Arrow-left | ![screen shot 2018-01-24 at 11 01 55 am](https://user-images.githubusercontent.com/10562544/35342958-6e1e9eac-00f7-11e8-9248-722e103a23f3.png) | ![screen shot 2018-01-24 at 11 02 01 am](https://user-images.githubusercontent.com/10562544/35342959-6e36f024-00f7-11e8-94db-40400644f2ae.png) |  |
| Arrow-right | ![screen shot 2018-01-24 at 11 02 08 am](https://user-images.githubusercontent.com/10562544/35342550-57c71680-00f6-11e8-8065-2ad6d5f4e0d3.png) | ![screen shot 2018-01-24 at 11 02 16 am](https://user-images.githubusercontent.com/10562544/35342551-57da6c6c-00f6-11e8-8a2f-999fe8cae016.png) |  |
| Arrow-up | ![screen shot 2018-01-24 at 11 02 42 am](https://user-images.githubusercontent.com/10562544/35342552-582130d4-00f6-11e8-8e2b-d5cebe3566bd.png) | ![screen shot 2018-01-24 at 11 02 47 am](https://user-images.githubusercontent.com/10562544/35342553-58383a68-00f6-11e8-9857-b536c40e2610.png) |  |
| Arrow-down | ![screen shot 2018-01-24 at 11 02 54 am](https://user-images.githubusercontent.com/10562544/35342554-58528710-00f6-11e8-9b8c-3774d640b121.png) | ![screen shot 2018-01-24 at 11 02 59 am](https://user-images.githubusercontent.com/10562544/35342555-588c2cb8-00f6-11e8-99eb-94d666869e16.png) |  |

**Comment by Dnpizarro** [comment]
@jimmynotjim @Scotchester  the SVG version for the navigation icons are below:
https://drive.google.com/drive/u/0/folders/1WO0iLdy4KJhIWSLfejiB2Sm4RMXBc749

**Comment by Scotchester** [comment]
`left-round` and `right-round` look numerically but not optically centered to me.

**Comment by jimmynotjim** [comment]
@Scotchester also making sure these two were updated.

**Comment by Scotchester** [comment]
Yes, they were.
