### ISSUE TITLE
Update group 7 icons - Social

### ISSUE THREAD

**Issue by jimmynotjim** [cfpb/design-manual#582]
Update the seventh group of icons and export for print and web. Ensure the file names match the names used in the Design Manual, the paths are grouped into a top-level group, and everything is converted to outlines.

**Comment by designlanguage** [comment]
We have two almost identical envelope icons in our font. We should remove one:

![screen shot 2018-01-24 at 4 32 44 pm](https://user-images.githubusercontent.com/10562544/35358338-57ef3394-0124-11e8-8e5b-136fc12492a8.png)

**Comment by Scotchester** [comment]
✅ ❌

**Comment by Dnpizarro** [comment]
The social icon SVGs can be found below:
https://drive.google.com/drive/folders/1Dj8BleWasxYYl_5IQb6Pkv1X4-l2S1tL

@jimmynotjim @designlanguage @Scotchester 

<img width="1081" alt="screen shot 2018-01-30 at 1 30 39 pm" src="https://user-images.githubusercontent.com/6852363/35584055-cb4f8734-05c1-11e8-86fb-056113ab8a96.png">
