### ISSUE TITLE
[bug] broken link in the Data Visualization section

### ISSUE THREAD

**Issue by amycesal** [cfpb/design-manual#621]
### Bug: 
On the "Emphasis!" page, the link to the text section does not exist. 

### Fix:
It needs to be re-linked to the "Chart Components" page. 

-----

<img width="886" alt="Screen Shot 2019-04-02 at 1 56 03 PM" src="https://user-images.githubusercontent.com/1656046/55425036-85f95c80-554f-11e9-9893-b79ed18835b4.png">

**Comment by marteki** [comment]
Resolved in PR #622. Closing as fixed.
