### ISSUE TITLE
Expandables missing icon

### ISSUE THREAD

**Issue by ascott1** [cfpb/design-manual#64]
The icon in the expandable demo is MIA

**Comment by stephanieosan** [comment]
![screen shot 2014-03-25 at 1 36 56 pm](https://f.cloud.github.com/assets/6433178/2515478/19b3a38e-b444-11e3-9be2-069db16781d1.png)
Appears to be showing up for me. Unless you're talking about someplace else?

**Comment by ascott1** [comment]
Sweet! Looks like it was fixed in [this](https://github.com/cfpb/design-manual/pull/65)
