### ISSUE TITLE
Identity section order

### ISSUE THREAD

**Issue by ohsk** [cfpb/design-manual#67]
Need to update the order of the sections in [Identity](http://cfpb.github.io/design-manual/identity/brand-guidelines.html) to reflect the sequence found in the Style Guide 2.0:
- Logo
- Color
- Typography 
- Minicons
- Isocons
- Illustration
- Beam pattern
- Photography
- Video

**Comment by stephanieosan** [comment]
And while someone is in there updating sections, might as well knock out this issue #34 as well.
