### ISSUE TITLE
Green bar in side nav inconsistently persistent

### ISSUE THREAD

**Issue by ohsk** [cfpb/design-manual#71]
The green bar appears when some pages are selected, but not others. (Seems fine on hover though)

Needs to be fixed for [Color](http://cfpb.github.io/design-manual/identity/color-principles.html) and [Beam Pattern](http://cfpb.github.io/design-manual/identity/beams.html).
### Doesn't appear when on the Color page:

![image](https://f.cloud.github.com/assets/1689222/2528298/274e53f2-b50e-11e3-833f-4cd97f2d633b.png)
### Appears fine when on the Logo page:

![image](https://f.cloud.github.com/assets/1689222/2528284/0cabd52e-b50e-11e3-9ab4-b6cb4e5ce6a0.png)

**Comment by ascott1** [comment]
I'd guess that it's because the name of the page is "Color principles", but the nav title was changed to just "Color."

**Comment by ohsk** [comment]
Ah, that would make sense, also for "Beams" vs. "Beam Pattern."

**Comment by ascott1** [comment]
Sorry! Didn't catch that when I was renaming the links in the nav.

**Comment by ohsk** [comment]
No problem! Just to be clear, I think the section and nav should all reflect the following:
- Color
- Beam pattern

**Comment by ascott1** [comment]
@ohsk it's still not working for "Beam Pattern." It looks like this is because the nav bar says "Beam Pattern" while the title says "Beam pattern." The capitalization, sadly, makes a difference. :crying_cat_face:
