### ISSUE TITLE
Video border

### ISSUE THREAD

**Issue by vz3** [cfpb/design-manual#72]
Our videos often depict a person speaking in front of a stark white backdrop. It's clean, modern, and in keeping with our visual identity. That said, when these videos are placed on our website with the same pure white background color, the subjects feel like video overlays (think: [Clippy](http://www.csub.edu/~jross/classes/gs390/Wordprocessing/Word2000/Wd2000Edit/OffAsst.GIF)). This could be fixed by adding a 1px border to all videos.

Here's a mockup of our [mortgages page](http://consumerfinance.gov/mortgage).

Before:
![video_noborder](https://cloud.githubusercontent.com/assets/582918/2530881/8c3c8384-b52b-11e3-8163-ae8212bba1b6.png)

After:
![video_border](https://cloud.githubusercontent.com/assets/582918/2530882/90462002-b52b-11e3-9400-1198a4257d3b.png)

**Comment by stephanieosan** [comment]
Should we standardize the border color as well as the width? What color are you using here, @vz3 ?

**Comment by vz3** [comment]
This is #E8E8E8, which is just what I pulled from the graphics @iuloshi [used in the manual](http://cfpb.github.io/design-manual/identity/video.html). Agreed on standardizing color and width, and defer to graphic designers on that decision.

**Comment by duelj** [comment]
I really rather prefer the border-less approach. I think it feels more integrated rather than just pasted in. It's too bad we couldn't make a custom title screen and use our play button icon to make the experience seem even more seamless.

**Comment by stephanieosan** [comment]
Wait, why can't we make a custom title screen with our play button icon?

**Comment by vz3** [comment]
We technically could. The title screens can be customized through YouTube. We'd just need to upload an image to act as the preview image.

**Comment by vz3** [comment]
On the note of border versus none, I think for animations it could be fine, but for people against a white backdrop I think it's problematic to have a contextless human body floating in front of a website. The effect is even stronger when you see it in motion:
http://www.consumerfinance.gov/mortgage/

I think we should continue to only use uncontained images for illustrations, not photo or video.

**Comment by himedlooff** [comment]
Well here http://www.consumerfinance.gov/es/quienes-somos/ we use a custom video poster. It's just an image that when clicked loads the youtube video. This allows us to depict the video any way we want and we are not needlessly loading youtube scripts in cases where no one actually watches the video. Also it allows us to decide on how to respond to someone clicking the video poster. For example on modern browsers we could embed the video in-place when the user clicks the poster. Or, for older browsers, where we don't want to deal with embedding third party code that probably doesn't want to support older browsers we can simply link directly to the video on youtube.

**Comment by vz3** [comment]
Oh wow, I totally forgot that we got responsive YouTube working for Babel. Good call.

Design-wise, I think we can do better than cropping out the faces of CFPB employees who are not recognizable to consumers and calling that a compelling preview image.

I do prefer the lighter colored YouTube player in the above example.

**Comment by vz3** [comment]
Here's some documentation on the various video players. In quienes somos, we used a white player with a red bar, which is what I suggest we standardize on site-wide:
http://techmarshal.blogspot.com/2011/08/use-black-youtube-player-for-embedded.html

``` html
<iframe src="http://www.youtube.com/embed/XXXXXXX?theme=light&color=red" frameborder="0" width="520" height="326" allowfullscreen></iframe>
```

**Comment by duelj** [comment]
I didn't mean to give the impression I didn't know we could have a custom title screen, like @himedlooff said I knew we did it with Babel. I guess it was my way of gently suggesting it... As for what is on the title screen I think having the person who is in the video gives context so the consumer knows what to expect when they click play, but I agree I would have no idea who these people are or why to find them interesting as a consumer. However, faces do lend warmth and ultimately I favor the context they provide from a UX perspective.

**Comment by stephanieosan** [comment]
Is this issue still applicable? What have we been doing with our videos recently? @elizbond @duelj

**Comment by Dnpizarro** [comment]
I think @duelj logic makes sense. Showing people's faces does elicit a more receptive response. Out of curiosity, @duelj do you plan on making a custom image for the "About us" video or using a still frame from the video?

**Comment by elizbond** [comment]
In Flapjack, the plan is to have custom images so we have our own play button.
via @duelj
