### ISSUE TITLE
Pattern library format

### ISSUE THREAD

**Issue by vz3** [cfpb/design-manual#73]
We should settle on a format for all elements in the UI toolkit (why don't we just call it a pattern library?).

Blatantly plagiarizing from the [design pattern library panel at SXSW](http://panelpicker.sxsw.com/vote/24247), one format could be:
-Name
-Description
-When/where to use
-Design rationale
-Examples & Variations
-Open issues

I think the open issues element is pretty genius, though if we stick with Git, issues may make more sense.

Some other models we can look at:
[Yahoo](http://developer.yahoo.com/ypatterns/everything.html)
[eBay](http://uipatterns.ebay.com/pe)
[Bootstrap](http://getbootstrap.com/components/)

I think this is worth getting input from all disciplines on the design team (FEWD, UX, Graphic Design).

**Comment by mebates** [comment]
@ohsk @stephanieosan and I decided on these four sections:
- Intro
- Style
- States
- Variations

For Friday, we'll have all the UI pages comped up with final copy using content from the old Digital Product Guide and this new structure. People can Pull Request copy edits after the pages are built. 

Stephen: Form fields, Tables
Stephanie: Modals, Pagination
Mollie: Expandables, Tooltips

**Comment by ohsk** [comment]
Latest comp for Links that reflects this approach:
_Updated with slight tweak_

![ui-toolkit_sk_140415_v1_links](https://cloud.githubusercontent.com/assets/1689222/2713331/4b305f36-c4e5-11e3-8b58-51b36c47826a.png)

**Comment by ell0ell0** [comment]
Wooo look at the fresh out of the oven comp. I'll get right on it

**Comment by iuloshi** [comment]
:clap: :clap:

**Comment by iuloshi** [comment]
Also we don't _really_ need a comp for every page, unless it diverges significantly from the above pattern. Feel free to just drop in the content and we can start applying styles. Maybe that can save some work time! :smile:

**Comment by mebates** [comment]
I think the comps will help us edit the text as we go.

**Comment by mebates** [comment]
@ohsk and @stephanieosan I'm running into trouble with Expandables and Tooltips. Both have extensive 'how to use' ux-type guidelines that don't fall under our three sections. Also, more about behavior than visual style. Can you take a look at the DPG guidelines and let me know what you think? Thanks!

**Comment by ohsk** [comment]
I think if that's the case, we could definitely consider adding another section called "use" or "use cases" or something for that added content.

**Comment by iuloshi** [comment]
Closing cause the UI toolkit pages are well into development. Further changes can be submitted as pull requests or filed as issues. Thanks all!
