### ISSUE TITLE
Identity > Minicons page

### ISSUE THREAD

**Issue by iuloshi** [cfpb/design-manual#78]
http://cfpb.github.io/design-manual/identity/minicons.html
- [ ] Build out Asset Library (FEWD)
- [x] Add scaling and color image examples (content task)

![minicons_minicons](https://cloud.githubusercontent.com/assets/1676307/2553341/2de9d2da-b6a4-11e3-8e70-bc9ed958c994.png)

**Comment by ohsk** [comment]
@Scotchester thought the scaling examples could be built in using the font rather than cutting images. 

Color and padding images are in, though!

**Comment by iuloshi** [comment]
@ascott1 Did you mention on Friday that the minicon library was getting added to Capital Framework, or am I completely Photoshopping that memory into existence? If I'm not cray-cray, then should we wait for that to happen before laying out the Minicon page in the Design Manual?

**Comment by Scotchester** [comment]
https://github.com/cfpb/cf-icons

**Comment by iuloshi** [comment]
:ok_hand:

**Comment by iuloshi** [comment]
A couple of FEWD questions regarding the Minicons Asset Library! @Scotchester @ascott1 

### Tables vs floated divs with regards to responsive design
- I tried out two versions of the [Asset Library sections on the Minicons page](http://iuloshi.github.io/design-manual/identity/minicons.html):
  1. The "Navigation" section uses a table, which creates a horizontal scroll if the browser width is less than the table width. [See code.](https://github.com/iuloshi/design-manual/commit/23a68ae36f9cad5f3be9c2286ac60130763ced06) (We run into the same issue on the [Colors](http://cfpb.github.io/design-manual/identity/color-principles.html) page/Issue #109.)
  2. The "Status" section has a bunch of floated divs with a fixed width, so that the number of minicons per row adapts responsively. [See code.](https://github.com/iuloshi/design-manual/commit/f4a642c3949922935dfc547f7593973e3a0c9fe8) *Note, we'd need to use some JS to figure out the number of divs per row so that we could add a horizontal rule between the rows and eliminate the `border-left` on the first div in the second row. [For reference](http://stackoverflow.com/questions/11539113/jquery-find-number-of-items-per-row-in-floated-lis).

How would you recommend to approach this problem overall?

![screen shot 2014-04-07 at 1 20 34 pm](https://cloud.githubusercontent.com/assets/1676307/2634679/ccffb058-be7c-11e3-996e-c7a28bce99d0.png)

### JS to pull in all minicons from Capital Framework
- Thus far, I've hand-coded the minicons and details, which is...tedious. 
- Is there an easy way so that whenever minicons are added/deleted, the Design Manual page is automagically synced, while still keeping in mind the different minicon categories?
- Or since I think designers would be responsible for updating this content, do you think that it'd be easier for them to update the HTML versus wrangling with JS?

**Comment by himedlooff** [comment]
You could do a custom layout for each size range for these icons. For example on small screens they can be 2 cols, for medium screens, 4 cols, and large, 6 cols. Here is an example: http://codepen.io/anon/pen/vDGqf

Instead of using JS to remove the borders you could use `:nth-child`. IE 8 and under won't understand it so they'll still see left borders on everything. This might or might not be a big deal to you. To me it's not.

**Comment by ascott1** [comment]
Could you use inline-block to do something like this? http://learnlayout.com/inline-block.html

Or am I just over simplifying?

**Comment by himedlooff** [comment]
She's already using `inline-block` to position them (although I'm not sure why `float` is also in there). 
I think the issue is around responsivizing the layout and making sure that when columns change due to viewport width that the border rules update properly as well. Correct me if I'm wrong @iuloshi.

The border rules are more difficult than you would think because if only two items fit in the viewport then you only need a border between the first and second item in a row. If three fit in a row then there are only borders between 1 and 2 and 2 and 3. This is hard to do when the number of cols in a row can change.

**Comment by iuloshi** [comment]
Hey thanks guys! :smiley_cat: 

@himedlooff Right-o, sir. Ideally, we'd also have a rule between the rows if there are more than 2. Anywhos, just wanted to make sure tables _weren't_ the way to go here.

Any thoughts on somehow having this page automatically sync with the minicons from Capital Framework, or should I just manually input them all into the HTML?

**Comment by himedlooff** [comment]
I gave @danny8000 some ideas on that. One way to do it is to run the Capital Framework CSS through Topdoc and spit out a partial HTML file that can be included in the page. Topdoc could take care of going through each icon and wrapping it in whatever HTML we want. @danny8000 have you looked into that yet? If not maybe I can take a quick stab at it.

**Comment by himedlooff** [comment]
And to clarify Topdoc is what we use in the Capital Framework to convert comments like this:

``` CSS
/* topdoc
    name: Default button
    family: cf-buttons
    notes:
      - "Note that the .visited, .hover, .focus, .active classes are for demonstration purposes only and should not 
        be used in production."
    patterns:
    - name: Default state
      markup: |
        <a href="#" class="btn">Anchor Tag</a>
        <button class="btn">Button Tag</button>
        <input type="submit" value="Input Tag" class="btn">
    - name: Hovered/focused state
      markup: |
        <a href="#" class="btn hover">Anchor Tag</a>
        <button class="btn hover">Button Tag</button>
        <input type="submit" value="Input Tag" class="btn hover">
    - name: Active state
      markup: |
        <a href="#" class="btn active">Anchor Tag</a>
        <button class="btn active">Button Tag</button>
        <input type="submit" value="Input Tag" class="btn active">
    tags:
    - cf-buttons
*/
```

Into HTML like this:

![screen shot 2014-04-07 at 4 57 56 pm](https://cloud.githubusercontent.com/assets/1093373/2636941/589e96c8-be97-11e3-8044-1686ede297bb.png)

What's cool is we can take the data from the comments and create any HTML template we want using only the data we want. So for example we could create a template that would only spit out the button markup like the [demo](http://cfpb.github.io/cf-buttons/demo/) page does.

**Comment by Scotchester** [comment]
Yeah, I think Mike's plan is a solid one. It requires being extra careful about keeping the CF docs (in the CSS) up-to-date, but that's not a bad thing. In fact, it's good to have more motivation to do that.

**Comment by Scotchester** [comment]
To follow-up on the original question, though: yeah, using tables is probably not the best idea. I implemented the scaling diagrams hastily and didn't think about that. Using grid columns is probably the way to go, adjusting the number of columns for smaller widths with media queries.

**Comment by iuloshi** [comment]
Nice! I think that makes a lot of sense, and I'd love to learn how to use Topdoc to pull in CF content on the other pages of the Design Manual. @himedlooff If you look at the [UI Toolkit](http://cfpb.github.io/design-manual/ui-toolkit/buttons.html), some of the content from CF is there, but the pages are still largely unformatted.

@Scotchester I think the scaling diagrams work as tables for now though because there are only about a half dozen columns, so they're not breaking like the much larger minicon asset library table.

**Comment by Dnpizarro** [comment]
@Scotchester is this task done?

**Comment by Scotchester** [comment]
Yeah, this was done long ago. Sorry for the delayed response!
