### ISSUE TITLE
Typography, markdown, spacing issue

### ISSUE THREAD

**Issue by mebates** [cfpb/design-manual#81]
On a page like [Design Principles](http://cfpb.github.io/design-manual/guides/design-principles.html), the H2 style is so far above the line below it that it visually links with the content above it. Can we fix this?

**Comment by stephanieosan** [comment]
I agree. 

There seems to be equal (or more) space between the last paragraph of the previous section and the H2 as there is between the H2 and the rule below it. There should be much less space between the H2 and its rule. Maybe half as much. And maybe more space above the H2, too.

**Comment by ohsk** [comment]
Hey guys, I have some of this outlined in this issue #37 I wrote for Dan to make stylistic updates to more closely reflect the spacing in the comps.

**Comment by stephanieosan** [comment]
I cut the spacing between the H2 and the rule below it in half. 
We're thinking we still need more space before the H2 and the previous section.

**Comment by mebates** [comment]
@stephanieosan I agree, a bit more above H2 would be nice. Good job! :star2:

**Comment by iuloshi** [comment]
Meant `margin-top` to H2s.

**Comment by mebates** [comment]
This is looking good to me now. Closed.
