### ISSUE TITLE
Home page content and design + Interior landing pages

### ISSUE THREAD

**Issue by mebates** [cfpb/design-manual#90]
Developing copy for home page and interior landing pages (Guides, Identity, UI) on this wiki: https://github.com/cfpb/design-manual/wiki/Overview-Explanatory-content

Copy is loaded on live site now for home page and Identity. Need some help to craft words for 'Guides' and 'UI Toolkit', please edit the wiki if you have some ideas, or comment below. 

Two options for the home page design, one more complex with a feed of recent updates and the other with a simple image. 

![screen shot 2014-03-28 at 6 02 10 pm](https://cloud.githubusercontent.com/assets/6223901/2555762/caa69354-b6c4-11e3-9c57-4c4be8a63f44.png)
![screen shot 2014-03-28 at 6 02 41 pm](https://cloud.githubusercontent.com/assets/6223901/2555763/caa9b778-b6c4-11e3-9030-dd03c98526d5.png)

**Comment by ohsk** [comment]
Previous comp, for reference sake.

![style_sk_140404_v6](https://cloud.githubusercontent.com/assets/1689222/2620406/ba7ffbae-bc3d-11e3-9097-bb941840f2ba.png)

**Comment by iuloshi** [comment]
Broke this down into two separate tasks: #121 & #122.
