### ISSUE TITLE
Identity > Hero images

### ISSUE THREAD

**Issue by dezzie** [cfpb/design-manual#97]
![hero_040114_dzg](https://cloud.githubusercontent.com/assets/1301932/2580621/8c938c8c-b9af-11e3-9167-77bce926b1c5.png)

**Comment by ohsk** [comment]
OMG SO GOOD.

**Comment by vz3** [comment]
👏👏👏

(That was the clapping emoji. Three of em.)

**Comment by dezzie** [comment]
April fool's :P
