### ISSUE TITLE
`grunt watch` task not working

### ISSUE THREAD

**Issue by iuloshi** [cfpb/design-manual#99]
`grunt less` successfully compiles CSS, but `grunt watch` runs into this error: 

![screen shot 2014-04-01 at 1 16 01 pm](https://cloud.githubusercontent.com/assets/1676307/2582151/5dedff0e-b9c1-11e3-83fc-afa148add6d2.png)

Do I need to reinstall grunt? 

cc: @ascott1 @Scotchester

**Comment by Scotchester** [comment]
Pretty sure it's related to the `Gruntfile` being located in the `front` folder. The PR I submitted fixes it for me locally. You should test this locally before merging the PR, though, @iuloshi.

**Comment by iuloshi** [comment]
:frowning: 

I'm now getting this error whenever I update a LESS file, after running `grunt watch`:

![screen shot 2014-04-04 at 6 05 11 pm](https://cloud.githubusercontent.com/assets/1676307/2620832/3a8827d4-bc45-11e3-9e8c-a2f0fc85a693.png)

And this error when I run `grunt less`:
![screen shot 2014-04-04 at 6 06 07 pm](https://cloud.githubusercontent.com/assets/1676307/2620836/5dd5a568-bc45-11e3-9ac9-8f8433835918.png)

**Comment by Scotchester** [comment]
Sorry, forgot to mention that you'll need to run `bower install` to get the
cf-icons component.

**Comment by iuloshi** [comment]
All good now. Thanks again @Scotchester!!
